### ISSUE TITLE
Proposal: secret/unlisted bins

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#1094]
Looking at gists as a potential reference (and I know there's other sites that have similar functionality).

Currently jsbin private bins work as:
- Switch a flag to private (this is on the bin, but doesn't affect the url)
- Now only the owner can see the bin, and no one else

Proposal for secret bins:
1. bins have 32 character urls (a hash like `0f5705484923edfb26b53e04f5015229ddf42802`)
2. If I share the url, other users can see the contents
3. Users _can_ copy and paste into a new bin (but this is the same in other applications)
4. Cloning will create a new secret bin (question: _what if they're not a pro user_)
5. Possible: typing doesn't save a new clone?

Any other concerns?

**Comment by Vanav** [comment]
Currently user's bins are exposed to public with: http://jsbin.com/:username/latest
So, it is really useful to have "unlisted" mode, that can be enabled by default, and will allow to access to bin only knowing the URL.
