### ISSUE TITLE
My Bins page doesn't use <title> when available

### ISSUE THREAD

**Issue by wraybowling** [jsbin/jsbin#1099]
I am continuously baffled why I need to add a meta description tag in order to give my jsbin projects titles. If anything, the description tag should make a description paragraph about the project. And if there's a title available, use it. Also, if this change is made, it would be wise to not auto-fill the title with "JS Bin"

**Comment by Daniel-Hug** [comment]
Related to #1390, #2106, #511. Looking forward to the title in my bin's `<title>` being its title in "my bins".
