### ISSUE TITLE
Change of delete shortcut [Proposal]

### ISSUE THREAD

**Issue by robertd** [jsbin/jsbin#1242]
![image](https://f.cloud.github.com/assets/31543/2324525/29940396-a3ca-11e3-873d-ba13e987b3bd.png)

Is there any way you can change delete shortcut since Chrome (on Win) is currently hijacking it?

**Comment by psiho** [comment]
Firefox hijacks it too. At least on Linux. This, together with not being able to multi-select archive items basically makes it impossible to manage my Bins. Currently I have 300 and and I don't plan to delete those by clicking on menu s :)
