### ISSUE TITLE
how to add images?

### ISSUE THREAD

**Issue by wilde** [jsbin/jsbin#1286]
to whom it may concern,

```
how to add image to jsbin?
```

**JS Bin info**
- [http://jsbin.com](http://jsbin.com)
- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36

**Comment by HosniArezki** [comment]
![image](https://user-images.githubusercontent.com/43354078/45651486-82c5e400-bac9-11e8-8077-c9f5e0d5fc4b.png)

Hello,
I don't know why I can't visualize the picture in the output section. Can anybody help me?
