### ISSUE TITLE
"Script error. (line 0)" for simple coffeescript is not enough to identify a problem

### ISSUE THREAD

**Issue by soswow** [jsbin/jsbin#1354]
Gives `Script error. (line 0)` for coffeescript code. 

UPD:
I found what was the problem - I forgot to add jquery as required by backbone. BUT The message is useless and it's already third time when I stuck. (previous time I guess it was the same problem, but I didn't remembered that this is the case now)

**JS Bin info**
- [http://jsbin.com/sazewire/5](http://jsbin.com/sazewire/5)
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36

**Comment by emrahtoy** [comment]
Here is the jsBin : http://jsbin.com/mafinupovi/2/

if you move first element to 3th line it will log newIndex 3 but it should be 2 because the list index starts from 0 ( you can drop it back to first line you will see newIndex = 0 )
