### ISSUE TITLE
Specifying the height of an embeded jsbin makes the html editor visible

### ISSUE THREAD

**Issue by robianmcd** [jsbin/jsbin#1468]
The following link should only show the js and output view but it also shows the html editor:

http://jsbin.com/waxanucu/embed?js,output&height=100%

If you remove height from it, it will show the specified views:

http://jsbin.com/waxanucu/embed?js,output

**Comment by jasonday** [comment]
`%` don't appear to work. If you put in a px value, it will work correctly. 

http://jsbin.com/waxanucu/embed?js,output&height=600px

You could always find the height of the window at runtime, and pipe that in prior to embed.js executing to dynamically get the correct px size.
