### ISSUE TITLE
Please add multiple js or arbitrary file support

### ISSUE THREAD

**Issue by ylluminarious** [jsbin/jsbin#1532]
I'm not seeing a way that you can currently add more than one js or other type of file. Could you please add a feature that would add a "+" button to the right of the top tabs that will be able to add additional js files that can be included by name? For example, I would like to add arbitrary "blah.js," "blah2.js," "blah3.js" files and then a "blah4.txt" file that will be able to all be included with includes or `require.js` from a `main.js` file...

**Comment by jeserkin** [comment]
Is this topic about refering to some additional files locally, like on `plnkr`?
