### ISSUE TITLE
Archive shortcut in Windows collides with system default

### ISSUE THREAD

**Issue by electricg** [jsbin/jsbin#1551]
In Windows the "CTRL+Y" shortcut is for the REDO action.
I tested in IE and Chrome on Win7 (virtual machine) and if I redo an action, this will also archive the bin.

**Comment by impressivewebs** [comment]
I was just about to open an issue for this. This is definitely a bit of an annoyance, so it would be great to get this corrected. CTRL-ALT-Y would probably make sense, although I'm not even sure why you'd even need a shortcut for this. How often are people archiving Bins that they need a shortcut key for it?

**Comment by remy** [comment]
I'm going to disable this entirely. It's come up more times than it should if it weren't a problem, and the usage stats are very very low for it.
