### ISSUE TITLE
console.clear() not working for some reason

### ISSUE THREAD

**Issue by MikeCheel** [jsbin/jsbin#1601]
http://jsbin.com/vojoliwi/1/edit

I was showing my daughter some js and noticed it stopped working. Vista so maybe old browser? Chrome says it's up to date though.

**JS Bin info**

* [http://jsbin.com/vojoliwi/1](http://jsbin.com/vojoliwi/1)
* Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.204 Safari/534.16

**Comment by jcrben** [comment]
Shouldn't this be closed since #1669 was merged in?
