### ISSUE TITLE
new hotkey alt+>

### ISSUE THREAD

**Issue by ghost** [jsbin/jsbin#1621]
I cannot write '>'  (on hungarian keyboard) any more because alt+Y is now a hotkey, and produces
this message:
The archiving failed. You can only archive bins that you own.

Please provide any additional information, record a screencast with http://quickcast.io or http://screenr.com and attach a screenshot if possible.

**JS Bin info**

* [http://jsbin.com](http://jsbin.com)
* Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
* 2astalavista

**Comment by remy** [comment]
Fixed https://github.com/jsbin/jsbin/commit/0486c25ec0eddad97523d37ee142dfc669cce9bf and live.
