### ISSUE TITLE
Custom bin for Marionette.js

### ISSUE THREAD

**Issue by peterblazejewicz** [jsbin/jsbin#1623]
@remy cc @electricg @allouis 
I've created a custom assets for eventual use as by Marionette.js users on jsbin.com:
https://github.com/marionettejs/backbone.marionette/issues/1538
and the people from Marionette.js project  also have been discussing possibility of such feature previously:
https://github.com/marionettejs/www/issues/81
Before making any PR I'd like to ask you about such custom/vanity domain: how can we eventually achieve having custom jsbin.com bin for a community like Marionette.js? In this commit you've mentioned custom pro account (ember.js/codeclub)
https://github.com/jsbin/jsbin/commit/84308ef68057e6f93ee192b6c0ac3004ad6c3a64
but I'm not able to find more information on that subject.
The feature has been discussed first on Marionette.js project and has :thumbsup: (with possible changes in L&F) as you could find in linked discussion.

Thanks!
:fingers_crossed:

**Comment by samccone** [comment]
I think this is still potentially a valid issue and since @peterblazejewicz has generated the assets it might still be an easy win.

Thanks!

**Comment by peterblazejewicz** [comment]
Hi Sam,
AFAIK  Remy is working on the new JSBin version, so maybe we could revisit that when the 5 hits public? I'd rather help him with new 5.* version, and later bring that content back to live.
Does it sounds OK?
Peter

**Comment by remy** [comment]
lol, me 4 years ago:

> This hasn't fallen on deaf ears.

I'm waiting for the stalebot to close out as much as it can, and since the label is removed here, I'll revisit what's outstanding to get a decent idea of what's missing in v5. 

Thanks for understanding! <3
