### ISSUE TITLE
JavaScript requires semicolons

### ISSUE THREAD

**Issue by colelawrence** [jsbin/jsbin#1658]
It's really a pet peeve of mine when semicolons are said to be required when they are actually _not_ required when engines use [ASI](http://inimino.org/~inimino/blog/javascript_semicolons).

Can this be a feature? I'd rather not work under the restrictions of a linter.

Thanks!

**JS Bin info**
- [http://jsbin.com/wifetehi/1](http://jsbin.com/wifetehi/1)
- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36

**Comment by arve0** [comment]
For those missing this note:
> When set to true, these options will make JSHint produce fewer warnings about your code.

In JSON:
```json
{
  "asi": true
}
```
