### ISSUE TITLE
run JS button not working

### ISSUE THREAD

**Issue by SKGrimes** [jsbin/jsbin#1664]
I am just learning how to code, however, I have found this service to be the best and have used it for many hours while prototyping code for some online courses.

Today, I wrote some basic code and hit "run with JS". Nothing.
I tried some pretty basic code like: console.log("hello, world"); this was typed into the JS column. I then proceeded to hit "run with JS". Nothing.

I was able to get the code to run by toggling the console (sometimes). Or by checking the auto run option. 

This is a huge hassle. I have used this service enough to believe this is not user error. I took away the complex code blocks and simply tried a few alerts and console logs. Is this normal. This was never an issue before.

**Comment by dovantuit** [comment]
the same trouble with me!!

**Comment by dovantuit** [comment]
thank you so much
