### ISSUE TITLE
CSSLint and Preprocessors

### ISSUE THREAD

**Issue by richardj** [jsbin/jsbin#1698]
CSSLint is not working nice with Preprocessors (SASS, SCSS, Stylus, Myth, Less).

Tested with all preprocessor variants and the issues seem to come back (most of them boil down to missing curly braces and everything else you expect from default CSS).

Maybe when a user has enabled CSSLint but using a preprocessor to disable the linting but show a small warning at the bottom (where now the normal warnings/errors are) that due to it being a preprocessor that CSSLint can't evaluate it.

![screenshot 2014-07-22 21 31 50](https://cloud.githubusercontent.com/assets/474024/3663824/e0013f66-11d6-11e4-9132-815ef86f1c8e.png)

**Comment by thinsoldier** [comment]
Choosing SCSS with compass in Firefox seems to disable the html and css editors. No changes in either take effect, not even after manually pressing the run button.

**Comment by sdeg** [comment]
**SCSS still not working since almost ONE year**, very annoying.  Cancellation account is imminent.

**Comment by remy** [comment]
@sdeg happy to help you with that. Your account renews early next month so it makes sense to do it before then. Happy to help delete the bins too if you need or want that too. Just let me know. Cheers.
