### ISSUE TITLE
Implement Twitter card API / Open Graph

### ISSUE THREAD

**Issue by richardj** [jsbin/jsbin#1709]
As JSbin has gone pro (hurray) i thought it might be a nice feature to be able to easier expose your bin to the world through the use of (for instance) the Twitter card.

This would mean that for every bin version it needs to have the settings integrated into the HTML. I don't know if it is possible with the way that jsbin works. But it would be nice to show the bin you are linking to without having to take a screenshot and attach it as well.

This could of course be implemented for multiple social networks, the Twitter card API for instance is based on the Open Graph standard, so that means that you can serve Facebook as well.

**Comment by sh4hidkh4n** [comment]
Why its not been added yet? Adding tags to head is easy but it show unnecessary markups completely unrelated to current project.

**Comment by remy** [comment]
@sh4hidkh4n I'm sorry, did you send a PR and I missed it?

**Comment by sh4hidkh4n** [comment]
@remy No.

**Comment by remy** [comment]
@sh4hidkh4n but you said it was "easy"? Ah well. Never mind then.

**Comment by sh4hidkh4n** [comment]
@remy I guess you got it wrong. I meant adding tags into head section manually.

**Comment by remy** [comment]
Ah, you mean in the authors code? Then yeah, that "easy" so far as your understanding of unfurl goes!
