### ISSUE TITLE
Adding description in combination with template engine

### ISSUE THREAD

**Issue by richardj** [jsbin/jsbin#1806]
When you are using a template engine and you "add a description" through the menu it will insert as normal HTML on line 1. This will not only result in it not being able to render properly, but also showing as text in your Output.

Jade panel
![screenshot 2014-08-08 22 13 29](https://cloud.githubusercontent.com/assets/474024/3862239/2b562c5a-1f39-11e4-9554-1ebb69c5c05a.png)

Output
![screenshot 2014-08-08 22 15 43](https://cloud.githubusercontent.com/assets/474024/3862240/2b5af046-1f39-11e4-8e72-e32e9bc33567.png)

I haven't tested it with markdown as of right now.

**update 1**: this should be the right format (not considering the yellow notification element thingy)

```
meta(name="description", content="[add your bin description]")
```

**update 2**: the Jade variant doesn't seem to be showing up on the 'my bins' page.

**Comment by happierall** [comment]
Dirty hack for jade:
```jade
//<meta name="description" content="Your description">
body
   .other_content
```
