### ISSUE TITLE
Customising editor no longer works

### ISSUE THREAD

**Issue by mcshaman** [jsbin/jsbin#1854]
I am having trouble customising JSBin editor. I have done it in the past using jsbin.settings.editor in the console but it no longer seems to work. jsbin.settings appears to be undefined.

If I run the following code in the console as instructed on this help page http://jsbin.com/help/customise-editor-settings

jsbin.settings.debug = true;

I get the following error in Chrome (mac)

TypeError: Cannot set property 'debug' of undefined

**Comment by code-read** [comment]
The above link currently results in "QuickCast is not currently available;" not sure how long it's been that way.  But from what I can tell, you simply enter a random string on the console and jsbin.settings starts working.  But this capability seems to have been supplanted by the builtin "Editor settings" menu available from within a JSBin session (left-click on "Account" at top right of JSBin screen and select "Editor settings").
