### ISSUE TITLE
Run JSBin Locally — npm  install error: zmq

### ISSUE THREAD

**Issue by ghost** [jsbin/jsbin#1857]
<strong>zmq</strong> node module is not installed correctly at <code> npm install </code> time. 

This module is not listed in package.json dependencies so I'll assume another module is depending on it: just don't know which one...

First WARN message reports 'set-immediate@0.1.1' was deprecated: <em>Use 'setimmediate' instead</em> — probably a minor issue.

Then <em>make</em> tries to build <strong>zmq</strong> but got a fatal error:

<em>zmq.h: no such file or directory<br>compilation terminated</em>

I am not sure what are the consequences for JSBin but when it starts running its front page is not rendered correctly — like it was missing its CSS files...

Could be another issue indeed but this <strong>zmq</strong> module problem is the only one I had so far.

**Comment by emnh** [comment]
Had the same problem with zmq.h missing. Fixed by "sudo aptitude install libzmq-dev".

Also had to set url.host in config.local.json to the server IP like nodeleaf did, but was unrelated to zmq issue I think.
