### ISSUE TITLE
Live preview not updating in real-time anymore

### ISSUE THREAD

**Issue by bclarke59** [jsbin/jsbin#1898]
Hi, the live preview feature is not updating for me in real-time anymore. It's fine when it's in the same tab (as in the default 'Output' section), but if I separate the output off into a new tab by clicking the 'Live Preview' arrow icon, the rendered page just stays static until I press the refresh button. I've made a screencast of the problem here --> http://www.fujjdesign.co.uk/jsbin.html

Many thanks

**Comment by dagatsoin** [comment]
Ok, this is not a new one!
Hy guys, I notice that (typescript in my case) is barely never updated, even if "saved" is displayed after an edit. Forcing a CMD+R continually (ex: https://jsbin.com/denetoy/edit?js,console)

**Comment by francoisp** [comment]
I've noticed the same on a local install, as opposed to the live version which sends you to a output.jsbin.com url, which might be a workaround ?

**Comment by remy** [comment]
@dagatsoin the console doesn't live render (which is what you have open).

I believe the original issue is old and long ago fixed, so I'm closing for now.

**Comment by arnavsatpute** [comment]
Similarly the title too does not reflect changes in real-time even on basic HTML,

For eg, below default HTML code with title text changed

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Change of Title</title>
</head>
<body>

</body>
</html>
