### ISSUE TITLE
SyntaxError: Illegal break statement

### ISSUE THREAD

**Issue by konijn** [jsbin/jsbin#1906]
Please provide any additional information, record a screencast with http://quickcast.io or http://screenr.com and attach a screenshot if possible.

**JS Bin info**
- [http://jsbin.com/yofosa/1](http://jsbin.com/yofosa/1)
- Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2143.0 Safari/537.36
- konijn

Greetings, when trying to execute http://jsbin.com/yofosa/1/edit I get the error mentioned in the subject. I am fairly sure this used to work.

The generate code has

try {/\* Permute will give all permutations ;window.runnerWindow.protect({ line: 1, reset: true }); for the provided array ( sourceSet )
do not provide usedSet nor permutationSet
Based on http://stackoverflow.com/a/9960925/7602
*/
function permute( sourceSet , usedSet , permutationsSet ) {;
if (window.runnerWindow.protect({ line: 1 })) break;

  permutationsSet = permutationsSet || [];
  usedSet = usedSet || [];

I am guessing my starting the code with a comment that has `for` in it is messing up your loop protection code. I read your blog and I was thinking, hmm, they could simply use esprima.js..

T.

**Comment by runsun** [comment]
Encountered this bug at a code below :<code><pre>this.footer= $('&lt;div>'
              , { id: `${this.id}_footer`
                , className: 'Panel_footer' 
                , css: { padding: '3px'
                        , background: '#666' 
                        , border:'2px #666 inset'
                        , display: opt.showFooter?'flex':'none'
                        } // <==== {{{ Uncaught SyntaxError: Illegal break statement }}}
                 }
              ).appendTo(this.wrapper)[0]
</pre></code>

This is part of javascript for a panel class, in which I have `.header`, `.content` and `.footer`, all have the same structure, but only the `.header` above generates the error.

Also, if I copy and paste the entire javascript code to a new file, there is no error.
