### ISSUE TITLE
JS function undefined, despite being defined ?

### ISSUE THREAD

**Issue by piotrpalek** [jsbin/jsbin#1948]
When you try to run the code in this bin: http://jsbin.com/romun/5 it will fail saying that the `assertEqualArrays` function is undefined (in FF, faild with "function is undefined in chrome) which is nonsense, since that function should be accessible from anywhere in the file.

**JS Bin info**
- [http://jsbin.com/romun/5](http://jsbin.com/romun/5)
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0
- piotrpalek

**Comment by doubleOrt** [comment]
@getify In the hoisting chapter of Scope & Closures, it is stated that "Function declarations that appear inside normal blocks typically hoist to the enclosing scope".
