### ISSUE TITLE
Embed on small screens, consider wrapping up menu

### ISSUE THREAD

**Issue by codylindley** [jsbin/jsbin#1955]
Would it be to much trouble to wrap up the menu system into a native dropdown like jsfiddle does when the jsbin appears on smaller devices?

https://www.dropbox.com/s/td6d97ecpbtxkmv/Screenshot%202014-09-25%2009.01.50.png?dl=0

**Comment by iamvdo** [comment]
What about rearranging items with CSS for now? 
Not create a complex dropdrown system, but only make sure there is no superposition. It's such a pain when using jsbin embedded in small screens.

I can make PR quickly if anyone agree.

**Comment by remy** [comment]
I'd be happy to review a PR.
