### ISSUE TITLE
Change "Asset manager" to "Assets"

### ISSUE THREAD

**Issue by dannyhope** [jsbin/jsbin#1990]
Change 
- [x] "Asset manager" to "Assets" (in the nav)
- [x] "/account/asset-manager" to "/account/assets"
- [x] "Your hosted assets" to "Assets" in the page title

RS additions:
- [x] Upload feedback if the user doesn't have the feature
- [x] Investigate possibility of moving the cursor as the mouse position changes to allow for accurate position DnD

**Comment by robdodson** [comment]
@remy is there an ETA on the asset management stuff?

**Comment by remy** [comment]
Have you got a pro account, if you do, just turn on experiments (in your profile) and assets will work.

I'll likely release to stable in the next week or so.

**Comment by robdodson** [comment]
@remy very cool. I'm going to take a look at this to see if we can switch our Polymer samples from Plunker to JSBin Pro.
