### ISSUE TITLE
Custom bin names for pro users

### ISSUE THREAD

**Issue by jpnelson** [jsbin/jsbin#2057]
Currently pro users have the ability to make bins such as `foo.jsbin.com/<random hash>/`

Would you consider letting a pro user make a bin with a custom name? For example, `foo.jsbin.com/name`?

**Comment by robiupui** [comment]
Actually, I just tried this workaround and when I do it the way that was suggested on 10/21, the JS console keeps giving the error "Warning: Something went wrong while saving. Your most recent work is not saved."
