### ISSUE TITLE
jsbin API

### ISSUE THREAD

**Issue by jpnelson** [jsbin/jsbin#2063]
What is the status of the jsbin API at the moment? http://jsbin.com/help/api indicates that there are GET and POST methods for bins, but I am having trouble getting this to work due to CORS issues.

Specifically, I am looking to get something like this to work:

```
$.ajax({
        url: 'http://jsbin.com/api/yutami/save', //yutami is a bin that I own
        type: 'POST',
        data: {
            'html': $('#html').text(),
            'javascript': $('#javascript').text(),
            'css': $('#css').text()
        },
        success: function (data) {
            console.log(data);
        }
    });
```

Alternatively, I have tried constructing the bin contents with the `html`, `js`, `css` URL parameters, but it appears as though these have no effect.

**Comment by dgrubelic** [comment]
2.5 years later... what is the status of this issue? :) Is it possible to create bins on jsbin.com via API?

**Comment by remy** [comment]
Yes, the API is available here:
http://jsbin.com/help/experimental-features#api

**Comment by dgrubelic** [comment]
Is it available to all or only to "Pro" users? I don't see a way to generate api key in my profile.

**Comment by remy** [comment]
@dgrubelic no, this is only available to pro users. It's also an experiment (as per the docs).
