### ISSUE TITLE
with 4-width tabs set in settings, pressing tab inserts 2 spaces

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/jsbin#2076]
I was able to reproduce this with a fresh bin, but, oddly, not with the editor preview on the [settings page](http://jsbin.com/account/editor).

**Comment by Daniel-Hug** [comment]
Remy, is this on someone's to do list? To answer your 2014 question: Even with [no spaces anywhere in this bin](http://jsbin.com/ladube/edit?html,output), pressing tab still inserts a space.

**Comment by remy** [comment]
It's not on anyone's todo. Currently, it's just me on jsbin, and I'm prioritising either the very interesting parts or sans-UI elements. I need to do a push to get contributors and I'd love to see you have some commits in the project given your long history with file issues (thank you) on the project.

Quickly trying, I can't replicate - it gives me two spaces both when I tab and shift+tab. I'm controlling my settings exclusively in the preferences now - I assume you are?
