### ISSUE TITLE
create a custom URL for a bin.

### ISSUE THREAD

**Issue by mikeBehar** [jsbin/jsbin#2079]
Previously I was able to create a custom URL for a bin.

Here is an example where the custom part is  "quizmaker"
http://jsbin.com/quizmaker/10/edit?html,css,js,output

I do not recall how I created this custom part and I don't see instructions in the documentation or FAQs.

Was this a feature or a bug?  
I hope it is a feature and still available.  If so, can you tell me how to do the customization?

Thanks,

Mike

**JS Bin info**
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0
- withforesight

**Comment by robiupui** [comment]
There's a hack/workaround mentioned in https://github.com/jsbin/jsbin/issues/2057
