### ISSUE TITLE
Sorry, that GitHub account is linked to another JS Bin account.

### ISSUE THREAD

**Issue by vicpuntnl** [jsbin/jsbin#2098]
When I to log in to my Jsbin via github, I get the message: 'Sorry, that GitHub account is linked to another JS Bin account.'. 
What does that actually mean?

Till now it always worked well, and even in another browser I can still login.

**Comment by johanbove** [comment]
Hello @remy I'm experiencing the same issue. My GitHub user name is @johanbove.
The error message is displayed when I click the big Github Login or Register button.
When I click "use your email address", the page reloads, but nothing else happens.
Thanks!

**Comment by HaPpOne** [comment]
I'm experiencing the same problem, actually.
Any suggestion?
THX

**Comment by thiagodebastos** [comment]
I've started experiencing this problem as of last night. I am not trying to create an account, just log into my account, with Github, like I always have in the past.

**Comment by judsonmitchell** [comment]
Specifically, deleting the jsbin cookies fixes this problem.
