### ISSUE TITLE
Inconsistency between ES6 code and the code validator

### ISSUE THREAD

**Issue by jaydson** [jsbin/jsbin#2114]
There's some kind of inconsistency in the editor when we're using ES6 both with traceur and 6to5.
![editor inconsistency](https://cldup.com/0JXVN7TaU8-2000x2000.png)

I get this using Firefox 33.0 on Ubuntu.

PS: This issue is intermittent.

**Comment by lberning** [comment]
you could add the following line into your jsbin to tell jshint about ES6:
/* jshint esnext: true */
