### ISSUE TITLE
Uncaught SyntaxError: Missing catch or finally after try

### ISSUE THREAD

**Issue by Palestinian** [jsbin/jsbin#2173]
I get this error when I wrap JS pane code in HTML pane's `head`.

HTML pane

```
<head>
  <!-- js libraries -->
  <script>%code%</script>
</head>
```

Javascript pane

```
(function ($, undefined) {
  /* ... */
}).(jQuery);
```

If I place code in HTML pane, the code works as expected.

http://jsbin.com/talonu/1/edit?html,js,console,output

**Comment by codetrash** [comment]
its not fixed yet till today...I hope it will get fixed
