### ISSUE TITLE
"CodeMirror-gutter" element interferes with code

### ISSUE THREAD

**Issue by impressivewebs** [jsbin/jsbin#2188]
At wide browser widths, the element shown in this screenshot interferes with the code in the JS window:

http://i.gyazo.com/c2b50fcaa071a92178345ec6839e59a6.png

Notice the element appears slightly overlapping the code, so I'm not able to select the start of the line, unless I move the cursor using the keyboard arrows. This doesn't seem to happen at smaller window widths.

It's quite noticeable because the cursor is usually an I-beam, but when above that "gutter" element, it's just a regular arrow, indicating that I can't select.

**Comment by impressivewebs** [comment]
I'm still seeing this problem... Any update on this?

**Comment by remy** [comment]
I've not looked at it. I'm open to a PR that can fix this (and tests across
the different gutter states).

**Comment by impressivewebs** [comment]
I'm on vacation now, but I'll see what I can do when I get back. Meantime, I've created a bookmarklet to remove the element for those who want it fixed:

https://gist.github.com/impressivewebs/4964d82509ba252a966d

**Comment by sukima** [comment]
@impressivewebs Why not just turn the gutter feature off instead of hiding DOM element.

```javascript
(function() {
  var settings = JSON.parse(localStorage.getItem('settings'));
  settings.hintShow.gutter = false;
  localStorage.setItem('settings', JSON.stringify(settings));
})();
```

**Comment by impressivewebs** [comment]
@sukima Sure, whatever works. But I don't know what the gutter feature is, or how to access it so I just did whatever I could to get it out of the way.

**Comment by sukima** [comment]
For completeness:
![screen shot 2015-02-17 at 8 59 10 am](https://cloud.githubusercontent.com/assets/70075/6229244/72fa45f0-b683-11e4-875e-e959829c31fc.png)

**Comment by impressivewebs** [comment]
@sukima Ah, I see, I had no idea about that. Ok, thanks, looks like that's the best solution for me.
