### ISSUE TITLE
I can't add close tag for html in jsbin with hungarian keyboard

### ISSUE THREAD

**Issue by NeoCsatornaja** [jsbin/jsbin#2195]
So I thing I found a very noing bug in jsbin.
For example if I would like to open a p tag like this:
<code>< p ></code>(sorry for the space in p, but I can't write out in there without space)
I can't close it becouse stack in there:
<code>< p </code>
So every time when i would like to close it, must be copy this character from a tag, and this not help too much fix some stiky bug.
I try set this atribute on the console:
jsbin.settings.keys = { disabled: true };
But I get back this erorr:
Uncaught TypeError: Cannot set property 'keys' of undefined.
I have a hungarian keyboard and I think is this is the problem.

**Comment by bigfooot** [comment]
_hu keyboard (QWERTZ)

AltGr + Y =    AltGr + : 
AltGr + Í =   AltGR + M
