### ISSUE TITLE
Provide JSBin embeds JS, CSS, HTML, etc

### ISSUE THREAD

**Issue by justinbmeyer** [jsbin/jsbin#2200]
I'm working on a documentation engine that I would like to show demo and example code in a JSBin for viewers of the generated documentation to play with. 

Is there a way to create a JSBin embed where the html, js, and css source is read from the embedding page?  For example, if someone wrote:

```
@example
console.log('hello world');
```

I could generate:

``` html
<a class="jsbin-embed" href="http://jsbin.com?html,js,output" js="console.log('hello world')">JS Bin</a>
```

If this is not possible, would you consider this feature?  I believe this is how Angular is able to do similar behavior with Plunkr [example](https://docs.angularjs.org/api/ng/directive/ngDisabled).

Thanks for your help and for creating an amazing tool.

**Comment by remy** [comment]
Huh, sorry, I said the w/e, then I got slapped with Christmas! I'll pick this up this week!

**Comment by remy** [comment]
...and I totally didn't.

Did you get anywhere with this (looking at the scoop links)?

**Comment by Alfredo-Delgado** [comment]
We played around with it, yesterday, and found that while the functionality in the docs hasn't been successfully implemented in embed.js, it is possible to pass code to jsbin.com via url parameters.

e.g.
http://jsbin.com/?html,css,js,console,output&html=%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3Cmeta%20charset%3D%22utf-8%22%3E%3Ctitle%3EJS%20Bin%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody%3E%3Cp%20class%3D%22pretty%22%3EHello%2C%20DOM.%3C%2Fp%3E%3C%2Fbody%3E%3C%2Fhtml%3E&css=.pretty%20%7B%20color%3A%20pink%3B%20%7D&javascript=console.log('hello%2C%20console')%3B

**Comment by m-mujica** [comment]
Hey @remy, hope everything is going well! 

Question: is it possible to embed an jsbin with dynamic content? e.g the link that Alfredo shared before, can we embed that? 

In the example here http://jsbin.com/help/how-can-i-embed-jsbin, the `href` is set to a jsbin that already exists (http://jsbin.com/iwovaj/73/embed?js,html,output).

**Comment by m-mujica** [comment]
@remy, sorry for not being clear, I'm actually working in the documentation engine that Justin mentioned before, the idea is that you can wrote something like:

```
@example
   console.log('hello world')
```

then, I'd generate something like 

```
<a class="jsbin-embed foo" 
   href="http://jsbin.com/?console&javascript=console.log('hello%2C%20console')%3B">
    Hello world
</a>
<script src="http://static.jsbin.com/js/embed.js"></script>
```
to create a jsbin embed of the given code in the generated documentation. 

I want to be able to pass it through the url, so when I change the code in the docs; lets say:

```
@example
   console.log('hello world updaded')
```

The resulting embed has the updated code. Makes sense?

**Comment by remy** [comment]
@m-mujica does the code in the documentation change in real-time, or do you mean in some kind of build process?

**Comment by m-mujica** [comment]
@remy nope, it won't change in real-time (or by any build process). 

Currently it seems that the only way that I can create an embed is with a saved jsbin, I want to know if it's possible to create an embed with code provided through URL params (or by any other mechanism); that's pretty much it.

**Comment by remy** [comment]
@m-mujica oh, you want to only inject a portion of code, not the entire thing? i.e. into a pre-existing template bin...if you follow. Is that right?

**Comment by remy** [comment]
Otherwise, what you've already got looks right to me...which is why I think I've misunderstood...!

**Comment by m-mujica** [comment]
@remy the problem is, the following snippet does not work

```
<a class="jsbin-embed foo" 
   href="http://jsbin.com/?console&javascript=console.log('hello%2C%20console')%3B">
    Hello world
</a>
<script src="http://static.jsbin.com/js/embed.js"></script>
```

I tried it out in jsbin itself (how cool is that?), this is the bin link http://jsbin.com/jonoworefi/1/edit?html,console,output; if you open the browser's dev tool, there is an error in the console:

`Refused to display 'http://jsbin.com/?console' in a frame because it set 'X-Frame-Options' to 'DENY'.`

How can I workaround this? Thanks for your help.

**Comment by remy** [comment]
Oooh, it's because it's hitting the edit page, which is blocking iframes, where as the embed page doesn't. Hmm. Yeah, okay, I see the problem.

I'm working on a PR that changes the embed view right now, so I'll see if I can safely get this working.

**Comment by lipp** [comment]
:+1: embedding dynamic content would be great to have! @remy any plans on this? Hitting @m-mujica X-Frame-Options Deny right now. 

Would really love to use this in addition / alternative to tonicdev on https://doclets.io Thanks for making the awesome JSBin!

**Comment by MomchilGorchev** [comment]
Hey @remy, +1 here, its would be great if jsbin allows bin creation with dynamically passed code.
You replied you are working on something related? How this is going ?
