### ISSUE TITLE
reloadAddons is not defined in editor-settings.js

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/jsbin#2203]
Similar to #2155:

To replicate:

1. Go to http://jsbin.com/account/editor
2. Check or uncheck a checkbox under 'Addons'
3. observe the console error:

> Uncaught ReferenceError: reloadAddons is not defined

Here's the relevant file & line: https://github.com/jsbin/jsbin/blob/master/public/js/account/editor-settings.js#L197

**Comment by remy** [comment]
This is fixed now (actually a while ago).
