### ISSUE TITLE
weird editor drag over / wild cursor bug

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/jsbin#2214]
Replicate:
1. Create a new bin: http://jsbin.com
2. Select some text in the address bar and drag it over the editor panel in focus, but don't drop it. Instead drop it somewhere where it won't have any effect.
3. Click in the editor panel to give it focus again, and notice that the blinking text cursor follows the mouse cursor around.

**Comment by bryc** [comment]
I have had this same issue for months. Happens when dragging files/text anywhere on the JSBin page, even the top right hand corner.

It can really mess things up when you're typing and end up moving your cursor. Only way to fix is refresh or toggle the textarea mode

**Comment by remy** [comment]
You can try (in the console) jsbin.panels.panels.html.editor.refresh() but
I'm unsure this will fix the issue and moreover, I've no clue what's at the
root cause.

**Comment by OscarGodson** [comment]
This is strange. This just happened to me making it impossible to edit further without refreshing. `jsbin.panels.panels.html.editor.refresh()` didn't work and I'm not sure how I even got into the state. I was just editing like normal it seemed like
