### ISSUE TITLE
Changing Editor Settings spacing only effects auto-indent, not actual tab-key

### ISSUE THREAD

**Issue by joelarson4** [jsbin/jsbin#2222]
If you go into editor settings and set spacing to 4 spaces, and go back to editor the auto indent does give you 4 spaces.  But actually pressing tab only gives you two spaces.  I'll take a closer look next week to see if I can find out why.  Probably just need to pass setting to codemirror somewhere.

....

Please provide any additional information, record a screencast with http://quickcast.io or http://screenr.com and attach a screenshot if possible.

**JS Bin info**
- [http://jsbin.com/kikava/1/edit](http://jsbin.com/kikava/1/edit)
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
- joelarson4

**Comment by kenmorechalfant** [comment]
This has been a problem for me as well. I also use 4 spaces and it only gives 2 when pressing tab.
