### ISSUE TITLE
Legitimate bins 410'ing

### ISSUE THREAD

**Issue by gdub22** [jsbin/jsbin#2224]
I have lost all of the bins in this series, specifically:
http://jsbin.com/hexifuvi/5

The bin used the location history api and an iframe.  I'm hoping to get the code back, and also to help improve this service's blacklisting.

They were made in March 2014 for this Modernizr PR which needs to be resurrected:
https://github.com/Modernizr/Modernizr/pull/1270

**Comment by remy** [comment]
Cheers for filing. I need to dig into the database to understand why these are 410'ing. 

The bin is there (I can see it in the db), but I'm not sure why it's saying it's blocked...

Oh. I know, spotted it. It's hitting a blacklist term.

The quick solution is for me to assign these bins to an existing user, and whitelist the user, and the bins will appear again. Are these yours and are you happy to own them?

**Comment by gdub22** [comment]
@remy awesome! Yes, they are mine and you can assign them to my user (same as github handle).  Thanks for sorting - glad to get the code back.

**Comment by remy** [comment]
There's 16 of them, are they all yours or from 1-5?

**Comment by remy** [comment]
Looking at 16, it looks pretty much the same, I'll assign them all and you can delete any that you don't want.

**Comment by gdub22** [comment]
That works. Thanks!

**Comment by remy** [comment]
Sorted. Not a quick fix, but pretty pleased I have the mechanism in place to sort it :)

**Comment by remy** [comment]
Feel free to upgrade to Pro too if you want to say thanks :-) !!
