### ISSUE TITLE
Archiving issue keeps happening.

### ISSUE THREAD

**Issue by gemallory** [jsbin/jsbin#2227]
JSBin will not save, prompting there was an error with the archive, and if this continues, to send the information onward, unfortunately I wasn't able to take a screenshot, since jsbin is not working for me anymore at all, and I can't actually access JS bin at the moment, since I closed my browser (to make sure that wasn't the issue).

Currently using Google Chrome. 

**JS Bin info**
- [http://jsbin.com/bepabu/1/edit](http://jsbin.com/bepabu/1/edit)
- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
- xerostyle

**Comment by remy** [comment]
Please provide any additional information.

...as per the actual text in your issue.
