### ISSUE TITLE
Editing and archived bin unarchives it.

### ISSUE THREAD

**Issue by apipkin** [jsbin/jsbin#2230]
See conversation here: https://twitter.com/apipkin/status/553587140475777024

**_Need_**
I want to use JSBin for code previews and share with coworkers, but I do not want the bin to be publicly discoverable. 

**_Attempt_**
I tried using "private", but that requires me to share my user/pass with team members. Using archive hides the list from public view, but if I edit the archived bin it unarchives it. 

**_Bug_**
Noticeably, this is probably a desired effect, but going to File to select Archive again is not an option – you must refresh the page for the option to become available. 

**_Thoughts_**
Bins could have a new state: published. 

`published` sharable, available in User Bins, available in My Bins
`unpublished` shareable, not available to others in User Bins, available in My Bins
`archived` sharable, not listed in My Bins or User Bins, accessed via link in My Bins
`private` not sharable, not available to others in User Bins, available in My Bins

Unarchiving a bin, will place it as unarchived and unpublished unless the bin was previously listed at private

**Comment by remy** [comment]
Definitely seems duff (the bug).

I suspect your states are similar to this suggestion: https://github.com/jsbin/jsbin/issues/1498

I do want to introduce the idea of sharable bins that are "unlisted" (ala youtube) - which I think is the same as your `unpublished`.
