### ISSUE TITLE
"Sharing" does not share in real time...

### ISSUE THREAD

**Issue by aekaterini** [jsbin/jsbin#2234]
Hi,
I am looking to use jsbin on an iPad and project what the code I type (on another pc) in real time in a classroom setting.
I click on share (after logging in with my account on ipad) > and use the "edit" link provided, but I don't see the changes updated on the PC (forget about real time)...
I also tried the Codecast link but nothing seems to work. The bin on the pc remains analtered.

What am I doing wrong?
Will the pro version help solve this issue?

Thanks,
K

**Comment by remy** [comment]
Pro won't solve this. I'll take a look at the real-time updating. It might be that the iPad is the problem, but I can't say for sure just yet.

**Comment by remy** [comment]
If you try it on two PCs and not an iPad, does it work as expected?

**Comment by b2mgithub** [comment]
We are having the same problem.  No matter what we do the only setting that will give live updating is if you click output only.  The editor codecast is not working whatsoever. We are not using an ipad.  We are using both PC and Mac. Neither is working.

**Comment by TrevorSayre** [comment]
Since you're using CodeMirror, perhaps consider: https://github.com/share/share-codemirror
