### ISSUE TITLE
Add Normalize library

### ISSUE THREAD

**Issue by mdo** [jsbin/jsbin#2235]
Just noticed that there's not an option for adding the [Normalize.css library](http://necolas.github.io/normalize.css/). It's probably the most commonly used CSS reset project. Would love to see it added.

/cc @necolas

---

**JS Bin info**

* [https://jsbin.com/edit](https://jsbin.com/edit)
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.10 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.10
* mdo

**Comment by remy** [comment]
Please add it then.
