### ISSUE TITLE
Miss the previous feature- resize Pane horizontally  

### ISSUE THREAD

**Issue by yidea** [jsbin/jsbin#2237]
Previously, the pane can be resized horizontally layout (2 pane in horizontal view), but looks like now it became only allow you do vertically layout. really miss that capability, wonder if there's a way to get it back

![screen shot 2015-01-16 at 9 22 40 am](https://cloud.githubusercontent.com/assets/1945035/5780669/433331fa-9d61-11e4-883e-5d62040799ab.jpg)

**Comment by remy** [comment]
Sadly, it was lost: https://github.com/jsbin/jsbin/issues/2021

I wanted to keep it, but users didn't :cry:

**Comment by jonleung** [comment]
I wish I could keep it as well!

**Comment by Nijikokun** [comment]
This was the best feature.

**Comment by remy** [comment]
I think saving was the best feature.
