### ISSUE TITLE
Use *latest* url from bootstrapcdn for Bootstrap library

### ISSUE THREAD

**Issue by peterblazejewicz** [jsbin/jsbin#2238]
I've just noticed that bootstrapcdn has symlink:
https://github.com/MaxCDN/bootstrap-cdn/blob/develop/public/twitter-bootstrap/latest
I'll check how it works and do PR! Thanks!

**Comment by cvrebert** [comment]
Refs #2239

**Comment by peterblazejewicz** [comment]
I agree with @cvrebert comments referenced above, so this is closed
Thanks!
