### ISSUE TITLE
When trying to log-in, I overlook the yellow button

### ISSUE THREAD

**Issue by dannyhope** [jsbin/jsbin#2240]
…because I’m looking for a normal looking login link – something innocuous.

Other users could have this same experience.

It could be a case of [benner blindness](http://en.wikipedia.org/wiki/Banner_blindness "")

**Comment by remy** [comment]
Odd, last I looked, our sign ins increased. It was a while back now though,
maybe something changed.

Did you find the login in the end?

**Comment by dannyhope** [comment]
This could be a good candidate for an A/B test. A: yellow, B: grey/no background

**Comment by remy** [comment]
I actually like, and don't miss the yellow button and like I said, our numbers went up for sign in.

I'm happy re-visit this if there's a load (say 5-10?) of +1 on the issue (i.e. other people miss the sign in too).

Aside, I'm happy to have a help doc that lists things we could A/B test. Obviously the priority will learn towards things that we both feel that can make jsbin better.

**Comment by remy** [comment]
Ref https://github.com/jsbin/jsbin/issues/1414 for a good example how to track A/B test (for success).
