### ISSUE TITLE
Run JSBin Locally - unable to save

### ISSUE THREAD

**Issue by emnh** [jsbin/jsbin#2242]
When I edit the HTML or JS I get the following red error message at the top:

"I think there's something wrong with your session and I'm unable to save. Refresh to fix this, you will not lose your code." Clicking refresh doesn't help.

JS console shows "POST http://192.168.100.128:3000/save 403 (Forbidden)".

Server log, same, forbidden:
192.168.100.1 - - [Sun, 25 Jan 2015 00:59:43 GMT] "POST /save HTTP/1.1" 403 2982 "http://192.168.100.128:3000/?html,js,output" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36"

**Comment by emnh** [comment]
Setting the session secret didn't help.

Production or development doesn't make a difference.

Setting logger to "dev" in config.local.json didn't give any more output.

Fixing timezone didn't help.

Any tips for how to debug it?

**Comment by emnh** [comment]
Found the error in the request response:

**Comment by emnh** [comment]
It works in IE but not in Chrome.

**Comment by emnh** [comment]
Tried it on a public facing web host and there it worked, also in Chrome.
Other than that, node binaries were 32-bit on this working server, only other difference I know.

**Comment by baixiaoji** [comment]
so answer is needing on a public facing web host ? today, I having the same error in Chrome  59.0.3071.104, and  I am on a public facing web host, even  though I having some doubts about meaning of  the  'public facing web host '?

**Comment by emnh** [comment]
I don't remember much about this, but I think the JSBin site had to be accessed through a public domain name (or maybe public IP address was enough?). Sorry, I don't remember.
