### ISSUE TITLE
Blacklisted?

### ISSUE THREAD

**Issue by tacogithub** [jsbin/jsbin#2245]
Getting "NetworkError: 400 Bad Request - http://jsbin.com/koxinu/4/save"
Unable to save: Post contains blacklisted content
My username is @tacogithub

thanks,
Jon

**Comment by tacogithub** [comment]
Nevermind. cannot legally add a script tag inside <body>

**Comment by tacogithub** [comment]
nm. cannot legally add script tag inside of body tag.

**Comment by remy** [comment]
Yes, you can. Provide the code you're trying to save here in github and I
can confirm the issue.

**Comment by tacogithub** [comment]
i narrowed the issue down to window.location.href inside of an anonymous function return.

**Comment by jcaponi** [comment]
> i narrowed the issue down to window.location.href inside of an anonymous function return.

Thanks you! This just solved my problem.
