### ISSUE TITLE
Feature Request: Vim Editor

### ISSUE THREAD

**Issue by emnh** [jsbin/jsbin#2246]
I have a [working demo](http://alexis.lart.no:3000/?html,js,vim,output) of Native Vim integration with JSBin running under [jor1k](http://github.com/s-macke/jor1k/) linux RISC emulation.

Is this something that could be accepted upstream if jor1k and friends are git submodules and the loading is made only on user request? Would you have jor1k live as submodules in jsbin repository, or prefer optional loading from another server, say github IO pages? I can send a pull request.

**Comment by emnh** [comment]
I have put my demo source code up on github as a [feature branch of JSBin fork](https://github.com/emnh/jsbin/tree/feature/jor1k).

**Comment by remy** [comment]
I tried this on my mac + chrome and it didn't actually work. 

Since codemirror already has a vim mode, I'm not sure it makes a lot of sense to add this in. I appreciate the work you've done, and it's definitely an interesting experiment, but I'm not sure it's the right thing for jsbin right now.

**Comment by emnh** [comment]
Ok. Thanks anyway!

What was the error you got?

I am going to try to integrate with [vim.js](https://github.com/coolwanglu/vim.js) as well since it might be more stable and faster, but in the end I might end up creating a Chrome or Firefox extension that can replace CodeMirror dynamically.
