### ISSUE TITLE
Multiple console-wrappers

### ISSUE THREAD

**Issue by hemanth** [jsbin/jsbin#2247]
![image](https://cloud.githubusercontent.com/assets/18315/5935849/4318e2de-a705-11e4-9999-564455f48ed2.png)

Multiple `console-wrapper` are being appended. 

//cc @remy

**Comment by remy** [comment]
?? Not sure how to replicate this, nor am I really a pro at 6to5. Totally open to help! :)

**Comment by hemanth** [comment]
*The below is the repo step* (I'm willing to contribute as well, not sure if this is specific to 6to5 though)

![repro](https://cloud.githubusercontent.com/assets/18315/5937299/e30bdd1a-a713-11e4-92d8-9f68ce9fd7f4.gif)

//cc @sebmck

**Comment by sebmck** [comment]
@hemanth Not a 6to5 issue. I wish I could help but I'm not at all familiar with JSBin. Only thing I was able to discern was that as you said, multiple `.console-wrapper`s are being added.

**Comment by hemanth** [comment]
Thanks @sebmck. 

@remy Now it's on us to debug further.

**Comment by remy** [comment]
Oh, sorry, I misunderstood. This is actually the UI that's messing up, rather than any code generation! I'll take a look.

**Comment by remy** [comment]
@hemanth can you share your jshint preferences? I've got custom ones set, so I'm currently not able to replicate.

**Comment by hemanth** [comment]
@remy any way to export them? It must be in my localstorage?

**Comment by remy** [comment]
Ah, no, I meant this:

![screen shot 2015-01-28 at 15 27 27](https://cloud.githubusercontent.com/assets/13700/5940340/39330a0e-a702-11e4-9053-34602ddf659c.png)

**Comment by hemanth** [comment]
Yeah, gave the json representation of the same.
