### ISSUE TITLE
Problem seeing images on jsbin

### ISSUE THREAD

**Issue by Merciaugust29** [jsbin/jsbin#2257]
I can't see the images I'm adding to my site on jsbin. I've designated the full path of the image but I can't see it. How do I go about doing it? I want to see the images on the site as I'm developing the site.

**Comment by remy** [comment]
I can't see the bin url you're referring to.

**Comment by remy** [comment]
Idle.

**Comment by Merciaugust29** [comment]
I wish you could help me see images on jsbin. I started a new bin called
  tejete
I have an image saved on my desktop at
 C:/Users/serge/Desktop/img/player.png
Then at jsbin(javascript) I created an image element with var image =
document.createElement("img");
I then set the source with
 image.src="C:/Users/serge/Desktop/img/player.png";

I then used the context of the canvas element that I had like this
 ctx.drawImage(image, 10,10);
But I don't see anything. Please help me. What's the problem?

**Comment by remy** [comment]
You can't. This is a security feature of the web. You need the image online
somewhere.
