### ISSUE TITLE
What does the arrow on the top right do?

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#2258]
I've captured replies via twitter: https://storify.com/rem/what-does-the-arrow-mean obviously only a very small sample set (I'm sure there's been more replies since to the original [tweet](https://twitter.com/rem/status/563383306461667328)).

I don't think this is being tracked via analytics, but I'd be willing to bet there's <1% usage on this UI element, maybe even as low as <0.1%.

If I can find time, I'll add tracking to this link and review the usage over 30 days. If my hypothesis is correct, I propose removing the element in favour of a reduced UI (since the feature is still available via the URL and the share menu).

As per #2240 I think a help doc with list of things we want to A/B test + hypothesis would be useful here.

**Comment by remy** [comment]
A useful [comment from twitter](https://twitter.com/justmarkup/status/563388372463661056) too.

> I use it quite often so I know it opens the output in a new tab. Maybe move "run w js, auto run" to js tab and name the arrow?

I'm not sure I like this (personally), but it's a change I hadn't thought of (though suspect @dannyhope *may* have thought of this along with the proposal of moving the library selection under the JS panel - which I've blocked in the past).

**Comment by keithamus** [comment]
What about moving the arrow to inside the output tabs title?

**Comment by remy** [comment]
Putting a clickable *inside* of another clickable object isn't a good idea.

**Comment by keithamus** [comment]
Here is a Chrome tab, which features a clickable area and a close button inside it.

![screen shot 2015-02-08 at 10 32 08](https://cloud.githubusercontent.com/assets/118266/6096218/c45cefea-af7d-11e4-9aa1-6949ae4aff81.PNG)

**Comment by remy** [comment]
Which, I agree work, but are a total pain when they're small (which our
tabs are).

Also, its more noise to the ui that I don't want.

**Comment by remy** [comment]
To add, it's a decent suggestion, but the work required doesn't outweigh
the benefit. Whereas the confusion around what it currently does vs just
removing it (and also gaining simplicity in the ui) *is* worth the work.

**Comment by dannyhope** [comment]
I wish I could get to JS Bin

**Comment by dannyhope** [comment]
I wish I could get to JS Bin :(

**Comment by peterblazejewicz** [comment]
The Glyphicons has a *new window* glyph ('glyphicon glyphicon-new-window') which can be better suited I believe:
http://jsbin.com/cesihi/?output
http://glyphsearch.com/?query=window

**Comment by mikerkeating** [comment]
Setu ping back to Freeformers: https://github.com/Freeformers/ff-jsbin-private/issues/40
