### ISSUE TITLE
No autohiding header

### ISSUE THREAD

**Issue by juanwmedia** [jsbin/jsbin#2262]
Hi, I'm struggling with a simple but annoying problem: **can't make the header bar (where the main menu is located) stops autohiding all the time**. I searched JSBin preferences but didn't found anything related. Thanks.

**Comment by remy** [comment]
If you're on a mac - it's `cmd+ctrl+\` and it'll show it again.

**Comment by juanwmedia** [comment]
It works!, thanks!.
