### ISSUE TITLE
Cannot use the word "for" in a javascript comment

### ISSUE THREAD

**Issue by ZachWatkins** [jsbin/jsbin#2264]
I noticed that there was an error being caused by my code, and after incrementally removing pieces of it I discovered the error was only occurring when a certain line of javascript comment code was present. The line was "/\* Is there even a need for this? */". I reproduced the results in a reduced test case available here: http://jsbin.com/gufawu/1/edit?js,console,output

Tested in Firefox 35.0.1, Chrome 40.0.2214.111 m, and IE9. Each browser produced a different error message.

Firefox: "k</b.render/<@http://static.jsbin.com/js/prod/runner-3.25.14.min.js:1:13838
    j</a.use/<@http://static.jsbin.com/js/prod/runner-3.25.14.min.js:1:10893"
Chrome: "SyntaxError: Illegal break statement
    at http://static.jsbin.com/js/prod/runner-3.25.14.min.js:1:13840
    at http://static.jsbin.com/js/prod/runner-3.25.14.min.js:1:10893"
IE9: "Can't have 'break' outside of loop"

Not a pressing issue, but it took a while for me to figure out what was causing the problem.

**Comment by trentv4** [comment]
Confirming this as a bug, tested via this code:
```
document.write("Testing...");
/* Is this even a need for this? */
document.write("Test passed!");
```
With the comment, it refuses to execute. Without, works as expected.

**Comment by remy** [comment]
It's a false positive on our loop protection. For now (i.e. until I get a fix landed) you can work around it by adding a comment `// noprotect` anywhere in the JS panel.
