### ISSUE TITLE
My picture

### ISSUE THREAD

**Issue by ramtob** [jsbin/jsbin#2267]
Hello. I've subscribed recently. I notice that my picture appears on jsbin pages. Where was the picture drawn from? Can I change it? Thanks.

**Comment by remy** [comment]
It's via gravatar. Right now the only way to change it is via gravatar - we don't have support for changing your avatar directly in jsbin (yet).

**Comment by ramtob** [comment]
Can you access my gravatar without my permission?

**Comment by remy** [comment]
Do you understand how gravatar works? I assume not. You encode your email
address as an md4 string and that's used as the url to gravatar (take a
look at their short docs).

So, short answer is: yes, that's the point of the gravatar service.

**Comment by ramtob** [comment]
Thank you. I thought that every access to my gravatar needs my permission.
