### ISSUE TITLE
Babel (formerly 6 to 5) seemingly needs its polyfill module added with its use in JSBin 

### ISSUE THREAD

**Issue by lozandier** [jsbin/jsbin#2268]
For some behavior like [nodeList having their iterator set](https://github.com/babel/babel/issues/790) ([solved within this issue thread](https://github.com/babel/babel/issues/545)), the current implementation of 6to5 on JSBin seems to *not* include babel/polyfill which [is supposed to, based on the docs automatically load with the current version it seems](http://babeljs.io/docs/usage/polyfill/).

This seemingly means that the version of Babel (labeled still as 6to5 on JSBin) would benefit from being updated or requiring this polyfill whenever the transpiler is used for JavaScript typed in the JavaScript panel.

**Comment by remy** [comment]
I'd happily merge a PR if you know what needs to be done?

**Comment by lozandier** [comment]
I don't not knowing how the different JS environments are being handled within JSBin; It seems your `6to5.min.js` file  inside `js/vendor` can be updated with an updated compilation of Babel since it doesnt seem the [`browser.js` version in the docs isn't being used](https://babeljs.io/docs/usage/browser/)?

**Comment by MoOx** [comment]
I would be interested to get an up to date version of babel.
Maybe vendors/*.min.js should be automated to avoid having to update by hand ?

**Comment by Vivi270** [comment]
JSBin seems to not include babel/polyfill which is supposed to, based on the docs automatically load with the current version it seems.

This seemingly means that the version of Babel (labeled still as 6to5 on JSBin) would benefit from being updated or requiring this polyfill whenever the transpiler is used for JavaScript

**Comment by remy** [comment]
This did get updated lately, do you want to check that it's okay now?

**Comment by lozandier** [comment]
Yeah, it now does a few weeks ago; I thought this issue was closed with
that update (referenced in the commit).

On Wednesday, June 17, 2015, Remy Sharp <notifications@github.com> wrote:

> This did get updated lately, do you want to check that it's okay now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2268#issuecomment-112962011>.
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>
