### ISSUE TITLE
JS in an HTML tag

### ISSUE THREAD

**Issue by sneakyhashtag123** [jsbin/jsbin#2269]
I know how there's a JS file, but I can't seem to be able to include JS code in a script tag in the HTML file.

**Comment by remy** [comment]
Example bin?

**Comment by sneakyhashtag123** [comment]
<!DOCTYPE html>
<html>
<head>
  <script src="ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js">
//whatever code I write here won't work, but if I copy/past the exact thing over to the JS file, it works.
</script>
	<style>
	
	</style>
  <title></title>
</head>
<body>

</body>
</html>

**Comment by remy** [comment]
That's not how script tags work. If you have a SRC attribute then you can't add JavaScript inside the script tag. You need a new script tag altogether.

**Comment by sneakyhashtag123** [comment]
OK.
