### ISSUE TITLE
Typescript Version throwing errors

### ISSUE THREAD

**Issue by nicholascm90** [jsbin/jsbin#2270]
Hi, I'm trying to use Typescript as the language in my jsbin and even when taking code directly from typescripts website (which is presumably error free), and it doesn't work for me. 

Am I doing something wrong or is this a known issue?

**Comment by remy** [comment]
I think typescript is out of date, and since it was contributed by a user,
I'm unsure how to update to the latest anymore.

**Comment by nicholascm90** [comment]
Ah, that's unfortunate. I'm fairly new to programming and was hoping to use
jsbin for typescript practice. Thanks anyways!

On Tue, Feb 17, 2015 at 1:26 PM, Remy Sharp <notifications@github.com>
wrote:

> I think typescript is out of date, and since it was contributed by a user,
> I'm unsure how to update to the latest anymore.
> On 17 Feb 2015 18:15, "nicholascm90" <notifications@github.com> wrote:
>
> > Hi, I'm trying to use Typescript as the language in my jsbin and even
> when
> > taking code directly from typescripts website (which is presumably error
> > free), and it doesn't work for me.
> >
> > Am I doing something wrong or is this a known issue?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jsbin/jsbin/issues/2270>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2270#issuecomment-74721942>.
>



-- 
Nicholas C. Morrell
Email: NicholasCM90@gmail.com
Cell: (850) 496-6910
