### ISSUE TITLE
How do I see images on my bin?

### ISSUE THREAD

**Issue by Merciaugust29** [jsbin/jsbin#2275]
I've saved an image on my desktop. How do I make this image appear on my bin?
My bin is      tejete
The location of the image is C:\Users\serge\Desktop\img\player.png

Please help. I haven't been able to use jsbin yet as I can't see image on the screen. How is it done?
How do I point jsbin to the location of the image that I want to display?

Help pleasezzzzzzzzzzzzzzzzzzz

**Comment by peterblazejewicz** [comment]
hi,
You can't. JSBin.com is a website and cannot access your (or anyone else) content on local machine. JSBin itself does not host images - so you will have to upload that image somewhere and link to it in your code.

**Comment by moonerjvck** [comment]
i tried writing a code linking an image to it but my jsbin wont load the image up
