### ISSUE TITLE
Deletion request for accidentally created bin

### ISSUE THREAD

**Issue by jacobq** [jsbin/jsbin#2276]
I didn't realize that I was not logged in when I first started editing, and it seems that I've now created a public, anonymous bin that I cannot delete. Would it be at all possible for me to email the id of it to an administrator to remove it for me? (It contains some non-secret but work-related data, which I'd rather not expose.) 

Also, it might be nice if users who've logged in on a browser in the past could set some local storage flag or cookie to indicate that they don't want to create anonymous bins but rather be prompted to login first.

**Comment by remy** [comment]
Sure, email remy@leftlogic.com
