### ISSUE TITLE
js bin installation failed

### ISSUE THREAD

**Issue by javedshamim** [jsbin/jsbin#2277]
Hiiiii..

I have installed nodejs with Current Version: v0.12.0. And after that I am trying to install jsbin with command  npm install -g jsbin but it is throwing below error and not letting me to proceed further.Please assist.

Your environment has been set up for using Node.js 0.12.0 (x64) and npm.

C:\Users\cem_india>npm install -g jsbin
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
/
> sqlite3@2.2.7 install C:\Users\cem_india\AppData\Roaming\npm\node_modules\jsbi
n\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: C:\Program Files\nodejs\node.exe --eval require('C:/Us
ers/cem_india/AppData/Roaming/npm/node_modules/jsbin/node_modules/sqlite3/lib/bi
nding/node-v14-win32-x64/node_sqlite3.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.

C:\Users\cem_india\AppData\Roaming\npm\node_modules\jsbin\node_modules\sqlite3\l
ib\binding\node-v14-win32-x64\node_sqlite3.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile

child_process: customFds option is deprecated, use stdio instead.

C:\Users\cem_india\AppData\Roaming\npm\node_modules\jsbin\node_modules\sqlite3>n
ode "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild --name=sqlite3 --configuration=Release --mo
dule_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=n
ode --node_abi=node-v14 --platform=win32 --target_platform=win32 --arch=x64 --ta
rget_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.a
mazonaws.com/ --module_path=C:\Users\cem_india\AppData\Roaming\npm\node_modules\
jsbin\node_modules\sqlite3\lib\binding\node-v14-win32-x64 --remote_path=./sqlite
3/v2.2.7/ --package_name=node-v14-win32-x64.tar.gz --staged_tarball=build\stage\
sqlite3\v2.2.7\node-v14-win32-x64.tar.gz --hosted_path=https://mapbox-node-binar
y.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s
3.amazonaws.com/sqlite3/v2.2.7/node-v14-win32-x64.tar.gz
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Rel
ease" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--
patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=win32" "--target_pla
tform=win32" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--h
ost=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=C:\\Users\\cem_
india\\AppData\\Roaming\\npm\\node_modules\\jsbin\\node_modules\\sqlite3\\lib\\b
inding\\node-v14-win32-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=no
de-v14-win32-x64.tar.gz" "--staged_tarball=build\\stage\\sqlite3\\v2.2.7\\node-v
14-win32-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/
sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/s
qlite3/v2.2.7/node-v14-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\cem_india\AppData\Roaming\npm\node_modules\jsbin\node_modu
les\sqlite3
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=sq
lite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major
=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=win32 --tar
get_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --ho
st=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users\cem_india
\AppData\Roaming\npm\node_modules\jsbin\node_modules\sqlite3\lib\binding\node-v1
4-win32-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-win32-x64.ta
r.gz --staged_tarball=build\stage\sqlite3\v2.2.7\node-v14-win32-x64.tar.gz --hos
ted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_ta
rball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-win32-
x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cem_india\AppD
ata\Roaming\npm\node_modules\jsbin\node_modules\sqlite3\node_modules\node-pre-gy
p\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1080:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\Users\\cem_india\\AppData\\Roaming\\npm\\n
ode_modules\\jsbin\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node
-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cem_india\AppData\Roaming\npm\node_modules\jsbin\
node_modules\sqlite3
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=sqlite3 --configuration=Release -
-module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtim
e=node --node_abi=node-v14 --platform=win32 --target_platform=win32 --arch=x64 -
-target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s
3.amazonaws.com/ --module_path=C:\Users\cem_india\AppData\Roaming\npm\node_modul
es\jsbin\node_modules\sqlite3\lib\binding\node-v14-win32-x64 --remote_path=./sql
ite3/v2.2.7/ --package_name=node-v14-win32-x64.tar.gz --staged_tarball=build\sta
ge\sqlite3\v2.2.7\node-v14-win32-x64.tar.gz --hosted_path=https://mapbox-node-bi
nary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binar
y.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-win32-x64.tar.gz' (1)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jsbin"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cem_india\npm-debug.log

C:\Users\cem_india>

**Comment by remy** [comment]
Try an older version of node (0.10) or try pulling directly from the repo.

**Comment by dlaflamme** [comment]
I had the same issue. I couldn't get an "npm install -g" to work. I cloned the repo, upgraded the dependency on sqlite to "3.x.x", and did an npm install. It failed because it couldn't find several grunt-contrib pugins, Installed those locally, then then was able to do "grunt build". I can run jsbin from the locally built copy. Not great, but it looks like it works.
