### ISSUE TITLE
I've lost my archive!!! -- Changing my GitHub account name has resetted my account

### ISSUE THREAD

**Issue by JoseViewer** [jsbin/jsbin#2278]
I've lost my JsBin archive before changing my name in GitHub.
At first my GitHub nick was JoseViewer. I used it for signing up to JsBin. Recently, I changed my nick to "EliasELM" (not a secret). I found my JsBin account as "EliasELM" signed and no contents.

As you can see, I've revert my nick. Clever idea, but has not worked.

HELP

**Comment by remy** [comment]
Sorry for the slow response.

Did you get your bins back? If not, *which* username did they live under before?

**Comment by JoseViewer** [comment]
Wow, so kind of you!!! 
Ok. In first place,I opened an account in Github as JoseViewer; that was in 2014/07/17. I had to reset my password like three times. A few weeks later I decided to to register in JsBin, I was writing some pieces of code... In 2015/01/15 I decided to install the Windows Github app, in order to learn anything about this Git and stuff (I didn't learn anything), and I was informed that "a new public key was added to my account.
So I tried to understand how to put this soft to work, and I think I was advise to change my alias, or my email... I become "EliasTellmymom" and change my email... Since Github ask me to verify my identity...
After all this changes, I realize that I have lost my access to JSBin ¿¿¿¡¡¡
Ok, i change my email again, I don't know why, and I pass to be "EliasELM". Then JSBin tell me that I am not "JoseViewer", that I am "EliasELM". Finally I decided to change to my first alias "JoseViewer" expecting JSBin to recognize me, but it does not work...
So at the end I uninstall the "·$% github app.
However I am not sure that this was the correct sequence of events. I can send you all my mails from Github, with all the codes and numbers, If it helps.....

I don't remember exactly what i had in my JSBIN account, but I know that I had some good ideas that I would recall if I can see the archive again.
Maybe this is to much to ask to anybody who does not know me, but if you could find these files.....THANK YOU

By the way, english is not my native language.
