### ISSUE TITLE
annoying clones

### ISSUE THREAD

**Issue by jasoncheng938** [jsbin/jsbin#2280]
sometimes when I'm editing a bin I save a snapshot, and when I come back I type something in the editor, and the bin gets cloned. this is annoying because I want to embed my bins in my website, but if the url changes I have to update it every day.

**Comment by remy** [comment]
If you don't own the original (i.e. version 1) bin, then it'll clone the bin. If you do, it won't ever clone unless you tell it to (at which point you'll own version 1 and it won't clone).
