### ISSUE TITLE
Refresh problems

### ISSUE THREAD

**Issue by javajosh** [jsbin/jsbin#2281]
Getting a refresh problem with http://jsbin.com/zokijo/edit?html,js,output

When I load the "share" url http://jsbin.com/zokijo it doesn't load properly and the console says
"The connection to http://jsbin.com/zokijo/latest?0.8465055927075699 was interrupted while the page was loading." (The number changes on every refresh).

I really love jsbin, so I hope this issue can go away soon!

**Comment by javajosh** [comment]
I actually rebooted my computer and it seems to be working now. I guess I'll leave this issue though, just in case.

**Comment by javajosh** [comment]
And now it's broken again, said the session crashed, and code updates aren't pushing to the 'share' URL without the editor.

**Comment by remy** [comment]
Sorry for the lack of response.

Is this a live-reload issue or that it's not saving anymore?
