### ISSUE TITLE
Results are not working when the code contains missing semi-colons

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2282]
Missing semi-colons (bad practise or not it's not the question) make the right Output Result view fail to run the code, the live preview on a separate window still works, but it's less practical.

Example: http://jsbin.com/yawewe/3/edit?js,output, the only errors shown in the code are missing semi-colons

Edit: after testing, some shorter code with missing semi-colons can still be previewed, so I don't really know what makes it fail

**Comment by remy** [comment]
I suspect this is a very isolated case. Can you share the bin you see this
happening on?

**Comment by cauburtin** [comment]
Yes, you're seeing this through email notifications, but I've edited it with an example bin

**Comment by remy** [comment]
This is a bug in the loop protection (sorry), if you add the following code `//noprotect` it'll work.

**Comment by cauburtin** [comment]
great, ok
