### ISSUE TITLE
Editor settings not saved

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2283]
I've tried many times setting Spacing to tabs and changing indent width, it does update on the settings page, even with a hard refresh but after a while it gets back to the old settings

**Comment by cauburtin** [comment]
Now, *Spacing* and *Indent width* have been updated on the editor pages (now they are tabs and width:4), but it still doesn't work on bins, pressing TAB I still get the old settings (2 spaces)

**Comment by cauburtin** [comment]
![screen capture](http://i.imgur.com/LJs8R7G.png)

**Comment by cauburtin** [comment]
It's almost working

When I type

     while(){ // and press enter
          // it gets indented right

but in the middle of the code, if I press tab, I still get the old 2 spaces...

**Comment by remy** [comment]
I think the fix to #2260 will fix this too...hopefully!

**Comment by cauburtin** [comment]
Yes it's working now, god job
