### ISSUE TITLE
request: display jsbin embed for bbcode 

### ISSUE THREAD

**Issue by kudataz** [jsbin/jsbin#2284]
hy jsbin
I need your help..
example i have this link 
```
http://jsbin.com/wihowe/3/ 
```
generate in share output only..
how to use jsbin in bb code editor..
here i try but not work :(
```
	$pattern[] = '#\[jsbin\]http://jsbin.com/(.*?)/([0-9]*)\[/jsbin\]#ms';
	$replace[] = '<a class="jsbin-embed" href="http://jsbin.com/$1/$2/embed?output">JS Bin</a><script src="http://static.jsbin.com/js/embed.js"></script>';
```
please your help ^^

**Comment by remy** [comment]
This sounds like either a PHP question or a bb code editor question. Either belongs on StackOverflow or the appropriate user board for either those two I mentioned.

Sorry I can't be more help.
