### ISSUE TITLE
Random css errors

### ISSUE THREAD

**Issue by xavio** [jsbin/jsbin#2285]
Hi!
Please correct me if this is a duplicate or just me, but couldn't find anything similar.

Getting a weird error when using sass/scss where jsbin says 
`Line 4: Invalid CSS after "100%": expected expression (e.g. 1px, bold), was ";"`

Code:
`* {box-sizing: border-box;}`
`html,`
`body {`
 `height: 100%;`
`}`

If I remove that line, the errors just jumps down along the code to a new spot.
Just tried a new bin and pasted the above code, switched to sass and the error lit up. http://jsbin.com/yuteka/1/edit

**Comment by electricg** [comment]
Hi, are you using sass or scss syntax?
Because if you want to keep that code, you have to select scss from the panel, otherwise if you select sass, the code is different (no braces or semicolon, for example).

**Comment by xavio** [comment]
Thought I tried scss at first, but when switching back to it now, the error disappears. Guess it's fine for now then, I'll let you know if anything comes up again. Thanks!

**Comment by xavio** [comment]
Reopening for now. Maybe found some more details, but now I'm quite sure there's some problem when using emmet commands.

Just used `mh100vh` and expanded it, but the error log said `invalid css after " mh"`. Seems like it gets stuck on short commands even after they've been expanded. Tried it a few times and doesn't seems like it happens all the time though.

Still unsure if this is just me, so sorry in advance if the error's on my end.

**Comment by xavio** [comment]
And when just testing a new bin, created mh100vh really quick, expanded and typed `asdasd` for some reason below.

This triggered and error, unsurprisingly. Expanded the error log, saw what it was and removed `asdasd`but the error didn't go away. Still said there was incorrect css at `asdasd`.

Seems like errors just simply don't clear when the code is corrected sometimes.
