### ISSUE TITLE
Add clone URL

### ISSUE THREAD

**Issue by kentcdodds** [jsbin/jsbin#2287]
I would like to have a URL that will automatically clone the jsbin. Something like this:

```
https://jsbin.com/:jsbinId/clone
```

I don't think it's necessary to explain use cases, but I'll mention one anyway :-)

The template feature is cool, but I like to code angular/react/bootstrap/vanilla/etc in jsbin and a single template is not enough. So I end up creating bins that I intend to clone to do all of these things, but I have to remember to clone them and sometimes I forget and wind up screwing up my template. With this feature, I could bookmark the clone URL and not worry about it :-)

**Comment by remy** [comment]
I was about to implement this when I realised why I can't/won't. It would completely open up JS Bin to abuse. Once an abuser creates a single bin, all they need to do is repetitively hit the bin url + clone and they'll create a tonne of bins through that url.

It's valid right now to click on the clone menu item, and it'll do a tiny bit of validation, but adding `/clone` to the url would lose that entirely.

Sorry, unless you have any suggestions, right now, I'm not prepared to add this into jsbin - sorry (again) :-(

**Comment by kentcdodds** [comment]
Understood. Thanks. If only everyone in the world was awesome and we didn't have to worry about abuse :-(

**Comment by kentcdodds** [comment]
Just thought about this... How is this any worse than me just hitting jsbin.com? It automatically creates a brand new bin for me when I do this. How is that different from cloning an existing bin?

**Comment by remy** [comment]
We use csrf to prevent you automating the process.

**Comment by kentcdodds** [comment]
Revealing my noobish nature. Why can't we do that with the clone url?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by remy** [comment]
Because the clone url would be instantaneous - as soon as you land on the url, it'll clone the bin for you right there and then (on the server).

I *guess* one work around would be to invoke a JS function in the jsbin client, that then triggers a clone from the menu, which *would* include the csrf and thus prevent some automation...

It could work, but it's not particularly high up on my priorities right now (currently fighting a redonculous wave of spammers).

**Comment by kentcdodds** [comment]
#jerks. Anyway, would love to have this eventually. Thanks for the work you
do!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by mkhatib** [comment]
Stumbled upon this, has this been reconsidered? It would be a really nice to have. 

One use case I'd love to have this for is to create a named short-url that I can use to always create a jsbin quickly from a template jsbin. For example something like tinyurl.com/new-css-anim

**Comment by kentcdodds** [comment]
One workaround I've found is create a jsbin with a different account (or even logged off in incognito mode or something) like [this one](http://jsbin.com/subenepide/edit?html,output). Start making changes then hit "save" and it'll clone a copy. This was sufficient for me and my use case.
