### ISSUE TITLE
issue in embedding JSBIN in wordpress

### ISSUE THREAD

**Issue by saan1984** [jsbin/jsbin#2289]
when i tried to embed JSBIN in my wordpress blog it is not rendering?Is it a issue? how to fix it?

Check the below link for see the issue:

http://www.tutorialsavvy.com/2015/02/random-number-generator-using-lodash-utility.html/

**Comment by remy** [comment]
*Where* is the embed supposed to be happening? I only see links to jsbin, I don't see the embed script being included...

**Comment by saan1984** [comment]
sorry it is my mistake.forgot to add class  class="jsbin-embed"

On Tue, Mar 3, 2015 at 1:11 AM, Remy Sharp <notifications@github.com> wrote:

> *Where* is the embed supposed to be happening? I only see links to jsbin,
> I don't see the embed script being included...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2289#issuecomment-76795616>.
>



-- 
Thanks
*Sandeep Kumar Patel*
www.tutorialsavvy.com
________________________

**Comment by remy** [comment]
...and the script that does the actual embedding..?

**Comment by saan1984** [comment]
Hi Remy,

The real issue is with the Blogger Importer plugin for wordpress. This
plugin is not importing few HTML elements, for my case it was the code for
JSBIN embed.

Thanks
Sandeep

On Tue, Mar 3, 2015 at 2:27 PM, Remy Sharp <notifications@github.com> wrote:

> ...and the script that does the actual embedding..?
> On 2 Mar 2015 19:55, "sandeep" <notifications@github.com> wrote:
>
> > sorry it is my mistake.forgot to add class class="jsbin-embed"
> >
> > On Tue, Mar 3, 2015 at 1:11 AM, Remy Sharp <notifications@github.com>
> > wrote:
> >
> > > *Where* is the embed supposed to be happening? I only see links to
> jsbin,
> > > I don't see the embed script being included...
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/jsbin/jsbin/issues/2289#issuecomment-76795616>.
> > >
> >
> >
> >
> > --
> > Thanks
> > *Sandeep Kumar Patel*
> > www.tutorialsavvy.com
> > ________________________
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jsbin/jsbin/issues/2289#issuecomment-76799186>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2289#issuecomment-76908549>.
>



-- 
Thanks
*Sandeep Kumar Patel*
www.tutorialsavvy.com
________________________
