### ISSUE TITLE
problem with html5 course example

### ISSUE THREAD

**Issue by ramjr2012** [jsbin/jsbin#2293]
Hi,

I'm learning/reviewing HTML and HTML5 through courses from John Bura of Mammoth Interactive.  One of his example uses this JavaScript code:

var aCanvas = document.getElementById("aCanvas");
var context = aCanvas.getContext("2d");
context.fillStyle('red');
context.fillRect(0,0,100,100);

The HTML page is:

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
  <canvas id="aCanvas">
  </canvas>
</body>
</html>

In his example, run, I think, on an older jsbin.com, this draws a red square.

When I plug it into the current jsbin.com I don't see anything.

Since I'm just learning most of this and in particular am not a JavaScript programmer, I don't know if this is a problem with what I've typed (I've reviewed it a dozen times, so I may be missing something), a problem with the original presentation material, or with the web page.

Any help would be greatly appreciated.

Bob

**Comment by ramjr2012** [comment]
Oops, it seems I need to escape the HTML, somehow.  Please let me know if it is needed and if so how to escape the code.

Thanks.

Bob

**Comment by kmgear** [comment]
Same issue.

**Comment by remy** [comment]
Can you share a jsbin url (from your code) so I can see?

**Comment by kmgear** [comment]
Hi Remy

Here's the link

https://jsbin.com/tufalaxito/1/edit?html,css,js,output

**Comment by kmgear** [comment]
https://jsbin.com/tufalaxito/1/edit?html,css,js,output

**Comment by kmgear** [comment]
my stupidity, forget it, had an '=' after fillRect
