### ISSUE TITLE
JS Panel Gutter Problem.

### ISSUE THREAD

**Issue by manix84** [jsbin/jsbin#2295]
The left hand gutter on the JS panel seems to sit over the first few characters. When I type "abcdefg", I can only see "cdefg" clearly (as in the screenshot below). I've seen this problem in three theme's so far (Solarized Light, Solarized Dark, and The-Matrix).
![screenshot 2015-03-06 14 03 47](https://cloud.githubusercontent.com/assets/373278/6527169/9aa8fe44-c410-11e4-8503-a14c2ccb6eab.png)

My settings at the time, in case they change the outcome:
![screenshot 2015-03-06 14 04 11](https://cloud.githubusercontent.com/assets/373278/6527178/a56d8d9a-c410-11e4-8fd0-1aa9f9f7ccd7.png)
Theme - Solarized Light/Solarized Dark/The-Matrix

**Comment by manix84** [comment]
I noticed yesterday that this problem appears when you enable gutter markings for jshint.

**Comment by abhisekp** [comment]
duplicate of https://github.com/jsbin/jsbin/issues/2295

**Comment by danielnieto** [comment]
After 3 years, this issue still persist, it is very annonying
![image](https://user-images.githubusercontent.com/2120107/39087573-84a0e382-4568-11e8-82d3-ba5458288fa8.png)

**Comment by remy** [comment]
@danielnieto yes, very annoying. I wish they'd just open source the project so someone like you could fix it. Sheesh.
