### ISSUE TITLE
Others cannot view shared output

### ISSUE THREAD

**Issue by clehnert-psl** [jsbin/jsbin#2300]
Hello,

Share links that I have given to others are displaying a "This page isn't here" message.

Here are the URLs in question:
http://jsbin.com/nokuzu/4/
http://jsbin.com/nokuzu/4/edit?html,css,js,output

I then added an email address to the account—hoping that would allow me to share the URLs. No luck with the new ones:
http://jsbin.com/xovipa/1/
http://jsbin.com/xovipa/1/edit?html,css,js,output

**Comment by remy** [comment]
I've noticed a bug and am working on a fix. What's your username?

**Comment by clehnert-psl** [comment]
Hi Remy,

Thanks. My username is "clehnert-psl".

--------------------------------------------------------------
*Charles Lehnert*
UI UX Development Lead
P\S\L Group America
--------------------------------------------------------------


On Thu, Mar 12, 2015 at 1:22 PM, Remy Sharp <notifications@github.com>
wrote:

> I've noticed a bug and am working on a fix. What's your username?
> On 12 Mar 2015 17:12, "clehnert-psl" <notifications@github.com> wrote:
>
> > Hello,
> >
> > Share links that I have given to others are displaying a "This page isn't
> > here" message.
> >
> > Here are the URLs in question:
> > http://jsbin.com/nokuzu/4/
> > http://jsbin.com/nokuzu/4/edit?html,css,js,output
> >
> > I then added an email address to the account—hoping that would allow me
> to
> > share the URLs. No luck with the new ones:
> > http://jsbin.com/xovipa/1/
> > http://jsbin.com/xovipa/1/edit?html,css,js,output
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jsbin/jsbin/issues/2300>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2300#issuecomment-78535792>.
>

-- 


The information in this communication may be confidential and/or privileged 
and is intended only for the person(s) to whom it is rightfully addressed. 
If you are not the intended recipient, you may not read, copy, use or 
disclose any information contained in or attached to this communication. If 
you have received this communication in error, please notify the sender 
immediately and delete the entire original communication, including any 
files or documents attached to it, without reproducing, distributing or 
retaining copies of any part thereof.


The views or opinions expressed may solely be those of the author and not, 
unless specifically stated, reflect those of our group or of any of the 
companies in our group.


Please note that we reserve the right to monitor electronic communications 
passing through our network

**Comment by remy** [comment]
That's fixed. Sorry you got caught in that bug!

**Comment by clehnert-psl** [comment]
Thanks, Remy.

------------------------------------------
Charles Lehnert
UI UX Development Lead
P\S\L Group America
------------------------------------------

On Mar 13, 2015, at 5:24 PM, Remy Sharp <notifications@github.com> wrote:

That's fixed. Sorry you got caught in that bug!

—
Reply to this email directly or view it on GitHub
<https://github.com/jsbin/jsbin/issues/2300#issuecomment-79416647>.

-- 


The information in this communication may be confidential and/or privileged 
and is intended only for the person(s) to whom it is rightfully addressed. 
If you are not the intended recipient, you may not read, copy, use or 
disclose any information contained in or attached to this communication. If 
you have received this communication in error, please notify the sender 
immediately and delete the entire original communication, including any 
files or documents attached to it, without reproducing, distributing or 
retaining copies of any part thereof.


The views or opinions expressed may solely be those of the author and not, 
unless specifically stated, reflect those of our group or of any of the 
companies in our group.


Please note that we reserve the right to monitor electronic communications 
passing through our network
