### ISSUE TITLE
prevent rude words in session Id

### ISSUE THREAD

**Issue by miketrebilcock** [jsbin/jsbin#2301]
Eg the letters 'sex' in the session Id will result in the url being blocked by school firewalls. Not sure when the Id Gets generated but at the moment it is possible to start a new session and do a load of work, if you then refresh the page for any reason the content filters kick in and blocks the request meaning the work has been lost.. It would be great with some 'rude' keyboards could Be avoided.

**Comment by Delapouite** [comment]
Noble cause to defend, but very hard in practice. What about foreign languages with their own (enormous), black lists for rude words?

**Comment by miketrebilcock** [comment]
Very good point. I guess the real problem is over zealous content blocking, but with children under 11 I guess they prefer to be cautious.  Not sure what the answer is. Could the session generator be modified to always use vowels in pairs? Therefore there is no blacklist, but the likelyhood of spelling a word is reduced, or might that mean the likelyhood of duplicating session id is too high?

**Comment by remy** [comment]
There's a reason that sometimes the letters make up words, or fragments of
words: http://jsbin.com/help/pronounceable-urls
