### ISSUE TITLE
Feature Request: Multiple panels of the same type

### ISSUE THREAD

**Issue by rplotkin** [jsbin/jsbin#2302]
I'd like to have my code separate from my unit tests (both JS), so I need two javascript panels. I'm happy to branch and address this issue myself, though I'm hoping to first generate some commentary on whether this is a desirable feature for everyone. I can, for instance, see it causing problems with a query string ?html,js,js,css, since it currently reduces that to ?html, js, css, and would no longer do so. Maybe a special:{type} panel that can be specified in the config?

**Comment by remy** [comment]
The bigger problem is the database can't support that model right now (and not for a foreseeable future). We currently have 15million bins in the db, and making changes to the db take around 6-8 hours of a locked table (yes, it's bad).

I think plunkr has this functionality (I might be wrong), so I'm deferring to them, whilst we have this support for now: http://jsbin.com/help/linking-bins

**Comment by rplotkin** [comment]
I wonder if it *must* be a database change. This could conceivably happen entirely in the view code, with some tagging in the javascript file that indicates where the JS should be split (even multiple times). Could even allow for virtual multi-file support. ??

**Comment by remy** [comment]
Possibly. It's not something I want to pursue, but I'd be open to discussing and reviewing code.
