### ISSUE TITLE
Embed view not always working on Firefox

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2303]
Both embed jsbins here http://jsbin.com/romija/ work on Chrome. On Firefox only the 2nd

It seems complaining about

```
ReferenceError: init is not defined
```

**Comment by peterblazejewicz** [comment]
@cauburtin 
Can you move both `init` and `render` to the bottom - after declarations? The hoisting could work differently then you expect here in bins.

**Comment by cauburtin** [comment]
Indeed, that was it
