### ISSUE TITLE
Changing my editor settings cleared my current bin

### ISSUE THREAD

**Issue by jamesarthur** [jsbin/jsbin#2304]
I was playing around with Bootstrap, had about 30 minutes worth of work but I hadn't saved using Ctrl+S. I wanted to change some editor settings.
1. "Account", "Editor Settings"
2. I think I activated Tern, Highlight and Match Brackets
3. "<- Back to JS Bin"

Blank/default JS Bin. I couldn't find a way to recover my work. There was no trace in My Bins either.

**Comment by remy** [comment]
Jsbin saves as you type, so this is very odd. What's your username?
