### ISSUE TITLE
Weird characters in some places

### ISSUE THREAD

**Issue by kentcdodds** [jsbin/jsbin#2306]
This happens sometimes and I don't know why...

![screen shot 2015-03-16 at 6 09 37 am](https://cloud.githubusercontent.com/assets/1500684/6665777/19dab5c4-cba3-11e4-8199-23cc70a667df.png)

**Comment by codylindley** [comment]
I'm seeing this as well. How can this be fixed?

**Comment by remy** [comment]
I think it's a font loading thing, and near impossible to replicate and thus debug...
