### ISSUE TITLE
save route unavailable

### ISSUE THREAD

**Issue by kaleb** [jsbin/jsbin#2312]
I installed jsbin from github and attempted to save a bin, but the save path was unavailable. I get a 403 when attempting to save.  This is my config file:

```
{
        "url": {
                "host": "192.168.15.41",
                "prefix": "/",
                "ssl": false,
                "port": 3000
        },
        "env": "development"
}
```

**Comment by c0nfused** [comment]
Just ran in to a similar problem...

`POST http://192.168.0.103:3000/save 403 (Forbidden)`

So I try to access `http://192.168.0.103:3000/save` in my web browser and get a 404 error.

**Comment by malash** [comment]
I face the same problem and spent many time on it.
Finally, I found that Jsbin must be accessed by domain name.
(╯' - ')╯︵ ┻━┻
