### ISSUE TITLE
Free upgrade for lecturers?

### ISSUE THREAD

**Issue by alixbergeret** [jsbin/jsbin#2315]
Hi,

I am a senior lecturer at the University of Wolverhampton (UK) and was wondering if I could gain free access to the more advanced features for jsbin? Also, a detail of what those features might be? Can students collaborate on the same piece of code?

Cheers!

Alix

**Comment by remy** [comment]
Please send an email to support@jsbin.com with any link to show you're an
educator (link on a site is fine).

The full details of the features are on jsbin.com/upgrade

Live collaboration isn't available on jsbin at present though.
