### ISSUE TITLE
I can not save the bin

### ISSUE THREAD

**Issue by Mikola35** [jsbin/jsbin#2318]
Today, no longer save changes to the bin. In the new bin does not appear unique url

![image](https://cloud.githubusercontent.com/assets/4017693/6840299/75871936-d386-11e4-8305-1bae583eceb8.png)

**Comment by samholmes** [comment]
Experiencing this same issue. Looks like s database table is full on the jsbin.com back-end?

**Comment by matthiasbayer** [comment]
Please see #2320

**Comment by remy** [comment]
Thanks @matthiasbayer :)

Closing. We're back.
