### ISSUE TITLE
JSBin.com not fully loading 

### ISSUE THREAD

**Issue by karlgroves** [jsbin/jsbin#2324]
Google Chrome Version 41.0.2272.104 (64-bit)
Mac OSX 10.10.2

Dave just sits & spins.  Accessing any other URL in JSBin that loads the same interface has the same result. Cannot login, etc.

Confirmed this is limited to Chrome.  Checking Firefox and Safari work fine.

Console shows only 1 error
Uncaught TypeError: Cannot read property 'font' of undefined

This console error not present in Firefox or Safari console.

**Comment by remy** [comment]
I can't fix this second, but if you can clear your browsing history for chrome, it might get around the issue.

I have a feeling I know where the issue would be, but I'm fairly sure its linked to the local storage on the browse (note that just trying to clear local storage from the console won't do the trick, we aggressively save back on unload!)

**Comment by karlgroves** [comment]
Clearing browsing history in Chrome does the trick.
