### ISSUE TITLE
Site-wide pro subscriptions

### ISSUE THREAD

**Issue by jamesshannon** [jsbin/jsbin#2326]
We use jsbin at my company and I'd like to try to convince the to support you. It'd be much easier to do as a "site license" than individual accounts. Is there any mechanism to do this (both from the payment / cost perspective and from the "all registered accounts with @site.com are pro accounts")?

Thanks,
James

**Comment by remy** [comment]
Hi James,

That's great news to hear, but you're right there's no mechanism right now
for that functionality.

If you email me offline: remy@leftlogic.com - I can discuss some options
with you and I might be able add something that's bespoke and private.
