### ISSUE TITLE
Code lost when logging in

### ISSUE THREAD

**Issue by cfjedimaster** [jsbin/jsbin#2328]
I noticed I lost my code when I logged in. This video demonstrates it.

https://www.youtube.com/watch?v=E-qpm-uc5-Q&feature=youtu.be

**Comment by sinkingshriek** [comment]
Works for me while signing in from github account. 
![anim](http://i.imgur.com/7EzdJaU.gif)

**Comment by cfjedimaster** [comment]
For me, I tested w/ the other login, so it may be just that.
