### ISSUE TITLE
JavaScript sinlge line if statement throws a error

### ISSUE THREAD

**Issue by karthick-manoharan** [jsbin/jsbin#2331]
On using 

```
(eachLength>longWord)?longWord=eachLength:longWord;
```

throws a error Expected an assignment or function call and instead saw an expression.

But the code works.

**Comment by ashclarke** [comment]
It is a code quality recommendation:

https://jslinterrors.com/expected-an-assignment-or-function-call

Moving the assignment out should meet the requirements of the recommendation:

`longWord=(eachLength>longWord)?eachLength:longWord;`
