### ISSUE TITLE
HTML attributes with periods

### ISSUE THREAD

**Issue by kaleb** [jsbin/jsbin#2337]
I use a web framework that uses periods in attribute names such as:

    <div foo.bar="baz"></div>

JSBin HTML editor displays the following warnings when using this style:

> Line 8: Special characters must be escaped : [ < ].
> Line 8: Special characters must be escaped : [ > ].
> Line 8: Tag must be paired, No start tag: [ </div> ]

http://jsbin.com/qenemu/1/edit?html

**Comment by kaleb** [comment]
Adding the following rule seemed to help:

    {
      "spec-char-escape": false
    }

**Comment by remy** [comment]
Going to close as it looks like you've found a fix for the error reporting. Cheers!
