### ISSUE TITLE
Appears Github Auth is broken

### ISSUE THREAD

**Issue by zchrykng** [jsbin/jsbin#2341]
Starting today, Github switched to a new version of auth. I am guess that I why I can't log into jsbin starting today. Says the token is expired every time I attempt connecting.

**Comment by remy** [comment]
I can't replicate (via my phone) - but I'm on holiday, so I can't even
address this if it needs a fix until next week anyway.

Does anyone else want to confirm this and have a crack at a PR to fix?

**Comment by zchrykng** [comment]
Just updating with a screenshot.

![image](https://cloud.githubusercontent.com/assets/1266571/7261178/af7ad4ae-e83d-11e4-94a0-15128bd91e7b.png)

Not sure what is causing it... only reason I was trying to login is that with how much I use the service I should probably pay for it at some point ^_^

**Comment by rmethod** [comment]
This is happening with me as well. It says I need to register with jsbin and link my username to github, but I can't register with jsbin.

**Comment by remy** [comment]
@rmethod try again now - it should work.

**Comment by remy** [comment]
This means the github account isn't authorising. 

Can you log out of github completely and then log back in with your credentials (github, not jsbin), *then* try jsbin.

**Comment by zchrykng** [comment]
Sorry, I thought I had closed this already. Turns out it was some software on my computer that was somehow interfering with the auth.

Got it working and signed up for pro. <3

**Comment by remy** [comment]
That's great to hear, thank you so much!
