### ISSUE TITLE
Google API not accepting http requests

### ISSUE THREAD

**Issue by rleite** [jsbin/jsbin#2344]
Right now i can't use angular lib because of the "//" relative protocol picker.
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js"></script>

**Comment by remy** [comment]
What protocol picker? Do you mean the script that's inserted? 

Either way, I'm going to deploy a change to the libraries so that, where possible, they all use https instead of relative urls.

**Comment by remy** [comment]
I moved all the libraries across to https as I mentioned.
