### ISSUE TITLE
I can't log in, and forgotten password email link isn't working

### ISSUE THREAD

**Issue by brookjordan** [jsbin/jsbin#2345]
My account at bjmonkey@gmail.com isn't allowing me to log in, even using the forgotten password email link thing... It gives me the message that I'm not logged in, but I'm not actually logged in.

Any ideas?

Thanks,
- Brook

**Comment by kayshacampbell** [comment]
The same thing has happen to myself! Someone hep

**Comment by remy** [comment]
Hmm, I just tried this out and it worked for me (that's not to say you're wrong, more that the reset process should let you in).

Can you confirm your usernames on jsbin please?

**Comment by brookjordan** [comment]
Mine is:
bjmonkey@gmail.com
