### ISSUE TITLE
Question about Pro account for student.

### ISSUE THREAD

**Issue by LiveLover** [jsbin/jsbin#2350]
Hello!
I am am  Ivan student from MSU Moscow, Russia.
I study math, but I wanna be web developer.

Pro account functions like 'syncing with Dropdox' and 'making private Bins' seems to be very useful.

I read that You provide free Pro access for educational purposes.

It would be so nice to use You Great service in full access mode for self education.

May be it is really possible? Do I (We) need to prove our education activity some way?

And Great respect to You for you extremely useful jsbin.com !

**Comment by remy** [comment]
The pro for education is for educators - i.e. the teachers, so, sorry, but it's not available for free to students. 

One day perhaps, but not yet.
