### ISSUE TITLE
<meta> not inside <head> on Download

### ISSUE THREAD

**Issue by LiveLover** [jsbin/jsbin#2354]
http://www.w3schools.com/tags/tag_meta.asp says
Tips and Notes
Note: <meta> tags always goes inside the <head> elemen

**Comment by Daniel-Hug** [comment]
I can confirm. There's a robots `<meta>` tag before the `<html>` tag!:

```html
<!DOCTYPE html>
<!--
Created using JS Bin
http://jsbin.com

Copyright (c) 2015 by creativity (http://jsbin.com/dorucu/1/edit)

Released under the MIT license: http://jsbin.mit-license.org
-->
<meta name="robots" content="noindex">
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
robots meta is outside head element!
</body>
</html>
```

**Comment by remy** [comment]
Fix needs to go in here: https://github.com/jsbin/bin-to-file/issues/1 - happy to take a PR.

**Comment by kp25** [comment]
@remy is this issue already fixed ?

**Comment by remy** [comment]
I don't remember, but it's possible. I'll close and see what happens.

**Comment by Daniel-Hug** [comment]
This has not been resolved. See [this bin](http://jsbin.com/kigicud/edit?html,js,output) I just made.
