### ISSUE TITLE
Anonymous bin removal request

### ISSUE THREAD

**Issue by Warf135** [jsbin/jsbin#2355]
Hello, 

I created an anonymous bin to help a friend debug some code, not realising that i would not be able to delete it afterwards.
It contains some business contact details and although not anything 'delicate', i would prefer it to be removed please. 

Here is the bin URL: http://jsbin.com/poqoxavure/1/edit?html,js,output

I have now signed up to github and will now create a JSbin account for future use.

Thanks in advance!

Norm.

**Comment by remy** [comment]
That's done now.

**Comment by Warf135** [comment]
Thanks!

Sent with AquaMail for Android
http://www.aqua-mail.com
