### ISSUE TITLE
Characters hidden behind line-numbers bar in JS pane

### ISSUE THREAD

**Issue by glnster** [jsbin/jsbin#2356]
In the JavaScript pane, about 2 2/3 characters are hidden behind the line-numbers bar (see screenshot). I've tested in Chrome and Firefox (both latest). Happens whether or not line-numbers are activated.

![screen shot 2015-05-06 at 10 57 31 am](https://cloud.githubusercontent.com/assets/230488/7499963/9f625b7a-f3df-11e4-968f-8deb0974fc8b.png)
![screen shot 2015-05-06 at 11 04 41 am](https://cloud.githubusercontent.com/assets/230488/7499985/ba622f40-f3df-11e4-8f63-7b95afc026c9.png)

**Comment by glnster** [comment]
Just discovered, this only happens with gutter linting checked.

**Comment by abhisekp** [comment]
Also sometimes the gutter becomes too large.
Much more than number of lines.

_See the **red** highlighted region_

> [![](http://i.imgur.com/nDWzQD4.png)](http://i.imgur.com/nDWzQD4.png)

**Comment by abhisekp** [comment]
duplicate of https://github.com/jsbin/jsbin/issues/2295
