### ISSUE TITLE
Make default price in USD and make the price in 48px font

### ISSUE THREAD

**Issue by bnolan** [jsbin/jsbin#2357]
It took drunken Ben way too long to work out how much the service cost. I'm not saying I would've signed up, but still...

![screen shot 2015-05-07 at 6 37 37 pm](https://cloud.githubusercontent.com/assets/17499/7509685/2882136a-f4e8-11e4-941f-476e247159d9.png)

**Comment by remy** [comment]
Why make the default price in USD?

**Comment by remy** [comment]
Actually, don't worry, I can guess why you think that. nm.
