### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by pedrojvrccosta** [jsbin/jsbin#2358]
Hi, I'm starting to learn Javascript and found your software interesting, and I'm trying to evaluate it. I'm getting errors in the process. The log file is extracted below. Can you help please? 
I'm running a Xubuntu 14.04 64bits
Node.js version is the last one 0.12.2

I have already installed sqlite3 version 3.8.2 if it's important.

Many thanks
Log:
20010 silly cache afterAdd wordwrap@0.0.2
...
30103 verbose stack Error: sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
30103 verbose stack Exit status 1
30103 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
30103 verbose stack     at EventEmitter.emit (events.js:110:17)
30103 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
30103 verbose stack     at ChildProcess.emit (events.js:110:17)
30103 verbose stack     at maybeClose (child_process.js:1015:16)
30103 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
30104 verbose pkgid sqlite3@2.2.7
30105 verbose cwd /home/pvc/sw/jsbin
30106 error Linux 3.13.0-52-generic
30107 error argv "/usr/bin/node" "/usr/bin/npm" "install"
30108 error node v0.12.2
30109 error npm  v2.7.4
30110 error code ELIFECYCLE
30111 error sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
30111 error Exit status 1
30112 error Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
30112 error This is most likely a problem with the sqlite3 package,
30112 error not with npm itself.
30112 error Tell the author that this fails on your system:
30112 error     node-pre-gyp install --fallback-to-build
30112 error You can get their info via:
30112 error     npm owner ls sqlite3
30112 error There is likely additional logging output above.
30113 verbose exit [ 1, true ]
30114 verbose unbuild node_modules/sqlite3
30115 info preuninstall sqlite3@2.2.7
30116 info uninstall sqlite3@2.2.7
30117 verbose unbuild rmStuff sqlite3@2.2.7 from /home/pvc/sw/jsbin/node_modules
30118 info postuninstall sqlite3@2.2.7
30119 silly gentlyRm /home/pvc/sw/jsbin/node_modules/sqlite3 is being purged from base /home/pvc/sw/jsbin
30120 verbose gentlyRm don't care about contents; nuking /home/pvc/sw/jsbin/node_modules/sqlite3
30121 silly vacuum-fs purging /home/pvc/sw/jsbin/node_modules/sqlite3
30122 silly vacuum-fs quitting because other entries in /home/pvc/sw/jsbin/node_modules

**Comment by remy** [comment]
I probably wouldn't recommend using a local jsbin as a way of learning javascript...least of all to say it's hardly the best example of code!

Re: errors. We run on node 0.10.x and whatever version of npm came with it. I doubt if that's it, but certainly give it a try.
