### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by findjerry** [jsbin/jsbin#2360]
The website appears to be down as I can no longer access pages.

**Comment by JamesWP** [comment]
I concur :(

**Comment by nightstalker22** [comment]
:( How am I supposed to conquer the world now?

**Comment by mkfreeman** [comment]
I'm giving a tutorial Monday (5/11) at 12:00 PST that relies heavily on using jsbins.  Any updates on this?

**Comment by carolineartz** [comment]
@mkfreeman if it doesn't resolve, you could always build jsbin locally for your tutorial...I just it did because I need it tonight. :)

**Comment by mkfreeman** [comment]
Thanks, @carolineartz -- unfortunately, I've already built all of my interactive examples, and they're only hosted on jsbin (maybe I won't be doing that in the future...).   I'll also need to have students accessing the examples, so I'd rather not push out another JS bin.... Hopefully this gets tended to soon....

**Comment by arashz** [comment]
The site appears to be down here as well.

**Comment by saske505** [comment]
Same here... why today?  Think me and @mkfreeman rows the same boat.

**Comment by remy** [comment]
Sorry, late to the party. For (yet) unknown reasons the server has been topping out at 99% cpu. It's back to normal now after a process restart. I'll keep my eye on it today, but I've been noticing it more lately, yet there's been no code changes in the core application in a good while...
