### ISSUE TITLE
Output URL

### ISSUE THREAD

**Issue by rduque123** [jsbin/jsbin#2361]
Hi!

I noticed when I share my links, people are redirected from jsbin.com to output.jsbin.com and my code is shown in the subdomain (output.jsbin.com)

How can I show my code in the domain jsbin.com insted of in output.jsbin.com? Would it be possible if I upgrade to pro?

thank you

**Comment by remy** [comment]
What's the issue with the url? Is it technical or vanity?

**Comment by rduque123** [comment]
technical

**Comment by remy** [comment]
Can you elaborate? What is it you're specifically wanting from the jsbin.com origin?

**Comment by remy** [comment]
ping...

**Comment by remy** [comment]
I guess not...
