### ISSUE TITLE
suggestion: asset uploading

### ISSUE THREAD

**Issue by rndme** [jsbin/jsbin#2362]
since this is missing for free users, a screenshot or at least a better explanation of what asset loading is/does and how it works would make for a better sales pitch. right now, it's hard to tell what exactly that is, and it's hard to picture the potential benefits for me. not saying it's not useful, just that it doesn't look like much from where i'm sitting, and it could be the best pro perk...

**Comment by remy** [comment]
You mean, like this? http://jsbin.com/help/asset-uploading or this http://jsbin.com/blog/asset-upload-oembed (both posted on 4-Feb 2015).

I might/should add links to the features from the upgrade page actually.
