### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by dijatul** [jsbin/jsbin#2366]
Hi there,

I am sorry to say you that I am new to jsbin. I don't understand how I can I start to write codes. Need help asap.

thank you

**Comment by saske505** [comment]
I'm sure by now you figured it out but here goes.

1.  Sign in with your github account on jsbin.com - the login is located top right.
2.  You will now have top left options your main menu, script libraries that you can add that will load from cdn's and be added to your header, then your 4 different areas to separate your code

html 
css
javascript
preview

3. each of these panels has some more options like:

- html : (top right down arrow) has the options for selecting html, markdown, jade or convert to html
- css : has the option to convert to scss, sass, less or convert to css 
- javascript : a whole bunch.  

I think if this is the basics to get going, so create your html in your html panel, style in your css panel, script in your javascript panel, and see the awesomeness in the preview panel.  

Hope this helps and happy coding @dijatul 

 heres a cloned bin as example : http://jsbin.com/?html,css,js,console,output

**Comment by dijatul** [comment]
I am sorry that its not working properly. I am not able to do it.

**Comment by saske505** [comment]
Hi @dijatul , I made some gifs for you to see, I'm not sure what your having trouble with, but hope these help you to maybe get started.

![getting-stated](https://cloud.githubusercontent.com/assets/5356951/7672177/1175bf24-fce9-11e4-8af8-1e708ab43f93.gif)

![css-tab](https://cloud.githubusercontent.com/assets/5356951/7672176/0cefac08-fce9-11e4-86ab-86c83832a547.gif)

**Comment by remy** [comment]
@saske505 :heart:

**Comment by dijatul** [comment]
Thank you
