### ISSUE TITLE
Publish to Vanity homepage shortcut and remove popup that needs to be dismissed.

### ISSUE THREAD

**Issue by williamsharkey** [jsbin/jsbin#2367]
Can you 
A. Add a shortcut for publish to vanity homepage?
B. Avoid popup which obscures part of the window that then needs to be dismissed.
Example: if it were a small notification on the top bar, then we could ignore it if we want.
![image](https://cloud.githubusercontent.com/assets/1079130/7632363/58e3ff28-fa1a-11e4-8b12-edd5232d42a6.png)

**Comment by remy** [comment]
a) I didn't put a shortcut initially as it's not something that particularly happens often (i.e. there's only a few keyboard shortcuts we can actually use - so they better be *used* a lot).

b) You can hit `esc` to dismiss the noticies. It's a middle ground...
