### ISSUE TITLE
Keyboard shortcut Ctrl+Shift+/ should comment, not search

### ISSUE THREAD

**Issue by dhenson02** [jsbin/jsbin#2375]
Using `Ctrl+/` comments as expected (one-liners in JS, blocks in CSS, etc) but doing `Ctrl+Shift+/` unexpectedly brings up the help/search input field instead of block commenting in JS.  The expectation of this key combination is toggling comments.

Can this either become customizeable or changed entirely? I don't know how often people search the JSBin help while they are coding but I doubt it's as often as commenting code.  This was changed in the commit from issue #1949 

Thanks :)

PS - Sublime keymaps enabled in options for me, also using Linux + Chrome.

**Comment by remy** [comment]
What's wrong with highlighting the lines and using ctrl+/ ?

**Comment by dhenson02** [comment]
Writing in CSS, nothing at all.  With JS, it only comments by line so to uncomment a set of lines I have to highlight all the lines together instead of leaving the cursor just somewhere inside to affect the whole block.

Also a little inconvenient when I have multiple sets of comments next to each other that should be separate.  Block comments will keep them easily distinguishable but single liners can get mixed together without extra text or whitespace.

**Comment by remy** [comment]
I believe this is a bug in CodeMirror and have filed it as such: https://github.com/codemirror/CodeMirror/issues/3328

**Comment by remy** [comment]
Sorry, to clarify, *not* the keyboard shortcut, but the multiline commenting - it shouldn't comment individual lines, it should wrap in a block comment. The shortcut will remain as is for now.

**Comment by dhenson02** [comment]
If that's approved in CM it'll be a perfect solution.  I hate one-liners + accessing site search functionality remains unchanged.

Good find

**Comment by remy** [comment]
Well, there you have it: https://github.com/codemirror/CodeMirror/issues/3328#issuecomment-111999581
