### ISSUE TITLE
I am unable to see the results of my JS code

### ISSUE THREAD

**Issue by Drock490** [jsbin/jsbin#2376]
For example if i type "rect(100, 100, 100, 100); I do not see a rectangle in the output. 
I know I must be doing something wrong. 

can you assist?
damonswagger@yahoo.com

**Comment by remy** [comment]
Bin url??

**Comment by Drock490** [comment]
drock490/test

**Comment by Drock490** [comment]
first time here...

**Comment by remy** [comment]
Can you try that again. This isn't a bin url: https://jsbin.com/drock490/test

**Comment by Drock490** [comment]
http://jsbin.com/feseme/1/ here is my site
I enter "rect(10, 10, 10, 10); " I should see a rectangle

**Comment by remy** [comment]
No, that's not JavaScript (nor a jsbin issue). I suggest checking out http://eloquentjavascript.net/ or posting your question to a community like StackOverflow - as you're asking a question about how JavaScript works.

Cheers and good luck.
