### ISSUE TITLE
Pro account terms & conditions?

### ISSUE THREAD

**Issue by sfbwalder** [jsbin/jsbin#2377]
I work for a corporation where our legal department needs to review and approve the terms and conditions for the use of a **pro account on jsbin.com** (not for use of the jsbin open source code locally) before we can purchase pro accounts.  I may have missed them, but I could not find any on either jsbin.com or here in github.

Could you please share with us any terms & conditions that are agreed to when a pro account is purchased?

Thanks.

**Comment by remy** [comment]
They're here: http://jsbin.com/help#legals (they apply to all usage, not
just pro)
