### ISSUE TITLE
How can I remove github-signed account?

### ISSUE THREAD

**Issue by hieroglyphic** [jsbin/jsbin#2378]
I have another pro account that I want to link with github.

**Comment by remy** [comment]
What is your jsbin username?

**Comment by hieroglyphic** [comment]
Nevermind, I got my new account linked to this github account. Thanks!

**Comment by hieroglyphic** [comment]
![image](https://cloud.githubusercontent.com/assets/1734074/7771132/2332553e-00d0-11e5-8529-76968ddfccd4.png)

**Comment by remy** [comment]
Okay, so what is the username that you've upgraded to pro with?

**Comment by hieroglyphic** [comment]
yut951121
