### ISSUE TITLE
Embedly

### ISSUE THREAD

**Issue by RubieV** [jsbin/jsbin#2380]
Dear JSbin,

Trying to use the output with Embed.ly is currently not working. 

Kind regards,
RubieV

**Comment by remy** [comment]
What did it do before?

**Comment by RubieV** [comment]
Before, if using the share link, the jsbin would load up as embedded output. Now, with the redirect to output.jsbin.com, only a link is visible in the embed.ly frame. It’s easy to check this using the embed.ly test page.

 

Met vriendelijke groet,

Ruben van Vreeland

 

Van: Remy Sharp [mailto:notifications@github.com] 
Verzonden: zondag 24 mei-5- 2015 08:55
Aan: jsbin/jsbin
CC: RubieV
Onderwerp: Re: [jsbin] Embedly (#2380)

 

What did it do before?

**Comment by remy** [comment]
Okay, will check that out. Cheers.

**Comment by remy** [comment]
Do you have an example I can look at? I just looked at embed.ly url but didn't get very far...
