### ISSUE TITLE
Problem with registering using GitHub

### ISSUE THREAD

**Issue by brianchr2400** [jsbin/jsbin#2382]
I have a github account and I am logged in to Github, I then try registering for an account on jsbin using my github account, and I get the following error:  Sorry, looks like that auth code has expired, please try and login again.

**Comment by helmutgranda** [comment]
Same issue here. I have had the same issue for about a month now.

**Comment by helmutgranda** [comment]
Safari throws the following error:

[Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
	setItem (jsbin-3.27.4.min.js, line 16)
	start (jsbin-3.27.4.min.js, line 16)
	global code (jsbin.com, line 561)

**Comment by helmutgranda** [comment]
possible related to: https://github.com/jsbin/jsbin/issues/2341

**Comment by remy** [comment]
I'm going to close this too - see comment: https://github.com/jsbin/jsbin/issues/2341#issuecomment-116858645
