### ISSUE TITLE
Laws broken using your system

### ISSUE THREAD

**Issue by GitFooo** [jsbin/jsbin#2383]
Hello,

The following site is being used for terrorism and the authorities are asking if you could kindly take it down:

output j5bin com / l i x u s o

Call with any questions:  608-243-0527

Thank you.

**Comment by remy** [comment]
You didn't include a country code with your phone number.

None the less, it's down.

**Comment by GitFooo** [comment]
Thank you.

**Comment by remy** [comment]
I assume you removed the bin url? (which is fine, though it doesn't exist and it's not cached anywhere), but you left your number on the bin...do you want to remove that too?

**Comment by GitFooo** [comment]
Yes - I removed the bin url.  The URL was cached by search engines.  Eventually it will be re-crawled and cleared out.  I'll remove the phone number as well.  Thanks for the help.
