### ISSUE TITLE
410: JS Bin gone error on homepage

### ISSUE THREAD

**Issue by Aweary** [jsbin/jsbin#2384]
As of right now ( 8:05PM CST) the jsbin.com homepage returns a 410 error page indicating that:

>### 410: This bin has gone
>"This bin has gone and there's no alternative that I'll redirect you to. It's quite possible this bin has been >blocked from appearing due to abuse content, so really, I'm just doing you a favour."

This issue seems to persists across browsers (current version of Chrome and Firefox on OS X) and after clearing cookies/cache.

**Comment by dhenson02** [comment]
Agreed.  Still happening at 11PM Central :(

**Comment by remy** [comment]
Fixed (6am GMT). Sorry! Related to this: https://twitter.com/rem/status/602585747602972672
