### ISSUE TITLE
Bin Gone WRong

### ISSUE THREAD

**Issue by GeeGeeb** [jsbin/jsbin#2385]
JS Bin all the sudden started doing this ..... http://prntscr.com/791sen
410: This bin has gone
This bin has gone and there's no alternative that I'll redirect you to. It's quite possible this bin has been blocked from appearing due to abuse content, so really, I'm just doing you a favour. 
 
what is going on guys? =(

**Comment by tjwudi** [comment]
+1 for this issue.

**Comment by remy** [comment]
Sorry, this was fixed this morning. Something went wrong after Anonymous decided to use jsbin to make a statement on the web :-\
