### ISSUE TITLE
Error: SQLITE_ERROR: table ownership has no column named flagged

### ISSUE THREAD

**Issue by omeid** [jsbin/jsbin#2386]
Because of #2381 I ended up install jsbin directly from github with `npm install -g jsbin/jsbin` but now when I try to register a user I get `Error: SQLITE_ERROR: table ownership has no column named flagged` with default configuration except the "env" being set to "production".

**Comment by mfilotto** [comment]
I'm afraid the data structure for SQLite is outdated.
No more updates since early 2014 : https://github.com/jsbin/jsbin/commits/f60f6dff290a4b65654743dc1108d1177a10cee5/build/full-db-v3.sqlite.sql

**Comment by mfilotto** [comment]
I manually made a version of the script.
It's working for me

**Comment by mfilotto** [comment]
I made a PR here #2399

**Comment by mfilotto** [comment]
The PR has been merged.
Try the last version 3.27.3 and tell me if it solved your issue.

**Comment by omeid** [comment]
Thanks! I really appreciate this.

I will check it in a little while.
