### ISSUE TITLE
jsbin doesn't work in an iframe

### ISSUE THREAD

**Issue by xgrommx** [jsbin/jsbin#2387]
Hello @remy. I think that jsbin doesn't work in an iframe. You can look on this http://xgrommx.github.io/rx-book/content/core_objects/observable/observable_methods/zip.html. If I press clear or run it's no working.

**Comment by remy** [comment]
The issue isn't jsbin, it's the whacking great anchor element sitting in front of the iframe:

![screen shot 2015-05-28 at 19 06 23](https://cloud.githubusercontent.com/assets/13700/7867224/b19e66be-056c-11e5-8620-3c860b5124e4.png)

**Comment by xgrommx** [comment]
No, this problem isn't in anchor. I found that 
![average _ rxjs - javascript library for functional reactive programming - google chrome 2015-05-31 14 43 16](https://cloud.githubusercontent.com/assets/1499594/7901799/c41766ae-07a3-11e5-84ac-79b47ed1b699.png)
