### ISSUE TITLE
Can't create new bins

### ISSUE THREAD

**Issue by crazy2be** [jsbin/jsbin#2388]
When I try to create a new bin, I'm presented with the following page:

![image](https://cloud.githubusercontent.com/assets/667720/7799015/ede6cda0-02ce-11e5-8052-5ddc3591b7fd.png)

I've been working around this since last night by just modifying existing bins, but it's a bit annoying since now the list won't separate them.

Thanks for this awesome tool, by the way! I use it almost daily, even when I'm not doing web development work (it's really handy to quickly prototype an algorithm).

**Comment by remy** [comment]
This should have been fixed a little whilst ago. Happy to reopen if you're still seeing it.

**Comment by crazy2be** [comment]
Works now, thanks!
