### ISSUE TITLE
Cannot type '>' on Hungarian keyboard (Alt Gr + Y)

### ISSUE THREAD

**Issue by galambalazs** [jsbin/jsbin#2389]
For what it's worth the CodeMirror demo works fine here: https://codemirror.net/

See also: https://meta.stackexchange.com/questions/163619/alt-gr-y-wont-insert-character-in-question-answer-using-hungarian-keyboar

**Comment by galambalazs** [comment]
I now found that it's the Archive shortcut. How can I disable this behavior (or remap the archive shortcut)?

**Comment by galambalazs** [comment]
Here is the offending line:
https://github.com/jsbin/jsbin/blob/master/public/js/editors/keycontrol.js#L50

`Alt Gr` is a combination of `Alt` and `Ctrl` so the logic should include `!event.altKey`:

     if (event.metaKey && !event.altKey && event.which === 89) {
        archive(!event.shiftKey);
        ...

Please fix this.

**Comment by remy** [comment]
Disable your keyboard shortcuts.

**Comment by remy** [comment]
Fixed https://github.com/jsbin/jsbin/commit/0486c25ec0eddad97523d37ee142dfc669cce9bf and live.

**Comment by galambalazs** [comment]
Awesome Remy!

Thanks :)
