### ISSUE TITLE
Embed mode on Chrome failing with "Uncaught TypeError: Cannot read property 'name' of undefined"

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2391]
http://cauburtin.blogspot.fr/2015/02/redundant-clock.html was working a few weeks ago, now it gives:

    Uncaught TypeError: Cannot read property 'name' of undefined

for other scripts too, on Chrome only, it gives this same error

**Comment by cauburtin** [comment]
It's not working when you have deselected **Auto-run JS**, even after you click run with JS on the output window, the error occurs.

But I've tried to load it on an incognito window, with Auto-run JS, it worked fine

**Comment by cauburtin** [comment]
@remy Now there the error is

> GET http://pagead2.googlesyndication.com/pagead/js/google_top_exp.js net::ERR_BLOCKED_BY_CLIENT

**Comment by cauburtin** [comment]
ok working fine now

**Comment by remy** [comment]
I didn't change anything further. Do you know what the google thing was?

**Comment by cauburtin** [comment]
Sorry, that error is still present, and is certainly due to blogspot site, not jsbin. Thanks for your work!
