### ISSUE TITLE
YOUR URL to   keyboard-shortcuts   = 404

### ISSUE THREAD

**Issue by stefanibus** [jsbin/jsbin#2392]
This page cannot be reached 
http://jsbin.com/help/keyboard-shortcuts

**Comment by remy** [comment]
Yeah, it's an intermittent fault. Keep refreshing.

**Comment by stefanibus** [comment]
Thanks. I worked my way around this intermittent fault  (missing search 
bar)  by clicking into the html area . At least that brings up the 
browsers own search-bar.  If inside the code-area that comes up neither. 
  I actually hoped for a jsbin-internat search feature. Shortkeys seem 
non-responsive though.  You can leave this ticket closed. Thanks again!



---
Stefan Brück * Krausestrasse 22  * 22305 Hamburg * 0170/ 38 37 0 17

Am 28.05.2015 19:59 schrieb Remy Sharp:
