### ISSUE TITLE
Delete Bins

### ISSUE THREAD

**Issue by bharath-c** [jsbin/jsbin#2393]
Request you to delete all the versions of the bin of URL http://jsbin.com/tavomo/

**Comment by remy** [comment]
I can, but any reason why you don't want to?

**Comment by bharath-c** [comment]
Thanks. Well i have submitted an propoal which they approved. Just wanted to make sure it not accessible by anyother person.
jsbin is a wonderful application, gr8 design. its awsome. hats off to the complete team.
