### ISSUE TITLE
BUG: jsbin crashes page after appearing in Chrome

### ISSUE THREAD

**Issue by people-06** [jsbin/jsbin#2402]
Hello!

I got strange behavior for "appearing". What I mean by appearing? I mean, when I have a hidden block, which contains embeded jsbin, and when I showing this hidden block (click or just show it from dev console), page going crazy. 
But not always!
Here is an example http://output.jsbin.com/mucazowebe/1
I'm played with different tags and code inside console. So shit happens all the time, when html-tab have form elements, like button and input.
Also I asked my friends to test this bug too. So bug is happens at Mac OS and at Windows 32bit, but bug wasn't find at Linux 64bit and Windows 64bit. Strange, but not fact, that there any correlation between 32bit and 64bit. 4 persons have chrome version 43.0.2357.81m and one 45.
I'll be happy to get any help from you!
PS: Test with just h1-tag JS-tab and Output-tab don't appeared http://prntscr.com/7ccmme /this happens not all the time, but many times.

Thank you for the awesome tool!
With best regards,
Lika

**Comment by remy** [comment]
I cannt replicate this at all...

Can you try another machine and repeat the process and let me know how you get on?

**Comment by bloodmars** [comment]
my tab in Chrome is dead
