### ISSUE TITLE
Embedded Bins That Used 6to5 Now Default To JavaScript

### ISSUE THREAD

**Issue by blesh** [jsbin/jsbin#2407]
If you created a bin in the past that used 6to5, and embedded it, now when you visit the embedded bin it defaults to JavaScript, breaking the bin.

Seems like a consequence of the 6to5 -> Babel upgrade.

**Comment by blesh** [comment]
An example can be found here (for now, until I'm able to update the embed): 

https://egghead.io/lessons/rxjs-what-is-rxjs

which points at:

http://jsbin.com/genizo/1/edit?html,js,output

**Comment by remy** [comment]
Damnit, I had a feeling this might happen. I'll look into it and try to get a fix in quickly.

**Comment by blesh** [comment]
Thanks, @remy

**Comment by blesh** [comment]
FWIW, updating the bins seems to solve the issue in the short term. But that may be time consuming for some.

**Comment by remy** [comment]
Yeah, it will do, but I'd rather fix it at the source (if I can).

**Comment by remy** [comment]
Fixed in live, and will automatically retroactively fix all bins using the old 6to5 processor (and update to using Babel).

**Comment by joelhooks** [comment]
Thanks @remy 👍👍😄
