### ISSUE TITLE
append the texbox horizontally

### ISSUE THREAD

**Issue by hazeleena14** [jsbin/jsbin#2412]
how do i append those textbox horizontally.. please help

jQuery(function($) {
  
  var i = 0;
  
  $('#theButton').click(addAnotherTextBox);
  
  function addAnotherTextBox() {
    $("#theForm").append("<br><label>Medical History <input type='text' name='teilnehmer_" + i + "' >");
  }
  
});

**Comment by remy** [comment]
This is a question for StackOverflow or even Google, and this is not a jsbin issue. Sorry, and good luck.
