### ISSUE TITLE
Error: ER_NO_DEFAULT_FOR_FIELD: Field 'streaming_read_key' doesn't have a default value

### ISSUE THREAD

**Issue by mfilotto** [jsbin/jsbin#2414]
Hi,
I have this error on the last versions of jsbin v3.27.X.
I created the mysql database from  full-db-v3.mysql.sql
But when I want to save a bin I have this error :

```
Error: ER_NO_DEFAULT_FOR_FIELD: Field 'streaming_read_key' doesn't have a default value
```

I found this old issue : #1102

What should I do ? remove the columns ?

**Comment by badmonster-nc** [comment]
+1

**Comment by mfilotto** [comment]
Hi there,
Any idea on this one ?
