### ISSUE TITLE
Can't register if github username is taken

### ISSUE THREAD

**Issue by aroberts** [jsbin/jsbin#2415]
With email registration turned off, I have no way of registering since my github name is taken.  Is there any way around this?

**Comment by remy** [comment]
1. Spammers
2. There might be. But I have to build it. What's your email address - I'll create some kind of whitelist process.

**Comment by remy** [comment]
@aroberts also, if you're not keen on posting your email, send a DM to @js_bin on twitter (make sure you make clear that you're @aroberts on github too!)

**Comment by aroberts** [comment]
DM'd

**Comment by remy** [comment]
You can now register using the "regular" route using the email address you DM'ed.
