### ISSUE TITLE
text area full screen

### ISSUE THREAD

**Issue by mccbjnn** [jsbin/jsbin#2416]
How do I get my text type area full screen.  I only have about the lower fourth of my laptop screen available to see text/code which I type.  Thanks.

**Comment by remy** [comment]
Can you provide a screenshot as this doesn't sound like the layout is right. It should be very large by default, i.e. this is my layout: https://cloudup.com/iDDT_Xh56wp

**Comment by mccbjnn** [comment]
Hi.  Thanks for trying to help. I Googled how to submit a screenshot.  I'm
supposed to use MS paint and make a png file ?  I've never done this.
Can I use my android phone and email it to you?
Will you get it at notifications@github?

This email also says I can reply via githib.  Sorry, I went through githiub
to go to jsbin.com and I only see a blog.  I didn’t even see my question.
Yes, I did log in.
Thanks.
Jeanne

Jeanne Mccabe

**Comment by remy** [comment]
Replies:

> I'm supposed to use MS paint and make a png file ? 

I'm not sure either (I'm on mac), but ---

> Can I use my android phone and email it to you?

Yes, so long as it's reasonably clear, this will do. You should be able to upload directly to this form (in github) - there's a file upload ("selecting them") attached to the bottom of this form.

> Will you get it at notifications@github?

Try doing it directly in the form first, then we'll see how we get on.

**Comment by mccbjnn** [comment]
Hi Remy
Thanks for your time.  I should probably tell you that I'm on the free edition of jsbin.  An online you tube tutorial I am taking on html suggested that we follow along on JSBin.   Perhaps I don't have all the features because I don't have the pro edition.  For example, I couldn't find this page from jsbin after logging in through github.  I got here through my email.  There aren't many navigation options that I see.
I am trying to upload the screen shot photo we were originally discussing and am having a problem finding the picture on my computer.  Google drive isn't syncing as is should.  I will have to try to send it to you through the @ notifications email.  Sorry about that.
Jeanne
![welcome_screen](https://cloud.githubusercontent.com/assets/12866230/8172564/c14edffe-1376-11e5-9744-3d418a5e95e8.jpg)
![20150402_185134 1](https://cloud.githubusercontent.com/assets/12866230/8172587/fdc131da-1376-11e5-800d-596027fd6321.jpg)

**Comment by remy** [comment]
The pro features are listed here: https://jsbin.com/upgrade

The link to this issue tracker is highlighted in the men you see below - and you can see I'm also logged out - i.e. it does not require pro.

![screen shot 2015-06-16 at 07 11 07](https://cloud.githubusercontent.com/assets/13700/8176910/eedb0d78-13f6-11e5-978b-ae0d335655fa.png)

If you don't see exactly the same as the screenshot above, I suspect there's something quite wrong. A quick way to check is by trying another computer (if you have one, or a friend, colleague, etc), but also try on a different connection.

Good luck none the less.

**Comment by mccbjnn** [comment]
Thanks for your help Remy.  I will continue to work on it and contact you
if there is something you can help with.
Have a good day.

Jeanne Mccabe

**Comment by mccbjnn** [comment]
Hi Remy
Finally I clicked around and did get my screen to match yours.  It was
easy...just had to have more patience.
Thanks!!!!

Jeanne Mccabe
