### ISSUE TITLE
I can't share jsbin links on facebook!

### ISSUE THREAD

**Issue by NeoCsatornaja** [jsbin/jsbin#2419]
Why i can share jsbin links?
I would like to post is on a programer group, and I get a Spam dialog messange bullshit :S

**Comment by remy** [comment]
Why are you telling me? Why aren't you telling facebook instead?

**Comment by NeoCsatornaja** [comment]
Becouse you're the developer, and would like to notify you about htis problem.

**Comment by remy** [comment]
Sadly there's nothing I can do about Facebook's blocking system. Again,
please do raise it to them, I'm sure they have devs that can make a change
or at least explain why they're doing it.

**Comment by s6323859** [comment]
@remy What can we do to change this? I like JsBin. This problem make me angry a long time.

**Comment by remy** [comment]
Any chance you could explain why you're asking *me*? It's *Facebook* doing
the blocking, not jsbin.

If you *really* want to use Facebook to share your code, the only
workaround I can offer is: use codepen or jsfiddle. They've not been
blocked (yet).

I'm closing this issue, thanks for the heads up everyone, it's a pain, but
nothing *I* can do anything about.

**Comment by NeoCsatornaja** [comment]
I have a idea.
What about if you create a mirror domain just for output?
Many, many free storage you can find on internet, maybe you can use it, just for facebook shares.
