### ISSUE TITLE
Why hotkey for JS Bin navigation bar work only on active console panel?

### ISSUE THREAD

**Issue by jeserkin** [jsbin/jsbin#2421]
Why hotkey for JS Bin navigation bar work only on active console panel?

**Comment by remy** [comment]
You're going to have to explain that in a bit more detail. Can you list out what keys you're using and what you're seeing and what you're expecting to see? (I don't quite follow your issue subject, having tested cmd+1,2,etc).

**Comment by remy** [comment]
Idle.
