### ISSUE TITLE
Saving and Archiving Bins

### ISSUE THREAD

**Issue by mccbjnn** [jsbin/jsbin#2424]
Hi Remy,
I was experimenting with some html and was hoping that the bin would save automatically.  I am logged in.  I looked for it and didn't see it.  So I tried to archive the bin while it was still open. A msg popped up that said that I could only archive a bin if I owned it.  I am the only one on this account, so I technically own everything in my repository.  Do I have to log out and then back on to find my current bin in the bin list?  I have archived bins before and I never did anything special except log in.  
Any ideas?
thanks

**Comment by remy** [comment]
Do you have the bin URL. It does save automatically and if you're logged in,

**Comment by mccbjnn** [comment]
Hi Remy
When logging back into jsbin, this bin that I tried to "save" when it didn't save automatically appears.  I logged in three times now.  It was never saved, it didn't allow me to archive, but it opens now upon login.  Should I just try to clear the console?  I was just making templates, experimenting with styles.
I don't need it but don't understand why this could of happened.
The URL name listed on the tab is strange, "jsbin.com/?html, output".  It,s not a typical bin name.
Thanks.

**Comment by remy** [comment]
The URL you're seeing tells me nothing is saving for you. Can test in
chrome and open the devtools and report back if there's any errors being
shown?

**Comment by mccbjnn** [comment]
HI Remy
I opened JSBin today and that URL and its input was gone.  Nothing was saved.  Today this URL
appeared: jsbin.com/velixi/edit?html .
I experimented with a few simple html tags which worked, I did see "saving" flash.  I tried an anchor tab which didnt work.   I opened the debugger tool (in chrome) and could not get the highlighted code to be reviewed.   I am sure the mistake was mine.  I have looked at the f12 developer/debugging tool in IE but never really used it.
If this looks like a good URL, I will continue on with my video tutorial.
Is the developer tool supposed to be intuitive?

**Comment by remy** [comment]
@mccbjnn you might find the developer tools in chrome a little easier - but if it's working, just keep an eye on it and just report back here. I'll help if I can.

**Comment by mccbjnn** [comment]
Hi Remy
I logged in to JSBin today after being off for a few days.  I realized that I had not been logging out.  I wonder if that was causing the problem.  Seems to be working fine now.  Thanks.

**Comment by AryanBeezadhur** [comment]
The zip file below has a screen recording of a 400 error that occurrs when I press CTRL + S. The URL clearly does not autosave, and neither does the editor say that the bin is too large to save.


[New Compressed (zipped) Folder.zip](https://github.com/jsbin/jsbin/files/3404914/New.Compressed.zipped.Folder.zip)
