### ISSUE TITLE
Posting to jsbin no longer works

### ISSUE THREAD

**Issue by cyberdash** [jsbin/jsbin#2425]
This example used to work:

http://jsbin.com/musera/edit?html,js,output

Specifically, the problem is posting to the jsbin URL with the contents of the bin.

You can an example of this in use here: https://docs.atlassian.com/aui/latest/docs/auiselect2.html (look for the "Edit in jsbin" button)

Was this intentionally removed, or is it a bug?

**Comment by kaelig** [comment]
Same issue on our side.

This page: http://registry.origami.ft.com/components/o-header@3.0.6/demos/edit/demos/header.html is used to redirect to JSBin and populate the HTML field but it doesn't work anymore.

**Comment by remy** [comment]
Sod, I know what's causing this. Gimme a few minutes.

**Comment by remy** [comment]
Okay, a fuck load more than a few minutes. The issue now is I can't hold the size of the request in a flash message (which happens to be in a cookie - so obv it blows up).

**Comment by remy** [comment]
Fixed and live. 

Oh man that one was painful. I nearly ended up upgrading all the code to express 4 - which I want to do, but it's not a single day job...too much pain. Fixed using a simple memory based flash store.

**Comment by cyberdash** [comment]
Thanks for the fast response on this! Very much appreciated :)
