### ISSUE TITLE
Updating an older link...

### ISSUE THREAD

**Issue by jshuadvd** [jsbin/jsbin#2432]
Hi there,
I wanted to know if there is a way that I can accomplish this. I sent a jsbin link out and have now updated said bin. However, when I updated it, the link changed. I would like to be able to edit that same link without the link changing so that the recipient can see the latest version without having to send another email with the new updated link. Is this possible, and if so how?

Here is the link to the old bin: http://jsbin.com/xaponacinu/11/edit?output

And here is the link for the new one: http://jsbin.com/weqome/edit?output

**Comment by remy** [comment]
Have you tried editing this link? https://jsbin.com/xaponacinu/11/edit?output if you're logged in, the url should not change, only the snapshot number will be removed (as you'll be on the latest version).

**Comment by jshuadvd** [comment]
I tried that to no avail. Now neither of the jsbin links  that I sent you seem to be working. Can you give me any idea why that is? I haven't changed anything...
