### ISSUE TITLE
On Share Window, Snapshot URL for Embed Code Is Not Updated

### ISSUE THREAD

**Issue by chibicode** [jsbin/jsbin#2436]
When I try to share a snapshot, the URL for the link is updated, but not for the embed (in the screenshot below, it should really be `wewimu/4/embed`). As a workaround, I have to manually add the revision number before `/embed` every time.

![pasted_image_6_23_15__9_52_pm](https://cloud.githubusercontent.com/assets/992008/8323748/5bbb8ad8-19fd-11e5-8829-e54b10692628.png)

Original Tweet: https://twitter.com/js_bin/status/613588258799382528

**Comment by chibicode** [comment]
@remy thank you!

**Comment by remy** [comment]
It's not live yet - I've got another fix to go up, but thank you for
reporting it!
