### ISSUE TITLE
Function declaration throw error on Firefox.

### ISSUE THREAD

**Issue by sgorec** [jsbin/jsbin#2439]
Example for reproducing: http://jsbin.com/mecufupaje/edit?js,console

**Comment by remy** [comment]
Not sure. This works in Chrome, so I would go to the browser vendors with the question or why does this work (or not work). Happy to re-open if this is a bug in jsbin...

**Comment by sgorec** [comment]
This bug not reproduce in Chrome/Opera/InternetExplorer and in Firefox if execute it without jsbin environment.

**Comment by eloyesp** [comment]
It happens in firefox in this example: http://jsbin.com/girena/edit?js,console
