### ISSUE TITLE
I can't disable the short cuts in chrome!

### ISSUE THREAD

**Issue by NeoCsatornaja** [jsbin/jsbin#2441]
I try disable shortcuts, becouse I can't close html tags.
First I typed the generate characters, then I pasted this:
jsbin.settings.keys = { disabled: true };
And after then I get a messange in the consle:
"jsbin.settings.keys = { disabled: true };
Object {disabled: true}" 
But this not true becouse I still can't close HTMl tags (so I just can write this character: <, but not this >).
So what can I do more?

**Comment by remy** [comment]
I think there's a live bug that prevents settings from being changed in
jsbin. Hold tight, I'll try to fix this w/e.

**Comment by NeoCsatornaja** [comment]
Littlel help:
My keyboard language is : Hungarian

**Comment by NeoCsatornaja** [comment]
I still can't write this character:
>
I need this, very hard work with this problem, copy and paste this character all the time...

**Comment by remy** [comment]
What actually happens when you *try* to type `>`?

**Comment by NeoCsatornaja** [comment]
I geted this messange:
"The archiving failed. You can only archive bins that you own."

**Comment by NeoCsatornaja** [comment]
In hungarian keyboard this caracter:
">" only can reach with altgr+Y

**Comment by NeoCsatornaja** [comment]
You're comit is a litle unclear for me.
Becouse if you not turn off the shortcuts you still can't close HTML tags with ">".
