### ISSUE TITLE
404 in jsbin script

### ISSUE THREAD

**Issue by NeoCsatornaja** [jsbin/jsbin#2446]
Please fix this error:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://output.jsbin.com/biqemo/1x

**Comment by remy** [comment]
"1x" isn't a valid snapshot, so yes, this is a 404.

**Comment by NeoCsatornaja** [comment]
The actual project in here:
http://jsbin.com/biqemo/edit?html,js,output

**Comment by remy** [comment]
And the output URL is http://output.jsbin.com/biqemo/1/

**Comment by NeoCsatornaja** [comment]
Thank you for fixing the 404 erorr in the chrome console.
It's mutch easier find out why not working this input in jsbin.
It's strange,becouse in output section I Saw something but in the edtor, it's fully dead after I accept the permission

**Comment by remy** [comment]
I'm unsure if you're saying this is still a problem, in that you see the URL with the `x` on the end? If you do, can you post a screenshot?

**Comment by NeoCsatornaja** [comment]
And the error is back :(
<img src="http://i59.tinypic.com/29qidsy.png"/>
http://i59.tinypic.com/29qidsy.png

**Comment by remy** [comment]
Oh wow, this is strange! I've reopened and will investigate.

**Comment by remy** [comment]
Actually something that might help here. If you're familiar with the devtools, you can open the network panel and find the 404. It should show the initiator (i.e. if it was script or something else). I can't think how (off the top of my head) it would make that request. If you can look at the network panel and either post screenshots of what you see or dig in for me - that would be super useful to debug (again, I've not seen this before so I can't replicate which makes it exceptionally hard to narrow down to fix).

Cheers!

**Comment by NeoCsatornaja** [comment]
I think this is a impossible problem:
http://i57.tinypic.com/245yi68.png
<img src="http://i57.tinypic.com/245yi68.png">

**Comment by NeoCsatornaja** [comment]
Oh wait here the screen after i Refreshed :  
http://i58.tinypic.com/sl0itk.png
<img src="http://i58.tinypic.com/sl0itk.png">

**Comment by remy** [comment]
Can you try repeating in an incognito window? I can't think at all how this is happening, but I see you've got a number of extensions. So if you can open a new incognito window, log in, and try that particular bin again and see if you can repeat.

**Comment by NeoCsatornaja** [comment]
I dosen't see this erorr in incognito window.
Maybe I have a conflict with some extensison?
I dosen't see this any other pages.

**Comment by remy** [comment]
Other pages on jsbin? Or other pages in general? If the later, then I suspect we have an extension that's having some interference, if you don't see it on jsbin...then... it's *super* strange!

**Comment by NeoCsatornaja** [comment]
In general.
I working this plugins a long time ago and I dosen't see any issu like that.

**Comment by remy** [comment]
Okay, so, one by one disable each plugin, then repeat the test until you find it. The fact it works fine in incognito suggests very strongly there's a plugin at blame here.

**Comment by remy** [comment]
Did you get anywhere with this?

Also, another idea that might lend support to the problem being extensions, is trying Firefox to run a few tests?

**Comment by NeoCsatornaja** [comment]
Sorry for the delay!
i have a hard week on my workspace.
I can answer your question in tomorow.
Thanks for the pattion.

**Comment by NeoCsatornaja** [comment]
And the result is:
I turned off all extension, but the 404 is still there.

**Comment by remy** [comment]
Can you try Firefox. Like I said, I've never seen this and can't replicate
myself, so I'm afraid the work is on your side to help track down the
source, and whether it is indeed jsbin or not.

**Comment by NeoCsatornaja** [comment]
Looks like ok (no 404), one thing left we can do.
I can add team viewer datas if you contact me:
szantai77@gmail.com

**Comment by evandana** [comment]
What was the result of this? I'm seeing the same error, but only when loading the page on the 1x monitor and NOT when loading the page on my retina screen.

**Comment by remy** [comment]
Its an error you can ignore for now. I now known what it is (the avatar
isn't loading - and the picture element is trying to load a relative URL),
but I don't have a fix yet.

**Comment by ChadRehmKineticData** [comment]
Did this issue ever get resolved.  I'm seeing the same thing.
