### ISSUE TITLE
Bin preview fails with X-Frame-Options refused to display javascript error

### ISSUE THREAD

**Issue by tadek-wojtych** [jsbin/jsbin#2447]
Bin preview normally displayed while highlighting bin on the list (File -> My Bins) failes with javascript error: "Refused to display 'http://output.jsbin.com/wizesi/5/quiet' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'".

**Comment by remy** [comment]
This is strange. I can't replicate this at all - see the screenshot:

![screen shot 2015-06-29 at 22 39 25](https://cloud.githubusercontent.com/assets/13700/8419181/be368922-1eaf-11e5-9011-ab30a0460bfe.png)

You can see it's rendered the iframe, but also not redirecting to the output URL (which I can see why it would do that...but mine isn't).

Can you send a similar screenshot?

**Comment by tadek-wojtych** [comment]
Here is what I get for all my bins – the error appears when I highlight the bin in the list on the left (any bin):
[cid:image001.png@01D0B319.146E4670]

**Comment by amzin7000** [comment]
same issue.  'Refused to display 'https://output.jsbin.com/*******/*/quiet' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by jeserkin** [comment]
Same here. I haven't paid too much attention, but recently I looked closer at it and found same error in console.

**Comment by fuzetsu** [comment]
Been getting the same error here for a while. I guess the origin is actually different now `output.jsbin.com` vs `jsbin.com`, so maybe `ALLOW-FROM jsbin.com` (or whatever) needs to be sent in `X-Frame-Options` instead of `SAMEORIGIN`.
