### ISSUE TITLE
Local install, ownership problem? Can't save preferences

### ISSUE THREAD

**Issue by pelonpelon** [jsbin/jsbin#2448]
On a local install (OSX) I have several problems that might be related. I followed install directions exactly. I set session secret and no longer get the warning. I'm using config.local.jsbin with only one change: the session secret.

Bin snapshots are stored successfully and are persistent between launches. [Save as template] works.

However:
- Profile settings **do** save and persist, but
- The `settings saved` yellow pop-up appears. 
- Editor settings and Preferences **do not save**, even in the same session.
- When deleting a snapshot there is a warning that `You do not own this snapshot so you can't delete it` but sometimes it deletes anyway. sometimes not.
- Archiving works and persists on relaunch.
- The box in the bottom right of the window says `1 viewers` and `Anonymous streaming`  with a spinner - while I am logged in.

I've tried shutting down the server, editing localstorage (for instance, to change font size). Localstorage gets replaced on next relaunch.

It feels like there something not happening regarding authentication. Am I missing a configuration step.

**Comment by remy** [comment]
I'm working on a 4.0 release that will automate deploying to npm and get the local installs working again (hopefully).

**Comment by pelonpelon** [comment]
I should have mentioned that I am running a clone of the latest github, not the old npm.

**Comment by qband** [comment]
i encountered the same problem. i even dockerize it.
jsbin from npm is too old.

**Comment by vfxdude** [comment]
Installed it locally on windows, and ran into this problem. Seems to be a session problem. user.settings is not added to the jsbin object. Removing user.settings from the cookie blacklist (in lib/app.js) fixes it.
