### ISSUE TITLE
Output error due to script being overriden

### ISSUE THREAD

**Issue by tadek-wojtych** [jsbin/jsbin#2453]
Output panel fails with error due to script change:
__var content = "&lt;html>&lt;head>&lt;meta charset='utf-8'>&lt;/head>&lt;body>";__
gets overriden with:
__var content = "&lt;html>&lt;head>&lt;meta charset='utf-8'>&lt;style id="jsbin-css">
&lt;/style>
&lt;/head>&lt;body>";__

**Comment by remy** [comment]
Do you have a bin that I look at?

**Comment by tadek-wojtych** [comment]
Just this line is enough:
![image](https://cloud.githubusercontent.com/assets/7103923/8485725/22dcc812-2100-11e5-91da-bfa6c50db198.png)
