### ISSUE TITLE
Would be great if you could set the panels you want opened by default, all the time.

### ISSUE THREAD

**Issue by jfraboni** [jsbin/jsbin#2454]
Setting Preferences > Panels > Open Panels > selecting JUST JavaScript and Console, and setting Focused panel to JavaScript, one would think you'd always have JUST the JavaScript and Console panels opened creating new bins or opening stored bins, but this is not the case - the HTML editor seems to be always opened by default, and or, opening previous bins that had JUST JavaScript and Console panels selected, I'm presented with an HTML panel.  This is confusing, one should be able to store the workspace state, and not have to close the HTML panel or Output panel each time - many simple projects may have not HTML at all, so why open this panel by default each time?

Expected result:  If you're working on a bin, and you only need JavaScript and Console panels, you should be able to save the state of the workspace such that when you return and open that bin again, those panels are the only ones opened.

**Comment by remy** [comment]
I don't understand the title of this issue. It *sounds* like a feature request, but what you're describing actually sounds like a bug.

I'm stuck trying to resolve that difference, perhaps I've misinterpreted the description and indeed it *really* is a feature request you're after. Or, maybe, I hope this doesn't sound rude, but you're being snarky about a tool that you're using for free?

I'm not sure. I'm happy to look at this if it is actually a bug you're trying to report, and happy to help update the title on this issue track.

Cheers!

**Comment by quangkieu** [comment]
Ask I remember, you should only have 1 tab or session open when you want to change the setting or your new setting will not apply. I tried many times, I keep the current working project and open another tab to change setting. It did not not work. Only until one day that I change the setting in the same tab (only 1 tab open) I got it.

**Comment by jfraboni** [comment]
I'll tell you what: https://repl.it/
