### ISSUE TITLE
TypeScript fails on basic console.log

### ISSUE THREAD

**Issue by johnlindquist** [jsbin/jsbin#2455]
http://jsbin.com/tobaxejaco/edit?html,js,console,output

This is only a basic `console.log("hi");` and it fails with the following error:

```
typescript processor compilation failed
jsbin-3.30.3.min.js:18 Object {}
jsbin-3.30.3.min.js:18 Uncaught (in promise) TypeError: Cannot read property 'html' of undefined
    at http://static.jsbin.com/js/prod/jsbin-3.30.3.min.js:18:11001(anonymous function) @ jsbin-3.30.3.min.js:18
```

**Comment by remy** [comment]
TS is utterly out of date, so I'm making a plea for help, because I could never get the client side script to build: https://twitter.com/rem/status/617451826263269378

I do know that it's since moved to github rather than MS's version of repo control, which might make it easer...who knows...

**Comment by johnlindquist** [comment]
Ok, I'll dig into it this week. I've used the client-side script with jspm, so I'll investigate how they're doing it.
