### ISSUE TITLE
problem when I pass dynamic value in wods

### ISSUE THREAD

**Issue by Ariel-Soft** [jsbin/jsbin#2456]
Hi Support,

when I pass dynamic value in words then its not working.
please help.

js code :

var span = document.getElementById('spanid').innerHTML;

$('p').wrapInTag({

  tag: 'em',
  words: [span]
});

**Comment by remy** [comment]
I don't see a jsbin url to confirm whether this is a jsbin bug or not.

**Comment by remy** [comment]
Idle
