### ISSUE TITLE
Console doesn't have context from "file -> new" but does on reload

### ISSUE THREAD

**Issue by peterdcasey** [jsbin/jsbin#2458]
I really like using JSBin in my computer labs to introduce Javascript programming but it has failed every time we try to use it this term. We have a lab of 28 computers and students are using their JSBin accounts to log in. The UI simply fails shortly after logging in and trying to add either HTML or Javascript.

Thanks for listening,

Peter Casey
Central Oregon Community College

**Comment by remy** [comment]
Do you have any screenshots or network information to help debug with?

**Comment by peterdcasey** [comment]
I am sorry I don't have much to go on. The screen shots would not help, the UI just stops responding. I agree that it probably is related to the network. We are in a lab with 28 computers and I have no idea what routers, etc., we go through to get to your service. It worked fine today and that adds to the mystery. Thanks for getting back and sorry about the lack of help from this end.

Peter

On 7/6/2015 11:51 AM, Remy Sharp wrote:
Do you have any screenshots or network information to help debug with?

On Sun, 5 Jul 2015 23:54 peterdcasey <notifications@github.com><mailto:notifications@github.com> wrote:

> I really like using JSBin in my computer labs to introduce Javascript
> programming but it has failed every time we try to use it this term. We
> have a lab of 28 computers and students are using their JSBin accounts to
> log in. The UI simply fails shortly after logging in and trying to add
> either HTML or Javascript.
>
> Thanks for listening,
>
> Peter Casey
> Central Oregon Community College
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2458><https://github.com/jsbin/jsbin/issues/2458>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/jsbin/jsbin/issues/2458#issuecomment-118956743>.


--
+------------------------------+
| Peter Casey                  |
| Professor of CIS             |
| Central Oregon Cmty. College |
| Bend OR 97701                |
| 541-383-7723                 |
| mailto:pcasey@cocc.edu       |
| http://pcasey.cocc.edu       |
+------------------------------+

**Comment by remy** [comment]
Can you explain why you mean by the ui fails? There's a number of ways it
could fail, so as verbose as a description would be useful, otherwise
there's nothing I can do.

For example: do you see an entirely blank page? Do you see the menu bar and
jsbin logo but nothing happens? Does the completed ui load but then freeze
up? What's the URL you visit in? What browser and OS? Etc

**Comment by AbdullahAlger** [comment]
I have a similar issue. After pushing run, any code is "not defined". I have to keep refreshing the browser and hope it works. I am using Chrome 43.0.2357.130.

**Comment by remy** [comment]
Similar to what???? Do you have a bin URL and/or a screen cast I can watch
to try to debug the issue?

**Comment by AbdullahAlger** [comment]
Similar to the issue of JSBin failing. Like I said, it comes and goes. When you start a new bin, all of the variables are undefined after pressing run. However, if you refresh the browser, then it starts to work normally. [Here is a screen cast.](https://goo.gl/g9VbKW)

**Comment by remy** [comment]
@peterdcasey not to hijack the issue, but if it's the same as @AbdullahAlger it means I can replicate and fix.
