### ISSUE TITLE
Issues with Exporting as Gist

### ISSUE THREAD

**Issue by Bijesse** [jsbin/jsbin#2459]
Hello,

Recently I have been having issues exporting my workspaces as Gists. A few months ago I use to be able to export a gist and it would appear GitHub with my account. Now when I "Export as Gist" the Gist appears as Anonymous even when I am logged in with my linked GitHub account.

This issue is common across several computers, browsers and with other users.

**Comment by remy** [comment]
This is odd. I'm on holiday this week without a machine. If anyone else
wants to take a look firstly to confirm the bug, but secondly to fix, that
would be good.

**Comment by Bijesse** [comment]
Thanks for the quick response. Should I reach out to someone else since you
are out of the office?

**Comment by remy** [comment]
Hehe, yeah "office". JS Bin is *just* me. There's some community members
that follow along jsbin, so I'm kinda hopeful. Otherwise it'll (likely)
have to wait.

**Comment by tnedich** [comment]
Same problem here :/

**Comment by remy** [comment]
Confirmed. I know what the bug is, I don't have a quick fix (or rather, I
have a quick fix - but I'm not convinced its secure). Watch this space.

**Comment by cshomaker** [comment]
I'm having the same issue - but the solution doesn't seem to be added here :( Anyone?

**Comment by HipsterZipster** [comment]
+1 same issue. Definitely logged into jsbin with github credentials and checked in gh account that jsbin was authorized

**Comment by kalpeshshirodker** [comment]
Issue still persists! Any updates on this one?

**Comment by padisio** [comment]
same problem here

**Comment by camabeh** [comment]
Still persists. Please fix.

**Comment by rwhat357** [comment]
same propb

**Comment by gbhushan** [comment]
Yup! I'm having the same problem!

**Comment by clearbug** [comment]
Yup! I'm having the same problem!

**Comment by remy** [comment]
So…lots of plusones then …

**Comment by Jn1532** [comment]
Hey Remy!
Anything yet on that fix?

**Comment by pfoser** [comment]
A fix would be greatly appreciated! As mentioned by somebody else, getting rid of a fork would simplify things in a teaching setting!

@remy,  btw., JS Bin is a wonderful teaching tool! Students (and teachers alike) love it! Many thanks!

**Comment by buleoer** [comment]
Same problem here...

**Comment by Lilletsy** [comment]
yeh same issue here

**Comment by chdonncha** [comment]
same issue here

**Comment by peterarza** [comment]
Having same issue with codepen.

**Comment by kentonlin** [comment]
Issue still not resolved

**Comment by FujiAppleSauce** [comment]
Same issue for me. No fix?

**Comment by kingzez** [comment]
maybe github api changed

**Comment by sirJconny** [comment]
Any updates on the fix? (:

**Comment by profSeeger** [comment]
Fix would be appreciated

**Comment by remy** [comment]
PR would be appreciated #alliteration

**Comment by yajurvendrasinh** [comment]
I am facing the same problem yet. Is there any way to contribute ? or let the dev people know to kindly fix this ? It would be great to have this feature. Thank you

**Comment by iriand** [comment]
there is duplicate #2856 of this issue, still not resolved although.
