### ISSUE TITLE
Update gratipay?

### ISSUE THREAD

**Issue by jcrben** [jsbin/jsbin#2460]
I'd like to give something in between a pro subscription and nothing (admittedly, not a lot), but it looks like the [gratipay link](https://gratipay.com/~js_bin/) needs an update. They changed to focus on teams and some configuration changes may be required. Some of the teams (jsbin is [not on the list](https://gratipay.com/explore/teams/)) do have a link for support ([example](https://gratipay.com/esdiscuss/)) while some don't.

Note: may be more worth your time to wait until the dust has settled on gratipay before fiddling with it.

**Comment by remy** [comment]
I know. I applied for a team, but haven't heard back. I added detail on the
"team" but wasn't sure if it was supposed to be public or not, so I assumed
not and gave a lot of personal detail (which I now see is used in public),
so I'm not sure when or if it'll happen.

**Comment by remy** [comment]
It just came through! https://gratipay.com/jsbin I'll also he updating docs, etc now.

**Comment by jcrben** [comment]
Great. Signed up to give you $1/week, which will hopefully be a sustainable level for my budget. ;)
