### ISSUE TITLE
sample1

### ISSUE THREAD

**Issue by Databoom** [jsbin/jsbin#2462]
Please provide any additional information, record a screencast with http://quickcast.io or http://screenr.com and attach a screenshot if possible.

**JS Bin info**

* [http://jsbin.com/edit](http://jsbin.com/edit)
* Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
* Databoom

**Comment by remy** [comment]
See other issue
