### ISSUE TITLE
JSBin embed adds the embedded page to browser history and breaks the back button

### ISSUE THREAD

**Issue by chibicode** [jsbin/jsbin#2464]
This is reported on OSX 10.10.4, Firefox 39.0

My page has a ton of JSBin embeds:
http://reactfordesigners.com/labs/reactjs-introduction-for-people-who-know-just-enough-jquery-to-get-by/

And every time you scroll past a JSBin, it seems to add the current page on the browser history. Please see this animated gif:

![](http://cl.ly/image/3b0H0a3E2V2Q/Screen%20Recording%202015-07-09%20at%2004.24%20AM.gif)

**Comment by remy** [comment]
This feels more like a browser bug. The iframe is lazy loaded to attempt to
avoid getting thrashed. I can't see how jsbin code could avoid pushing to
the history...

**Comment by briancappello** [comment]
FWIW this behavior is reproducable on Chrome 43 / Linux as well.

**Comment by codelitt** [comment]
Reproducible in Chrome Canary  45 / Mac and Chromium / Arch as well. 

>  more like a browser bug

Does not seem to be a browser bug if it's happening across most browsers.

**Comment by chibicode** [comment]
Hmm ok.

Just posting that someone saw this on Safari as well:
https://news.ycombinator.com/item?id=9857177

**Comment by Aldarone** [comment]
It happens with Firefox 40 on GNU/Linux as well.

**Comment by jjt** [comment]
It's probably due to this line in the embed script https://github.com/jsbin/jsbin/blob/master/public/js/embed.js#L222

Maybe switching it to use something like `iframe.contentWindow.location.replace(url);` for supported browsers.

**Comment by remy** [comment]
I'd be open to a PR to change `embed.js` if this will resolve the issue. I'm on holiday ATM so the best I can do is merge PRs and push a release at the weekend.

It looks like @jjt has most of it already (can you also test that it does work as you expect - or at least run a pared down test).

**Comment by chibicode** [comment]
thanks, I'm not familiar with the codebase but I'll try to edit based on @jjt's changes/run the test and open a PR sometime today or tomorrow. @remy sorry to make you respond when you're on a holiday.

**Comment by chibicode** [comment]
@jjt @remy i did some investigation (took me a while to get it set up locally), but it turns out that `iframe.contentWindow` or `iframe.contentDocument` is only accessible when the iframe window has the same origin URL as the host page. So it wouldn't work for JSBin.

According to Stackoverflow, I think the only possible way seems to be to swap the old iframe with a new iframe:
http://stackoverflow.com/a/8681618/114157

I can pursue this approach if @remy is ok with it.

**Comment by remy** [comment]
Okay, so I *nearly* went down this path so it should be simple to
implement. Instead of updating the SRC, when the iframe does the full load,
it gets swapped for a new iframe.

I can do this relatively quickly.

**Comment by chibicode** [comment]
@remy great, if you could take care of this that'd be fantastic. but nothing urgent though. thank you!

**Comment by chibicode** [comment]
@remy thank you!!
