### ISSUE TITLE
Please delete my account

### ISSUE THREAD

**Issue by dharFr** [jsbin/jsbin#2466]
Username: dharFr 

Thanks.

**Comment by remy** [comment]
Hi there,

Sorry for the delay, I've finally got around to exposing the functionality to delete accounts directly - so although you're leaving JS Bin, you've made it a little better for everyone else too: https://jsbin.com/account/delete

Cheers and goodbye :'(

**Comment by dharFr** [comment]
Hi @remy, 
Thanks for your reply. 

I just tried to actually delete my account by following instructions on the provided URL and I got an `Internal Server Error` (and the account still exists). 
I can open a new issue if you think it's more appropriate.

Oh, and btw I'm not leaving, justing deleting my second, unused account. ^^

**Comment by remy** [comment]
I've just releasing a patch to fix that. It hit that error when your username didn't match the confirmation, but I suspect I need `toLowerCase` the check. You should be able to give it another go now.

**Comment by dharFr** [comment]
Worked like a charm. Thanks.
