### ISSUE TITLE
auto indent not working with %code%

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/jsbin#2470]
Here's a demo of the bug: http://jsbin.com/noyuvu/edit?html,output

Select all the HTML, then press <kbd>Shift</kbd>+<kbd>Tab</kbd> (at least on Windows) to reindent. The indenting gets screwed up.

**Comment by remy** [comment]
Is this only a problem when it contains the %code% fragment?

**Comment by kamidev** [comment]
I can reproduce this (on a Mac) too. Markup directly after the %code% does not reindent correctly. Markup elsewhere does not seem to be affected.

**Comment by Daniel-Hug** [comment]
Remy, yes.

**Comment by remy** [comment]
That makes sense then. The %code% token is entirely custom on jsbin's side,
so it must be breaking the beautifier token parser.

I feel like this might be a bit of a edge case that we leave unless someone
PRs a new beautifier.

A workaround is beautify without %code% then reinsert it.

Is that reasonable?

**Comment by Daniel-Hug** [comment]
Sounds reasonable. I don't see how that could break anything else.
