### ISSUE TITLE
How to add resources such as audio 

### ISSUE THREAD

**Issue by MingXingTeam** [jsbin/jsbin#2471]

**Comment by MingXingTeam** [comment]
i want to test this:<audio src="test.mp3" controls="controls">not supported!</audio> ，but i dont know how to add local resource：test.mp3. Does jsbin support this?

**Comment by remy** [comment]
This is a pro feature. You need to drag the asset into the asset manager in
your account.

**Comment by MingXingTeam** [comment]
thank you @remy
