### ISSUE TITLE
I have two accounts that I would like to merge

### ISSUE THREAD

**Issue by samholmes** [jsbin/jsbin#2476]
I signed up to jsbin before GitHub integration was even a thing. I later clicked login with GitHub, and then it created an extra account using my GitHub username. Now, when I try to link my GitHub account with my original account, it's telling me that I cannot do this because my github account is already associated with the newer account.

At first, I thought I lost my original bins, but it looks like all I needed to do was login using my email, and boom, all my old bins.

This is annoying having two accounts. I want to merge them in some way. I prefer the old username @sammy vs the new one @samholmes, even though the latter is my github account name. How can I go about merging the accounts so I only have one that I can log into with github or email?

**Comment by remy** [comment]
I have to do it manually.

Can you confirm (so I don't mess it up) which should be the master account, and I'll transfer all the bins across from the old account, then you can go ahead and delete the old account.

**Comment by samholmes** [comment]
@remy The master account I want is @sammy.

**Comment by samholmes** [comment]
Any news on this? I still notice that I have two separate accounts. I'd like @sammy to be my master account and username, and I'll like the @samholmes account to be removed but all the bins moved over to @sammy and the github connection to route to @sammy. Can this be done please? :)
