### ISSUE TITLE
Broken avatar

### ISSUE THREAD

**Issue by Vanav** [jsbin/jsbin#2479]
Hello.
My avatar is broken (empty URL), but I have avatar on GitHub and I have Gravatar.
I had no avatar on GitHub or Gravatar at time of sign up, but since then I've added them.

**Comment by Vanav** [comment]
:-(

**Comment by remy** [comment]
...to gravatar?

**Comment by Vanav** [comment]
I've set email in settings, and now avatar is shown from Gravatar.
