### ISSUE TITLE
I want to preview my website as in Homesite

### ISSUE THREAD

**Issue by Ellena2015vip** [jsbin/jsbin#2480]
can anybody advise,please?
I would like to have a chance to see my web-site on the right as in homesite, with pics etc. If I buy pro, will I be able to do it ?

**Comment by remy** [comment]
You can preview a page in jsbin, and with pro you can use a vanity url (such as http://dave.jsbin.com) and you can drag and drop images into the browser to upload. But jsbin should not be used to host whole web sites (as per the [legal terms](https://jsbin.com/legals/#111)) - jsbin obviously welcomes trying code out, testing it, hacking around to learn etc.

**Comment by Ellena2015vip** [comment]
Thank you, and how can I drop images into the browser ? Is there any video  for me to have a look and to learn how to do it ?

**Comment by remy** [comment]
There is! http://jsbin.com/help/asset-uploading
