### ISSUE TITLE
Babel won't work in the Live Preview aka ↗.

### ISSUE THREAD

**Issue by lolmaus** [jsbin/jsbin#2484]
1. Take any working JSBin. Have this one for an example: http://emberjs.jsbin.com/voquba/4/edit?html,js,output (Don't forget to clone it).
2. See it work fine in the Output panel.
3. Click `↗` to open the output in a separate tab (Live Preview) and see it work fine.
4. Swtich the JS panel to `ES6 / Babel` mode.
5. See it still work in the Output panel.
6. Refresh the Live Preview tab and see it fail.

> Uncaught ReferenceError: App is not defined

Switch JS mode back to vanilla, refresh Live Preview and it works again.

**Comment by remy** [comment]
Does it work if you set babel before you pop out?

**Comment by lolmaus** [comment]
No, sir, it doesn't. You can try yourself.
