### ISSUE TITLE
es6 / babel and Array.from (polyfills)

### ISSUE THREAD

**Issue by duivvv** [jsbin/jsbin#2485]
I keep getting 

    "TypeError: Array.from is not a function
    at _toConsumableArray (mudata.js:3:178)
    at mudata.js:5:39
    at https://static.jsbin.com/js/prod/runner-3.34.0.min.js:1:13603
    at https://static.jsbin.com/js/prod/runner-3.34.0.min.js:1:10524"

when I use spread operators or Array.from in jsbin (ES6 / Babel) setting.

is there a way to include "babel/polyfill" in the js build?

thanks a lot :)

**Comment by remy** [comment]
Using a script tag in the html.

**Comment by duivvv** [comment]
Hmm. Tried it yesterday with the CDN version and didn't seem to work, guess i'll have to host my own version of the polyfills. Thanks for the answer.

**Comment by KamilLelonek** [comment]
How did you solve that?

**Comment by fritx** [comment]
How did you solve that? +1
I'm using nw 0.12.3 which is in iojs 1.2.0 & chromium 41.0
There is no `Array.from`
My babelrc is:

```plain
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ]
}
```

**Comment by fritx** [comment]
Oops :/

**Comment by jesselee34** [comment]
+1 How did you solve that?

**Comment by AlexBai1991** [comment]
import 'babel-polyfill' in your entry point.

**Comment by fritx** [comment]
babel-polyfill, or use babel-plugin-transform-runtime
https://babeljs.io/docs/usage/polyfill/
