### ISSUE TITLE
Getting error when running D3 code

### ISSUE THREAD

**Issue by lavnishl** [jsbin/jsbin#2486]
Hi
Please find attached snapshot of error i get when i try to run a basic D3 code. the same code runs fine on local browser.

![error](https://cloud.githubusercontent.com/assets/10140690/8792847/fea4ea9e-2f8a-11e5-8224-aa4db9648b8b.PNG)

**Comment by remy** [comment]
Not including the actual bin means I can't actually debug it, but wild
stabs as they are: try adding "// noprotect" to your js panel and let me
know.
