### ISSUE TITLE
Non-Profit interested in jsBin pro version

### ISSUE THREAD

**Issue by Bijesse** [jsbin/jsbin#2487]
Hello,

I work at a non-profit in NYC called ScriptEd. With the help of our volunteers we teach front-end web development students in under-resourced schools. We have been using jsBin in our classrooms for over a year now... We love jsBin. With a new school year starting and ScriptEd growing to 600 students I would be interested in learning more about the advantages of going pro.

Can someone please contact me with this information. Apologies for posting in issues. I was not sure the best way to reach out with the question.

Thanks,
Tom Bijesse
(917) 566-7564

**Comment by remy** [comment]
Please email me at remy@jsbin.com
