### ISSUE TITLE
Pro access for education

### ISSUE THREAD

**Issue by gleicher** [jsbin/jsbin#2489]
Hi - this seems to be the only way to communicate with you.

I would like to use jsbin with my class (CS559, Computer Graphics at the University of Wisconsin). We're switching the assignments to Javascript, and JSBIN will be really handy. 

Your signup page says that you support education users for free. Is it possible for me to get a "pro" account for free (as an educator who will be using it for a class). Or at least an academic discount. 

I thought I'd ask - the price is pretty reasonable even without any discount. I just need to make sure I'll actually get enough value from it. (using JS for the class is an experiment)

Thanks,

Mike (gleicher@cs.wisc.edu)

**Comment by remy** [comment]
@gleicher drop through an email to support@jsbin.com and I'll reply with the discount code you'll need as an educator.
