### ISSUE TITLE
Please move keybinding Ctrl+Y to something else

### ISSUE THREAD

**Issue by quangkieu** [jsbin/jsbin#2491]
It happened 3 times already. As we - developers - know that in text editor, there is combo Ctrl+Z to "Undo" and Ctrl+Y to "Redo" an action. But JSBin binds the the combo Ctrl+Y to something and now the server temporally block me for hours because I use Ctrl+Y so many time in short period. When you produce a product for developers, you at least should know those basic combos and use different combo for your advance feature. And i working environment, that is freaking frustration because of the delay.

**Comment by remy** [comment]
Sure. Can you list those "basic shortcuts" and their function? Don't forget
to cover both Mac and windows. Cheers. I appreciate the feedback.

**Comment by remy** [comment]
How you getting on with that list?

**Comment by quangkieu** [comment]
Tab: next editable element or character tab
Shift+Tab: Previous editable element
F1: Help menu
F2: could be extra Help menu
F3: Open find menu if first run or find next match if not first run
Shift+F3: Previous match
F5/F4: Build the project/solution or run the code for script
F10: mostly main menu
F12: sub-menu
Home: start of sentence
Ctrl+Home: start of document
End: end of sentence
Ctrl+End: end of document
Backspace: Delete previous character
Ctrl+Backspace: Delete previous word
Delete: Delete next character
Ctrl+Delete: Delete next word
Insert: Toggle Insert/Replace mode
Ctrl+Y:Redo
Ctrl+Z:Undo
Ctrl+C: Copy
Ctrl+X: Cut
Ctrl+V: Paste
Ctrl+A: Select All
Ctrl+R: Reload file of some IDEs or Align Right in WYSIWYG editor
Ctrl+W: Close tab, windows (mostly will take over by browser)
Ctrl+H:Find+Replace (program specific feature so you could add this for Jsbin)
Ctrl+F:Find (most likely will take over by browser itself)
Ctrl+B:Bold in WYSIWYG editor (Jsbin could make it a shortcut to add <b> tag over selected text)
Ctrl+I: Italic in WYSIWYG editor (Jsbin could make it a shortcut to add <i> tag over selected text)
Ctrl+U: Underline in WYSIWYG editor (Jsbin could make it a shortcut to add <u> tag over selected)
Ctrl+E: Align Center in WYSIWYG editor (Jsbin could make it a shortcut to add <center> tag over selected or add style="text-align: center")
Ctrl+L: Align Left in WYSIWYG editor
Ctrl+J: Align Justify in WYSIWYG editor
Ctrl+N: New file (new bin in jsbin)
Ctrl+O: Open file menu (browser most likely or jsbin could take over to open my bins menu)
Ctrl+P: Print (take over by browser most likely)
Ctrl+T: new tab (mostly browser)
Ctrl+Right Arrow: move to next word
Ctrl+Right Arrow: move to next word

**Comment by remy** [comment]
So, starting with the very first item on the list, you think when you're in the editor, when you press tab, instead inserting an actual tab (since that's how users code), that you should tab *out* of the editor?

(You've also missed all the international keyboard shortcuts that use alt+Ctrl to make altgr that are used to make extra characters).

**Comment by quangkieu** [comment]
I just updated the list. How do you think about it now? I do not have any experience with alt+Ctrl or altgr  so I don't think that I am good person to fill in those.

**Comment by abhisekp** [comment]
@quangkieu usually, developers use <kbd>**CTRL**</kbd>`+`<kbd>**SHIFT**</kbd>`+`<kbd>**Z**</kbd> to undo.

**Comment by remy** [comment]
cmd+y / ctrl +y has been removed (as of last week).
