### ISSUE TITLE
Allow custom embed hook

### ISSUE THREAD

**Issue by gajus** [jsbin/jsbin#2492]
Now the only [documented](http://jsbin.com/help/how-can-i-embed-jsbin) way to embed jsbin using the following syntax:

``` html
<a class="jsbin-embed" href="http://jsbin.com/nexuqo/embed?js,console"> on jsbin.com</a>
```

However, using an inline element for the purpose of generating a block element causes issues in edge cases, e.g. when used in markup the above code becomes:

``` html
<p>
    <a class="jsbin-embed" href="http://jsbin.com/nexuqo/embed?js,console"> on jsbin.com</a>
</p>
```

which in turn becomes:

``` html
<p>
    <iframe class="" id="" src="http://jsbin.com/nexuqo/embed?js,console" style="border: 1px solid rgb(170, 170, 170); width: 100%; min-height: 300px; height: 673px;"></iframe>
</p>
```

after `DOMContentLoaded` event.

It would be great if we could use any element with custom `data-` attribute.

**Comment by danielsharvey** [comment]
Can we re-open this? Still seems applicable to me...
