### ISSUE TITLE
Allow babel options

### ISSUE THREAD

**Issue by gajus** [jsbin/jsbin#2493]
Babel has a lot of [options](https://babeljs.io/docs/usage/options/). Options such as `stage` are critical for making learning examples. Configuration could be passed in a form of a comment at a beginning of the babel script:

``` js
// <namespace> <JSON configuration>
```

e.g.

``` js
// babel {"stage": 1}
```

**Comment by remy** [comment]
I agree we need a way of getting options in. I'm not sure comments in the JavaScript is the right way to do this.

I feel like it needs to be part of the UI somehow...
