### ISSUE TITLE
Some problem with setTimeout()

### ISSUE THREAD

**Issue by xanaduhl** [jsbin/jsbin#2494]
when I exec fellow code:

console.log(1)  
setTimeout(function () {console.log('a')}, 10);  
setTimeout(function () {console.log('b')}, 0);  
var sum = 0;  
for (var i = 0; i < 1000000; i ++) {  
    sum += i;  
}  
console.log(sum);  
setTimeout(function () {console.log('c');}, 0);  

The result same has some problem , it different with brower's results.
My English is not well , sorry

**Comment by remy** [comment]
Try adding `// noconflict` to the js.
