### ISSUE TITLE
Babel asyncawait does not work

### ISSUE THREAD

**Issue by gajus** [jsbin/jsbin#2495]
Looking at the code I can tell that you are [executing babel using `{stage: 0}` option](https://github.com/jsbin/jsbin/blob/a236ce5662891277095527379ba1ca8b52c745b5/public/js/processors/processor.js#L512).

``` js
babel: createProcessor({
  id: 'babel',
  target: 'js',
  extensions: ['es6'],
  url: jsbin.static + '/js/vendor/babel.min.js',
  init: function (ready) {
    ready();
  },
  handler: function babelhandle(source, resolve, reject) {
    try {
      resolve(babel.transform(source, { stage: 0 }).code);
    } catch (e) {
      console.error(e.message);
      reject([{
        line: e.loc.line - 1,
        ch: e.loc.column,
        msg: e.message.split('\n')[0].replace(new RegExp('\\\(' + e.loc.line + ':' + e.loc.column + '\\\)'), '(' + e.loc.column + ')')
      }]);
    }
  }
}),
```

However, I have tried creating a simple `async` example using jsbin:

``` js
async function foo () {
    console.log('OK');
};

foo();
```

and I am getting an error:

```
SyntaxError: Unexpected token ;
    at https://static.jsbin.com/js/prod/runner-3.34.1.min.js:1:13603
    at https://static.jsbin.com/js/prod/runner-3.34.1.min.js:1:10524
```

Looking at the evaluated code, this is what jsbin is trying to run:

``` js
try {'use strict';

function foo() {
    return regeneratorRuntime.async(function foo$(context$1$0) {
        ;window.runnerWindow.protect({ line: 5, reset: true }); while (1) switch (context$1$0.prev = context$1$0.next) {;
if (window.runnerWindow.protect({ line: 5 })) break;

            case 0:
                window.runnerWindow.proxyConsole.log('OK');

            case 1:
            case 'end':
                return context$1$0.stop();
        }
    }, null, this);
};

foo();
} catch (error) { throw error; }
```

However, knowing babel, this is what it is supposed to run instead:

``` js
'use strict';

function foo() {
    return regeneratorRuntime.async(function foo$(context$1$0) {
        while (1) switch (context$1$0.prev = context$1$0.next) {
            case 0:
                console.log('OK');

            case 1:
            case 'end':
                return context$1$0.stop();
        }
    }, null, this);
};

foo();
```

From that I can tell that jsbin is injecting `;window.runnerWindow.protect({ line: 5, reset: true });` which is causing the syntax error.

**Comment by gajus** [comment]
Using this I have been able to find this issue https://github.com/jsbin/jsbin/issues/1906. It advises to disable https://github.com/jsbin/loop-protect/blob/master/README.md#abstract using `// noprotect` comment.

When [this is done](http://jsbin.com/xepesa/2/edit?js,console), a new error is thrown.

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

It appears that Babel public API is not exposed in the running context.

**Comment by gajus** [comment]
Assuming that `babel/polyfill` is not going to be included in the core a simple workaround is to add the [polyfill](https://babeljs.io/docs/usage/polyfill/) as a script tag.

```html
<script src='https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.js'></script>
```

http://jsbin.com/xepesa/edit?html,js,console,output

**Comment by burabure** [comment]
Thank you so much for the info!

btw the polyfill url now is:
```https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser-polyfill.min.js```

**Comment by StarpTech** [comment]
Didn't work for me run into `babel not defined`
