### ISSUE TITLE
Embed output only

### ISSUE THREAD

**Issue by iamvdo** [jsbin/jsbin#2499]
When choosing "Embed ouput only" for a Snapshot, I get the following code:
```
<a class="jsbin-embed" href="http://jsbin.com/jixanu/1/embed">JS Bin on jsbin.com</a><script src="http://static.jsbin.com/js/embed.min.js?3.34.1"></script>
```
Using this code generates a full editor, not only output: http://codepen.io/iamvdo/pen/OVBepx 
What am I doing wrong?

**Comment by remy** [comment]
You can embed with the output open, but you can't embed just the output
without jsbin

**Comment by iamvdo** [comment]
OK, so I find share options quite confusing.
It seems there is no difference between "View > Editor > Ouput" vs. "Ouput only", but previews are different.

![jsbin](https://cloud.githubusercontent.com/assets/1260529/8926676/dd2fedc8-3511-11e5-9b1f-cf18836f0361.png)

**Comment by remy** [comment]
You're right, that's a visual confusion. The "what they'll see" is for the
shared link, rather than the embedded view.

**Comment by kropsi** [comment]
OUTPUT ONLY with livereload means output only. This is VERY misleading!

It just cost me €112, as I thought you were able to embed output without advertisement for jsbin when you upgraded to PRO.

So what exactly am I getting for PRO if not that functionality?

**Comment by remy** [comment]
@kropsi embeds should definitely not contain advertising if you've got a pro account. Can you point me to a URL where you're able to see this so I can fix it?
