### ISSUE TITLE
404 error page is shown after clicking the "File" menu button or its download option

### ISSUE THREAD

**Issue by user-e** [jsbin/jsbin#2500]
When using the website, after clicking the "Download" option in the "File" menu on the toolbar  
(to download a copy of code to local computer filesystem), it goes to a 404 not found error page.

Also, there's a similar problem where a 404 not found error appears after clicking the "File" toolbar  
button to use its drop-down menu, in a mobile web browser _(that's based on Google Chrome)_.  
When clicking it, the page `http://jsbin.com/edit#file` opens in a new tab before the menu appears.

Editor with file menu screenshot | 404 error page screenshot
--- | ---
![image named 112593f0-3551-11e5-829c-a37660ca3fc9](https://user-images.githubusercontent.com/13541254/34724590-429b4580-f546-11e7-90f2-1402465cbe21.png) | ![image named 204f85fc-3551-11e5-9fab-a3f1cf2d85a7](https://user-images.githubusercontent.com/13541254/34724729-d838b82a-f546-11e7-8d42-df1ea92dc40b.png)

I think the cause of this problem is that when no code had been added to any of the
editor tabs *(I hadn't typed any code)*, it wasn't saved so there's nothing to be downloaded
by clicking that menu item. When I started editing, it was saved and that button worked.

So, to sort out this problem, when there's no code to download, the menu item should be  
disabled or a nicer error message shown on the page, saying that there's nothing to download.
However, the template (default code) for new _bins_ automatically adds some HTML code
which means that the editor tabs aren't blank and can probably be downloaded without editing.

**Comment by remy** [comment]
What bin URL are you trying to download?

**Comment by user-e** [comment]
Oh, it doesn't matter what bin URL, I have noticed the reason the page
appears to be missing. When you haven't typed anything into the editor,
it isn't saved, so the "Download" page doesn't have any work to download.
When you start editing, it saves it and you can download your work.

I don't think this is an issue apart from the fact the "Download" page shows
a 404 error which could possibly be confusing to the user.

**Comment by user-e** [comment]
I think I will close this issue.
If anyone disagrees with my choice, you might be able to re-open the issue.

**Comment by user-e** [comment]
Ok, this is how I close it.

**Comment by Arthur-W-White** [comment]
Hi, this is confusing... It should either let you download the contents or grey out the download button? It is a bad UX choice right now.

**Comment by remy** [comment]
Happy for you to send a PR to fix it if you think it's worthwhile (I mean, you commented, so I'm guessing you feel it's worthwhile). Thanks in advance.

**Comment by user-e** [comment]
Improved this issue's title. I agree with @Arthur-W-White that it's confusing so the _File>Download_ menu link should be disabled for unsaved work, not a 404 error page.
I'm reopening this issue so a pull request or discussion with other people can close it properly.

**Comment by remy** [comment]
Doesn't need to be open to have a PR or extra discussion. More pressing issues, but looking forward to your PR.

**Comment by user-e** [comment]
@remy 
I've improved the description about this issue and found a similar problem, see above.
