### ISSUE TITLE
How to change my avatar?

### ISSUE THREAD

**Issue by chrisco** [jsbin/jsbin#2502]
It looks like it is using a picture from a few years ago.  When I log in to Gravatar.com, it's not even there.  Thanks.

**Comment by remy** [comment]
It's based entirely on the email jsbin has, but this is (normally) carried through from github. If you check https://jsbin.com/account/profile - make sure the email address is the one that you use with gravatar.com.

**Comment by chrisco** [comment]
Thanks for the reply and comments.  I got it fixed now.  Love your service (and which you offered a less expensive paid option for very light users who still want to support you and get some pro features).

**Comment by remy** [comment]
I have that too: https://gratipay.com/jsbin
