### ISSUE TITLE
Not updated when commenting

### ISSUE THREAD

**Issue by juanpastas** [jsbin/jsbin#2503]
I used `ctrl + /` to comment some lines and then re run script.

Changes were not detected. I had to fire enter some keys for changes to be detected.

**Comment by remy** [comment]
There's a little latency, but that's normal - I'm just hitting `cmd+/` (mac).

![http://zippy.gfycat.com/FewHarmlessFlyinglemur.gif](http://zippy.gfycat.com/FewHarmlessFlyinglemur.gif)

Not quite sure (from the description) what you're referring to if not the JS...
