### ISSUE TITLE
GIVE free STUFF

### ISSUE THREAD

**Issue by McJSBIN** [jsbin/jsbin#2504]
JSBIN should be free for learning GOOD example w3shool has help me and many others to learn i wish jsbin DO the same as well. Its good to pass knowledge and skills to the next generation and its about making money be remember to give back to the communities of jsbin-thats my option - whats your say-you out there!!!!!

**Comment by Delapouite** [comment]
w3school is just the worst example you could have used to illustrate your point.

**Comment by remy** [comment]
Urm...unless I'm totally mistaken, jsbin *is* free. Heck, you've commented on the git repo that contains all the source...for free.

The only thing that isn't free are a handful of pro features, and the income from that doesn't even touch the sides of the hosting and development. A **handful** compared to a tonne of free features, including **being able to save any content without even having a god damn account**, live reload, code casting, coffeescript, babel, sass, scss, account history, editor preferences, embedding, ssl, downloading bins, exporting and much much more.

So, yeah, it's already free.

**Comment by Prajjwal** [comment]
You made this account *just* to troll @remy? :laughing:

**Comment by motyar** [comment]
We want more !!!! more FREE stuff lol

**Comment by mazer-rakham** [comment]
Remy, why you making alts to talk to yourself? Lol /joke
