### ISSUE TITLE
Allow to inject one jsbin into another using shadow DOM

### ISSUE THREAD

**Issue by gajus** [jsbin/jsbin#2505]
I use jsbin quite a lot to design and prototype components, e.g. http://jsbin.com/varore/9/edit?html,css,output. It would be awesome if I was able to include one jsbin into another using some sort of shadow DOM equivalent.

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
    <div id='app'>
        <jsbin src='http://jsbin.com/warene' alt='search'>
        <jsbin src='http://jsbin.com/varore' alt='screenings'>
    </div>
</body>
</html>
```

**Comment by remy** [comment]
What would that look like?

**Comment by gajus** [comment]
A very rough example, http://jsbin.com/mufozo/2/edit?html,js,console,output.

```js
var entryElement,
    shadow,
    shadowBody,
    binData;

entryElement = document.querySelector('jsbin');

shadow = entryElement.createShadowRoot();

// Some magic method of capturing data from 'http://jsbin.com/' + entryElement.id
entryElement.id;

binData = {
    // document.body of the target bin
    body: '<div class=\'test-a\'>Test A</div>',
    // document.styleSheets
    style: '<style>.test-a { background: #f00; }</style>'
};

shadowBody = binData.body + binData.style;

shadow.innerHTML = shadowBody;
```

**Comment by gajus** [comment]
Importing JavaScript part... thats possible, though not something I'd aim for the first implementation.

**Comment by gajus** [comment]
Never mind. It can be achieved using HTML imports, http://www.w3.org/TR/html-imports/.

**Comment by gajus** [comment]
However, if you try that now (http://jsbin.com/mufozo/4/edit?html,css,console) it will fail because loading the resource ("http://jsbin.com/lopigo") results in 302 response code.

**Comment by gajus** [comment]
Sorry, the URL should have been http://output.jsbin.com/lopigo. Nonetheless, because the content is being generated dynamically, I am not able to make it work using jsbin.com. However, I have setup a quick sandbox on my own host (http://gajus.com/sandbox/jsbin-test/), set `Access-Control-Allow-Origin: http://null.jsbin.com` header and produced an example of a working implementation:

http://jsbin.com/mufozo/5/edit?html,js,output

**Comment by gajus** [comment]
This feature could be abstracted using `<jsbin>` custom attribute and HTML imports polyfill, http://webcomponents.org/polyfills/html-imports/.
