### ISSUE TITLE
Looking for a page source

### ISSUE THREAD

**Issue by etienne-ch** [jsbin/jsbin#2507]
Hi,

I'm a newbie in JSBin.
I'm just looking for the source of this page : 

http://output.jsbin.com/heboke/19

When I click on the 'edit' button I only get minimal html / javascript sheets
This file is part of the edX html5 course from W3C.

Thanks for your help,
Etienne

**Comment by remy** [comment]
Can you post a screenshot of what you see, because when I hit edit, I see
the full source.

**Comment by etienne-ch** [comment]
Yeah, this is what i get : 

![cap_jsbin](https://cloud.githubusercontent.com/assets/13596249/9023242/97087d58-3893-11e5-9da2-7b2c0cf68170.png)

Any idea ?

**Comment by etienne-ch** [comment]
This must be something with my browser settings. I'm using Icecat on linux right now.
The content displays well on another browser.

**Comment by etienne-ch** [comment]
Well with the other browser which is Abrowser I can download only the html file, not the css sheet.
Getting frustrating .... cause it won't even allow me to copy/paste it in a text editor.......

**Comment by remy** [comment]
This is all very strange. Can you try directly navigating to the edit window in a private browsing session (I *think* you're using Firefox, but I'm not 100% sure), but in Chrome this would be an incognito window, and then visiting http://jsbin.com/heboke/19/edit - this can rule out either any local storage values or plugins messing with the page.

**Comment by etienne-ch** [comment]
Icecat is the GNU version of firefox. It has some privacy features like pretending its a Windows app so maybe that's what is messing it up.
I've tried private mode but it didn't change anything.

**Comment by remy** [comment]
Super weird! But glad you're able to work around it.

It sounds like Icecat is worth looking at one day for bugs then.

I'll close this for now though, since you're able to get there.

Thanks for the bug report!

**Comment by caskuplich** [comment]
I got the same error using IceCat 38.8.0 when I visited the URL https://jsbin.com/viyima/edit?html,output as such as the JS Bin home. I runned IceCat in safe mode to disable all add-ons but the same page with the JavaScript error showed by @etienne-ch's screenshot appears to me. Thanks in advance.
