### ISSUE TITLE
Facebook embed code dosen't work on jsbin

### ISSUE THREAD

**Issue by NeoCsatornaja** [jsbin/jsbin#2508]
Hy!
I would like to try out facebook embed, but unfortunetly dosen't work.
Can you help me out?
The code was:
http://jsbin.com/tulikukani/edit?html,output

**Comment by remy** [comment]
Facebook is blocking jsbin. There's nothing I can do about it.

**Comment by NeoCsatornaja** [comment]
The whole site?
Wow!
I mean, I know i can't share esaly jsbin links, but I also can't run facebook scipts?
That's crazy

**Comment by remy** [comment]
Sorry, I misunderstood. I thought you wanted to embed in fb. 

Regarding your source code - it looks like there's errors embedding whilst inside an iframe: 

<img width="1276" alt="screen shot 2015-08-02 at 14 12 08" src="https://cloud.githubusercontent.com/assets/13700/9026250/8f8410a0-3920-11e5-92de-e4f7b30d4e56.png">

If you view the full output (without jsbin's iframes) then the embed renders (I just cloned it and saw the embed).

**Comment by NeoCsatornaja** [comment]
Okey, but what can I do?
Is that possible run facebook scripts in jsbin somehow?

**Comment by remy** [comment]
Yes, but just use the live reload in a new window (click the pop out icon).

**Comment by NeoCsatornaja** [comment]
Not working, this just open a new window with code but I doesn't  see the final output.
