### ISSUE TITLE
How to run client-side processor which depends on runtime code?

### ISSUE THREAD

**Issue by roman01la** [jsbin/jsbin#2509]
I'm trying to setup self-hosted ClojureScript (this [PR](https://github.com/jsbin/jsbin/pull/2506)), the runtime is a huge blob, 5MB, so it's inefficient to move it into the sandbox every time it is being reloaded. Is there another way to include runtime code into the sandbox? I can only think of a worker thread.

**Comment by remy** [comment]
If this is for jsbin, I'm pretty certain the processor is loaded in the
chrome (the editor part of jsbin) and the processing happens there, and
only the output gets injected over and over in the sandbox.

Or is the resulting code supermassive?

**Comment by roman01la** [comment]
The thing is that the resulting code is dependant on the runtime, which is the processor itself, so when it's being evaluated it throws.

I've moved CLJS runtime into a web worker, so it's always there, and it works fine, actually I like it. But this means it's no longer possible to work with DOM :(

**Comment by remy** [comment]
Can you have the resulting code communicate through the sandbox on message
event bus?

**Comment by roman01la** [comment]
Does it mean to pass code to the editor, eval, and put it back into the sandbox? I'm not sure how to do it, but wouldn't it be not safe to eval code in the main thread? I could just eval in the processor then, but it doesn't feel right.

**Comment by roman01la** [comment]
I think I'm fine with web worker, since there's no access to DOM, unless it's possible to not reload sandbox, but I guess this is not an option.
