### ISSUE TITLE
Help newbie

### ISSUE THREAD

**Issue by breslin2** [jsbin/jsbin#2512]
I don't see a place to enter my HTML code. I hit "New Bin" but nothing. The following image is what I am seeing. This is my first time here and I am newly registered. I have not received any welcome emails of any sort from you so I hope all is well with my account.  Thank you for your help in getting started.

![jsbin](https://cloud.githubusercontent.com/assets/13650498/9100754/50c22472-3bac-11e5-9b0b-f5b59b9d895c.png)

![jsbin](https://cloud.githubusercontent.com/assets/13650498/9100862/a9b880e8-3bad-11e5-8fce-c2a0a1c76b2d.png)

**Comment by remy** [comment]
JS Bin isn't loading. What browser is that? Also, can you capture and report any errors found in your browser's native console?

**Comment by breslin2** [comment]
Internet Explorer 11

(Please see attached screenshot of what I am seeing).

This is my first time trying to use JSBIN so maybe I am not clicking on something I should be.

I clicked on “New Bin” thinking I would see a place to enter my HTML code but nothing happens when I click on “New Bin” as if it is inactive.

I really appreciate you getting back to me so quickly. I’d be happy to work with you to resolve this issue. If we need to cancel my JSBIN account and start over I would be willing to do that too. Thank you again. / Ed

**Comment by remy** [comment]
It's not your account, it's the browser. The screenshot didn't turn up. Can you upload it to github?

**Comment by breslin2** [comment]
The browser is Internet Explorer 11.
Screenshot attached.

![jsbin com problem using internet explorer 11_](https://cloud.githubusercontent.com/assets/13650498/9140634/ae9baf64-3d00-11e5-98eb-0dee31de980d.png)

**Comment by breslin2** [comment]
I am using IE 11.

I uploaded the attached screenshot to github.

**Comment by remy** [comment]
Also, can you capture and report any errors found in your browser's native console?
