### ISSUE TITLE
Inconsistent Insertation of tabs

### ISSUE THREAD

**Issue by coaster3000** [jsbin/jsbin#2514]
## Environment

**Browser Information:** Firefox version 39.0.3
Build identifier: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
**System Information** 
**Operating System:** Windows 8.1
Other details not important at time.
## Problem

Using the tab key is resulting in extremely inconsistent behavior with the code editor. It will not consistently use the tab character in input. Setting the editor settings to tabs will not change the action on the tab key to insert a tab character. 

Setting the editor to use spaces then back to tabs seems to make it function only for a short while before returning to its inconsistent behavior.

**Panels Affected**: Currently only tested the css panel under the Sass Editor mode.
SCSS Panel is also affected,
other panels currently not tested. However it is assumed that they result in the same issue if one editor window is inconsistent.

Using shift tab will _Sometimes_ make the editor replace spaces with tabs. Also very inconsistent.
Editor will complain about inconsistent code indentation due to this error. Once this message displays once. Even if you correct it, this error message will never go away until you refresh the page after fixing the issue the error relates to.

**Comment by raldred** [comment]
Yeh. This is a big issue when using a indentation sensitive preprocess like sass or coffeescript.
The only solution at the moment is to use spaces.

**My system info**
OSX 10.10 Yosemite
Chrome 47

**Comment by sbrl** [comment]
I have found that setting my spacing preference to 'tabs' has absolutely no effect at all. I can't use jsbin without getting frustrated if I can't have tabs.
