### ISSUE TITLE
Live reload only working with https is not mentioned on features page

### ISSUE THREAD

**Issue by SamHasler** [jsbin/jsbin#2517]
Steps to reproduce:
1. Create a new bin
2. Type something in the `<body>` tag
3. click the "Live Preview" arrow in top right of output tab (this opens a new tab in the foreground)
4. switch back to edit tab
5. type more text in the  `<body>` tag
6. Wait for "Saved" message to appear at the top of the HTML tab
7. Switch back to output tab that was opened in previous step

Expected to see updated output with text added to body tag but output was still showing original output when the tab was first opened.

**Comment by remy** [comment]
Don't do it in a tab, do it in a new window.

**Comment by SamHasler** [comment]
Aha! it only works with https!

I assume that's intentional. Could http://jsbin.com/help/features be modified to say:

> * Live reload both in editor and in full preview (only on https)

**Comment by remy** [comment]
No, it should work over http *and* https...
