### ISSUE TITLE
How to make <username>.jsbin.com open to the editor view instead of the display view

### ISSUE THREAD

**Issue by cvrebert** [jsbin/jsbin#2518]
(Following up from https://twitter.com/mdo/status/631642152561324032 )
If I open http://emberjs.jsbin.com , I get an editor view, with a JS pane and an Output pane.
If I open http://bootstrap.jsbin.com , I get the display view, with no editor panes nor even the usual "Edit in JS Bin" button that normally appears on hover.

What do we have to do to get http://bootstrap.jsbin.com to act like http://emberjs.jsbin.com ? I couldn't seem to find anything relevant in the docs.
Thanks!

CC: @remy

**Comment by remy** [comment]
What the ember page has is different. But what I intended to do is change the vanity support to allow *you* to select whether vanity pages show the output or show the editor (ie. To offer a template).

I'll keep this issue updated as I start the change.

**Comment by cvrebert** [comment]
Any news on this?

> What the ember page has is different.

Well, what exactly do they have? We'd be quite satisfied to have the same thing. If it requires some subscription account level beyond Pro, I'm pretty sure we'd be happy to pay and upgrade.

**Comment by remy** [comment]
@cvrebert drop me an email offline: remy@jsbin.com - and I can explain what the option is (currently).

**Comment by cvrebert** [comment]
@remy Sent you an email on Oct 13; haven't seen any reply. Sent you another one just now.
