### ISSUE TITLE
Collaboration on bins

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#2519]
I've been asked about this, and though I've got bigger ideas, really there's a question around what can be done today that gets us closer to "my bigger ideas".

This is **not** real-time collaboration (we tried with togetherjs, but it doesn't work well with CodeMirror). This is adding other users to a bin to allow them to edit and save changes *on top of the same namespace".

I'm thinking [npm-style collaboration](https://docs.npmjs.com/cli/owner). Simple: you can add someone. There's no concept of an admin, anyone who can edit can remove a collaborator.

The ui will be simple at first (similar to the transfer bin inside the bin info card), except this will likely be left limited to pro accounts (since I need a justifiable reason to implement it).

Thoughts?

**Comment by richardj** [comment]
Would the invited user have to be a pro user? And would the initial creator of the bin stay the owner of it as long as the person doesn't decide to transfer it? (when everybody can just remove a collaborator it could be possible to be removed from your own created bin).

**Comment by remy** [comment]
Yes, and yes.
