### ISSUE TITLE
saving embed style

### ISSUE THREAD

**Issue by cjseeger** [jsbin/jsbin#2522]
Noticing that it does not save the option to show line numbers in the embed style

**Comment by remy** [comment]
Can you point me a bin url so I can check this out?

**Comment by cjseeger** [comment]
Remy,

http://cjseeger.jsbin.com/zalinu/edit?html,css,js,output


<a class="jsbin-embed" href="http://jsbin.com/zalinu/embed?html,css,js,output">JS Bin on jsbin.com<http://jsbin.com></a><script src="http://static.jsbin.com/js/embed.min.js?3.34.2"></script>



On Aug 19, 2015, at 3:18 PM, Remy Sharp <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you point me a bin url so I can check this out?

**Comment by cjseeger** [comment]
Remy,
Did you have a chance to look at why when I check the line numbers in the Embed Style that upon return to the page the box is not still checked?

Also had a question about deleting bins.  Maybe I am not using JSBin as intended, but I work on a project and generate 10 - 20 versions. I then get to a point that I think this file is final. Is there an easier way to delete all those versions? Or should I just clone the final as a new bin and go delete the most recent of the old ones?


I also still think it might be need to have some additional way to categorize bins.  For example I could label bins I do with Leaflet as ‘Leaflet’ those that test Census API’s  as “Census”  then those I use for student tutorials as “tutorials”


Thanks,

Chris









On Aug 19, 2015, at 10:13 PM, Seeger, Christopher J [L A] <cjseeger@iastate.edu<mailto:cjseeger@iastate.edu>> wrote:

Remy,

http://cjseeger.jsbin.com/zalinu/edit?html,css,js,output


<a class="jsbin-embed" href="http://jsbin.com/zalinu/embed?html,css,js,output">JS Bin on jsbin.com<http://jsbin.com/></a><script src="http://static.jsbin.com/js/embed.min.js?3.34.2"></script>



On Aug 19, 2015, at 3:18 PM, Remy Sharp <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you point me a bin url so I can check this out?
