### ISSUE TITLE
transfer feature looses current snapshot

### ISSUE THREAD

**Issue by SamHasler** [jsbin/jsbin#2523]
I hit the bottom right `viewsers > transfer` menu item on bin `miwumo` but did not enter anything in the dialog. I was on snapshot 39 which is now unaccessable. I cannot view https://jsbin.com/miwumo/ although https://jsbin.com/miwumo/38 works. I cannot make clones or snapshots.

**Comment by remy** [comment]
Ah poop - I ran into this the other night. Yeah, hitting cancel successfully transfers it to noone (or rather, disowns the bin!). 

BUG!

It needs a PR on here: https://github.com/jsbin/jsbin/blob/master/public/js/chrome/transfer.js#L5 just need to wrap the ajax call to check if `to` has a length.

**Comment by remy** [comment]
Wanna take a crack for some jsbin kudos?
