### ISSUE TITLE
Facebook Chat Sees as Unsafe

### ISSUE THREAD

**Issue by miguelzuleta** [jsbin/jsbin#2530]
Hello!

I was sending a jsbin link to someone else through facebook's web app, and it didn't let me. It blocked it from sending it saying it was unsafe. Check out the issue as an image attached.

![unsafe](https://cloud.githubusercontent.com/assets/8463388/9481770/0795aae4-4b42-11e5-926f-dd714d622929.jpg)

It seems to be a very new thing because I was able to send links yesterday. I hope this helps!

Thanks for the awesomeness!

**Comment by remy** [comment]
I think this has been resolved now. Not that I can do anything about it if it's not!
