### ISSUE TITLE
Someone stole my code...

### ISSUE THREAD

**Issue by RidderJanssen** [jsbin/jsbin#2535]
A while back, I made this thing, useful for a site named www.demnia.nl/
First versions: http://output.jsbin.com/nafote/1
Final versions: http://output.jsbin.com/gixofa/14

However, I quit the site because I was not able to get along with one of the owners of the site. I did leave my creation available for use.
But now, the owner of the site has copied all of the code and she pasted it into her own jsbin. She hardly changed anything. But she did change the part where I put my name on it: she changed my final message to just 'Thanks to jeannearc', which is me.
This is her version: http://jsbin.com/lulocutifu/1/edit?html,css,js,output
Compare it to my last version: http://jsbin.com/gixofa/14/edit?html,css,js,output

I of course am not happy to see this. My request is for her copy to be removed. Is that possible?
I am able to show 24 different versions from different times in the past that show my creation growing. Compare that to her lonely anonymous bin. That must be enough evidence to show that it was me, right?

Thanks in advance for your help!
-Ridder Janssen, also known as applepie, also known as jeannearc

**Comment by remy** [comment]
By "stole" you mean the user clicked on the "clone" menu item? Which is a feature of jsbin, allowing users to clone each other's work to build upon and learn. 

So you're asking me to delete a bin that has cloned and learnt from your bin?

If you know the creator (that you refer to as "she") why not ask them to delete the bin?

**Comment by RidderJanssen** [comment]
Well, she did not exactly 'learn' from it: she copied the code without making any changes to it. (She did make a tiny little changes: she changed one almost irrelevant sentence: my final message to the people of that website).

I understand that people should be able to learn from the code of other people. However, I do not call this 'learning'. I suspect that she was not satisfied with my final message, and therefore deciding to make a clone, so that people from the site won't see my message. (The message is not discriminating, etc. in any way).

If it happens to be the case that you won't be able to do anything about it, I surely will try to contact her to delete the bin. But, as I said, I can't get along with her very well, so I doubt that she will actually remove it.

Thanks in advance!
-Me

**Comment by remy** [comment]
If I were to remove the clone, what is stopping **anyone** from cloning your bin and filing this issue again? Anyone can view source and paste. I can view source on _this_ page and paste...

I'm not sure deleting the bin, particularly as you know the owner, would solve anything...
