### ISSUE TITLE
VAT query

### ISSUE THREAD

**Issue by jonathanlu** [jsbin/jsbin#2536]
Hi, 

We are currently being charged VAT on our invoices but are a VAT registered business. Our VAT number is 111 2777 45. If you could please add this to our billing account and refund the VAT paid on the past three invoices would be much appreciated. 

Best, 
Lizzy

**Comment by remy** [comment]
This is strange, it shouldn't have invoiced you the VAT. 

I'll get this refunded and corrected as quickly as I can. Thanks for letting me know

**Comment by remy** [comment]
To add: I'll also comment here when I've completed the refund.

**Comment by remy** [comment]
Ah, no, sorry, I jumped the gun.

Your business is registered in the UK (or at least, that's what you selected when you upgrade). If that's correct, UK business are charged VAT and you claim your VAT back using the normal VAT reporting process.
