### ISSUE TITLE
Editor preview messes with markup of <head> itself; Output view doesn't

### ISSUE THREAD

**Issue by cvrebert** [jsbin/jsbin#2537]
If you open http://jsbin.com/kufika/edit?html,js,output , the console logs 7 items because the custom `<head name="aa">` from the bin source got lost, whereas on http://output.jsbin.com/kufika the console logs 8 items because the head tag got preserved. This inconsistency is annoying, particularly for a debugging tool like JS Bin.

**Comment by remy** [comment]
My browser logged 8...

<img width="955" alt="screen shot 2015-09-03 at 11 41 24" src="https://cloud.githubusercontent.com/assets/13700/9656511/bcf92222-5230-11e5-8f6f-3bd3c3560bab.png">

I assume then that this is a browser inconsistency which we might be able to work around.

---

Oh, but now I see in the native browser console it logs 7 initially and then 8 when I click run.

I'm afraid this is the effect of running inside of an iframe dynamically. There's a lot of weirdness in building a dynamic iframe and running code, most of which are subtle and rarely bumped into, but they do exist...

Some context: https://www.youtube.com/watch?v=heyoi0JURkE
