### ISSUE TITLE
add p5.js to libraries

### ISSUE THREAD

**Issue by freder** [jsbin/jsbin#2538]
hi,

I saw there is [processing.js](http://processingjs.org/) in the list of libraries, but not [p5.js](http://p5js.org/) (which is another, newer port of processing to the web). — would be a nice addition.

thanks! 👍

**Comment by paked** [comment]
:+1:

**Comment by remy** [comment]
Libraries are handled through PRs. Closing this, I'll welcome and merge a PR to get the library in the list.
