### ISSUE TITLE
install won't work with node > 0.12

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/jsbin#2539]
Here's a pastebin of what followed after I ran `npm install -g jsbin` in git bash on Windows 8.1: http://pastebin.com/mCF93qrD

**Comment by remy** [comment]
Node 0.12 isn't supported.

**Comment by harriha** [comment]
Ran into the same issue. FWIW, tried updating the sqlite3 dependency to 3.x.x, after which installation worked fine on the same Windows setup @Daniel-Hug described. No idea (yet) whether something broke or not in the actual app, but at least based on a quick look things look fine. There might be a valid reason why sqlite3 version is `~2.2.0`, thus I assume something related to local data storage isn't working fully on this 3.x.x version.

**Comment by dlaflamme** [comment]
I also got this working by updating the sqlite dependency to 3.x.x but was not able to install jsbin locally. I had to run "grunt build" in the git checkout and run from there.

**Comment by remy** [comment]
Sorry, meant to close this. Only node 0.10 is supported atm. There's a massive update to express that needs working into jsbin. Happy to take a PR, I've had a shot a couple of times, but I'm not familiar with the migration path.

**Comment by AppShipIt** [comment]
[This](https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x) the one you're referring to? Debating taking a stab tomorrow rather than downgrade. Do you remember any particular pain points?

**Comment by remy** [comment]
I don't, no. If it was going to be upgraded, jump past 0.12 and head straight for node 4 LTS land. Problem is: the deps are very much in need of updating, express in particular. I do have some time sectioned off in the near future to upgrade the deps (which _might_ get it working on node 4), but I can't commit any dates atm.

**Comment by AppShipIt** [comment]
I'm running `5.6.0` 😉 I'll PR on an upgrade branch if its on your roadmap anyway. I just don't want to diverge significantly before/after adding another feature.
