### ISSUE TITLE
Generators seem to not be working

### ISSUE THREAD

**Issue by togakangaroo** [jsbin/jsbin#2541]
This is in Chrome 45 which fully supports generators. [This jsbin seems to not work](http://jsbin.com/decovo/6/edit?js,console,output). 

A `while(true)` seems to break even though it has a `yield in it`

**Comment by remy** [comment]
Tried with //noprotect?

**Comment by togakangaroo** [comment]
That *does* work by the way. Might be a good idea to have that be a checkbox under options or mention it somewhere on the front page (in errors?)

**Comment by sukima** [comment]
Also when using ES6/Babel you need to add the poly fill to the HTML:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.25/browser-polyfill.min.js"></script>
```

And to stop the linting errors add this to the JavaScript:

```javascript
/*jshint esnext: true */

Code goes here

//noprotect
```
