### ISSUE TITLE
Problem embedding HTML5 video player

### ISSUE THREAD

**Issue by rcrooks** [jsbin/jsbin#2542]
I'm having an intermittent problem with embedding a Brightcove Video Player (based on video.js). Sometimes works fine, sometimes not, as in https://jsbin.com/jakusi/12/edit?html,css,output

The only error I'm seeing in the console (repeatedly) is this rather odd one: Blocked a frame with origin "https://null.jsbin.com" from accessing a frame with origin "https://jsbin.com". Protocols, domains, and ports must match.
(anonymous function)onloadwff.js:358:353

**Comment by remy** [comment]
https is blocking the content from loading.

You can switch to http and it should (I think) load the player. Or, load the player over https to keep the entire connection secure.
