### ISSUE TITLE
Beautify code not working?

### ISSUE THREAD

**Issue by JWo1F** [jsbin/jsbin#2544]
Hi all! When I press ctrl+shift+L I see "Uncaught TypeError: b is not a function"

**Comment by tyler-canton** [comment]
So 15+ days and still not answer on this. Guys I'm getting the same error as well please advice...

**Comment by rfay** [comment]
One note: Everything is working in the browser using, so a fatal error in your *own* js can cause failures like this. So make sure to test all keybindings with a working bit of js, or none.

**Comment by kaihendry** [comment]
I get this issue too on Chrome 48.0.2564.10. 

http://s.natalian.org/2015-11-21/1448114876_1246x1058.png

Annoyingly it works fine in Firefox 42.

**Comment by remy** [comment]
"Guys"? Who are you referring to? If its me, its singular. Either way, I
didn't implement this (it was a community PR), so if it's broken my only
option is to remove support if no one wants to take a shot at fixing it.

Let me know what you think you'd like me to do.

**Comment by kaihendry** [comment]
Is there an un-minified jsbin I can use to debug with? Without setting up jsbin myself?

**Comment by remy** [comment]
Drop a cookie that has the name and value of "debug=1"
