### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by MJae** [jsbin/jsbin#2545]
Is it just me and browser or is the console supposed to pop out everytime? If not, how do I disable it?
![screenshot - 20150915 - 132745](https://cloud.githubusercontent.com/assets/815568/9868613/a6898d84-5bad-11e5-896a-6be206efdfbb.png)

**Comment by remy** [comment]
Firebug lite is "user code" - ie code that exists inside your code, and nothing to do with jsbin.

So, the answer is "maybe, depends what you told it to do".
