### ISSUE TITLE
All stats lost!

### ISSUE THREAD

**Issue by Sawovsky** [jsbin/jsbin#2546]
So I played a little bit last night and absolutely all of a sudden I noticed that none of my decks have any stats, except two decks I played last night. All deck are there but HDT shows no stats for any of them, and glabal stats aren't showing all those games also, and I have like ~3k games registred with Herthstone Deck Tracker prior to this.
I didn't do anything in HDT unusually, simply turned it on to play Hearthstone as usual. I'm very sad if 6 months of stats are lost for good in a second just like that. I tried backups, it did't work...

**Comment by remy** [comment]
I'm sorry, I have absolutely no idea what you're referring to at all. JS Bin is a code development environment, and you're referring to a game and decks...

Wrong repo?

**Comment by Sawovsky** [comment]
Sorry, I wanted to post a specific issue here
https://github.com/Epix37/Hearthstone-Deck-Tracker , but apparently I did
it in a wrong place :)

2015-09-16 23:49 GMT+02:00 Remy Sharp <notifications@github.com>:
