### ISSUE TITLE
D3.js Library Not Loading on Bins Using Https

### ISSUE THREAD

**Issue by kevinfjbecker** [jsbin/jsbin#2549]
What:

After selecting the D3.js library from the libraries dropdown, d3 references in a bin's javascript throw "is not defined" errors.

Examples:

The d3.js source src="http://d3js.org/d3.v3.min.js" doesn't work with https pages.
Example: https://jsbin.com/zunapu/1/edit?html,output

Using an https cdn seems to work: src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"
Example: https://jsbin.com/zunapu/2/edit?html,output

Details:

Error reported in Chrome's console "Mixed Content: The page at 'https://output.jsbin.com/zunapu/1/' was loaded over HTTPS, but requested an insecure script 'http://d3js.org/d3.v3.min.js'. This request has been blocked; the content must be served over HTTPS."

The error shown in jsbin is "ReferenceError: d3 is not defined
    at zunapu.js:5
    at runner-3.34.3.min.js:1
    at runner-3.34.3.min.js:1
zunapu.js:5 Uncaught ReferenceError: d3 is not defined(anonymous function) @ zunapu.js:5(anonymous function) @ runner-3.34.3.min.js:1(anonymous function) @ runner-3.34.3.min.js:1"

See also issue #2486

**Comment by AverageMarcus** [comment]
d3.v3.min.js isn't server over https and Chrome is correctly blocking the mixed content. To get around this I simply replaced my script tag for D3 with...
`<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>`

**Comment by remy** [comment]
Someone should PR the `libraries.js` file and change the D3 entry to use https instead. @AverageMarcus you should use https instead of relative-less - better practise (and cheers for solving this).

**Comment by AverageMarcus** [comment]
@remy Yeah, I thought about that after I commented but didn't seem worth going back to edit for. I don't mind updating the `libraries.js` if you like.
