### ISSUE TITLE
Help search not working

### ISSUE THREAD

**Issue by juliankrispel** [jsbin/jsbin#2550]
I was working on my pr and noticed that the help search isn't working. It fires one api request before you interact with it and then goes silent. :(

![image](https://cloud.githubusercontent.com/assets/1188186/9953406/d0dc63f6-5de0-11e5-957d-691f760ee5ff.png)

**Comment by remy** [comment]
Is this a local issue or live? As it depends on another service being up
(the learn repo).

**Comment by juliankrispel** [comment]
Live, I didn't even see the input locally...
