### ISSUE TITLE
Different origin issue when using Web Worker

### ISSUE THREAD

**Issue by roman01la** [jsbin/jsbin#2551]
When loading ClojureScript processor, which uses web worker, worker installation fails.

<img width="560" alt="screen shot 2015-09-18 at 6 24 34 pm" src="https://cloud.githubusercontent.com/assets/1355501/9958281/889022ca-5e32-11e5-85b8-28793ca7075c.png">

Turned out Web Worker script should be served from same origin as the parent page. The error message on the screenshot above clearly tells that the worker should be on the same origin.

Is there a way to move the script to `jsbin.com`? Maybe there's another solution as well.

**Comment by roman01la** [comment]
@remy 👋 Is it possible to move the worker file to jsbin.com?

**Comment by remy** [comment]
Not really, jsbin.com only serves dynamic content.

**Comment by roman01la** [comment]
I understand. I'll try with an iframe and submit another PR.
