### ISSUE TITLE
jsbin embedding not working

### ISSUE THREAD

**Issue by fend-classroom** [jsbin/jsbin#2554]
I have a JS Bin free account and I want to embed a bin on my website. This MWE doesn't work neither when I open it on my Desktop using Google Chrome nor live, using a Github page. 

Here's the code:

```html
<!DOCTYPE html>
<html>
<head>
	<title>JS Bin</title>
	
</head>
<body>

	<a class="jsbin-embed" href="https://jsbin.com/cidehel/2/embed?html,css,output">JS Bin on jsbin.com</a>
	<script src="https://static.jsbin.com/js/embed.min.js?3.35.0"></script>
</body>
</html>
```
Here's how I generated the link for the embedding (I've tried the "snapshot" and the "latest" option, but both failed).

![JS Bin Share](https://cloud.githubusercontent.com/assets/14221343/9977981/943f5744-5f13-11e5-9e71-7f7cfe762dde.png)

And this is the result I'm getting:

![Error](https://cloud.githubusercontent.com/assets/14221343/9977984/072a82ec-5f14-11e5-99b9-e420fb044b52.png)

By the way, I've used the Live Example Code from this document and it worked perfectly: http://jsbin.com/help/how-can-i-embed-jsbin 

Please help! Thanks for your time :+1:

**Comment by remy** [comment]
Swap the https in the jsbin links to http and it'll embed.

**Comment by fend-classroom** [comment]
Thank you, Remy! :smile:

**Comment by murielg** [comment]
For anyone looking into this issue in 2017, it appears that swapping http with https will not suffice unfortunately:

https://gyazo.com/1d0fe3f27a4ff223b0cf29503ded468a
