### ISSUE TITLE
Snapshots of first bin are not shown

### ISSUE THREAD

**Issue by richardj** [jsbin/jsbin#2556]
When working on your first bin (as a registered and logged in user) and making a few snapshots of what you are working on, those are not shown when looking at the 'my bins' page. Only after creating a new bin the previous bin is shown with its snapshots.

![screenshot 2015-09-20 12 41 43](https://cloud.githubusercontent.com/assets/474024/9980344/fd42551c-5f94-11e5-8a8e-e88880532d80.png)

This is after the creation of the second bin, i don't have a screenshot of the first bin during the snapshots, but that was an empty 'my bins' screen, so not really useful here.

**Comment by remy** [comment]
This is "very first" bin for a user, right? I know why this is, it's kind of an edge case (because the history is only loaded once for the user, and the bin doesn't exist when it loads for the first time).

**Comment by richardj** [comment]
Indeed it is, and I was aware of it being an edge case and in a way making sense. But maybe trigger the history when snapshots are created?
