### ISSUE TITLE
ES6/Babel generators not working

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2558]
A simple generators example:
https://jsbin.com/moleda/edit?html,js,output

error:  
runner-3.35.0.min.js:1 error SyntaxError: Unexpected token ;
    at https://static.jsbin.com/js/prod/runner-3.35.0.min.js:1:13603
    at https://static.jsbin.com/js/prod/runner-3.35.0.min.js:1:10524
moleda.js:7 Uncaught SyntaxError: Unexpected token ;(anonymous function) @ runner-3.35.0.min.js:1(anonymous function) @ runner-3.35.0.min.js:1

in full screen, the error is:  
moleda:21 Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by confiks** [comment]
As you can read in the [Babel documentation](https://babeljs.io/docs/learn-es2015/#generators), you must include the [Babel polyfill](https://babeljs.io/docs/usage/polyfill/) to use generators. You can include it via a script tag, for example from cdnjs:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.25/browser-polyfill.min.js"></script>

**Comment by cauburtin** [comment]
Ok thanks, I edited https://jsbin.com/moleda/edit?html,js,output it doesn't work in the output window, but it works on https://output.jsbin.com/moleda

**Comment by avanslaars** [comment]
@cauburtin Have you had any luck getting this to work in the editor? I'm running into this same issue and can't seem to get past the generic error message

**Comment by cef62** [comment]
@avanslaars @cauburtin if you haven't found a solution a workaround is pointed out in #2541, just append `// noprotect` to your javascript code. For me work in chrome canary and also using babel polyfill as pointed out by @confiks
