### ISSUE TITLE
Add ESLint to JSBin

### ISSUE THREAD

**Issue by confiks** [jsbin/jsbin#2559]
I want to add ESLint to JSBin when it's using the Babel transpiler. Currently the hinter/linter messages are very broken when using the 'ES6 / Babel' option. I'm using ESLint with Atom, and it really saves me so much time. I expect it will truly help students not to get bogged down by syntax issues too.

I'm creating this ticket mainly to track [my fork](https://github.com/confiks/jsbin)'s progress. To get familiar with your codebase I'm going to refactor addons.js a bit, hopefully I can fix some other bugs too.
- [ ] See if I can use [angelozerr/codemirror-lint-eslint](https://github.com/angelozerr/codemirror-lint-eslint)
- [ ] Fix editor-settings.js's call to reloadAddons, so it actually reloads without a refresh

**Comment by JordanAdams** [comment]
Is there any update on this?

**Comment by JasonSooter** [comment]
Any update on this?
