### ISSUE TITLE
Real time collaborating

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#256]
So, @guille, how do we make this happen :)

**Comment by remy** [comment]
¯\_(ツ)_/¯

**Comment by luisincrespo** [comment]
Hey @remy ... Why did you close this issue?. Is it already implemented?. I know that someone can see me coding live in a JSBin, but can multiple users edit live at the same time?.

Great work with this platform by the way!. Best.

**Comment by remy** [comment]
Because it's 3 years old and its not making any progress.

**Comment by luisincrespo** [comment]
OK but is the feature (real-time collaboration for 2 or more people) implemented or not?.

**Comment by johnmellor** [comment]
These days, there are off the shelf APIs for adding collaborative text editing to webapps, like https://developers.google.com/google-apps/realtime/overview, which handle propagation of changes, conflict resolution, etc for you - I wonder if that would make it easier to implement this?

**Comment by remy** [comment]
This feature is not implemented and I've not had anyone in 3 years send a
PR.

We've tried a few times to no avail.

I also backed the prose mirror project with the aim to add the live
collaboration, but I see no time to do this, let alone even check the code
to see what's required.

**Comment by nitinsurana** [comment]
Can't see live collaboration on jsbin.com, so probably it's not implemented yet.
`OT.js` - operational transform can be used to provide live-collaboration. Firepad uses it for live-collaboration.
