### ISSUE TITLE
Snapshots of current bin no longer possible.

### ISSUE THREAD

**Issue by arttronics** [jsbin/jsbin#2564]
I've deleted old snapshots for my jsBin at https://jsbin.com/megeko/ and am no longer to perform snapshots. This jsBin was previously archived, then un-archived as well.

jsBin actually can show the last snapshot URL of https://jsbin.com/megeko/17/edit?html,css,output but again, it creates a new jsBin upon any code changes.

Is there a way to continue using URL with /megeko/ with either /1/ or /18/ as a new snapshot?

Screenshot showing baseline /megeko/ and /17:

![screenshot](https://cloud.githubusercontent.com/assets/960123/10125522/a73b86dc-652c-11e5-8182-0ec7454b4eba.png)

**Comment by remy** [comment]
Did you delete the snapshot 1?

**Comment by arttronics** [comment]
Yes, all previous snapshots were deleted.

**Comment by remy** [comment]
I suspected this. The logic works by checking who owned the first bin, and
then allowing them write perms on subsequent bins - which is why it's
cloning for you. I'm not 100% sure where the change is, but I think if the
delete flag is ignored for this case, it would fix it.

#help-and-pr-wanted

**Comment by arttronics** [comment]
I am the owner of this first bin.
I'm not understand what you mean by the delete flag is ignored.

Since I have access to the /megeko/ as well as /17/ edit version, is there a way to snapshot from either of those points, with the same baseline URL?

**Comment by arttronics** [comment]
Bump.
Is there a solution for this bug?

**Comment by remy** [comment]
The only workaround is to start another bin base url (i.e. it's a bug that needs a software patch).

**Comment by arttronics** [comment]
Thanks for your help Remy. I'll do just that.
