### ISSUE TITLE
Allow disable redirect to /embed when in iframe.

### ISSUE THREAD

**Issue by rchrd2** [jsbin/jsbin#2567]
In some cases it makes sense to run jsbin in a frame. However, the default behavior seems to be to redirect to /embed when in a frame. Is there a way to disable this? What line of code does this redirect?

**Comment by remy** [comment]
No, its part of the security model jsbin uses.

**Comment by rchrd2** [comment]
Thanks for the reply. I'm attempting to package JsBin so that it can easily be installed with Sandstorm (https://sandstorm.io/). The thing is, all sandstorm apps run within an iframe. Could you please tell me how I could disable the redirect for the sandstorm-specific fork i'm working on? Please please :)

**Comment by rchrd2** [comment]
Never mind. I think I found it. It's in the index.html. I couldn't find it, because I was searching all the js files. I believe commenting this out for Sandstorm is okay, as the sandstorm instances are meant to be run on private machines with access control.
