### ISSUE TITLE
Question: Relative URLs?

### ISSUE THREAD

**Issue by SabrinaCaldwell** [jsbin/jsbin#2568]
Hi, I'm a newbie to JSBin. I'm trialling using it to build a simple website to integrate with an online course, and so far so good except that I just came to a sticking point.  I can't see any way to demonstrate relative URLs in JSBin because the bin structure doesn't seem to incorporate the notion of a directory tree.  

So for example I have in my html code an absolute URL <a href="http://take-a-screenshot.org">http://take-a-screenshot.org</a> and this works just fine.  But I also want to include a relative URL such as <a href="/subdiraboutcopyright/copyright.html">copyright</a> to go down one level or  
<a href="../higherleveldirectoryaboutphotos/photos.html">photos</a> to go up and sideways in the tree
but I can't work out if it is even possible to have a tree as such in the JSBin environment. 

I tried to find something about this in the blog and wiki but haven't yet.  I would appreciate advice whether this is something that is not possible, or if it is possible, how to do it.

**Comment by remy** [comment]
Hi @SabrinaCaldwell,

The short answer is - no, there's no way to do relative urls in jsbin (or not in the way you've described).

You *could* make one bin, and then link them relatively together (using `../myotherbin/3` in a url in `/myfirstbin/1` for instance) - but I don't think this is what you're after.

**Comment by SabrinaCaldwell** [comment]
Thanks very much for your answer.  Much appreciated.  Yes, as you say, I'm after something a bit different; might still use jsbin but differently.


Cheers,


Sabrina


______________________________________

Dr Sabrina Caldwell
N319, CSIT Bldg 108
Research School of Computer Science
The Australian National University
Acton ACT 0200
Email: sabrina.caldwell@anu.edu.au
Phone: +612 6125 9663
weblog: http://www.thephotographicalist.wordpress.com/



________________________________
