### ISSUE TITLE
How to deal with blocked http ressources?

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2571]
I'm on Chrome 45, since jsbin is in https once you're logged in, any http script or css link is blocked

**Comment by remy** [comment]
Either use https resources or go to preferences and uncheck "use SSL by default".

**Comment by cauburtin** [comment]
thanks

**Comment by cauburtin** [comment]
https://jsbin.com/texatu/edit?html,css,js,output

![image](https://cloud.githubusercontent.com/assets/3134574/10345245/913bcd98-6d28-11e5-88a3-fcc9968eaf1e.png)

![image](https://cloud.githubusercontent.com/assets/3134574/10345261/a9c0b2de-6d28-11e5-89b7-f9cd2792ea17.png)
