### ISSUE TITLE
bin's current version number

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2575]
Currently it's a bit hard to know on which version number you are, I sometimes save a snapshot, and have no idea which version it was, I find it by testing jbin.com/hash/someNumber until it doesn't load

Also another unrelated suggestion, a shortcut for toggling comments would be great

**Comment by remy** [comment]
If you're on latest, there's no version number. If you're not, it'll appear
in the URL.

Re: comments, cmd+/ (IIRC)

**Comment by cauburtin** [comment]
yes, but when you're working on latest, and want to give a link to someone on a version that won't change you 'save snapshot' and then you need that version number to give the link to , and it's hard to find it out

nvm... just remembered that share button, stupid me
