### ISSUE TITLE
Imported Gist JS null => sadfsdfsafsdsdsadf

### ISSUE THREAD

**Issue by maxkfranz** [jsbin/jsbin#2576]
If a Gist is imported and the Gist only contains a HTML file (with embedded JS in it), the JavaScript pane contains `sadfsdfsafsdsdsadf` instead of being empty.

**Comment by remy** [comment]
Do you have an example of the gist url I can test with?

**Comment by remy** [comment]
I couldn't replicated this by the way.

**Comment by maxkfranz** [comment]
Sure, here's one:

JSBin : http://jsbin.com/gist/f70c9e45c43f40f7dfe1?js,output
Gist : https://gist.github.com/maxkfranz/f70c9e45c43f40f7dfe1

**Comment by remy** [comment]
Got it - sorry, I tried *with* JS rather than *not* with JS.

I see the issue now.

**Comment by Mottie** [comment]
Any update? I am still seeing this issue...

And I was using the link from the example page: https://jsbin.com/help/import-gists

**Comment by remy** [comment]
No, there's not. There's a PR that was open (rather than "any update"),
which I need to find time to test.

**Comment by digitaccel** [comment]
I am getting this same issue. Even when there is original Javascript. Any updates on this?

**Comment by remy** [comment]
No this particular issue no. It's all fixed in the refactor going live in the coming months.

**Comment by digitaccel** [comment]
Ok thank you.
