### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by dodger487** [jsbin/jsbin#2577]
I volunteer with ScriptEd (http://scripted.org/). We teach JS in low income schools. JSBin is an invaluable tool for us, because a lot of our students don't own computers, so JSbin works on many browsers on many different types of machines that the schools can occasionally provide. I mention this because it's part of our use case-- users with little familiarity with computers trying to save their projects. JSBin is great because it's a very low overhead "IDE" and it works!

We're trying to have our students save their projects by exporting to Gist. However, recently, even when students are logged in, the gist shows up as anonymous. The students then have to fork the project. Every extra step is a stumbling block for our learners, so it would be great if we could export to gist to the logged in gist account, and not have it save as anonymous.

**Comment by dskecse** [comment]
No need to create duplicated issues. Look at https://github.com/jsbin/jsbin/issues/2459.
