### ISSUE TITLE
http/https (#2571 follow-up)

### ISSUE THREAD

**Issue by cauburtin** [jsbin/jsbin#2579]
I have the option "use SSL" unchecked, I don't know if this has an effect on it but everytime I open a saved bin, a new bin, a forked bin, anything, it comes with the https scheme, I often have to pass in http to have htttp script or call http services.

I'd prefer to be in http on those actions and all the time, since I don't really mind of privacy for this stuff, is it possible? sorry for opening a new issue and last point, I really like jsbin

**Comment by remy** [comment]
It could be a caching issue in your browser...maybe. I've seen this kind of thing before.

If you try a different browser altogether, and sign in, stay away from https, what happens?

**Comment by cauburtin** [comment]
right, it's staying in http now
