### ISSUE TITLE
XMLHTTPrequest stopped working

### ISSUE THREAD

**Issue by ProfBlack** [jsbin/jsbin#2582]
I was demonstrating XMLHttpRequest to a class, and right in the middle of the class, it stopped working. None of the event handlers fire, it just goes out and never comes back. Even if I pass it a bad URL, it doesn't even error out. I've tried different browsers, I've tried it not logged in, and it just doesn't work. 

If I create a new bin while not logged in, the code runs fine. If I create a new bin while logged in and copy the code, the code doesn't run.

The misbehaving bin: https://jsbin.com/hutuwu/8/edit?html,js,output

**Comment by ProfBlack** [comment]
It is working once again. So perhaps I hit some DoS prevention threshold?

**Comment by remy** [comment]
Possibly, though I don't understand why you were able to open new bins...

**Comment by ProfBlack** [comment]
It is indeed mysterious.  In any event, it was definitely a show stopper...

**Comment by ProfBlack** [comment]
I know you closed this, but it happened again. My demo was working just fine fetching my sample json file right up until the moment when my students all loaded the codecast, at which point it stopped again.

**Comment by remy** [comment]
If you're in a class its possible you're hitting the ip based throttling.
Either post your ip here or send a DM to @js_bin on twitter and I'll white
list it for you.
