### ISSUE TITLE
Starting template sometimes won't save.

### ISSUE THREAD

**Issue by ghost** [jsbin/jsbin#2584]
I like to make my own starting templates, with things that I'll use every time, such as random number generators or simple functions that saves a lot of typing. Unfortunately, sometimes when I open a new bin the starting template isn't there. It isn't that much of an inconvenience because I save a template on Google Docs to copy and paste, but it's still very annoying.

**Comment by remy** [comment]
Are you using the same browser each time? It's associated with localStorage, and not your account.

**Comment by jasoncheng938** [comment]
I'm always using chrome, but if I refresh the page on a fresh bin the code will revert to the original template.
