### ISSUE TITLE
JavaScript alert() doesn't open a dialog

### ISSUE THREAD

**Issue by mkfreeman** [jsbin/jsbin#2586]
The JavaScript alert() function doesn't open a dialog window.  I'm using Google Chrome (Version 46.0.2490.71 (64-bit)) on Mac OS-X (Yosemite).  Here is a test bin (http://jsbin.com/xeyiru/edit?html,js,console,output), and attached is a screencast.  Thanks.
![jsbin-demo](https://cloud.githubusercontent.com/assets/1373882/10560967/224327ce-74d0-11e5-819e-d38fcbaeed20.gif)

**Comment by remy** [comment]
Can you repeat but in an incognito window? (It allows me to rule out any
extensions interfering).

**Comment by mkfreeman** [comment]
Yea, I repeated it in an incognitio window and got the same result as in the gif above.

**Comment by remy** [comment]
Can you open devtools, and run `jsbin.settings.debug = true` then re-run
and post the contents of the output panel?

I can't replicate this at all on my side which is why I'm debugging through
you :)

**Comment by remy** [comment]
Just also double checking, do you see *any* issues on the native browser console?

**Comment by mkfreeman** [comment]
See attached screenshot -- there is an error in the browser console when you load the page.  The content in the Output tab only appears after re-rerunning with jsbin.settings.debug = true;
<img width="1440" alt="screen shot 2015-10-18 at 8 14 51 am" src="https://cloud.githubusercontent.com/assets/1373882/10564667/ffc32a9a-7570-11e5-9317-813b470caf8c.png">

**Comment by remy** [comment]
Oh hell. I've worked it out. The latest update in Chrome is blocking the alert box from the iframe. Terrific.

Paging @mikewest - did you mention something like this a month ago?...
