### ISSUE TITLE
Getting ReferenceError: ReactDOM is not defined when using latest version of ReactJS API

### ISSUE THREAD

**Issue by veeracs** [jsbin/jsbin#2587]
I'm referring to the latest FB React version, //fb.me/react-0.14.0.js, chose JSX (React), getting error,

"ReferenceError: ReactDOM is not defined
    at bufakesole.js:7:1"

Here's my simple markup,

````
var HelloMessage = React.createClass({
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
});

ReactDOM.render(<HelloMessage name="John" />, document.body);

````

**Comment by remy** [comment]
I'm afraid that means nothing to me. I'm not familiar with React, so don't know what that means. Maybe find someone that can translate? Sounds like you're using a variable that doesn't exist in the react-0.14.0.js?

**Comment by veeracs** [comment]
@remy Yes, ReactDOM should be available in the latest version of ReactJS 0.14.0. React.render works, but not ReactDOM.render. Not sure why JSBIN is complaining ReactDOM is not available, will research more on this. Thanks!

**Comment by veeracs** [comment]
@remy I see the problem, looks like I have to do a commonjs require, require('react-dom'); before I use the ReactDOM.render. I can close the ticket, for now, I don't know how to use latest version of ReactJS on jsbin.

**Comment by chetankhargone** [comment]
@veeracs , I got same error. But this is how I fixed. Hope it helps to you.
` <script src="https://fb.me/react-15.0.1.js"></script>
   <script src="https://fb.me/react-dom-15.0.1.js"></script>
   <script type="text/javascript" src="~/Scripts/myreactfile.jsx"></script>
`

Adding the react-dom-*.js, has fixed the issue.
