### ISSUE TITLE
Build problems on El Capitan

### ISSUE THREAD

**Issue by stonemirror** [jsbin/jsbin#2591]
I'm using an up-to-date, Brew-installed version of node (v4.2.1) and npm (v2.14.7) on a OS X system running El Capitan (v10.11). Having cloned the repository, I'm attempting to run the command "npm install --dev", and running into several pages of warnings about unmet dependencies, culminating in a fatal error:

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package karma@0.10.10 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.10 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mcfate/Projects/jsbin/npm-debug.log

Any ideas?

**Comment by remy** [comment]
Node 4 isn't supported. Node 0.10 is.
