### ISSUE TITLE
Line Number coloring

### ISSUE THREAD

**Issue by ndrone** [jsbin/jsbin#2594]
When enabling line numbers on any dark themes. The line numbers are difficult to read. I would be nice if they switch to a white in color.

**Comment by remy** [comment]
Its CSS, I'd gladly take a PR to fix it.

Thanks.

**Comment by ohiocowboy** [comment]
Sounds good. With all the branches, do you want me to open a PR against master? Or do you have another branch in mind?

Thanks,

**Comment by remy** [comment]
Master is good
