### ISSUE TITLE
Add library only works if run once with HTML tab open

### ISSUE THREAD

**Issue by TrueWill** [jsbin/jsbin#2595]
With a ?js,console URL, add a library. Attempt to call it in JavaScript. The call will fail.

Now open the HTML tab and run the JavaScript again. The call will succeed.

After that you can close the HTML tab and just leave the JavaScript and Console tabs open.

(Tested in Chrome on Mac)

**Comment by remy** [comment]
I don't follow at all. Can you add a screencast of what you mean.

**Comment by TrueWill** [comment]
![jsbinaddlib](https://cloud.githubusercontent.com/assets/1709726/10639245/d4706d74-77d4-11e5-8bd9-f78425b01de1.gif)
