### ISSUE TITLE
I need a Receipt

### ISSUE THREAD

**Issue by Databoom** [jsbin/jsbin#2599]
Colleagues, 
I have the bank record 
07.07.2015	09.07.2015	Card ***7159 JS BIN JS BIN PRO +4412735577	12.99 GBP	
I paid it in July for Pro account. I can't see the recieipt that I need to supply to my accountant. 
Probably that's because my account not in Pro status now. 
Could you please send me the receipt on my Email vc@databoom.space
?

**Comment by remy** [comment]
That should have been sent now directly from Stripe.
