### ISSUE TITLE
The script doesn't run until JS tab is open

### ISSUE THREAD

**Issue by gaearon** [jsbin/jsbin#2602]
I can't reliably reproduce this, but I have this issue every once in a while.
Sorry for low quality gif:

![](https://s3.amazonaws.com/f.cl.ly/items/3C391W1Q1035372R3V3u/Screen%20Recording%202015-10-28%20at%2015.57.gif)
1. Go to fiddle by link where JS tab is hidden
2. (In this case, I have Babel enabled.)
3. Nothing happens! The script doesn't run.
4. Even pressing “Run with JS” doesn't run it
5. Now open the “ES6 / Babel” tab
6. It runs!

I don't think it's intended behavior but let me know if I'm missing something.

**Comment by remy** [comment]
Could be that the processor hasn't loaded (or run) until the panel is rendered?

**Comment by gaearon** [comment]
Yes, that's the feeling I was getting. As you see the tab title changes to “Babel”. Race condition?

**Comment by remy** [comment]
Can you capture with the browser console open? It'll tell you if the processor isn't ready, or throwing there.

**Comment by gaearon** [comment]
It does say that processor isn't ready when it fails:

![](https://s3.amazonaws.com/f.cl.ly/items/1t0I1w3b1n32011y3d2g/Screen%20Recording%202015-10-28%20at%2016.16.gif)

However even when I can't repro the issue and it works fine, it still says so—it just manages to run the code after processor loads without me selecting the tab.

**Comment by remy** [comment]
I take it this is happening on and off then - I've tried a couple of times myself and it's not happening, but I'm guessing it's because in some cases, the processor (possibly) happens after the code tried to run...

**Comment by gaearon** [comment]
Right now I can consistently reproduce this with https://jsbin.com/tipevi/edit?html,console,output when I'm logged into the account. If I'm not logged in, the issue seems to go away.
