### ISSUE TITLE
Top-level 'use strict' does not appear to work

### ISSUE THREAD

**Issue by gaearon** [jsbin/jsbin#2603]
https://jsbin.com/kuhoza/edit?html,js,console

``` js
'use strict';

var x = {};
Object.freeze(x);
x.a = 42; // should throw in strict mode

var isStrict = (function() { return !this; })();
console.log(isStrict);
```

Expected: it throws.
Actual: it prints `false` because `'use strict';` seems to have no effect.

I understand I could wrap it all into an IIFE but I'd rather not do it.
Any way to make the top-level `use strict` work?

Thanks!

**Comment by skolwin-CA** [comment]
This is still an issue as far as I can see? @gaearon should we reopen?

**Comment by ashwyn222** [comment]
This is still an issue as far as I can also see. Can we reopen?
