### ISSUE TITLE
Javascript code sometimes impossible to select

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2607]
it's not easy to reproduce, sometimes I just can't select any code in the js tab, I think I already had this problem a few times but currently it's happening with ES6/Babel mode activated, maybe that's why?

**Comment by saske505** [comment]
Hi @cauburtin, I found this problem happens right after I sometimes by accident switch between INS and OVR while working in JSBIN, could you maybe let me know if this is the case with you?  Cause I would love to get to the bottom of this one on my local server.
