### ISSUE TITLE
ES6/Babel not working with react

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2608]
http://jsbin.com/cimabi/edit?html,js,output

```
error ReferenceError: exports is not defined
     at cimabi.js:3:23
 cimabi.js:3 Uncaught ReferenceError: exports is not defined
```

**Comment by cauburtin** [comment]
well I'm new to ES6/7, it seems `export` keyword is not valid there? I got this code from http://facebook.github.io/react/docs/reusable-components.html#es6-classes

**Comment by kirjs** [comment]
This is correct, browser doesn't know how to handle exports. 
Just removing experts should work: http://jsbin.com/niyivi/edit?html,js,output
