### ISSUE TITLE
JavaScript Basic : Exercise-3 with Solution

### ISSUE THREAD

**Issue by Maheshsatam** [jsbin/jsbin#2609]
My Code is 
<html>
<head></head>
<body>
<script>
var today = new Date();
var day = today.getDay();
var month = today.getMonth()+1;
var year = today.getFullYear();
if ( day<10 )
{
	day=0+day;
	
}
if ( month<10)
{
	month='0'+month;
}
today = day + ' - ' + month + ' - ' + year;
document.write(today);
</script>
</body>
</html>
 and the diplay i am geting is one day behind that is 4-11-2015 but actuly it is 5th nov 2015

**Comment by remy** [comment]
This isnt a jsbin issue, so I'll close this. You want to ask something like the stackoverflow community. Good luck.

**Comment by Maheshsatam** [comment]
Thank Remy,

i Shall ask to Stackoflow..
