### ISSUE TITLE
Website is Not Completely HTTPS, Can't fully log in

### ISSUE THREAD

**Issue by bones192nd** [jsbin/jsbin#2613]
Dear Jsbin Admins

I have issues logging into your Jsbin website. When logging in to jsbin via Github, the website goes from https to http, and then my company's internet filter blocks the webpage. I can access Github and then log in through there. But that is because the website does not leave a secure connect. 

I can access jsbin without logging in but I would like to save my work into my account. 

https://i.imgur.com/mhS3xcD.jpg

![image](https://cloud.githubusercontent.com/assets/10578405/10998973/38dd378a-8467-11e5-869a-7379fe96a956.png)

**Comment by remy** [comment]
No, it *is* secure, but your proxy has it under a blacklist, as it states in your screenshot. You'll have to get it whitelisted to get a completed sign in. Sorry I can't help with that.
