### ISSUE TITLE
Store template(s) with user account

### ISSUE THREAD

**Issue by viveleroi** [jsbin/jsbin#2614]
I'm assuming that default templates are stored in local storage because anytime I restart my browser (I clear data on close) my default template has been lost.

I would prefer to have it saved with my user account, so that when I login it's always there.

**Comment by samhagman** [comment]
+1

**Comment by remy** [comment]
That's not the reason. It's because templates existed before user accounts.

That's all.

Happy to take a PR that adds this functionality and I can help direct the
required UI changes.
