### ISSUE TITLE
Denuncia de dados espostos

### ISSUE THREAD

**Issue by vinigamesfz** [jsbin/jsbin#2621]
https://jsbin.com/gefemayoqi/1/edit?html,output
meus dados pessoais foram espostos podem retiralos ? porfavor
oque ele diz ali n eu n fiz nd ele esta se confundindo e eu fui espostos
skype buzzcufx9

**Comment by remy** [comment]
Sorry, this is an english speaking repo, so I can't help in whatever language that is. I'll close the issue, but if anyone else wants to take a run at answer...?

**Comment by vinigamesfz** [comment]
A man took all my information no reason and put them on the internet can chop them off porfavor? https://jsbin.com/gefemayoqiHe did it for no reason and it's all right I'm scared

By google translate
________________________________
De: Remy Sharp<mailto:notifications@github.com>
Enviada em: ‎12/‎11/‎2015 06:11
Para: jsbin/jsbin<mailto:jsbin@noreply.github.com>
Cc: vinigamesfz<mailto:viniciusfz@outlook.com.br>
Assunto: Re: [jsbin] Denuncia de dados espostos (#2621)

Sorry, this is an english speaking repo, so I can't help in whatever language that is. I'll close the issue, but if anyone else wants to take a run at answer...?

---

**Comment by vinigamesfz** [comment]
A man took all my information no reason and put them on the internet can chop them off porfavor? https://jsbin.com/gefemayoqiHe did it for no reason and it's all right I'm scared

By google translate

Enviado pelo meu Windows Phone
________________________________
De: Remy Sharp<mailto:notifications@github.com>
Enviada em: ‎12/‎11/‎2015 06:11
Para: jsbin/jsbin<mailto:jsbin@noreply.github.com>
Cc: vinigamesfz<mailto:viniciusfz@outlook.com.br>
Assunto: Re: [jsbin] Denuncia de dados espostos (#2621)

Closed #2621.

---
Reply to this email directly or view it on GitHub:
https://github.com/jsbin/jsbin/issues/2621#event-462171031

**Comment by vinigamesfz** [comment]
Link this https://jsbin.com/gefemayoqi/1/edit?html,output


Enviado pelo meu Windows Phone
________________________________
De: Remy Sharp<mailto:notifications@github.com>
Enviada em: ‎12/‎11/‎2015 06:11
Para: jsbin/jsbin<mailto:jsbin@noreply.github.com>
Cc: vinigamesfz<mailto:viniciusfz@outlook.com.br>
Assunto: Re: [jsbin] Denuncia de dados espostos (#2621)

Sorry, this is an english speaking repo, so I can't help in whatever language that is. I'll close the issue, but if anyone else wants to take a run at answer...?

---

**Comment by remy** [comment]
Deleted. Thank you for translating.

**Comment by vinigamesfz** [comment]
Thanks

Enviado pelo meu Windows Phone
________________________________
De: Remy Sharp<mailto:notifications@github.com>
Enviada em: ‎14/‎11/‎2015 13:21
Para: jsbin/jsbin<mailto:jsbin@noreply.github.com>
Cc: vinigamesfz<mailto:viniciusfz@outlook.com.br>
Assunto: Re: [jsbin] Denuncia de dados espostos (#2621)

Deleted. Thank you for translating.

---
