### ISSUE TITLE
Not running saved on chrome

### ISSUE THREAD

**Issue by aliksend** [jsbin/jsbin#2622]
When I try to open saved in Chrome I get it in DevTools console

```
Uncaught SecurityError: Blocked a frame with origin "http://null.jsbin.com" from accessing a frame with origin "http://jsbin.com". Protocols, domains, and ports must match.
```

and nothing in `Output` window

**Comment by remy** [comment]
I can't replicate this (with the little info you've given). Can you add a screencast?

**Comment by aliksend** [comment]
Hmm, It is a problem, because I can't stable repeat it.
I can give you [a link](http://jsbin.com/qidosap/43/edit?html,js,output) that working good in private mode in chrome and sometimes working in normal mode for me. 
Now I opened the app and do not see anything in the output window. I push the `Run with JS` button and nothing happens. The same in Safari on my OS X. In private mode in Chrome all is working good.

**Comment by Ncage1974** [comment]
I'm having the same issue:
Uncaught SecurityError: Blocked a frame with origin "http://jsbin.com" from accessing a frame with origin "http://null.jsbin.com". Protocols, domains, and ports must match.b @ (index):2Object.defineProperties.contentWindow.get @ (index):2a.setup @ jsbin-3.35.9.min.js:18a.onload @ jsbin-3.35.9.min.js:18

Chrome Version 48.0.2564.116 (64-bit)
OSX El Capitan 10.11.3

If i run in incognito mode then its fine. 

Same in safari Version 9.0.3 (11601.4.4).

You request some screenshots so here you go:

<img width="1280" alt="screen shot 2016-03-04 at 7 48 03 pm" src="https://cloud.githubusercontent.com/assets/1213549/13544871/1eea9c76-e242-11e5-8797-ac3884391ce8.png">

<img width="1259" alt="screen shot 2016-03-04 at 7 49 23 pm" src="https://cloud.githubusercontent.com/assets/1213549/13544879/4224d102-e242-11e5-8e31-641da4a25ff4.png">

**Comment by remy** [comment]
My feeling here is that it must be an extension blocking the iframe. Do you have a common iframe across Firefox and chrome?
