### ISSUE TITLE
Please add riot.js to the Library list

### ISSUE THREAD

**Issue by aMarCruz** [jsbin/jsbin#2624]
http://riotjs.com/

https://cdnjs.cloudflare.com/ajax/libs/riot/2.3.1/riot+compiler.min.js

riot have 7,833 starts in github

**Comment by remy** [comment]
I don't maintain the changes to the libraries - it's done entirely through PRs.

**Comment by aMarCruz** [comment]
Thanks @remy , I just sent [the PR for riot](https://github.com/jsbin/jsbin/pull/2625).
