### ISSUE TITLE
False positive abuse detection

### ISSUE THREAD

**Issue by terribleplan** [jsbin/jsbin#2626]
We were trying to use JSbin for a class we were running on Monday (Nov 16), and many of our students reported seeing some sort of notification that we were abusing jsbin, and blocked from accessing it. We have about 100+ students in our class, so I could see how it could look like a (poorly done) DDoS attack when the instructor has them all follow the same link at the same time.

I can provide more info via email if someone is willing to contact me at kegan@launchcode.org

Thanks!

**Comment by remy** [comment]
If you email support@jsbin.com I can whitelist your IP address (as it's getting caught in the fail2ban ddos protection).
