### ISSUE TITLE
https://jsbin.com/hendry/last has different content to https://jsbin.com/hendry/last/edit

### ISSUE THREAD

**Issue by kaihendry** [jsbin/jsbin#2628]
Compare:

<img src=http://s.natalian.org/2015-11-21/1448114583_1918x1058.png alt="CORRECT: my last workings">

<img src=http://s.natalian.org/2015-11-21/1448114567_1918x1058.png alt="WRONG: some Java project?">

**Comment by abhisekp** [comment]
@kaihenry The url https://output.jsbin.com/hendry/last doesn't load now. Probably, a vestigial thing.
Now it is https://output.jsbin.com/hendry/latest

@remy this issue maybe closed :x:

**Comment by abhisekp** [comment]
Weird ... anyway the latest can be accessed from https://jsbin.com/hendry/latest
