### ISSUE TITLE
JavaScropt is not working at the moment

### ISSUE THREAD

**Issue by dotabjorn** [jsbin/jsbin#2629]
What ever i write in the JavaScript panel, comes up at the bottom of the Output panel wrapped in a try-clause.  Probably the code that will execute the JavaScript code.  The JavaScript code its self does not execute.

**Comment by remy** [comment]
Since you've not provided an example bin URL, I'm going to guess, and say that you probably don't have any html for the JS to render against. Stick a minimal tag in there and it'll work, otherwise all jsbin is doing (on purpose) is echoing out the JS.
