### ISSUE TITLE
A simple typo "$($)" locks up the entire bin and can't be recovered

### ISSUE THREAD

**Issue by eepMoody** [jsbin/jsbin#2632]
I was working on a bin today and accidentally started a jquery selector inside another. I didn't get very far, but as soon as I hit the $ inside the selector the entire bin locked up. There's no way for me to step back or fix it, so I just have to start over with a new bin.

**Comment by remy** [comment]
Hmm. Given that I don't know what library you're also including (jQuery, something else, nothing?) I can't replicate (I took a shot with jQuery, but it didn't replicate), but also, yeah, if you write something that causes an infinite loop through recursion, it's lock your browser up - it can't be helped I'm afraid!

**Comment by Michael-F-Ellis** [comment]
I know you've closed this but it just bit me, too.  It's a full day's experimentation totally inaccessible now.  The URL is http://jsbin.com/moropa.

It's Coffeescript and the JQueryMobile.  Same story as eepMoody.  I accidentally typed "$ $" and that was the end of the show.

Is there some way to at least recover the the code as a text file?  The best I've been able to do so far is use wget to fetch it from output.jsbin.com.  That gets me the JS but of course not the CS source.  Thankfully it's not a huge script (just hard to get right) and I can re-create the CS.

Would you consider adding a recovery URL that would allow fetching un-transpiled sources?

Thanks!

**Comment by remy** [comment]
There is, add `source` to the URL: http://jsbin.com/moropa/source/

**Comment by remy** [comment]
Of course, if it was in the JS panel, then you can just add `.js` to the original URL too: http://output.jsbin.com/moropa.js

**Comment by Michael-F-Ellis** [comment]
Nice!  And I see that moropa.coffeescript also works.

Thanks much for the quick reply and for developing this excellent resource!
