### ISSUE TITLE
Github username is not in the shared link

### ISSUE THREAD

**Issue by brxue** [jsbin/jsbin#2637]
Hi,

I just registered an jsbin account through my Github account, that being said my user name is 'brxue'. After created some bins, I noted that when I click share the link address is not under 'brxue', but will be under some random word, for example,

https://jsbin.com/goyuge/edit?html,output
https://jsbin.com/yugafu/edit

and when I enter https://jsbin.com/brxue in browser URL window, it returns a 404 page.

My question is that is this a characteristic of free jsbin account? thus only PRO users have address like https://jsbin.com/brxue?

Thanks,
Brian

**Comment by remy** [comment]
Usernames are not in the pathname of share links. Only in the cname of pro user accounts.
