### ISSUE TITLE
jsbin.com is down right now

### ISSUE THREAD

**Issue by jagtesh** [jsbin/jsbin#2649]

**Comment by dylmye** [comment]
this isn't a code issue, it's a server issue

**Comment by timsooo** [comment]
Any info when it'll be back?

**Comment by timsooo** [comment]
Does that happen often with jsbin? Just wonder whether I should continue using it?

**Comment by jagtesh** [comment]
@timsooo Not really. It's the first time this has happened to me. I've been using it for years. @dylmye I understand, just didn't know where else to voice my concern.

**Comment by 29er** [comment]
any timeframe on this being fixed ?

**Comment by remy** [comment]
No timeframe at the moment, there's something seriously wrong with the app
server ebs drive. And I'm about to board a 14 hour flight. Will keep you
all posted.

**Comment by pmunin** [comment]
It's been 3 days already

**Comment by wpcarro** [comment]
Any updates on this? I was really enjoying JSBin's ease of adding libraries!

**Comment by remy** [comment]
JS Bin is back up. It was down for short of 24 hours (due to my flights and the serve outage).

**Comment by remy** [comment]
For more context the load on the machine is increasing without cause. I've
started two additional ec2 machines to no avail.

**Comment by timsooo** [comment]
I've lost like an hour of work :(

**Comment by dylmye** [comment]
possible DDoS? check access logs and maybe block some offending IP ranges
