### ISSUE TITLE
window.open doesn't work when js is auto-run

### ISSUE THREAD

**Issue by robianmcd** [jsbin/jsbin#2651]
If I put the following code in a jsBin

```
console.log(window.open);
setTimeout(function() {
  console.log(window.open);
});
```

it will log out the following on the intial load and when the bin it reloaded with auto-run. `window.open` does not work in this scenario.

```
function (){}
undefined
```

However if I click "run with JS" then it log out:
```
function open() { [native code] }
function open() { [native code] }
```
and `window.open` does work.

Sample jsBin: https://jsbin.com/yaxofamodi/edit?html,js,console,output

Any idea why this is happening?

**Comment by robianmcd** [comment]
This issue is happening for me in Firefix, Edge, and Chromium but not in Chrome or IE11.

**Comment by chriskdon** [comment]
+1

**Comment by jFrenetic** [comment]
+1

**Comment by simevidas** [comment]
Try in `/quiet` mode. The `/edit` mode is iframed, so it's not completely reliable.

**Comment by remy** [comment]
It's actually a little more sublte than that. The `/edit` mode removes blocking functions like `open`, `alert` etc and once the code has run through it deletes the `noop` function that was put in place. ie.

```js
window.alert = function (){};
// ... Some time later
delete window.alert;
```

This restores the original prototype value, except, oddly in `open`s case. It seems like `open` isn't really part of the `window` object, so when the `noop` is deleted, we're left with `undefined`.

The fix here is to cache the original function, then put it back when restoring (perhaps only treating `open` as the edge case).

**Comment by dandv** [comment]
+1 - the [highest voted answer on StackOverflow about creating desktop notifications](http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example/13328513#13328513) is broken by this.

**Comment by remy** [comment]
So don't forget, this is an **open source** project. Anyone can fix this with the time, it would seem plusones sadly don't actually change code. I don't have much/any free time ATM with work, so if it's important to you, I'd love for a PR to be created and I can nerge and release. I'm more than happy to point someone in the direction of the fix. :heart:

**Comment by ericelliott** [comment]
:heart: @remy

**Comment by twidi** [comment]
To not open a new window without user action seems like a defensive anti pop-up feature by a browser. 
Maybe it's not the real cause but it would seem logical to me.

**Comment by remy** [comment]
I've explained the issue and solution here https://github.com/jsbin/jsbin/issues/2651#issuecomment-167203740

**Comment by f5io** [comment]
@remy is the main crux of it [here](https://github.com/jsbin/jsbin/blob/e9eaa748f8ab9a72f8cdee302e8f096aebca2f28/public/js/runner/processor.js#L10-L16)?

**Comment by remy** [comment]
Yes to both questions. I'd also be inclined to delete old object after use (but maybe do a cursory check that it doesn't blow away `window[m]` function - but I'm pretty sure it won't).

Probably worth namespacing the polluting variables.

Maybe also worth sticking the try/catch inside the loop, so that if restoring `open` fails, it doesn't prevent restoring `alert` from failing (for instance).

Also: thank you.

**Comment by f5io** [comment]
@remy, Cool, I'm on it, but it seems there is an issue getting the site to run with your latest bump to `loop-protect`. `rewriteLoops` does not exist on the `loopProtect` object. Am I right in thinking [both references](https://github.com/jsbin/jsbin/search?utf8=%E2%9C%93&q=rewriteLoops) to the `rewriteLoops` method should now just use `loopProtect(code)` rather than `loopProtect.rewriteLoops(code)`? And if so would you like a separate PR?

**Comment by remy** [comment]
@f5io cheers, and I've fixed the loop protect stuff - somehow got it a pickle.

**Comment by f5io** [comment]
@remy No problem, glad I could help.

+ 1 :wink:

**Comment by remy** [comment]
Fixed and live thanks to @f5io.

**Comment by mgingras** [comment]
@remy :+1:

**Comment by dandv** [comment]
Thanks @f5io and @remy.

Sorry I don't have much time these days to contribute; just trying to make that [desktop notification example](http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example/13328513#13328513) work. But now after clicking the Notify button, the script stops with this error:

"ReferenceError: notifyMe is not defined
    at HTMLButtonElement.onclick (http://null.jsbin.com/runner:1:31)"

Let me know if I should file a separate issue.

**Comment by remy** [comment]
I'm seeing it working - what's the url you're viewing (mine defaults to https IIRC): 

<img width="1280" alt="screen shot 2016-01-08 at 17 43 14" src="https://cloud.githubusercontent.com/assets/13700/12204933/62bc9a92-b62f-11e5-9a41-8de0a8760d15.png">

**Comment by dandv** [comment]
`http://`. The HTTPS page works.

**Comment by robianmcd** [comment]
Awesome thanks! I built an app (http://robianmcd.github.io/the-sandbox-challenge/#/ES6) that wraps jsbin and uses `window.open` to login and it's working now
