### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by GhostGambler** [jsbin/jsbin#2652]
http://output.jsbin.com/ruxona
Status page says everything is alright, nevertheless this page does not load.

(btw. is it really reasonable to forward everyone from the temporary error pages to the github issue tracker? :confused: )

**Comment by remy** [comment]
What temporary error page?

**Comment by GhostGambler** [comment]
I think it was http error 503? … some text about someone being lost watching lights or something.

I feel a bit uncomfortable opening an github issue for the only reason, that a page does not load, which might not be a bug concerning the source code, but just an infrastructure issue.

**Comment by remy** [comment]
The main issue is fixed now anyway.
