### ISSUE TITLE
Output shows HTML rather than DOM elements

### ISSUE THREAD

**Issue by Bjvanminnen** [jsbin/jsbin#2655]
![screenshot from 2015-12-16 23 34 28](https://cloud.githubusercontent.com/assets/1767466/11863968/92eab7d8-a44d-11e5-9140-8cbb71675d97.png)

This appears to be tied to my account, as things work if not logged in. I was mucking with some of my settings earlier today, which probably broke things somehow, but I'm not sure what/how. Account name is Bjvanminnen. Let me know if there's anything else I can do to help debug.

**Comment by remy** [comment]
It's possible you're in a debug mode. Open the browser devtools, and set
`jsbin.settings.debug=false`

**Comment by Bjvanminnen** [comment]
This was it. Thanks so much! JS bin rocks!
