### ISSUE TITLE
Recover my account

### ISSUE THREAD

**Issue by GuimDev** [jsbin/jsbin#2659]
Hi,

I want to recover my account "GuimDev", but I deleted my Github account, and I can't login in.... I need to get a jsbin bin. :/

Can I recover my account ?

Thanks. ;)

**Comment by remy** [comment]
Are you able to sign in with github? I can transfer the account across assuming we can prove that you really do own these bins.

**Comment by GuimDev** [comment]
I can't

>     Your GitHub username is taken on JS Bin. If this is you, please register with JS Bin and link your GitHub account.

(Actually I have this account : @Hors-Sujet)

How can I prove that is my account ?

With my account, I make : 
This PR : https://github.com/jsbin/jsbin/issues/190 and jsbin : https://github.com/jsbin/jsbin/issues/1909

http://jsbin.com/royawo/1/edit?html,output
http://jsbin.com/warit/1/edit?html,output

(If I remember my template is : 

```
function log() {
	var p = document.createElement("p"),
		text = Array.prototype.join.call(arguments, ", ");
	p.textContent = text;
	document.getElementById("console").appendChild(p);
	return text;
}

log("Hello word !");
```
)

I need to recover my account, because I lose the link of the JS script who convert string to : 
```
var alphaC = "zyxwvutsrqponmlkjihgfedcba~?>=<:.-,+`";
var alphabet = "/-\n codebasvilkunprmf(gtw)=\t[0];'hy!>";
var code_de_base = ["zzyyyyyyyyyyyyyy",
	"yyyyyyyyyyyyyyyyyyxzzyyyyyyyw$vu",
	"tswtswrqpsw█████████yyyyyyyyyyyx",
	"zzyyyyyyy██yyyyyyywo██nqw$mss$lm",
	"uktwyyy██yxxzzw$ujwihs██jtwmqwih",
	"sgnshs█wqhgs██xnf██wedsc█$bsqiuj",
	"eaw~~w█jkmma██x?p██sc$bs█qiujeds",
	"c$bsq█iujpea██>=<██a:xxzz█w$ujwh",
	"svkis█hswm.sjjsgnwmswimkp█wihuv-",
	"sxoqh█wsjsg█████████,w~wd█sc$jsq",
	"hspc$s█jsg,█ea:█xxz█zw$u█jwp.qii",
	"huv-sw█tswm█.sj████jsgnw█pnwrspu",
	"njxnfwe██dsc███$vsmm$c██u$kps$bs",
	"qiujesjsg██,aw+~wdsc██$vsmmeaax?",
	"guos$cubqht█████████esjsg,a:xxzz",
	"w$ujwsppq,swtswmknwcnhshwtsppkpx",
	"b-nmswekps$bsqiujesjsg,aw`~w=a:x"
].join("").decompressIA(alphaC, alphabet);
```
It's the one of latest script that I made, before I lost my account.

I have others scripts, but I made it when I not login on...

Thanks.

Sorry for my English, I'm French.

**Comment by GuimDev** [comment]
What should I do ?

**Comment by GuimDev** [comment]
@remy What should I do ?

**Comment by GuimDev** [comment]
@remy What should I do ?

**Comment by GuimDev** [comment]
?

**Comment by remy** [comment]
So, I can't really follow your explanation of what's what.

The username "GuimDev" was created 2014-07-03 and last logged in on 2015-01-06.

This is not the account you've ever had access to, I'm gathering that because your account (on github) was created on December 2015 (after the last login) and the user I have (with the same name) in my database logged in via github (but has since removed their account).

You've mentioned a username of "Hors-Sujet" but this user has an active log-in, saying that they last logged in on 2016-03-28.

So I'm unclear what account you're trying to claim. Perhaps give me your email address and I can try to look up your account that way?

**Comment by GuimDev** [comment]
I deleted my github account "GuimDev". After, I could no login on my JsBin account.

I remade my github account (with the same id "GuimDev") to access to JsBin account but I can't.

("Hors-Sujet" is my [another account](https://output.jsbin.com/pijubi/edit/?html,output)).

Where do I send my email address ?

**Comment by remy** [comment]
You can send it to support@jsbin.com (please include your username in the subject).

Thanks.

**Comment by GuimDev** [comment]
Sent it. (14 avril) Re-sent today.

**Comment by GuimDev** [comment]
Thanks. :)
