### ISSUE TITLE
add mithril.js to the "Add library" list

### ISSUE THREAD

**Issue by futurist** [jsbin/jsbin#2666]
the latest version is:

https://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.2-rc.1/mithril.min.js

**Comment by JackC27** [comment]
Love this idea. :)

**Comment by remy** [comment]
Needs a PR: http://jsbin.com/help/adding-libraries

**Comment by futurist** [comment]
Please review PR: https://github.com/jsbin/jsbin/pull/2881

**Comment by JackC27** [comment]
Whoa. Awesome. Wow. Thank you. That is going to be really great. :) So cool!

**Comment by futurist** [comment]
@JackC27 AD:) maybe you can also have a look at my lib: [cssobj-mithril](https://github.com/cssobj/cssobj-mithril), it's embed css into mithril, with local class names and auto vendor prefixer.
