### ISSUE TITLE
ES6 warnings with Babel & React preprocessors

### ISSUE THREAD

**Issue by ericelliott** [jsbin/jsbin#2667]
## The problem

I'm seeing ES6 warnings, even with Babel or React preprocessors.

**Intermittent:** Appears and disappears seemingly randomly as I work in JSBin. I have seen it several times over the past few days.
## Reproduce

https://jsbin.com/buwaju/edit?html,js,output

Dev console output:

```
Mixed Content: The page at 'https://jsbin.com/buwaju/edit?html,js,output' was loaded over HTTPS, but requested an insecure image 'http://i0.wp.com/blank'. This request has been blocked; the content must be served over HTTPS.
jsbin-3.35.5.min.js:18 Processor is not ready yet - trying again
runner-3.35.5.min.js:1 d[ o_0 ]b
```

Empty JSHint settings:

``` js
jsbin.user.settings.jshintOptions // Object {}
```

Browser:

```
Google Chrome   47.0.2526.106 (Official Build) (64-bit)
Revision    19b9e1a5713f4b9ae324bd59bbe16ca6eb91d0e0-refs/branch-heads/2526@{#532}
OS  Mac OS X
```
## Actual ouptut

<img width="635" alt="screen shot 2016-01-07 at 2 04 40 pm" src="https://cloud.githubusercontent.com/assets/364727/12182809/cd92df0e-b547-11e5-8c0f-1e8823abb997.png">
## Expected

There should be no warnings about ES6 syntax with these preprocessors selected.

**Comment by remy** [comment]
Pretty sure the linter isn't changing to es6 when Babel is selected. I'll
check the code and confirm when at my desktop later today.

**Comment by ericelliott** [comment]
Yep. Keep in mind this is intermittent. Not sure if that will help identify the issue. I think I've seen the errors vanish after interacting with the page for a bit... =)

**Comment by danday74** [comment]
annoying, switching to Javascript and then back to Babel/ES6 fixes it. 

Had to switch to JavaScript permanently to ensure this did not happen (which gave me a load of linting errors).

**Comment by yhaskell** [comment]
![image](https://cloud.githubusercontent.com/assets/1381813/25561860/ad56775c-2d9e-11e7-8da9-e3b9eb0d7262.png)

I have some problem in both Firefox and Chrome. 
"Fix" usually requires for a new bin to save it, then select es6/babel, and then reload page.
