### ISSUE TITLE
I am missing bins (PLEASE HELP!!)

### ISSUE THREAD

**Issue by BernhardBruhnke59** [jsbin/jsbin#2671]
I am currently working on a javascript bootcamp. I had a weekend project. I saved the sections in separate bins. Today, when i'm reviewing, of the seven sections I made, five are missing. Is there something that may have happened to lose these bins. PLEASE HELP!

**Comment by remy** [comment]
Are you logged in?

**Comment by remy** [comment]
Will be closing this issue soon, if it remains idle.

**Comment by abhisekp** [comment]
@remy time to close I guess? :smirk:
