### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by riznob** [jsbin/jsbin#2672]
I am following the guide [here](https://github.com/jsbin/jsbin/blob/master/docs/running-your-own-jsbin.md) and I get the following error when running npm install. Please help!

npm WARN EPEERINVALID mocha-casperjs@0.5.5 requires a peer of casperjs@>= 1.1.0-beta3 but none was installed.
npm WARN EBUNDLEOVERRIDE Replacing bundled sqlite3 > node-pre-gyp with new installed version
npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/local/node-v5.4.0-linux-x64/bin/node" "/usr/local/node-v5.4.0-linux-x64/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path /home/rande4/Downloads/jsbin/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/rande4/Downloads/jsbin/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rande4/Downloads/jsbin/npm-debug.log

**Comment by remy** [comment]
Node 5 is not supported. 0.10 is.

**Comment by 100ideas** [comment]
I think you'll need to use 0.10.26 - otherwise semver carets in the package.json file will cause errors. https://github.com/jsbin/jsbin/pull/2561
