### ISSUE TITLE
Inexplicable errors

### ISSUE THREAD

**Issue by keenwon** [jsbin/jsbin#2676]
![image](https://cloud.githubusercontent.com/assets/5516478/12344120/c30a07d2-bb74-11e5-9062-1d03c6c06081.png)

I create two same Bins，but one of them report an error：
success: http://jsbin.com/rilaca/edit?js,console
error: http://jsbin.com/wenamo/1/edit?js,console

**Comment by leeyeh** [comment]
The second one is in ES6/Babel.

**Comment by keenwon** [comment]
Recent Babel instability
