### ISSUE TITLE
Stop Auto Saving

### ISSUE THREAD

**Issue by felippenardi** [jsbin/jsbin#2681]
I'm experiencing some lag when editing HTML because JSBin keeps auto saving.

My Javascript Auto-run is already disabled.

Is there  away to disable the auto saving? (even if it is not a feature, but I a command I can use on the console?)

**Comment by remy** [comment]
If you have a pro account, you can visit https://jsbin.com/null - this won't save by default.

**Comment by remy** [comment]
Also aliased to `-` on the url - more here: http://jsbin.com/help/sandbox-mode
