### ISSUE TITLE
Training course support

### ISSUE THREAD

**Issue by dnOnGitHub** [jsbin/jsbin#2684]
After using JSbin for the first time during a recent course (as a trainee), I have been asked to design an Introductory level course. I see that your service's objectives include education.

1 to save "re-inventing the wheel", are you aware of existing courses which introduce JS and/or JSbin?

2 (assuming the course is actually mounted) are we able to group the class's members and work on JSbin (or is everyone's account basically individual)?

3 is a private bin, accessible only by the individual (owner) or is he able to make the files contained therein available to (only) selected other users?

4 given that a pro account enables asset up-loading, could this facility be used to make images, CSS files, JS scripts, etc, available for trainees to access by name to use in their own work? (thus providing a convenient CORS-avoiding mechanism)

5 is there an education rate for the (normally 100 pounds) pro account?

6 if there are other facilities or suggestions you are able to bring to my attention, I will appreciate your attention...

Regards,
=dn

**Comment by remy** [comment]
1. Yes, lots, google will help. A start is http://eloquentjavascript.net/
2. Accounts are individual. There was going to be some work to allow users to share access to write to a specific bin, but this not available soon (and will require pro).
3. Accessible only to the owner.
4. Correct.
5. No, only for educators (with some proof of the institution they work for
6. Code casting perhaps. But there's also some articles in the [help](http://jsbin.com/help)
