### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by ProteusCortex** [jsbin/jsbin#2689]
Hello,

I have an account using my Github username. I would like it to be deleted.

Thank you.

**Comment by remy** [comment]
Is it yours? If so, you can go to jsbin and delete it from the /account page.

**Comment by ProteusCortex** [comment]
Ah, I read that you handled such things from here. Thanks!

**Comment by remy** [comment]
I used to, but I always intended to add the functionality (and eventually
did).

Can you point me to where you read it so I can update (or ask for an
update)?

Cheers,

– Remy

**Comment by ProteusCortex** [comment]
Sure. I got it from issue #1010, mentioned by [justdelete.me](http://justdelete.me).
