### ISSUE TITLE
Credit cards get declined when trying to upgrade to Pro

### ISSUE THREAD

**Issue by jewelsjacobs** [jsbin/jsbin#2690]
They are American Visa cards that don't get declined any where else right now. :( Plenty of credit!

**Comment by jewelsjacobs** [comment]
Solved issue - Apparently in Chrome if you have a credit card in Google Wallet your card gets declined even if you don't choose it to register for pro. I deleted the one card I had in Google Wallet and all was well.

**Comment by remy** [comment]
Wow, and well played on debugging!
