### ISSUE TITLE
Getting internal server error trying to connect dropbox

### ISSUE THREAD

**Issue by avanslaars** [jsbin/jsbin#2691]
From my profile page (pro account) I clicked on the link to connect dropbox. The address bar shows https://jsbin.com/auth/dropbox and I receive a 500 error.

**Comment by remy** [comment]
Fixed. Sorry about the outage.

**Comment by avanslaars** [comment]
Excellent, thanks!

**Comment by freddnyg** [comment]
I upgraded to pro today and I got the mentioned error. https://jsbin.com/auth/dropbox
