### ISSUE TITLE
Still being billed

### ISSUE THREAD

**Issue by yahwehisourgod** [jsbin/jsbin#2692]
Hello, I deleted my pro account a couple of months ago. However, I'm still being billed for it. I, of course can't sign in, so I created another account hoping to just link the payment with the new account. That is not working, so I was hoping we could just stop billing for the account that is no longer available. Thanks

**Comment by remy** [comment]
Did you cancel the subscription? Also, what was the username you were being billed under so I can investigate?

**Comment by ldian** [comment]
dear Remy,

Calm down is not the  biggest thing is a oldschool cell...skubido

2016-01-31 21:57 GMT+01:00 Remy Sharp <notifications@github.com>:

> Did you cancel the subscription? Also, what was the username you were
> being billed under so I can investigate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2692#issuecomment-177608667>.
>



-- 
*Tisztelettel:*
Dian László
Tel.:06/703774257

**Comment by yahwehisourgod** [comment]
I am not entirely sure if I canceled the subscription. I thought that was
what I was doing when I canceled the account. :/
The username should have been yahwehisourgod.
I created a new one under this username today.  If there is anyway to
transfer the billing to this new account, I would be ok with that.  I just
didn't want to subscribe to a new pro account when I was already being
billed.  If any of that makes sense. .

**Comment by remy** [comment]
I'll take a look at this in the morning and get back to you. I suspect I should be able to activate against your new account, but I want to be sure first.

**Comment by yahwehisourgod** [comment]
Thank you so much

**Comment by remy** [comment]
I've found your account active in stripe (exactly as you said, it's still billing). I've updated your account so that you've got the pro status again. If you can also check jsbin.com/upgrade to make sure you have details of your invoices - that would be perfect.

**Comment by yahwehisourgod** [comment]
All as it should be.  Thanks for your help!
