### ISSUE TITLE
Jsbin Pro free for education

### ISSUE THREAD

**Issue by joao-mc** [jsbin/jsbin#2695]
Hi there

I am a cs teacher in public school in Portugal and am teaching web development. I would like in deed to use this great tools for education purposes in my classes. How can I get a free pro account?

Please reply to me asap

Many thanks and regards

João Costa

**Comment by remy** [comment]
Please can you provide some proof of your teaching position? Thanks.

**Comment by joao-mc** [comment]
HI
Yes, I can give you my institutional email address. How can I send it to you and further details?

**Comment by remy** [comment]
Drop an email to support@jsbin.com
