### ISSUE TITLE
Template Strings

### ISSUE THREAD

**Issue by stefnotch** [jsbin/jsbin#2697]
JSBin doesn't support template strings. Simple programs such as ```var x = `This is a template string`; ``` will cause it to throw a large number of errors.
https://jsbin.com/tomidu/edit?js

**Comment by kirjs** [comment]
Apparently this is because your browser doesn't support template strings. 
Try switching from JavaScript mode to es6/babel

**Comment by stefnotch** [comment]
(I'm using the latest Firefox version. It does support ES6.)
`/*jshint esnext: true */` solves the problem.

**Comment by chilipepper987** [comment]
The warning on jsbin says something like "let is available in ES6, use esnext option" but doesn't actually tell you how to "use an option"... and picking ES6/babel from the menu doesn't fix it... so thank you for explaining how to actually do it
