### ISSUE TITLE
Please delete the following code immediately please

### ISSUE THREAD

**Issue by supersi47** [jsbin/jsbin#2699]
https://jsbin.com/tiyacimufu/edit?html,output

Could this page be deleted and all code removed with immediate effect please??

HELP, this wasnt meant to be saved, when I delete it and try to erase the content it doesnt work!

Please quickly, could confirmation of this be sent to simon.clenton@ukpowerreserve.com?

Thankyou

**Comment by remy** [comment]
Done.
