### ISSUE TITLE
Changing file name

### ISSUE THREAD

**Issue by pogradytuba** [jsbin/jsbin#2707]
Hello,

I have a file name of pedusa, which I do not like very much.  Can I change that name to something else?

Thank you,

Patrick O'Grady

**Comment by remy** [comment]
Clone it.

**Comment by pogradytuba** [comment]
Thank you Remy.

On Fri, Feb 19, 2016 at 2:13 PM, Remy Sharp <notifications@github.com>
wrote:

> Clone it.
>
> On Thu, 18 Feb 2016 23:25 pogradytuba <notifications@github.com> wrote:
>
> > Hello,
> >
> > I have a file name of pedusa, which I do not like very much. Can I change
> > that name to something else?
> >
> > Thank you,
> >
> > Patrick O'Grady
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jsbin/jsbin/issues/2707>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2707#issuecomment-186431138>.
>



-- 
Patrick O'Grady
Puba <http://patricktuba.weebly.com>
