### ISSUE TITLE
Strange and random scss errors?

### ISSUE THREAD

**Issue by alancwoo** [jsbin/jsbin#2708]
I'm getting really confused because I am always getting errors with basic SCSS such as:

```
$grey-light: rgb(240,240,240);
body {
  color: $grey-light;
}
```

Which results in

>  Line 4: Invalid CSS after " color: ": expected expression (e.g. 1px, bold), was "$"

or

> Line 4: Invalid CSS after " color:": expected pseudoclass or pseudoelement, was " $grey-light;"

For example, in the jsbin: http://jsbin.com/ruwife/1/

Screenshot: http://d.pr/i/1bqI8/xVKJKC6i

---

Or when using stylus with simply:

```
$grey-light = rgb(240,240,240);
body {
  color: $grey-light;
}
```

I get the error:

> Line 1: undefined

**Comment by WolfieZero** [comment]
I was also getting this error yesterday but I can't see to replicate it now. What it seems like is when an error occurred with the SCSS, JS Bin wouldn't do any more checks on SCSS without reloading the whole app.

**Comment by Melluish** [comment]
I too am getting errors along the same lines as the OP. Seems the parser also has some issues with variables that contain a dash, although that's legit SCSS as far as I'm aware?
![screen shot 2016-06-13 at 18 20 40](https://cloud.githubusercontent.com/assets/878650/16016579/a1cf6c66-3193-11e6-8063-30bc26410ef0.png)
