### ISSUE TITLE
Vue.js library not load

### ISSUE THREAD

**Issue by zyf0330** [jsbin/jsbin#2711]
jsbin is https, but vue.js url is http, so it doesn't be load.

**Comment by remy** [comment]
Yeah, so change jsbin to http

**Comment by zyf0330** [comment]
@remy Are you kidding me? This is be Ok?

**Comment by remy** [comment]
I'm not entirely sure what part is the joke? Also "This is be OK" - not sure what you're actually asking.

Still, perhaps this will help: http://jsbin.com/blog/ssl-for-all#sslnowavailabletoall SSL was originally never part of jsbin for very specific reasons related around exactly the issue you raised.

**Comment by zyf0330** [comment]
OK.  if HTTPS is not necessary, why require it.
That is what I mean. And it caused problem like above.
Maybe it is a little question for developer , but in other hands, they are
also user include me. It is not a good experience, especially when I have a
bad network.

On Wed, Feb 24, 2016, 18:41 Remy Sharp <notifications@github.com> wrote:

> Closed #2711 <https://github.com/jsbin/jsbin/issues/2711>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2711#event-563357566>.
>
-- 

追随

**Comment by remy** [comment]
https is necessary (security over not having it, users can opt-in, allows for future offline support), it's just not required (as you saw be changing it).

Not sure what it has to do with the network though? But the bottom line is that there's no way to tell if a script didn't load using browser APIs to warn the user of this. 

If you don't want to use SSL, opt-out user the settings (as per the blog post).

**Comment by revathskumar** [comment]
@zyf0330 I had the similar issue and I used `Vue` from https://cdnjs.com/libraries/vue which worked fine. 

@remy  Is there any way to point the `asset_url` of `Vue` to point to cdnjs instead of vuejs.org when selecting `Vue` from **Add Library**.

**Comment by zyf0330** [comment]
I haven't found a HTTPS resource of vue then.

On Wed, Feb 24, 2016, 21:47 Revath S Kumar <notifications@github.com> wrote:

> @zyf0330 <https://github.com/zyf0330> I had the similar issue and I used
> Vue from https://cdnjs.com/libraries/vue which worked fine.
>
> @remy <https://github.com/remy> Is there any way to point the asset_url
> of Vue to point to cdnjs instead of vuejs.org when selecting Vue from *Add
> Library*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2711#issuecomment-188262080>.
>
-- 

追随

**Comment by remy** [comment]
@revathskumar yup, a simple pull request to the libraries.js file will fix it.

@zyf0330 the https version of vue is right there, where @revathskumar pointed you to...

**Comment by zyf0330** [comment]
Thanks you all. It is good end.

On Wed, Feb 24, 2016, 22:07 Remy Sharp <notifications@github.com> wrote:

> @revathskumar <https://github.com/revathskumar> yup, a simple pull
> request to the libraries.js file will fix it.
>
> @zyf0330 <https://github.com/zyf0330> the https version of vue is right
> there, where @revathskumar <https://github.com/revathskumar> pointed you
> to...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsbin/jsbin/issues/2711#issuecomment-188269576>.
>
-- 

追随
