### ISSUE TITLE
My account 'My Bins' are gone

### ISSUE THREAD

**Issue by StevanSkrbic** [jsbin/jsbin#2714]
'My Bins' are gone ? At one moment there was some issue during my work in JS Bin like it was suddenly became slow to Run my code. And since then when I looked in My Bins there were a lot of some other bins (i can guess that they are Chinese language named) and all my bins are gone. I had a lot of work that is very important for me, and now they are lost? Is there sth we can do to bring them back, please?

My account on jsbin is steva.skrbic@gmail.com

**Comment by remy** [comment]
Do you know what your username was, or is it the same as your github username? I can take a look at the db to see what's going on (hopefully).

**Comment by StevanSkrbic** [comment]
I was loging with my emial: steva.skrbic@gmail.com or my github account, I merged it a long time ago, I think.
But I think that my username that is appearing in top right of window was changed to sth generic when this issue happened, and the eyes of JSBin logo became pink, and Im not sure that was the case when everything was ok? (but email stays the same in Profile info).
Hope this info may help you with resolving the issue.

**Comment by StevanSkrbic** [comment]
![01_jsbinerror](https://cloud.githubusercontent.com/assets/10964795/13347341/69d8d412-dc6d-11e5-85bb-feb64064c9a5.PNG)
I am sending you my home cpu (on Windows 8.1) screenshot where everything is ok with My Bins. And you can see my account username (original).

But on my business cpu there is still a problem (i've attached that screenshot, too), as you can see there is some other user name account, but same email (my email). 
![selection_077](https://cloud.githubusercontent.com/assets/10964795/13347418/da60a55c-dc6d-11e5-8449-117107056a45.png)

**Comment by remy** [comment]
This is super weird. Can you sign out on the business machine? And try signing in again?

Is it at all possible that someone else signed in that machine? And...possibly (and this is a long shot) the email is pre-populating from your browser's autofill?

**Comment by StevanSkrbic** [comment]
Yes, I've done that (on business machine), and my previous bins are now back, though my last 4-5 bins disappeared (because they were on that strange merged account)?
I guess I cant recover it now?

No, there is no possibility that someone else signed on my business machine (it is locked with my pass).
