### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by AlSmith87** [jsbin/jsbin#2715]
I had a non-github account. It appears this can no longer be used and I created a git hub account to log in with. I now cant login at all and get this message - "Your JS Bin account (undefined) has been linked to your GitHub account (AlSmith87). Nice.", but never actually logs in.

Does this also mean I have lost all my old projects linked to my non-github account?

**Comment by remy** [comment]
Do you remember what your non-github email was? (if you don't want to post here, you can DM the js_bin twitter account). I can't look right now, but I should be able to link up your account.

**Comment by AlSmith87** [comment]
Yeah it was the same email as I have re-registered with - asmith@djsresearch.com

**Comment by AlSmith87** [comment]
When can someone take a look at this. I really need to access my other account asap now.

**Comment by AlSmith87** [comment]
Do you know when you will be able to take a look at this? I really need to
get my account back up and running. I currently cannot even log in with my
new account to save any new bins.



[image: DJS_Signature] <http://www.djsresearch.co.uk/>

*Alistair Smith* | Operations Manager - Data Services

asmith@djsresearch.com
+44 (0)1663-767857
http://www.djsresearch.co.uk/



[image: twitter] <https://twitter.com/DJSResearch>  [image: linkedin]
<https://www.linkedin.com/company/djs-research-ltd>  [image: googleplus]
<https://plus.google.com/b/113329919709971528784/+DJSResearchcouk/posts>
 [image:
facebook] <https://www.facebook.com/DJSResearch>  [image: youtube]
<https://www.youtube.com/user/DJSOnline01>



To learn more about us, why not view a two minute introductory video:
https://vimeo.com/109113047

For regularly updated market research findings from your sector, please
have a look at our complimentary insights:
http://www.djsresearch.co.uk/blog/articles

This email is private and may be confidential and is for the intended
recipient only.  If misdirected, please notify us and confirm that it has
been deleted from your system and any copies destroyed.  If you are not the
intended recipient you are strictly prohibited from using printing, copying
distributing and disseminating this email or any information contained
within it. We use reasonable endeavours to check all emails leaving our
systems but no warranty is given that this email and any attachments are
virus free, you should perform your own virus checking.  The right to
monitor email communications through our networks is reserved by us. This
e-mail does not constitute a consent to the use of sender's contact
information for direct marketing purposes.

Please consider the environment before printing this email.

DJS Research Limited.  Registered Address: 3 Pavilion Lane, Strines,
Stockport, Cheshire, SK6 7GH.  Company registration number: 5494158



*From:* Remy Sharp [mailto:notifications@github.com]
*Sent:* 25 February 2016 10:31
*To:* jsbin/jsbin
*Cc:* AlSmith87
*Subject:* Re: [jsbin] Login issue (#2715)



Do you remember what your non-github email was? (if you don't want to post
here, you can DM the js_bin twitter account). I can't look right now, but I
should be able to link up your account.

—
Reply to this email directly or view it on GitHub
<https://github.com/jsbin/jsbin/issues/2715#issuecomment-188712641>.

**Comment by karlgroves** [comment]
@AlSmith87  try clearing *all* cookies and offline storage. I had the same problem as you.  I spent a long time chasing my own tail this morning trying to replicate it across other browsers and it turns out that, for whatever reason, I had to clear cookies in order to login.

**Comment by AlSmith87** [comment]
Thanks. I have actually just tried this myself and can now login and save new bins. Look like I have lost all my old projects though.

**Comment by remy** [comment]
@AlSmith87 your old username was "asmith" did you try logging in using that? You had what looks like 3 unique bins (and multiple versions of one in particular) from around late September. Sound right?
