### ISSUE TITLE
Pro account vanity URL not working

### ISSUE THREAD

**Issue by Xinchro** [jsbin/jsbin#2719]
I got a pro account a few months back and my vanity URL is not redirecting correctly (I assumed it was a manual process, so I gave it time). Using `<vanity>.jsbin.com/<binID>` simply redirects to `output.jsbin.com/<binID>` and pushing a bin to the vanity URL itself says it succeeds, but it does not.

Username is `Xinchro`

**Comment by Xinchro** [comment]
Hey, not to bother...but has this been looked into?

**Comment by remy** [comment]
Hey sorry, I've been trying to look at this but not making any progress. I think I need to double check the logic around the redirect to output (which is relatively recent too).

**Comment by BrentonCozby** [comment]
Same issue with me. I clicked "Publish to my vanity homepage" while viewing one of my projects, and it gave me this link:

http://brentoncozby.jsbin.com/

...but this takes me to a blank JSBin project (http://jsbin.com/?html,css,js,output).

**Comment by remy** [comment]
I'm taking a look at this now.

**Comment by remy** [comment]
Took a lot of digging, but managed to get there in the end.

@Xinchro sorry for the delay getting this one to land!

**Comment by BrentonCozby** [comment]
@remy Thanks Remy! Works now. :)

http://brentoncozby.jsbin.com/

**Comment by Xinchro** [comment]
@remy 10/10 Great work. Thanks!
