### ISSUE TITLE
Web Teacher - Haverhill High School

### ISSUE THREAD

**Issue by pcosgrove01860** [jsbin/jsbin#2728]
Is there a route for my students to use some assets (images and icons) that does not involve money?

We are loving your playpen for showing code and css and javascript - it really is awesome. hat would it cost too get a limited ability to play with images?

**Comment by remy** [comment]
I'm afraid, as you well know, everything invokes money. I suspect you specifically mean: that does not involve supporting jsbin's continued service.

You can host the images on other sites, or even local school machines, and have their bins point to those hosted images. That's probably the cheapest way to get around the asset issue.
