### ISSUE TITLE
logging in problems

### ISSUE THREAD

**Issue by dipetersen** [jsbin/jsbin#2731]
When I try to log in using my GitHub account, I get the error that says that the GitHub account is linked to another JSBin account.  How do I get it synced so I can log into jsBin?

**Comment by dipetersen** [comment]
email address:  david@dipetersen.com
username: dipetersen

**Comment by thiagodebastos** [comment]
I am having the same issue with Chrome (Version 52.0.2743.116 (64-bit) Mac), but when I try to log in with Chrome Canary, Firefox Developer Edition or Safari, it works just fine. 
Its strange because I have the same plugins on both versions of Chrome.
