### ISSUE TITLE
My Bins --> Archive link

### ISSUE THREAD

**Issue by shoukath** [jsbin/jsbin#2734]
Hi, Im a regular user of JS Bin. In the My Bins page, the archive link get displayed in the middle of the selected line and on hover. There are my times when I click on the archive link instead of the page. It would be great if the archive link is to the right instead of middle.
Thanks
Shoukath

**Comment by abhisekp** [comment]
I've also felt this UX issue a lot in past.
But overtime I've gotten used to... :stuck_out_tongue_winking_eye: 

Would be nice if the archive link be to the *right*

> [![](http://i.imgur.com/lyMRm30.png)](http://i.imgur.com/lyMRm30.png)
