### ISSUE TITLE
Session Bug?

### ISSUE THREAD

**Issue by ktilcu** [jsbin/jsbin#2736]
I was working on one of my bins and went to change an account setting and realized that I was somehow logged into another account. I can see this accounts active bins and other information. I assume this is bad but couldn't find a way outside of github to notify you. I'm going to log out of this person's account but I wanted you to have the information.

**Comment by remy** [comment]
If you remember any of the details, in particular the username of the other account, can you email support@jsbin.com so I can take a look how this could have happened? Thanks for letting me know too!
