### ISSUE TITLE
Free CDN

### ISSUE THREAD

**Issue by cdn77oskar** [jsbin/jsbin#2743]
Hi,

I see that you are serving static files through Cloudfront. If you're paying them for the traffic, let me know at oskar[atsymbol]cdn77[com] and we might be able to provide the CDN free of charge.

Kind regards
Oskar

**Comment by remy** [comment]
The CDN isn't anywhere near the bulk of the costs, the EC2 machines are. Thank you, but I'll pass in favour of keeping the tech in one place.
