### ISSUE TITLE
Gateway timeout when attempting to upgrade... :-(

### ISSUE THREAD

**Issue by boisdunord** [jsbin/jsbin#2752]
Error 504 from nginx when attempting to upgrade to jsbin pro

**Comment by boisdunord** [comment]
Took my money but account is not upgraded... :-(

**Comment by boisdunord** [comment]
Sorry - didn't mean to close the issue... still outstanding...

**Comment by remy** [comment]
Hi Tom,

Sorry this caught you - the money taking part is Stripe, and annoyingly JS Bin gave you a 504 (which I'm investigating separately) when Stripe went back saying it was authenticated.

I'm looking at the database record for your account, and it says you're pro. It might be worth just logging out and back in and it might pick it up then?

I'll keep an eye on this issue this evening to make sure you're all sorted (your email caught me just as I was heading to put my kids to bed, so couldn't sort it out right away - sorry).

**Comment by boisdunord** [comment]
Logged out and back in - all good!

And thanks for looking into it.

Thanks,
Tom.
