### ISSUE TITLE
Want to register but not give access to modify gist

### ISSUE THREAD

**Issue by zoldello** [jsbin/jsbin#2753]
It would be nice to register with jsbin without granting it access to read and write to my gist. That is too invasive to me.

**Comment by remy** [comment]
Then you need to register through the old method. Please add to the existing thread in github.

**Comment by zoldello** [comment]
I tried registering with the old method but it is now disallowed.

**Comment by remy** [comment]
Indeed. You need to follow the directions in the issue thread.
