### ISSUE TITLE
JSBin arbitrarily created nearly 700 snapshots of my current bin

### ISSUE THREAD

**Issue by chrislambrecht** [jsbin/jsbin#2763]
I don't have a good explanation as to why, but I wanted to at least make you aware that last week I somehow ended up with nearly 700 snapshots of a bin I've been working on. It's a project that I've been working on casually at work during downtime. I first noticed the issue when I saw an absurdly high number next to 'My Bins' in the File menu.

Apart from telling you that the window/tab was open for most of the day in the background while I worked on other stuff, I don't know what other details I can provide or how to recreate the issue. I'm not using any libraries or jquery or anything. The project I'm working on is a simple HTML canvas game that is really nothing fancy.

I'm sorry I don't have any information; I know this isn't real helpful. But if this were my website/app, I'd want to know.

**Comment by remy** [comment]
It lets me know it's happened and I'm grateful for that.

Do you have any browser extensions that you could list here? Possibly they're interfering with the session. Equally do you block cookies (I've guessed not, but still work asking).

**Comment by chrislambrecht** [comment]
The only extensions that are installed are ones from Google: just about four plug-ins related to Google Docs/Sheets/etc. And no, cookies are not blocked.

I should have mentioned this before, but I was using Chrome (50) on a Windows 7 machine when I experienced this issue.

**Comment by abhisekp** [comment]
Sometimes deliberately clicking <kbd>**Ctrl**</kbd>`+`<kbd>**S**</kbd> everytime some changes are made create a lot of snapshots.

I was working on a bin for 2 days and as my net is unstable and I don't have a UPS for my computer (_which means browser crashes/disk corruption_), I press <kbd>**Ctrl**</kbd>`+`<kbd>**S**</kbd> frequently to save my work to the cloud :cloud: 
I ended up with 100+ snapshots and my JSBin dashboard was a mess. Had to run an archive script to archive all those. :expressionless: 

Maybe a UX change to collapse past related snapshots by default (_apart from the current/latest one_) make it less messy?

**Comment by remy** [comment]
I believe it's actually related to windows, there's a handful of users that have a problem where every change creates a new version. It could be cookies disabled (so the session is lost, and jsbin makes a new bin), but I highly doubt it. I'm still none the wiser about this though.
