### ISSUE TITLE
The line numbers are not clear when using solarized-dark highlight theme.

### ISSUE THREAD

**Issue by mindnova** [jsbin/jsbin#2764]
The line numbers are in a dark color which could not be seen clearly in solarized-dark theme.
![default](https://cloud.githubusercontent.com/assets/8268760/15267772/8b703728-19fd-11e6-98c5-e162b73c04a6.png)

**Comment by abhisekp** [comment]
@remy I guess this is fixed now

> [![](http://i.imgur.com/bvVYICB.png)](http://i.imgur.com/bvVYICB.png)
