### ISSUE TITLE
Auto-run is now disabled by default, and missing entirely? 

### ISSUE THREAD

**Issue by jaepage** [jsbin/jsbin#2770]
This is one of the main reasons I prefer JSBin and Codepen over JSFiddle. Is there some setting I'm missing, and a way to make the UI more clear if it is? Thank you.

**Comment by remy** [comment]
I've not changed the UI. What do you see?

This is what I see:

<img width="1280" alt="screen shot 2016-05-26 at 21 59 33" src="https://cloud.githubusercontent.com/assets/13700/15589972/2982b38a-238d-11e6-8408-091028b3dbba.png">

**Comment by jaepage** [comment]
![pic 2016-05-26 at 14 23 33](https://cloud.githubusercontent.com/assets/4712441/15590612/75ef8af8-234d-11e6-9fe5-fa967fc47250.png)

**Comment by jaepage** [comment]
I see the difference now. If I hide the output panel, I lose auto-run. Is that by design? I found it frustrating for one. Thank you.

**Comment by remy** [comment]
It's very much by design, otherwise the console becomes unusable and littered with output.

**Comment by jaepage** [comment]
It might be nice to add some kind of clue. Perhaps a tooltip-like suggestion on hover of the 'run' button, or at the bottom of the console pane. Thanks for considering, and assisting.
