### ISSUE TITLE
Underscore library include doesn't work.

### ISSUE THREAD

**Issue by HamsterCoder** [jsbin/jsbin#2771]
Steps to repro are simple:

I choose underscore from the dropdown list and the following is added to the html tab

`<script src="//jashkenas.github.io/underscore/underscore-min.js"></script>`

The library cannot be loaded this way though:

`Mixed Content: The page at 'https://jsbin.com/vudewok/edit?html,js,console' was loaded over HTTPS, but requested an insecure script 'http://underscorejs.org/underscore-min.js'. This request has been blocked; the content must be served over HTTPS.`

It also looks like it redirects to underscorejs.org.

**Comment by dhenson02** [comment]
Until the URL is changed, you can visit your [Preferences](http://jsbin.com/account/preferences) to change your account's `Use SSL by default` setting to **false** (unchecked) and access [http://jsbin.com](http://jsbin.com).

**Comment by HamsterCoder** [comment]
Okey, thanks, I fixed it by linking to a https cdn.
