### ISSUE TITLE
Is it possible to add html controls in context menu if cmd is "nofilter" using jquery Datable?

### ISSUE THREAD

**Issue by rinimujeeb** [jsbin/jsbin#2773]
$(document).contextmenu({
                delegate: ".dataTable td",
                menu:
                    [
                  { title: "Approve", cmd: "filter", uiIcon: "ui-icon-volume-off ui-icon-filter" },
                  { title: "Reject", cmd: "nofilter", uiIcon: "ui-icon-volume-off ui-icon-filter" },

                    ],
                  select: function (event, ui) {
                  
                    var coltext = ui.target.text();
                    var colvindex = ui.target.parent().children().index(ui.target);
                    var colindex = $('table thead tr th:eq(' + colvindex + ')').data('column-index');
                    switch (ui.cmd) {
                        case "filter":
                            //  alert(ui.cmd);
                            var firstname = ui.target.parent().children()[0].innerText;
                            var email = ui.target.parent().children()[1].innerText;
                            var receipt = ui.target.parent().children()[5].innerText;
                            var reason = '';
                            sendMail(firstname,email,receipt,ui.title,reason);
                            break;
                        case "nofilter":
                            // alert(ui.cmd);
                            DisplayPopUp();
                            break;
                    }
                },
                beforeOpen: function (event, ui) {
                    var $menu = ui.menu,
                        $target = ui.target,
                        extraData = ui.extraData;
                    ui.menu.zIndex(9999);
                }
            });

**Comment by remy** [comment]
I think this question is specific to your code, so probably best to open something on stackoverflow.
