### ISSUE TITLE
Bin not saving correctly?

### ISSUE THREAD

**Issue by laij84** [jsbin/jsbin#2780]
When trying to call a simple Javascript function in the console, i always seem to get "not defined" errors even though the function is defined. 

It seems like the bin isn't saving correctly, if I delete some characters and retype them exactly the same, I can then call the function in the console. See screenshots attached. Can you advise a solution?

![2016-06-06_09h30_31](https://cloud.githubusercontent.com/assets/18145822/15818039/fd483a94-2bd2-11e6-8805-8ca690d9c6e6.png)
![2016-06-06_09h39_57](https://cloud.githubusercontent.com/assets/18145822/15818040/fd4822c0-2bd2-11e6-9f87-05b71a2ad291.png)

**Comment by remy** [comment]
It's possibly to do with rendering. The console doesn't re-render as you type, so (I think) you have to hit ctrl+enter to get it to render (a good way to check is to add something like `console.clear(); console.log(new Date())` - then once it's rendered, it'll have injected your function.
