### ISSUE TITLE
html mangled in gist export

### ISSUE THREAD

**Issue by keithohara** [jsbin/jsbin#2782]
In addition to the gist anonymous bug #2459 which I have also run into, I am getting some strange behavior when I export a bin.  

The index.html includes the javascript twice.  Not sure if the desired behavior for index.html is to include all panes (as if you download from jsbin) or include only the HTML pane. But the current export doesn't seem to be either

http://jsbin.com/sujeda/edit?html,js,output
https://gist.github.com/anonymous/22b389fd4f8ba96e122750c59a917a92

**Comment by buleoer** [comment]
Same problem...
