### ISSUE TITLE
Adding new library to console doesn't work

### ISSUE THREAD

**Issue by cazaraghi** [jsbin/jsbin#2784]
Hey

We're new to jsbin. Trying to add Tangle.js as a new library on browser console, got stuck! Can anyone tell us where we're going wrong?

var mylib = {
	text: 'Tangle',
scripts: [
    { text: 'Tangle.js', url: 'http://worrydream.com/Tangle/Tangle.js' }
  ]
}; // the "My Library" object above
libraries.add(mylib);

**Comment by svandergaag** [comment]
Your code works fine overhere (JSBin v3.35.13,  Firefox 47). Do you care to elaborate on the symptoms regarding your stuckiness?

**Comment by remy** [comment]
@cazaraghi did you do this in your browser's native console?
