### ISSUE TITLE
Firefox does not show saved bins

### ISSUE THREAD

**Issue by phistuck** [jsbin/jsbin#2786]
For example, http://jsbin.com/vutotadido/1/edit?html,js,output shows this HTML (snippet) in Chrome -
```
<!doctype HTML>
<div id=remainsBlurry style="width...
```
In Firefox, it shows some default -
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>

</body>
</html>
```

This is caused due to the apparent reliance on the Referer header in start.js. In Firefox, the Referer header contains the URL of the script instead of the URL of its containing document.

**Comment by remy** [comment]
I've just tried this, and can't replicate it at all. You're right that it uses the referrer to work out the URL, but FF does send the right header. I appreciate this was a while ago, but are you still seeing it?

**Comment by phistuck** [comment]
I reproduced this, but then I clicked on Refresh Firefox which deletes bad settings, add-ons and similar (even though I used a new profile, if I remember correctly - and I successfully reproduced it back then) and I can no longer reproduce this.
