### ISSUE TITLE
ES6/Babel Not Working?

### ISSUE THREAD

**Issue by mikeerickson** [jsbin/jsbin#2790]
Trying a simple test to see how ES6 works

```
const = new Date()
```

Produces following error:

http://d.pr/i/1irEi

Should I have to link to babel as well?

**Comment by mikeerickson** [comment]
Here is the URL for the problem bin

http://jsbin.com/ziyakiw/edit?html,css,js,output

**Comment by shri3k** [comment]
@michaelbragg: you might have to refresh your page after you've switched ES6/Babel. Your example works for me btw.
