### ISSUE TITLE
esnext option - where? how?

### ISSUE THREAD

**Issue by largeDachshund** [jsbin/jsbin#2792]
I'm new to jsbin.  Thanks for building this tool.  i'm trying to test some rxjs, but I'm getting this error: 

> arrow function syntax (=>)' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).

The help makes no mention of where this esnext option lives?  Am I supposed to select ES6/babel?  

I can't find "moz" either.

It would be nicer to have a more verbose message to direct the user.  

Thanks,

**Comment by remy** [comment]
Your errors have nothing to do with jsbin, they're coming from what ever library you're using. If you want to use Babel, select it from the JavaScript panel. Otherwise you may want to raise this issue again the library you're using if you're having trouble with it.

**Comment by jeantimex** [comment]
For me, I choose ES6/Babel, go to account settings -> preferences -> linting -> jshint, and add the following rules:
```javascript
{
  "esnext": true
}
```
and it works for me.

**Comment by Spiralis** [comment]
Eh. I can see no rules above...

**Comment by 0x0936** [comment]
Using jsbin without logging in, add a comment at the top of the JavaScript panel `//jshint esnext:true`

**Comment by josephrocca** [comment]
Relevant parts of [jshint documentation](http://jshint.com/docs/options/):

![image](https://cloud.githubusercontent.com/assets/1167575/20593309/f38d75fc-b285-11e6-9442-859bc24768f7.png)


![image](https://cloud.githubusercontent.com/assets/1167575/20593290/e360d8ae-b285-11e6-9f80-c91390a25ec4.png)

Newer `esversion` syntax doesn't seem to work in jsbin. Old `esnext` option does, but it's a bit buggy for me (I get weird "missing semicolon" errors).

**Comment by seanohue** [comment]
Agreed, especially if the editor is set to Babel/ES6.

**Comment by ivan-zakharchuk** [comment]
Common, it's definitely a UX issue if you open this tool for the first time. Just put this piece of information or link to the tooltip or make it even smarter by asking the user to automatically change its jsHint config on changing script type.

**Comment by unnikrishnanrp** [comment]
Add the following line in the beginning of JS Bin JavaScript editor:

`/* jshint esnext: true */`

**Comment by technotomahi** [comment]
Please recheck if you are using the console or the output window for the result.

**Comment by tkahmedkamal** [comment]
> For me, I choose ES6/Babel, go to account settings -> preferences -> linting -> jshint, and add the following rules:
> 
> ```js
> {
>   "esnext": true
> }
> ```
> 
> and it works for me.

Thank you

**Comment by codebuilderspk** [comment]
Add the following line in the beginning of JS Bin JavaScript editor:
/* jshint esversion: 6 */

These configurations come from [JShint](https://jshint.com/docs/options/#esnext)

**Comment by mary20218** [comment]
Thank you !!!

**Comment by kokogee** [comment]
Thank You.

**Comment by johnaweiss** [comment]
only esnext style works for me.

**Comment by Instrumedley** [comment]
Not even with /* jshint esnext: true */ line added
I click in Run on console window, nothing happens. Get a bunch of errors on my console
I'm using Chrome Version 83.0.4103.116 (Official Build) (64-bit)
