### ISSUE TITLE
npm install -g jsbin (SQLlite3 Error)

### ISSUE THREAD

**Issue by clement360** [jsbin/jsbin#2793]
running npm install -g jsbin ends in the following error:

> npm WARN In sqlite3@2.2.7 replacing bundled version of readable-stream with readable-stream@1.0.34
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "jsbin"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

> npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1

Any ideas of how to get this thing going, Thanks!

**Comment by remy** [comment]
Node 6 isn't supported

**Comment by 100ideas** [comment]
If you can install [nvm](https://github.com/creationix/nvm), then the following should work:

```bash
> nvm install v0.10.26 
   ...
> nvm use v0.10.26 
   Now using node v0.10.26 (npm v1.4.3)
> npm install
   ...
   Done, without errors.
```

If everything installed correctly, you should be able to start jsbin with `./bin/jsbin`.

Npm installed `connect` in `./node_modules` but `express` couldn't find it for some reason when I tried to start jsbin.

```bash
> ./bin/jsbin                                                            
   Config from /Users/macowell/dev/node/jsbin/lib/config.local.json

   module.js:340
      throw err;
      ^
   Error: Cannot find module 'express/node_modules/connect'
```

`> cd ./node_modules/express; npm install` fixed it for me.
 
also see:
- https://github.com/jsbin/jsbin/issues/2672
- https://github.com/jsbin/jsbin/pull/2561
