### ISSUE TITLE
Live Update Output doesn't catch onunload / onbeforeunload Events

### ISSUE THREAD

**Issue by seanpoulter** [jsbin/jsbin#2795]
While trying to implement an auto-save on exit, I realized that the live update `iframe` did not respond to the usual DOM events like `window.onbeforeunload`. From what you understand from DOM events, would it be possible to post the `render` message to the `iframe#live` and bubble up to the runner? Could it be captured that way?

While I re-architect things to save after domain changing Events, I'll switch to the manual <kbd>Ctrl</kbd>-<kbd>Enter</kbd> to update.

**Comment by remy** [comment]
I don't see the point of auto-save on exit since all the code is saved as the user types - therefore there's only extremely slim situations (when the user codes and immediately quits) that this could happen...

**Comment by seanpoulter** [comment]
Ah, sorry for the confusion and missing your reply a while ago @remy. The issue wasn't supposed to be a feature request to save as the user types, but rather different behaviour than I expected using `window.onbeforeunload` in my own JavaScript.

I realize that some example code would have really helped. Here is a very simple example to demonstrate that the live-reloading bypasses the `window.onbeforeunload` hook, and does **not** increment the counter that is output on the console.
https://jsbin.com/lebesal/3/edit?html,js,console,output
