### ISSUE TITLE
javascript in my jsbin is missing

### ISSUE THREAD

**Issue by thujone** [jsbin/jsbin#2802]
Hi, last night at around 2 a.m. Pacific Time, I had finished some javascript code on a JSBin I was doing for a job interview. I'm trying to look at it this morning, and it seems to be missing entirely. I'm not sure what happened, but I spent a few hours on this code. Is there any way I can get the js back?

https://jsbin.com/wehoha/edit?js,console,output

**Comment by thujone** [comment]
I was able to get the code from a snapshot. Still wondering what happened, but at least i didn't lose my code. Thanks...

**Comment by remy** [comment]
So…was the code lost or not? I'm a little confused.
