### ISSUE TITLE
Production install - Code-casting is not working

### ISSUE THREAD

**Issue by spdustin** [jsbin/jsbin#2805]
I can confirm that the EventStream of a watcher is receiving data. e.g.:

`Id: 0, Type: css:, Data: body {background: red;}`
`Id: 0, Type: css:processed, Data: body {background: red;}`

But the pane doesn't update.

*Edit - Additional information:*

If I simply reload the page from the watcher's browser (anonymous user), I do not see the changes made by the editor. If I copy the URL and load in a new tab, I do see the changes.

**Comment by spdustin** [comment]
More info:

If I open the *eventsource* directly in a new tab, e.g. `/deg?0.37627764842583855`, I do in fact see live changes happening there. It's just not happening in the output tab on the codecast page.

**Comment by remy** [comment]
The problem is that the jsbin.state.live isn't being set. I've not got
further than that yet though.

**Comment by spdustin** [comment]
Reverting back to **3.35.13** resolves the issue, which lays the blame at the new service worker code, it would seem. I can look into it further (likely) tomorrow

**Comment by remy** [comment]
Grab the latest code. I fixed it. Thanks though—you got pretty close :)
