### ISSUE TITLE
Problem taking my debit card

### ISSUE THREAD

**Issue by alexoviedo999** [jsbin/jsbin#2806]
I'm trying to update my pro account payment with a new debit card and it tells me that the number is incorrect.  I've tried using my wife's debit card as well and I'm getting the same error.  Suggestion: implement Paypal payment services.  Please advise as to how to best set up my payments.

**Comment by eliapplethetech** [comment]
Possibly related to #2810?

**Comment by remy** [comment]
I think I know what's going on here. @alexoviedo999 can you confirm that the card you're using **does not** end with `···· 2087`? I believe this was an old card, but you're trying to use a new card, but behind the scenes Stripe is never making use of the new details (due to a bug on my side).

**Comment by remy** [comment]
This issue has been auto-closed with a commit I just landed, but I'm 99% sure that the update will fix this issue entirely (I hope!).

If you want to give it another go, I believe it'll go through. Let me know how you get on.
