### ISSUE TITLE
Trying to upgrade to pro, but all cards are declined

### ISSUE THREAD

**Issue by clln** [jsbin/jsbin#2810]
Tried three different cards to upgrade to pro and all were declined. Made attempts using both Chrome and Safari – my Safari install has no extensions/blockers.

**Comment by remy** [comment]
@clln I'll try to look up your details in stripe to see what's going on. Are the cards the same type (i.e. visa, etc)?

**Comment by remy** [comment]
@clln I'm going to drop you a direct email as I want to confirm a few bits about your card. I have a feeling I know what's going on but it needs a few more insights before I can go ahead and fix anything.

**Comment by remy** [comment]
This issue has been auto-closed with a commit I just landed, but I'm 99% sure that the update will fix this issue entirely (I hope!).

If you want to give it another go, I believe it'll go through. Let me know how you get on.
