### ISSUE TITLE
Include support for Moment 2.14.1 

### ISSUE THREAD

**Issue by arasu01** [jsbin/jsbin#2813]
I have used the JSBIN to test my javascript code (https://jsbin.com/xogipabapi/edit?js,console). But when executing the functions I found need for moment file to be include.
The version support in JSBin is 2.10.6 but i require 2.14.1.

Please let me know how to include the support for moment 2.14.1 or please let me know when JSBin will support it?

Thanks

**Comment by remy** [comment]
Here's how to update it in a pull request: https://github.com/jsbin/jsbin/pull/2593/files

Should be simple enough. Good luck, and do raise the PR and I'll merge and release when I have a moment.

**Comment by arasu01** [comment]
Done. https://github.com/jsbin/jsbin/pull/2828
