### ISSUE TITLE
Auto clear & run in console

### ISSUE THREAD

**Issue by saintcrawler** [jsbin/jsbin#2815]
It would be nice if in `console` window there will be another button which clears the console and runs the script on its change.

**Comment by remy** [comment]
This has been asked for before, and the reasons for not implementing are the same: it would pollute the console as you typed making it near useless.

Regarding clearing: either use `console.clear()` or cmd+L

**Comment by saintcrawler** [comment]
1) How can it pollute the console if the console will be renewed after each keypress?
2) That is the current behavior (polluting the console) if you have both `console` and `output` windows at the same time, and in the output window you have selected `Auto-run JS`
