### ISSUE TITLE
Bin naming

### ISSUE THREAD

**Issue by mhigley** [jsbin/jsbin#2817]
Hey Remy. Been a long time fan of your work and I'm now in a position to share the knowledge that I've learned along the way to a fresh crop of students. I've begun heavily utilizing JSBin as script embeds into my instructional documentation but find the naming convention of the bins is still exceedingly vague. The pronounceable URLs are great and all, but confidently identifying a bin without previewing it is difficult. There is a short snippet of the first line or two of text as a helper to identify it, but how about reflecting the <title> tag instead. Or maybe somewhere to edit bin meta data? Is there already a solution in the works? Or am I the only schmuck with poor organizational skills?

**Comment by remy** [comment]
Have you tried adding a meta description element to your markup? I can't
remember if that does the trick or not, but I'd start there.

**Comment by mhigley** [comment]
Freakin' good show man! You're a poet and a scholar, and it's an absolute honor to have you respond to me. You've cemented my pro membership. At least until something better comes along.  *wink wink* :)

Cheers mate!
