### ISSUE TITLE
dynamically loaded embed links do not hydrate to iframes

### ISSUE THREAD

**Issue by jayphelps** [jsbin/jsbin#2819]
If you're using a single-page app style system (in my case, [gitbook](gitbook.com)) any embed links you create after DOMContentLoaded will not hydrate to iframes.

This is because the embed does not set up any sort of interval or mutation observer and if you include the script on the page again, along side the link, it is effectively a noop because of `if (window.jsbinified !== undefined) return;`.

Any suggestions besides hardcoding the iframe directly or is that indeed the best option?

You can demo this by visiting http://redux-observable.js.org/docs/recipes/Cancellation.html, noticing the JSBin embed, then click on the "Error Handling" section on the left hand side, under "Recipes".

**Comment by remy** [comment]
You're right, the embed script isn't watching for new elements being inserted. I wonder if the `embed.js` could be upgraded to expose some kind of API to create this…

But for now, I'd recommend making an iframe and simply replace the `/edit` in the URL for `/embed`. Not ideal I appreciate.

**Comment by jayphelps** [comment]
I was thinking about an API too..but didn't suggest simply because it's not ideal in my use case 😆 

Perhaps exposing an API, but if you reload the script again (usually meaning you have yet another embed) it invokes the `readLinks()` from the API for you before returning? That seems like a decent solution, giving people the power to just copy-pasta embed sources or if they want more explicit control, invoke the API themselves to hydrate.

**Comment by jayphelps** [comment]
In case someone stumbles on this issue..I worked around it for now by `delete window.jsbinified` after we transition away to a new page, which will let them embed script reinitialize things. Be careful about this technique though, because if the older embeds are still on the page it may cause issues; I'm not sure cause I don't have that use case.

For gitbook, it meant using the [addcssjs plugin](https://www.npmjs.com/package/gitbook-plugin-addcssjs), having it inject this "loadLoad" script:

```js
window.gitbook = window.gitbook || [];
gitbook.push(function () {
  gitbook.events.on('page.change', function () {
    delete window.jsbinified;
  });
});
```

**Comment by remy** [comment]
Wondering if it makes more sense just to expose the `embed` method to allow
you to drop in new anchor elements to initialise the frame.
