### ISSUE TITLE
ECMAScript6 support

### ISSUE THREAD

**Issue by greatpie** [jsbin/jsbin#2820]
When I try to write ES6,it will comes to "Line 1: 'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).". So,does Jsbin support ES6?

**Comment by remy** [comment]
It's a linting warning. 

JS Bin is running in your browser, and if your browser supports ES6, then yes, it does (though, technically, ES6 is a big collection of things, and there's no real "supporting ES6", it will support a sub-set of ES6).

If you go to your preferences, you can add the jshint rule that says `"esnext": true`.
