### ISSUE TITLE
Add library script tag placement [feature request]

### ISSUE THREAD

**Issue by pravinweb** [jsbin/jsbin#2821]
Hello,

Thanks for this great tool and really useful!

Bug environment:
Chrome: Version 51.0.2704.103 (64-bit) Mac OSX El Capitan

Bug Description and step:
1) Created new jsbin
2) place your cursor in 'HTML' section below title element
3) Click on add library > add any library for ex: RequireJS
4) It include library just below head element and not below title element 

Expected behaviour:
library should be included where you had placed cursor before adding library.

Many Thanks
Pravin

**Comment by remy** [comment]
Thanks. Happy to take a feature PR to update this.

**Comment by remy** [comment]
Details of feature request:

- Insert the library selected at the cursor position, not detected from the head element

**Comment by alanyjw** [comment]
@remy I would like to work on this. However, it seems like there isn't any tests written. Should I add one for this PR?

**Comment by remy** [comment]
Definitely go for it. Yep, tests are a MAJOR weakness on this project. Any
tests added would be great (prefer tap), though I don't even know how you'd
begin to test with code mirror in the project...

**Comment by alanyjw** [comment]
@remy I've made a fix. My initial plan was to come up with unit tests for the code. But I feel that it is too cumbersome to test, since it depends on global state.

Having said that, I feel that #2124 would be a better approach to testing and I'm keen to look into that 😄

**Comment by pravinweb** [comment]
Works Fine Thanks
