### ISSUE TITLE
Save autorun as part of state

### ISSUE THREAD

**Issue by ShadSterling** [jsbin/jsbin#2823]
I was using JSBin to debug a problem with a downloading library, and turned off autorun to avoid constantly downloading files.  Unfortunately, every time I share or return to [the URL](https://jsbin.com/zacapa/edit?html,js,output) autorun is turned back on.  The instant download is an unpleasant surprise to people who opened the link in a new tab while reading about the problem.  Since there isn't a URL query option to force the initial state, it should be remembered along with the content.

**Comment by remy** [comment]
Auto run is a user preference, rather than a bin preference.

I appreciate the problem you're facing with this particular bin. But I do
see this as an edge case.

**Comment by abhisekp** [comment]
It would be nice to have a query string such as **`?autorun=false&lineno=true`** to force some preference while sharing the url.

**Comment by abhisekp** [comment]
Also it would be nice to see theme and line number preference be available for non-logged in users

> [![](http://i.imgur.com/2h4Q3K2.png)](http://i.imgur.com/2h4Q3K2.png)

**Comment by remy** [comment]
You can share line numbers by clicking on the gutter and sharing the link: https://jsbin.com/capepa/edit?js,output

Anything that comes under "it would be nice", if you want to start a PR, you're welcome to. It's worth coordinating your work with me (as I lead the project) so that it's got a good chance of being merged.

**Comment by abhisekp** [comment]
woah! Line numbers can be toggled by double clicking the **Processor** choice dropdown link :smiley: 

Nice :sparkles:
