### ISSUE TITLE
Why won't my function run? 

### ISSUE THREAD

**Issue by dfrho** [jsbin/jsbin#2824]
I'm sure it's a feature and not a bug. See attached. I keep getting 316px as output if I don't do the console.log() statement. I clicked "Run with JS" Thanks.
![js_bin_-_collaborative_javascript_debugging](https://cloud.githubusercontent.com/assets/3064557/17074630/5f380eae-504b-11e6-9e4d-74a43ea77f95.png)

**Comment by remy** [comment]
The 316px is the size of the output window, and not part of the HTML output.

The output window it the rendered output, and you don't have any body in your HTML, so I suspect you actually want the console (since you're logging out).

**Comment by dfrho** [comment]
Nope not closed. I wanted to know how to run pure JS. It doesn't show in
the console. Please reopen and answer my question?
David

**Comment by remy** [comment]
Can you share the URL that doesn't log in the console?

**Comment by dfrho** [comment]
It's working now, not sure why. No worries - I just cut and paste the
problem into repl.it which works fine.
David

**Comment by remy** [comment]
Hey, I replicated your bin from the code I could see in the screenshot and I didn't get the issue you were seeing before: https://jsbin.com/cumuces/edit?js,console (note that I have the console panel open, not the rendered output panel, as your screeshot did). Screen for reference:

<img width="1000" alt="screen shot 2016-07-25 at 22 05 47" src="https://cloud.githubusercontent.com/assets/13700/17117480/159a357c-52b4-11e6-8697-07ef00a21406.png">

**Comment by Bheki-Ntanzi** [comment]
hi
Has this issue been fixed, cause i am having the same problem, "run" function does not work :)
Thanx

**Comment by malikburhanm** [comment]
Same I am having the same issue
