### ISSUE TITLE
I may have been spam blocked.

### ISSUE THREAD

**Issue by AaronCZim** [jsbin/jsbin#2825]
I was redo'ing a bunch of times by holding down ctrl-y. After that I got an red warning at the top of the page saying the file failed to be archived. I tried reloading the page several times, but I can't get back into JS Bin at all. I'll try not to do any operations like holding down ctrl-y or z, but there really should be some kind of limiter (if you use RxJS, a debounce(2000) on archiving would do the trick). I don't feel like I did anything wrong. Alternately, there may also be a bug that occurs if you try to redo an action that hasn't been done. It's not likely, but I thought I should bring it up.

**Comment by remy** [comment]
The jail only last 10 minutes IIRC, but give it a check again now and if
it's still blocked drop me an email at support@jsbin.com with your IP and
I'll take a look.

**Comment by abhisekp** [comment]
@AaronCZim try using <kbd>**CTRL**</kbd>+<kbd>**SHIFT**</kbd>+<kbd>**Z**</kbd> to undo.

**Comment by remy** [comment]
@abhisekp it's likely this user is referring to the [fail2ban blocking that's in place on jsbin](https://remysharp.com/2015/09/14/jsbin-toxic-part-1#fail2ban)

**Comment by abhisekp** [comment]
> I was redo'ing a bunch of times by holding down ctrl-y. 

@remy they were banned because they used <kbd>**CTRL**</kbd>`+`<kbd>**Y**</kbd> instead of <kbd>**CTRL**</kbd>`+`<kbd>**SHIFT**</kbd>`+`<kbd>**Z**</kbd> to redo.
