### ISSUE TITLE
`console.assert()` seems to log out instead

### ISSUE THREAD

**Issue by paulcuth** [jsbin/jsbin#2833]
`console.assert()` appears to be behaving the same as `console.log()`, instead of evaluating the first argument and only outputting the second if the first is falsy. For example:

```
var a = 1;
console.assert(a === 1, 'a should be one');
console.assert(a === 2, 'a should be two');
```

Expected result (in console):

```
"a should be two"
```

Actual result:

```
true
"a should be one"
false
"a should be two"
```

**Comment by remy** [comment]
Happy to take a PR that adds this functionality.

**Comment by elderfo** [comment]
Submitted PR #2951 for this

**Comment by sanjsanj** [comment]
@remy Since PR #2951 was merged in does that mean this issue is resolved or is it still open?

**Comment by remy** [comment]
@sanjsanj 👍
