### ISSUE TITLE
[bug] JSHint wonky

### ISSUE THREAD

**Issue by abhisekp** [jsbin/jsbin#2837]
I've the following JSHint config with **`asi:true`** but it doesn't work. I've to manually add **`// jshint asi:true`** to make it work.
I've been having this issue since a year but never had the courage to file an issue.

### JSHint Config

```json
{
  "globals": {
    "_": true,
    "jquery": true,
    "fp": true,
    "lodash": true
  },
  "globalstrict": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "esversion": 6,
  "forin": false,
  "freeze": true,
  "immed": true,
  "newcap": true,
  "noarg": true,
  "nonbsp": true,
  "nonew": true,
  "undef": true,
  "unused": false,
  "strict": true,
  "debug": true,
  "sub": true,
  "browser": true,
  "couch": true,
  "devel": true,
  "jquery": true,
  "node": true,
  "worker": true,
  "esnext": true,
  "asi": true <---------------------------------
}
```

### Screenshots
> [![](http://i.imgur.com/7SshUUw.png)](http://i.imgur.com/7SshUUw.png)
[![](http://i.imgur.com/02sUTdj.png)](http://i.imgur.com/02sUTdj.png)

### Demo
:point_right: **https://jsbin.com/hupobaq/1/edit?js,output**

**Comment by remy** [comment]
Can you explain what this means (the rest I follow): 
<img width="266" alt="screen shot 2016-08-06 at 12 31 08" src="https://cloud.githubusercontent.com/assets/13700/17456510/afc1a5c4-5bd1-11e6-89c0-3ea29a82481b.png">

**Comment by abhisekp** [comment]
@remy well, I see the word "Processor" there instead of the processor I'm using now.
Previously, it was showing JavaScript or ES6, etc.
It was helpful and now it just says *Processor*. Doesn't look good :worried: 

btw, I like the new UI font. :+1:

**Comment by remy** [comment]
The processor being used is here (at the other end of your arrow):

![https://camo.githubusercontent.com/fccf9894892eaf2da24b48687f0e9052426d49b2/687474703a2f2f692e696d6775722e636f6d2f486d75693967462e706e67](https://camo.githubusercontent.com/fccf9894892eaf2da24b48687f0e9052426d49b2/687474703a2f2f692e696d6775722e636f6d2f486d75693967462e706e67)

**Comment by abhisekp** [comment]
@remy yes but why not also show it there?
From UX perspective, it adds more meaning to the current pane if shown in the dropdown list too.

As of now, It is not easy to reason that the current pane is for HTML, CSS or JS.
Currently, my brain does a linear search to match the opened panes to the highlighted menu.
But the UX should be obvious on the first look (*even without any code in the pane*).

**Comment by remy** [comment]
Let's see how it goes. I appreciate a change to the familiar might not be always welcome. I can of course revert it back if it isn't clear. This could have also been a cog, ala the github labels and milestones.
