### ISSUE TITLE
[bug] Export as gist creates anon gist

### ISSUE THREAD

**Issue by abhisekp** [jsbin/jsbin#2838]
I've github linked but when I **Export as Gist**, it always creates an anonymous gist.

> [![](http://i.imgur.com/ZIE4uCb.png)](http://i.imgur.com/ZIE4uCb.png)

**Comment by remy** [comment]
Yeah…this is already open elsewhere. This "third party link" is primarily for your log in. I'm going to close this in favour of keeping it in a single thread #2757
