### ISSUE TITLE
[missing-feature] Custom library

### ISSUE THREAD

**Issue by abhisekp** [jsbin/jsbin#2839]
I read through http://jsbin.com/help/adding-custom-libraries 
I get excited
I open devtool
`console.log(typeof libraries) // 'undefined'` :expressionless: 

How do I add custom libraries?
I want to add the following snippet of code when I click **Lodash FP Latest** menu item. (*after addition*)

```html
<script src="https://cdn.jsdelivr.net/g/lodash@4.13.1(lodash.min.js+lodash.fp.min.js)"></script>
<script>
  window.fp = _.noConflict()

  // Globally available functions
  // (comment on production)
  Object.assign(window, fp)

</script>
```

**Comment by remy** [comment]
I'm not sure why I'm seeing something different, but can you double check. This is what I see when I look for `libraries` in the devtools (and I also see the `.add` function):

<img width="1082" alt="screen shot 2016-08-07 at 07 06 58" src="https://cloud.githubusercontent.com/assets/13700/17460823/a396799a-5c6d-11e6-9e02-7fd2e637ce14.png">

**Comment by abhisekp** [comment]
@remy I got it working trying it many times both in normal and incognito.

Anyway, I added the script successfully.
Is there any way to add the following too?
```js
<script>
  window.fp = _.noConflict()

  // Globally available functions
  // (comment on production)
  Object.assign(window, fp)

</script>
```

**Comment by remy** [comment]
Yeah, I think so…maybe. Check the source of libraries.js and library.js,
there's a couple of examples that add some extra bits similar to what you
want to do.

**Comment by abhisekp** [comment]
:smile: :smile: :smile: Thanks

```js
var lodash = {
  "url": "https://cdn.jsdelivr.net/g/lodash@4.13.1(lodash.min.js+lodash.fp.min.js)",
  "group": "Lodash",
  "label": "Lodash-fp Latest",
  "snippet": "<script>\n\twindow.fp = _.noConflict()\n\t// Globally available functions\n\t// (comment on production)\n\tObject.assign(window, fp)\n</script>"
}
```

----
@remy May I submit a PR for updating lodash and also adding the lodash fp and grouping it as "Lodash"?

**Comment by remy** [comment]
Please do update lodash. What's 'lodash fp'?

**Comment by abhisekp** [comment]
@remy lodash fp is the functional variant of lodash similar to Ramda **https://github.com/lodash/lodash/wiki/FP-Guide**
