### ISSUE TITLE
JS-loop prevention code insertion is confused by "}" string

### ISSUE THREAD

**Issue by AmeliaBR** [jsbin/jsbin#2844]
`SyntaxError: Unexpected token catch` caused by JSBin inserting extra code incorrectly.

[Demo case](http://jsbin.com/jubawocire/1/edit?js,console,output)  
Be sure to use Dev tools to check the JS that's actually getting sent to the browser.

I'm assuming the extra code you're inserting is to prevent infinite loops that cause the browser to hang (very kind of you).  Unfortunately, you're using some slightly too simplistic regEx-ing to figure out where to add your closing `}`.  Instead of adding it after the closing brace in my for loop, it's added in after a "}" in a string.  Result, unbalanced braces, and syntax error.

**Comment by remy** [comment]
I'm not using regexp to do the work, unreliable for this kind of stuff. But
it's certainly simplified compared to the 700K AST :) You can side step by
adding `// noprotect` and it won't kick in.

If I can, I'll file against the loop-protect repo and fix.

**Comment by AmeliaBR** [comment]
The demo case (link in the original post) is still showing the error.

**Comment by remy** [comment]
You're right it's broken in current jsbin, but new-jsbin is good:

<img width="1390" alt="screen shot 2018-01-19 at 23 04 28" src="https://user-images.githubusercontent.com/13700/35175760-28e3d18c-fd6d-11e7-99c6-4984f0c05dec.png">

The old loop protection has been deprecated and won't be supported, so I'm going to close this issue as fixed (and hopefully live very soon!!!!).

(also, if you want to try out new-jsbin - open your browser's console - there's a cheat mode to try it out 😄 )

**Comment by AmeliaBR** [comment]
Awesome! I hadn't realized that the new changes hadn't rolled out yet. All good, then.
