### ISSUE TITLE
Underscore library not defined

### ISSUE THREAD

**Issue by pravinweb** [jsbin/jsbin#2850]
Example
https://jsbin.com/vayarixovo/edit?html,js,console

Bug Reproduce Environment
Mac OSX El Capitan Chrome Latest

Bug Reproduce Steps
1) create new jsbin
2) add library underscore.js
3) when you use underscore it gives error of undefined - 'the content must be served over HTTPS'

Note:
When I added underscore manually - 'https://underscorejs.org/underscore-min.js' it works fine

Thanks,
Pravin

**Comment by remy** [comment]
Hmm, you said it works fine: https://underscorejs.org/underscore-min.js but this is what I see:

<img width="928" alt="screen shot 2016-08-18 at 14 13 24" src="https://cloud.githubusercontent.com/assets/13700/17774936/f09c9524-654d-11e6-82d5-43fb36b1c8a2.png">

Can I suggest you (or someone) raise a pull request to remove and fix the URL to underscore (I don't manage these myself as they're community contributed): http://jsbin.com/help/adding-libraries

**Comment by pravinweb** [comment]
Hi Remy,

I have raised this with underscore team - https://github.com/jashkenas/underscore/issues/2578

Thanks
Pravin

**Comment by mark-williams** [comment]
It worked for me when I refertenced version 3 from the jsbin _add library_ dropdown, resulting in the following script tag:

`<script src="https://cdn.jsdelivr.net/lodash/3/lodash.min.js"></script>`
