### ISSUE TITLE
Can't share bins

### ISSUE THREAD

**Issue by bl4ckdu5t** [jsbin/jsbin#2854]
![jsbin screenshot](https://i.gyazo.com/8d11cabc981f2c5aec951857cb333c32.png)
From the screenshot above I created a new bin and when I couldn't find a share menu I thought my URL would be automatically updated to a sharable one but there it is with no custom url to share. Then I tried `jsbin.com/myusername/last` and got a 404 because even `/myusername` returns a 404.

**Comment by bl4ckdu5t** [comment]
I derived from the console that the save script returns a 500 header
![500 Error console log](https://i.gyazo.com/dbe2fab117facbfd0795c21c2e4489bf.png)

**Comment by remy** [comment]
I can see from the screenshot it didn't work. What was the content of the
html you were trying to save with? And does it still happen?

**Comment by bl4ckdu5t** [comment]
I created a new bin in a different browser (Safari) and copied the contents from Chrome in there since that had a URL. The HTML content is [here](https://jsbin.com/qohupiw/edit?html,css,js,output)
