### ISSUE TITLE
Export as gist publish as anonymous

### ISSUE THREAD

**Issue by RandallFlagg** [jsbin/jsbin#2856]
When ever I publish a gist it is published as anonymous although I am logged in using github

**Comment by andzi** [comment]
Agree, it should be **explicitly noted or fixed** (if not intended behaviuor), because it's risk to _leave and forget_ that exported peace of code.
Also it would be usefull to mark as **exported**.

**Comment by RandallFlagg** [comment]
+1 for this

> Also it would be usefull to mark as exported.

**Comment by iriand** [comment]
+1
