### ISSUE TITLE
My credit cards keep declining despite being valid with plenty of funds?

### ISSUE THREAD

**Issue by Deanb100** [jsbin/jsbin#2861]
Hi I've just attempted several times to make payments via my Amex card and then received an alert from Amex to confirm if the transaction was legitimate or not.  I confirmed it was and as suggested I re-tried but the transaction was declined a couple more times.  I then tried my two Visa cards and both declined.  Note, all cards have more than sufficient funds available.  Is this some sort of blocking via Stripe or your website due to Amex initially suspecting fraud?  Please advise how I resolve this.
Regards, Dean 
deanb100@gmail.com  (Note I'm joining as part of my General Assembly web development immersive training course in Melbourne, Australia)

**Comment by remy** [comment]
Going to close, I believe this was sorted in the end.

**Comment by Deanb100** [comment]
Confirmed all sorted thanks.

Dean
