### ISSUE TITLE
Output pane only shows size

### ISSUE THREAD

**Issue by kirstyannepollock** [jsbin/jsbin#2862]
The Output pane doesn't show anything - even when I click "Run with JS" only adds some size info. (e.g. 465px).

I am not sure what could be wrong?

Chrome Version 52.0.2743.116 m (64-bit)  on Windows 8.1

![jsbin issue](https://cloud.githubusercontent.com/assets/15169282/18013599/150a2bde-6bbf-11e6-90ff-9052eccbb769.PNG)

**Comment by remy** [comment]
Your html is empty. So it's correctly rendering an empty page.

**Comment by kirstyannepollock** [comment]
Oh my, do I feel stupid. Of course. I thought I had the something in the body, but I've only the title in the head. Thanks!
