### ISSUE TITLE
Theme does not work; code syntax highlight does not work while logged in

### ISSUE THREAD

**Issue by naknode** [jsbin/jsbin#2863]
![image](https://cloud.githubusercontent.com/assets/616320/18020833/32209fac-6ba9-11e6-92b3-a94b1b99fbe5.png)

No matter what Editor theme I select, it does not change.
And the syntax highlight neither. The syntax highlight DOES work when I am logged out of my GitHub user.

What a strange bug...

**Comment by remy** [comment]
Can you click the jsbin logo, and see if you have "texterea mode" checked or not. You'll want it unchecked if you want highlighting and themes to work.

**Comment by naknode** [comment]
Oh, wow. I didn't know that. Thank you!
