### ISSUE TITLE
Error: Unexpected token if 'for' in Error constructor

### ISSUE THREAD

**Issue by jakub-gawlas** [jsbin/jsbin#2864]
If word `for` before expression in template strings which passed to Error constructor then occurs an error:

```
"SyntaxError: Unexpected token ;
    at https://static.jsbin.com/js/prod/runner-3.39.14.min.js:1:13926
    at https://static.jsbin.com/js/prod/runner-3.39.14.min.js:1:10855"
```

Example code generates above error:

```
const foo = 'bar'
const err = Error(`Foobar for ${foo} bar`)
```

Example templates strings works correct:

```
`Foobar fork ${foo}`
`Foobar for ${foo} for`
`for Foobar for ${foo}`
```

Error is not present with ES6/Babel transpiler.

Browsers: Firefox 48.0.1, Chrome 52.0.2743.116 (64-bit)

**Comment by remy** [comment]
Can you use `// noprotect` to work around the problem.
