### ISSUE TITLE
 Cannot find module "\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node"

### ISSUE THREAD

**Issue by jasonleft** [jsbin/jsbin#2868]
My node version is `4.2.3`
I use git clone to download the src code, and then `npm install` ,then `cd jsbin & node bin/jsbin JSBIN_CONFIG=./config.local.json`, Meet error!
Then i look up `node_modules\sqlite3\lib\binding\node-v46-win32-x64\` directory, no `node_sqlite3.node` found, what i should do next ?
^_^

**Comment by jasonleft** [comment]
`WIN 7` os

**Comment by remy** [comment]
Node 4 is not supported.

**Comment by jasonleft** [comment]
uh...what a pity.
