### ISSUE TITLE
error installng on Linux mint 17KDE

### ISSUE THREAD

**Issue by Blessings9** [jsbin/jsbin#2870]
encoutered the following error when install JSBIN

┌─[±][master ✓][jsbin][]
└─▪ npm install

> jsbin@3.39.14 postinstall /home/coder/Developer/jsbin
> grunt build && npm run selenium:install

Running "concat:dist" (concat) task
File "public/js/prod/jsbin-3.39.14.js" created.

Running "concat:runner" (concat) task
File "public/js/prod/runner-3.39.14.js" created.

Running "uglify:dist" (uglify) task
File "public/js/prod/jsbin-3.39.14.min.js" created.

Running "uglify:runner" (uglify) task
File "public/js/prod/runner-3.39.14.min.js" created.

Running "uglify:embed" (uglify) task
File "public/js/embed.min.js" created.

Running "uglify:addons" (uglify) task
File "public/js/prod/addon-tern-3.39.14.min.js" created.

Done, without errors.

> jsbin@3.39.14 selenium:install /home/coder/Developer/jsbin
> selenium-standalone install

sh: 1: selenium-standalone: not found

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "selenium:install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jsbin@3.39.14 selenium:install: `selenium-standalone install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jsbin@3.39.14 selenium:install script 'selenium-standalone install'.
npm ERR! This is most likely a problem with the jsbin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     selenium-standalone install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsbin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jsbin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/coder/Developer/jsbin/npm-debug.log

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! jsbin@3.39.14 postinstall: `grunt build && npm run selenium:install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsbin@3.39.14 postinstall script 'grunt build && npm run selenium:install'.
npm ERR! This is most likely a problem with the jsbin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build && npm run selenium:install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsbin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jsbin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/coder/Developer/jsbin/npm-debug.log
┌─[±][master U:1 ?:1 ✗][jsbin][]
└─▪ sudo npm install
[sudo] password for coder: 
Sorry, try again.
[sudo] password for coder: 
npm WARN cannot run in wd jsbin@3.39.14 grunt build && npm run selenium:install (wd=/home/coder/Developer/jsbin)
npm WARN cannot run in wd jsbin@3.39.14 npm run snyk-protect (wd=/home/coder/Developer/jsbin)
npm WARN unmet dependency /home/coder/Developer/jsbin/node_modules/snyk/node_modules/snyk-resolve-deps/node_modules/clite/node_modules/update-notifier/node_modules/configstore/node_modules/mkdirp requires minimist@'0.0.8' but will load
npm WARN unmet dependency /home/coder/Developer/jsbin/node_modules/snyk/node_modules/snyk-resolve-deps/node_modules/minimist,
npm WARN unmet dependency which is version 1.2.0
npm WARN unmet dependency /home/coder/Developer/jsbin/node_modules/sqlite3/node_modules/node-pre-gyp requires semver@'~2.3.0' but will load
npm WARN unmet dependency /home/coder/Developer/jsbin/node_modules/semver,
npm WARN unmet dependency which is version 5.3.0

**Comment by remy** [comment]
Hmm, we should make the selenium optional deps I think. CC @kirjs
