### ISSUE TITLE
Very poor performance in history view having many bins

### ISSUE THREAD

**Issue by cforsyth68** [jsbin/jsbin#2871]
**Preconditions:**
Having over 10,000 bins with many history items in each
Tested in IE 11

**Steps to reproduce:**
1. Browse to http://jsbin.com/
2. Log in with your github account
3. From the **File** menu choose **My Bins**

**Expected behavior:**
User interface should be responsive and it should be easy to scroll down the list. 

**Actual behavior:**
User interface is very slow, to a point where it is not at all usable. Clicking on the "archive" link next to items takes 10+ seconds each. Making it impossible for the end user to fix his own problem (presumably of having too many bins)

**Assumed problem**
It is likely that the problem is caused by having too many bins, the UI is not able to keep up.
This is likely a result of having too many registered events attached to too many DOM objects, event delegation would fix this

**Suggestion:**
Allow users to delete extraneous history items from saved bins in bulk (one at a time is impossible when response times are several seconds between actions)
Allow users to reduce the number of bins by deleting them in bulk
Paginate the results
Allow users to filter results to reduce the number of records on the page

**Comment by remy** [comment]
Event delegation is used. The problem is that bin is its own table and IE doesn't render that many tables well. Bulk delete is the answer, but, it's an edge case since the average bin count is down in the 50s, and there's only a handful of users with bin count this high.
