### ISSUE TITLE
my windoes is 64 bit so i have downloaded 6.5 version (64bit) node but still so many errors and jsbin not working 

### ISSUE THREAD

**Issue by desaisameer4u** [jsbin/jsbin#2875]
**what i should do please tell me soon**

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\SAM>npm install -g jsbin
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
C:\Users\SAM\AppData\Roaming\npm\jsbin -> C:\Users\SAM\AppData\Roaming\npm\node_
modules\jsbin\bin\jsbin

> sqlite3@2.2.7 install C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\node
_modules\sqlite3
> node-pre-gyp install --fallback-to-build

(node:1288) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
(node:1288) DeprecationWarning: child_process: options.customFds option is depre
cated. Use options.stdio instead.

C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\node_modules\sqlite3>if not
defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --name=sqlite
3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 -
-minor=2 --patch=7 --runtime=node --node_abi=node-v48 --platform=win32 --target_
platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=h
ttps://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users\SAM\AppData\R
oaming\npm\node_modules\jsbin\node_modules\sqlite3\lib\binding\node-v48-win32-x6
4 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v48-win32-x64.tar.gz --sta
ged_tarball=build\stage\sqlite3\v2.2.7\node-v48-win32-x64.tar.gz --hosted_path=h
ttps://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=http
s://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v48-win32-x64.tar.gz
 )  else (node "" rebuild --name=sqlite3 --configuration=Release --module_name=n
ode_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_
abi=node-v48 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x
64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.co
m/ --module_path=C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\node_module
s\sqlite3\lib\binding\node-v48-win32-x64 --remote_path=./sqlite3/v2.2.7/ --packa
ge_name=node-v48-win32-x64.tar.gz --staged_tarball=build\stage\sqlite3\v2.2.7\no
de-v48-win32-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.co
m/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/s
qlite3/v2.2.7/node-v48-win32-x64.tar.gz )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--nam
e=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2
.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v48" "
--platform=win32" "--target_platform=win32" "--arch=x64" "--target_arch=x64" "--
module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/"
 "--module_path=C:\\Users\\SAM\\AppData\\Roaming\\npm\\node_modules\\jsbin\\node
_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64" "--remote_path=./sqlite3/v2
.2.7/" "--package_name=node-v48-win32-x64.tar.gz" "--staged_tarball=build\\stage
\\sqlite3\\v2.2.7\\node-v48-win32-x64.tar.gz" "--hosted_path=https://mapbox-node
-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-
binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v48-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\node_modules\sq
lite3
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=sq
lite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major
=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v48 --platform=win32 --tar
get_platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --ho
st=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=C:\Users\SAM\AppDa
ta\Roaming\npm\node_modules\jsbin\node_modules\sqlite3\lib\binding\node-v48-win3
2-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v48-win32-x64.tar.gz -
-staged_tarball=build\stage\sqlite3\v2.2.7\node-v48-win32-x64.tar.gz --hosted_pa
th=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v48-win32-x64.ta
r.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\SAM\AppData\Ro
aming\npm\node_modules\jsbin\node_modules\sqlite3\node_modules\node-pre-gyp\lib\
util\compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SAM\
\AppData\\Roaming\\npm\\node_modules\\jsbin\\node_modules\\sqlite3\\node_modules
\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\node_m
odules\sqlite3
node-pre-gyp ERR! node -v v6.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=sqlite3 --configuration=Release -
-module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtim
e=node --node_abi=node-v48 --platform=win32 --target_platform=win32 --arch=x64 -
-target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s
3.amazonaws.com/ --module_path=C:\Users\SAM\AppData\Roaming\npm\node_modules\jsb
in\node_modules\sqlite3\lib\binding\node-v48-win32-x64 --remote_path=./sqlite3/v
2.2.7/ --package_name=node-v48-win32-x64.tar.gz --staged_tarball=build\stage\sql
ite3\v2.2.7\node-v48-win32-x64.tar.gz --hosted_path=https://mapbox-node-binary.s
3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.a
mazonaws.com/sqlite3/v2.2.7/node-v48-win32-x64.tar.gz' (1)
C:\Users\SAM\AppData\Roaming\npm
`-- (empty)

npm WARN In sqlite3@2.2.7 replacing bundled version of readable-stream with read
able-stream@1.0.34
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jsbin"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SAM\npm-debug.log
npm ERR! code 1

C:\Users\SAM>jsbin
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\SAM\AppData\Roaming\npm\node_modules\jsbin\b
in\jsbin'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

C:\Users\SAM>

**Comment by remy** [comment]
Jsbin only supports node#0.10
