### ISSUE TITLE
Tab key does not produce whitespace (JS pane)

### ISSUE THREAD

**Issue by dhenson02** [jsbin/jsbin#2877]
Pressing tab does not produce any space or tab character(s) no matter where in the code it is pressed.  Some places will generate the auto-complete menu but it is inconsistent.

This is not the case in the CSS and HTML panes.

Attempted all key bindings options and tried different Javascript transpilers/vanilla.  Also tried turning off tern.js

Chrome 53.0.2785.92 (64-bit)
Ubuntu 16.04
https://jsbin.com/tilanu/edit?html,js,output

**Comment by imaverage** [comment]
darn
