### ISSUE TITLE
GitHub login problem

### ISSUE THREAD

**Issue by felixfong227** [jsbin/jsbin#2882]
Today i find out my account is been logout for some reason,so i click the GitHub login button,but after that it pop up a error message said "Sorry, that GitHub account is linked to another JS Bin account."so now all my bins is lost and all my settings are lost too

**Comment by remy** [comment]
Do you remember what your username on jsbin was?

**Comment by moongod101** [comment]
I try to using the email login system,but when every click the "use your email address" is just redirect to the home page

**Comment by matthewmueller** [comment]
Running into this too, my email should be mattmuelle-at-gmail.com

**Comment by barneycarroll** [comment]
@matthewmueller @felixfong227 I followed the advice in #2098 - clearing cookies and signing it fixed it for me :)
