### ISSUE TITLE
Footer Ad position

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2888]
Just a note, now the advertisment strip at the bottom is a bit annoying :)  taking 33px `height: calc(100% - 33px);` , I don't mind ads as long as they don't take too much room. It's maybe possible to put it elsewhere, if not it doesn't matter

![image](https://cloud.githubusercontent.com/assets/3134574/18635232/9680ea0e-7e84-11e6-818f-d2df36f0a998.png)

**Comment by remy** [comment]
If you're a paying user and supporting jsbin's costs, then you don't see the ad. But also, all the spots you've pointed at have variable width, so they're no good. I'm pretty comfortable with loosing 33pixels from a potential several hundred. Thanks for the feedback though.
