### ISSUE TITLE
"window is not defined error" on String based webworker example

### ISSUE THREAD

**Issue by BlessYAHU** [jsbin/jsbin#2891]
creating a webworker from a string is giving "Uncaught ReferenceError: window is not defined" error.

jsFiddle: http://jsbin.com/darati/edit?js,console,output
code:
<pre>
function worker() {
  
  var n = 1;   
  postMessage('n is ' + n);
  search: while(n < 2000) {
    n += 1;
    for (var i = 2; i <= Math.sqrt(n); i += 1) {  
      if (n % i == 0) {     
        continue search; 
      }  
    }  // found a prime!
    postMessage(n); 
  }
}

var code = worker.toString();
code = code.substring(code.indexOf("{")+1, code.lastIndexOf("}"));

var blob = new Blob([code], {type: "application/javascript"});
var aworker = new Worker(URL.createObjectURL(blob));

aworker.addEventListener('message', function(m) {
  document.body.innerHTML += m.data;
  console.log("msg %o", m.data);
});
</pre>

jsbin source image:  
![image](https://cloud.githubusercontent.com/assets/317033/18713202/7415368a-7fdf-11e6-89d3-a7fd201e41ac.png)

**Comment by kirjs** [comment]
Looks like loop protection code is interfering.
See if you can disable it as a workaround: https://jsbin.com/blog/protection

**Comment by remy** [comment]
Yep, what @kirjs said. (the same applies if you try to console log actually).
