### ISSUE TITLE
Deleting an important bin that contains my schoolwork!

### ISSUE THREAD

**Issue by librafraudster** [jsbin/jsbin#2892]
https://jsbin.com/yururucaka/edit?html,output

I tested this code anonymously on JS bin, it is a very important piece of my schoolwork! I really can't afford to have it found my another student doing the same task or I will fail. I suppose in the future I will always test my code while logged in, in order to avoid such a dilemma. 

Is there any way it can be deleted?

**Comment by remy** [comment]
Sorry this took a few days, read the email but didn't have access at the time. This is done now.
