### ISSUE TITLE
Add jQuery 3.1.1

### ISSUE THREAD

**Issue by timmywil** [jsbin/jsbin#2893]
Please add jQuery 3.1.1 to jsbin.

Thanks!

http://blog.jquery.com/2016/09/22/jquery-3-1-1-released/

**Comment by remy** [comment]
i don't add these myself, I let the community manage them via PRs

**Comment by timmywil** [comment]
Ok, just wanted to give a heads up. I usually just do a jsfiddle issue to notify them of the release as soon as I post it, but thought I'd branch out and open an issue here as well. I would like jsbin to update faster, but it's probably too much for me to take on a PR for every release. But it sounds like I should refrain from opening an issue next time?
