### ISSUE TITLE
Embed script secure origins error

### ISSUE THREAD

**Issue by garrettreed** [jsbin/jsbin#2898]
```
runner:26 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
    (anonymous function) @ runner:26
        Promise (async)
    (anonymous function) @ runner:26
       runner-3.39.19.min.js:1
```

![screen shot 2016-09-30 at 12 26 44 pm](https://cloud.githubusercontent.com/assets/4079858/18998979/0f369eee-8709-11e6-8a9a-f05bfeb1755a.png)

**Comment by justinbmeyer** [comment]
@remy this was related to the problem I emailed you about .. the ability to __rerun the conversion to iframes.__

We are currently re-injecting the script tag.  But it recently stopped working on the second injections. 

We're not sure if this error is related, but thought to post it anyway.

**Comment by garrettreed** [comment]
The behavior can be seen at http://canjs.github.io/canjs/doc/guides/chat.html. If you navigate anywhere using the sidebar and back to Chat Guide, the embed request is made but not executed. 

![untitled](https://cloud.githubusercontent.com/assets/4079858/19002288/4bd873f8-8719-11e6-83f4-287202aa4e1d.gif)

**Comment by remy** [comment]
But this isn't a fatal error though, right?

I could add a guard to check if the page is on https to prevent it dropping into the code I guess.

**Comment by garrettreed** [comment]
It's likely this wasn't the cause of our issue - just something new that I noticed. I found a workaround mentioned [here](jsbin/jsbin#2819). Feel free to close the issue, though it would be nice to eliminate the console error.
