### ISSUE TITLE
Mobile site text area not visible when typing 

### ISSUE THREAD

**Issue by chewspot** [jsbin/jsbin#2899]
Mobile browser (chrome/opera mini), when the keyboard is open, cannot see text area 

[keyboard closed](https://cloud.githubusercontent.com/assets/4828474/19012980/ccf5593c-87f6-11e6-9926-905613acdab3.png)

[keyboard open](https://cloud.githubusercontent.com/assets/4828474/19012972/85185740-87f6-11e6-82f6-7ac91366b750.png)

**Comment by remy** [comment]
Huh. That's strange. So when the keyboard is in focus, the textarea vanishes, right?

**Comment by chewspot** [comment]
yup. that appears to be the case. in my screenshots, i was using chrome/swiftkey.

Here are some more screenshots, but using opera/hackers keyboard.

js keyboard open
![js keyboard open](https://cloud.githubusercontent.com/assets/4828474/19012959/13323ae2-87f6-11e6-8970-4b3ede5c600e.png)

js keyboard closed
![js keyboard closed](https://cloud.githubusercontent.com/assets/4828474/19012957/13313bb0-87f6-11e6-91ea-91d2b73e5fe3.png)

console keyboard open
![console keyboard open](https://cloud.githubusercontent.com/assets/4828474/19012958/13319e48-87f6-11e6-8f0c-ce288b77f64b.png)

**Comment by remy** [comment]
Sorry for the late reply. Can you try with the default keyboard? I very much doubt if it'll make a difference, just want to rule it out.

**Comment by remy** [comment]
I'm finally able to replicate this. I'll start looking at how to fix it in the coming week.
