### ISSUE TITLE
"Run" button does not work

### ISSUE THREAD

**Issue by itsthecheat** [jsbin/jsbin#2901]
Hello,
Newbie here, just recently started learning JavaScript and am in the midst of doing some course work which utilizes JS Bin. When I type code into the JavaScript panel and click "Run", nothing happens. If I type it directly into the console and hit enter that works. I've just been playing around with very simple expressions such as `2 + 2;` as an example. Auto-run is checked, I've also tried unchecking and checking again to no avail. Any help or advice as to whether I'm doing something wrong on my end is greatly appreciated!

**Comment by remy** [comment]
Just to clarify, the run button does work :)

I'm pretty sure it's something on your end, but without actually seeing your code, I can't tell you.

Certainly if you have `2 + 2` as the only code in the JavaScript panel, the result on the output *and* console will be blank.

**Comment by itsthecheat** [comment]
Well, I feel dumb.
Thank you for the clarification, makes more sense now :)

**Comment by remy** [comment]
No problem :)
