### ISSUE TITLE
How come my JS "Main" function is not being invoked?

### ISSUE THREAD

**Issue by RSmithBothell** [jsbin/jsbin#2902]
Very first action in the page.
http://jsbin.com/jaxaco/edit?html,css,js,console,output

You'll also notice in the tiny function Mainn (formerly Main), the jsbin linked pages are not being loaded into the output.
What am I missing?

Thanks!!!!!!!!

**Comment by remy** [comment]
Not totally sure, but JS Bin isn't the cause as you have the same bug in the full output (with all JS Bin chrome removed): https://output.jsbin.com/jaxaco/quiet

Suggest you post to stackoverflow or something (it could be hoisting an undefined value, but not totally sure).
