### ISSUE TITLE
Node v0.10 EOL soon

### ISSUE THREAD

**Issue by steakknife** [jsbin/jsbin#2909]
FYI: Node v0.10 maintenance phase [ends in about two weeks (2016-10-31)](https://github.com/nodejs/LTS) and will begin accumulating even more dust, incompatibilities and unpatched vulnerabilities.

**Comment by steakknife** [comment]
Different than #2793

**Comment by remy** [comment]
Yeah, I know. I don't have the time, or more importantly, the money to do a full upgrade on jsbin's source to node4-6 (ideally 6). There were major changes in express that break code in jsbin (not sure what exactly, I just know it's not a straight forward upgrade).

**Comment by steakknife** [comment]
Rationalizing BS. FOSS dilettante, greedy poser. GFL
