### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by amaliapage** [jsbin/jsbin#2910]
Hello,

I am having no issues with login at github.  But when I try to log into jsbin I get "No Dice. Those details didn't work".  When I try to reset password I do not get an email. I got "I looked, but I couldn't find any user with those details. Sorry!".  But it appears my username and email are accurate and are unavailable.  I really need to get this resolved very soon.

amalia

**Comment by remy** [comment]
Your account doesn't have an email address attached, which is why you can't reset your password (since we don't have an email address). Sign in with your github (since you have no issues with that) and add your email address.

**Comment by amaliapage** [comment]
My email address has been added.  But I am still having the same issue.  Is it because it is "private"?

**Comment by remy** [comment]
Added in jsbin? There's no such thing as a private email on jsbin, so it makes me think you're referring to github
