### ISSUE TITLE
Uncaught (in promise) DOMException: Only secure origins are allowed

### ISSUE THREAD

**Issue by hakib** [jsbin/jsbin#2913]
Runner stops working after a while using chromium (53.0.2785.116 (64-bit) or arch linux).

This is the URL attached to the error:

[https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)

Looks like something to do with loading the service worker.

I tried firefox as well and I get `SecurityError: The operation is insecure.`.

**Comment by remy** [comment]
Do you have an example bin url?

**Comment by hakib** [comment]
Sure.

https://jsbin.com/wegizaf/2/edit?output

I ran it locally and it worked fine.
