### ISSUE TITLE
jsbin.settings.editor assignment returns 404 on refresh

### ISSUE THREAD

**Issue by kingram6865** [jsbin/jsbin#2920]
Is the ability to change the editor settings only available on a PRO account?

jsbin.settings.editor.linenumbers=true;

![image](https://cloud.githubusercontent.com/assets/13263318/19782152/6eb2b2fc-9c41-11e6-8ccc-7cfe0a7dbed3.png)

**Comment by remy** [comment]
No, but I think you're missing a line in your console output. Try reloading
with devtools open.
