### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by mikhoul** [jsbin/jsbin#2921]
Hi, :smile_cat: 

I'm new to JSbin and I try to find where to go to change my Avatar : http://i.imgur.com/w9ltbhZ.png

I did not found anything related to the avatar in the settings/preferences, my account is linked to github: http://i.imgur.com/J9eJsJZ.png

I rely a lot to see my avatar on online services to see if I'm logged in or not.  :octocat: 

Thanks for this useful service :+1:

**Comment by remy** [comment]
jsbin uses gravatar for your avatar. IIRC, a single account is free, and we
use your email to find it.

**Comment by idfubar** [comment]
@remy: Just wanted to echo the sentiment... but no issue as long as the mail addresses match... (so maybe a 'Closed' issue rather than an 'Open' one?)
