### ISSUE TITLE
Wrong result of JavaScript code execution

### ISSUE THREAD

**Issue by kamilmielnik** [jsbin/jsbin#2931]
The following code should log `1000000` (1 million) but instead it produces a random number, usually in range `100000` - `160000`.

Executing code in my browser's console produces a correct result.
My browser is Chrome 54.0.2840.71 m.

```
const limit = 1000 * 1000;
let i;
let iterations = 0;

for(i = 0; i < limit; ++i) {
   iterations += 1;
}

console.log(iterations);
```

**Comment by remy** [comment]
Loop protection. Add `//noprotect` to the JS and it won't kick in.
