### ISSUE TITLE
Configuration no longer works

### ISSUE THREAD

**Issue by stashaway** [jsbin/jsbin#2937]
I'm trying to enable lineWrapping in the javascript panel and the methods described in help and elsewhere online don't work anymore.  jsbin.settings.editor.lineWrapping=true; yields an error.  Are those settings stil available? Thanks

**Comment by remy** [comment]
That's super old. Sign in. Use your account settings.

**Comment by povrotha007** [comment]
If file breaks the rules or infringes copyrights, please report it now. We review every reported file.

**Comment by remy** [comment]
Not sure what that previous comment was, nonsense perhaps.
