### ISSUE TITLE
"You're currently viewing someone else's livestream" right after cloning

### ISSUE THREAD

**Issue by josephrocca** [jsbin/jsbin#2938]
Here's how to reproduce this bug (on Chrome, at least):

1. Open up jsbin.com and make some random edits
2. Now press `ctrl`+`f5` to "hard reset" chrome (clear cache and reload page)
3. Now you've lost ownership of the bin
4. Make some more edits and the "You're currently viewing someone else's livestream" message pops up
5. No worries, just click the "clone your own copy" link or press `ctrl`+`shift`+`S` to clone a new copy
6. Start making edits in your new copy
7. And now (here's the bug), the "You're currently viewing someone else's livestream" message comes up again
8. Go to step 5

I've got no idea what's causing this. I sometimes need to "hard reset" Chrome with `ctrl`+`f5` because codemirror has a bug that wont go away otherwise.

**Comment by jimeast** [comment]
looks like the bug was never fixed, I'll stop using jsbin

**Comment by remy** [comment]
Thanks for letting me know @jimeast.

**Comment by ccoxwell** [comment]
will this be addressed? seems like i could clone to infinity and still get the same message.

**Comment by remy** [comment]
Short answer: yes. In v5.
