### ISSUE TITLE
console error:  throttle is not defined

### ISSUE THREAD

**Issue by ivernaloo** [jsbin/jsbin#2942]
just set up the project
after npm install && grunt build
used the ./bin/jsbin started the service
then
i don't know what missed lead the problem
such as below
![20161126003002](https://cloud.githubusercontent.com/assets/219693/20631056/9d87c71c-b36f-11e6-9628-57e3e6242820.png)

**Comment by remy** [comment]
Probably install from github, but still, I don't know what's wrong either. Looks like some scripts are missing…?
