### ISSUE TITLE
Syntax highlighing is not working in iPad

### ISSUE THREAD

**Issue by yoshiboarder** [jsbin/jsbin#2944]
Code highlighting is not working in mobile safari

Could you please fix this problem?

**Comment by remy** [comment]
Okay… 
<img width="307" alt="screen shot 2016-11-26 at 09 24 15" src="https://cloud.githubusercontent.com/assets/13700/20639391/1d89e48c-b3ba-11e6-9b29-1b91f85491f4.png">

**Comment by remy** [comment]
Oh, iPad. I missed that.

No. Syntax highlight isn't supported on iPad because CodeMirror doesn't work on mobile (you can see this by trying something like codepen and making code changes, you'll find the cursor jumps around).

**Comment by yoshiboarder** [comment]
Okey Thanks for reply 👍
