### ISSUE TITLE
No output in jsbin console for instanceof

### ISSUE THREAD

**Issue by itsthomas** [jsbin/jsbin#2945]
Hi,

I just fount out that the following code, doesn't give any out put in jsbin console:

var test = function(){}
test instanceof Function // true
test instanceof Object // true

Is it a bug? 

I spend 20 minutes to find out that my example code was ok and works in browser console and also in repl.it. But no console output in jsbin.

Not a big deal, but I thought you should know about it and if it's a bug to fix it.

Thanks

**Comment by jamez14** [comment]
You have to explictly tell jsbin to output to the console. This code works:

```
var test = function(){}

console.log(test instanceof Function); // true
console.log(test instanceof Object); // true
```
