### ISSUE TITLE
Installation failed: Running locally

### ISSUE THREAD

**Issue by aldomolina** [jsbin/jsbin#2952]
$ npm install -g jsbin
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN engine sqlite3@2.2.4: wanted: {"node":">= 0.8.0 < 0.13.0"} (current: {"node":"4.6.0","npm":"2.15.9"})
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.4 install C:\Users\AppData\Roaming\npm\node_modules\jsbin\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

**Comment by vitali2y** [comment]
This workaround works great for me:
```
# wget https://registry.npmjs.org/jsbin/-/jsbin-3.11.23.tgz
# tar xvfz jsbin-3.11.23.tgz
# cd package
# sed -i '/    "sqlite3": "~2.2.0",/c\    "sqlite3": "*",' package.json
# npm install --build-from-source -g
# cd /usr/local/node-v6.9.4-linux-x64/lib/node_modules/jsbin && npm install express
# cd ./node_modules/express && npm install connect
```

**Comment by derekbtw** [comment]
@vitali2y

![image](https://cloud.githubusercontent.com/assets/3450398/24574970/0f7f4c8c-1658-11e7-861f-2e081410e561.png)
