### ISSUE TITLE
HTML/CSS/JS/Console first item bug

### ISSUE THREAD

**Issue by chat-du-cheshire** [jsbin/jsbin#2954]
When html inactive it displays with bug. First items has bold text style and look unligned

![2016-12-09_14-36-25](https://cloud.githubusercontent.com/assets/18593655/21047867/4fe2c350-be1d-11e6-8b08-5123d7ed57d7.jpg)

**Comment by remy** [comment]
It's not inactive, it bold because there's some content in there. Since you're starting from boilerplate, it has some text characters in it, therefore bold.

**Comment by chat-du-cheshire** [comment]
But does they really look like this? They are not in line, it look likes a bug.
![2016-12-10_03-42-48](https://cloud.githubusercontent.com/assets/18593655/21069462/33aafda6-be8b-11e6-850c-a0e7af54ad80.png)
