### ISSUE TITLE
in console if the object i print then it print like below

### ISSUE THREAD

**Issue by sibaspage** [jsbin/jsbin#2957]
![123](https://cloud.githubusercontent.com/assets/13863225/21354774/5ea4b812-c6f1-11e6-90e8-703141c8c296.png)

**Comment by sibascodeking** [comment]
i just checking why the C and D are not coming. Then by alert i get it.

**Comment by briwa** [comment]
The C and D is there, hence the `{ . . . }`. I think JSBin is limiting the depth level of printed objects
