### ISSUE TITLE
Display: flex;  Not updating working

### ISSUE THREAD

**Issue by githubH** [jsbin/jsbin#2961]
A Udemy instructor has a bin that works in his tut, but not on jsbin!  Check the attached screenshot and tell me how I'm screwing up...seems like it should show the output as an inline flex container...but doesn't?!
JSBin is infallible...where's my error?

![screenshot 2016-12-22 11 25 40](https://cloud.githubusercontent.com/assets/3130953/21437710/4d63fd7a-c83a-11e6-90d4-625a53bc6457.png)

**Comment by psimyn** [comment]
looks fine - do you have the link? Unless that Safari version is <9 it should work :)
