### ISSUE TITLE
student

### ISSUE THREAD

**Issue by rjk40** [jsbin/jsbin#2964]
I am not recognized as as student

**Comment by remy** [comment]
Why did you expect to be? And what did you expect from that anyway?

**Comment by rjk40** [comment]
The code packages were cheaper for one

**Comment by rjk40** [comment]
Js bin so i can help you and contribute and learn, like imalready have

**Comment by remy** [comment]
There's no student packages. PRs are welcome as it's an open source project. Generally feature dev is on the long term back burner.
