### ISSUE TITLE
Add Library inserting outside of <html> tag

### ISSUE THREAD

**Issue by xylude** [jsbin/jsbin#2965]
This might just be me, haven't tried on another machine - but it has been happening for a while on this computer. If you can't reproduce it, or need more info feel free to contact me.

Steps to reproduce:
1. Click 'Add Library'
2. Add Library of your choice
3. In HTML view, the library is at the very beginning of the document

Here is a screenshot of my HTML tab after adding a library:
![screen shot 2016-12-29 at 2 51 48 pm](https://cloud.githubusercontent.com/assets/831373/21553537/d68e7160-cdd6-11e6-8755-66d74c158cc3.png)

**Comment by jamez14** [comment]
This is actually a feature. 

[This PR](https://github.com/jsbin/jsbin/commit/2d059408bf8dd38fce7956ee4a0d0d20ea17be27) shows that when adding a library, it adds it at the users cursor position in the HTML.
