### ISSUE TITLE
[Question] Cannot update old snapshots? There is an expiry date?

### ISSUE THREAD

**Issue by bryc** [jsbin/jsbin#2968]
I remember being able to specify a snapshot # and being able to modify that snapshot itself.. however, when I try this now, one of two things occur:

1. A new snapshot # is created (auto-incremented) and the original snapshot remain unchanged.
2. The bin is cloned with a new URL id, starting at snapshot 1. The original URL id appears 'lost'. I believe this happened only on bins that lack a revision 1 (it being deleted).

I cannot reproduce this when creating a new bin, as modifying it and refreshing all results in the same snapshot being modified. I can only force a new snapshot in the file menu. But for old bins I have no choice but to have a new snapshot created (or otherwise a bin being cloned).

I don't see any related info on the FAQ that explains this - any links or explanation on this behaviour?

**Comment by remy** [comment]
This was never a feature. A snapshot is locked for all time. The reason you
can edit the current URL even after a refresh is that you're editing the
live URL, not a snapshot.

So if you try to edit a snapshot URL it'll either create a new
milestone/snapshot or if it can't assertain if you were the original owner,
it'll clone (as you're seeing).
