### ISSUE TITLE
Files that  displayed correctly last week are not now

### ISSUE THREAD

**Issue by JoAnn21** [jsbin/jsbin#2969]
Last week nav displayed correctly. Since end of last week, now nav bar is not appearing correctly--never changed any code. Appears correctly in Dreamweaver, but I need to use JSBin for classwork. Help please.

https://jsbin.com/hemosi/2/edit

**Comment by remy** [comment]
I'm assuming what you mean is the output from your code (rather than jsbin)
isn't rendering as you'd want? I can't help you really. You're the only one
that has access to changing the code but I also see you pull in external
asserts for your page.

Nothing I can help with I'm afraid.
