### ISSUE TITLE
hi there

### ISSUE THREAD

**Issue by intracodeltd** [jsbin/jsbin#2970]
Hi, it's Martin @ intracodeltd here, just joined!
I'm a bit stuck, I can't seem to delete my bins and I get a frame error even when using http
now I have done a lot of trying to save/load bins I believe I will get blocked as a spammer if I am not careful
but I am really stuck
All I want to do is create a few bins and manage them!
its a great tool I may buy a subscription if I can get this working 
so I go to 'my bins' try to click one or double-click - delete and it gives a warning but does not go
I can't seem to delete the first one in the list, and the pane to the right is a frame error
I am on ie11
best regards
Martin

**Comment by remy** [comment]
Can you include a screenshot of the error you're seeing?

**Comment by intracodeltd** [comment]
thanks or quick reply - I am ok now. I did not realise the 'archive' functionality by clicking on this text. but by luck i found it!  it would be great to have option to hide the snapshot auto-saves so you can just see the bin's you've worked on 

is it possible to pay via paypal instead of card for a one off 12m? I don't like using them on-line
best regards
Martin
