### ISSUE TITLE
JSBin's XSS security techniques

### ISSUE THREAD

**Issue by josephrocca** [jsbin/jsbin#2973]
This isn't an issue with JSBin per se, but just a query about the technique JSBin uses to prevent cross-site scripting. I'm wondering if anyone knows why JSBin uses a sandboxed iframe *inside* a normal iframe that points to `null.jsbin.com/runner`. Is the internal sandboxed iframe required? Why not just put the sandbox attributes on the outer iframe and run the user's scripts directly in that? Just curious, because it's different to jsfiddle.net and others in that regard (which just use one sandboxed, "subdomained" iframe). Thanks!

**Comment by helmutgranda** [comment]
You may be able to get a response in SO than here, this section is mainly for issues. However, the owner of the project may feel inclined to respond :).

**Comment by remy** [comment]
@josephrocca you'll find that the other pastebins do the same thing (if you look carefully), but also it's two fold: 

1. It prevents the output window from reaching up into the top level domain (i.e. to steal cookies)
2. It prevents accidental DDOS attacks on jsbin.com - where a user is entering multiple `img` tags (for example) whilst they don't have completed `src` attributes (or relative `src`) they would point to jsbin.com's servers. Using the origin of `null.jsbin.com` means that the requests never touch the main server: https://github.com/jsbin/production/blob/master/apps.jsbin.com/etc/nginx/nginx.conf#L87-L92

**Comment by josephrocca** [comment]
Thanks @helmutgranda! I think I'll ask this SO.

Thanks for your answer, @remy! I really appreciate it. I either don't quite understand, or you've misunderstood my question slightly: My query is about why **two** iframes (one inside the other) are necessary.

Couldn't the same thing be achieved by just creating an iframe that points to `null.jsbin.com/runner` and then adding sandbox attributes to that same iframe?

I'm all for extra layers of security, but am just curious if there was a specific security-based intention behind having a "2-layers-deep" environment for the user's code to run in. Thanks for your time (and for JSBin)! I completely understand if you don't get around to answering this.

**Comment by remy** [comment]
Okay, this is where jsbin is unique. The deepest iframe is dynamically
constructed so it contains all your code. The other pastebins render the
first layer iframe on the server so it's both on a different origin but
also contains your code.

The upshot for jsbin is that it's faster to render, but also works fully
offline (if you have experiments turned on in pro accounts).

**Comment by josephrocca** [comment]
Makes sense! Thanks for the explanation :+1:
