### ISSUE TITLE
Prison break, how do you escape the "for" statement?

### ISSUE THREAD

**Issue by jjcale** [jsbin/jsbin#2979]
Hi, I am testing JS Bin:

![image](https://cloud.githubusercontent.com/assets/3494914/22338317/5ccda086-e3e7-11e6-9099-e863a48f5aa6.png)

http://jsbin.com/metohac/edit?js,console

I am getting the following console outputs:

150000
"break"
"out"
150000
"break"
"out"
150000
"break"
"out"
150000
"out"
146241
"break"
"out"
150000
"break"
"out"
150000
"out"
141291
"break"
"out"
150000
"break"
"out"
150000
"out"
132795
"out"
145700

How come this is possible? In Mozilla Firefox it works flawlessly like a charm.
Regards,
Jan

**Comment by remy** [comment]
Add `// noprotect` - it'll remove the loop protection.
