### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by GarthDB** [jsbin/jsbin#2980]
I no longer need the pro features, but I forgot to cancel before the billing cycle started.

Is it possible to get a refund for the year?

**Comment by remy** [comment]
Can you email me support@jsbin.com with details of your account. Thanks.

**Comment by GarthDB** [comment]
@remy I tried sending you an email but it was rejected with this message:

The response from the remote server was:
Your email to group support@jsbin.com was rejected due to spam classification. To address this issue: * Contact the owner of the group, who can choose to enable message moderation instead of bouncing these emails. * Set up SPF records for your sending domain if you have not done so already. Instructions for both steps can be found here: https://support.google.com/a/answer/168383.

**Comment by remy** [comment]
Oh yay 😐

Can you try remy@leftlogic.com
