### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by winmintin** [jsbin/jsbin#2982]
I wrote this using javacript but the loop only run once. This code work using sololearn playground
https://code.sololearn.com/W2K4iIufBDva/#js

I don't know why?
////////////////////////////////////////////////////////////

var randomNumber = getRandomNumber(10);
var guess;
var guessCount = 0; 
var correctGuess = false; 

function getRandomNumber(upper) {
   var num = Math.floor(Math.random() * upper) +1; 
   return num;
}

do {
  guess = prompt("Guess a random number between 1 and 10");
  guessCount += 1;
  if (parseInt(guess) === randomNumber) {
    correctGuess = true;
  }
} while (!correctGuess)
  

document.write("It took you " + guessCount + " to guess the number " + randomNumber);

**Comment by jamez14** [comment]
Appears there are some protections against this in jsbin's codebase. See your browsers console for more info. 

What it said though was: "Exiting potential infinite loop at line 11. To disable loop protection: add "// noprotect" to your code"

So at the top of your scripts, just add `// noprotect` and you'll be all set.

**Comment by remy** [comment]
👍
