### ISSUE TITLE
The JavaScript sub window just can not scroll.

### ISSUE THREAD

**Issue by licdream** [jsbin/jsbin#2984]
The sub window of JavaScript just can not scroll by mouse wheel when I code too long. And I have tried to use the Down-Arrow key on keyboard, but it works strange. it can scroll down but no scroll the browser window up when code scroll back to the top of sub window. The screenshots below shows what happen to me. wish it could show you the problem clearly.
![snipaste20170214_104124](https://cloud.githubusercontent.com/assets/9717793/22912909/de8cf09e-f2a2-11e6-8dc2-aa514e95b249.jpg)
![snipaste20170214_104439](https://cloud.githubusercontent.com/assets/9717793/22912920/ee870f98-f2a2-11e6-8b18-2fad89391350.jpg)
（cut-of）
![snipaste20170214_110156](https://cloud.githubusercontent.com/assets/9717793/22913358/38ea3a40-f2a5-11e6-856f-933d2d16f0cb.jpg)
![snipaste20170214_104535](https://cloud.githubusercontent.com/assets/9717793/22912919/ee833788-f2a2-11e6-918f-d16760463574.jpg)

**Comment by remy** [comment]
Can you replicate in an incognito window? I see you have some plugins
overlaying the page and I'd like to rule those out first.

**Comment by licdream** [comment]
It seems the same in an incognito window.
![snipaste20170214_175857](https://cloud.githubusercontent.com/assets/9717793/22924233/52aaab60-f2df-11e6-8bc9-6d5b9a379f93.jpg)

**Comment by licdream** [comment]
Console in an incognito window.
![snipaste20170214_180353](https://cloud.githubusercontent.com/assets/9717793/22924451/223f7892-f2e0-11e6-9947-e984fcdfc916.jpg)
