### ISSUE TITLE
Support syntax highlighting for iPAd

### ISSUE THREAD

**Issue by ShawnBaek** [jsbin/jsbin#2987]
Hi you know iPad is also really great device for programming

But syntax highlighting is always black!

Please fix this problem

**Comment by remy** [comment]
Well, here's the option: syntax highlighting, but editing doesn't work (you can try against codepen of jsfiddle), select/change etc breaks.

Or: no syntax highlighting and you can actually make code changes. 

Closing as I think I know the answer.
