### ISSUE TITLE
logging in problem

### ISSUE THREAD

**Issue by sunlight200** [jsbin/jsbin#2989]
I'm trying to log in to jsbin using my github account and I'm getting this message ,sorry this github account is linked to anther jsbin account ,I tried alot and couldn't get into my jsbin where i saved all my files

**Comment by erwar** [comment]
i have this problems too

**Comment by renaudtertrais** [comment]
Clearing cookies seems to fix the issue. https://github.com/jsbin/jsbin/issues/2882

**Comment by erwar** [comment]
@renaudtertrais thanks its work!
