### ISSUE TITLE
Arrow function doesnt work in jquery custom events

### ISSUE THREAD

**Issue by felipe-coelho** [jsbin/jsbin#2990]
Arrow function doesnt work in jquery custom events.
I write this code using ES6/Babel
See my code:
$('.box').on('re:paint', () => {
  // do something
})

When i change to:
$('.box').on('re:paint', function() {
  // do something
})

then works fine

**Comment by remy** [comment]
Does work: https://jsbin.com/jikitim/edit?html,js,output

I suspect you're getting confused about how the arrow function changes the bound context.
