### ISSUE TITLE
Problem with Login - cannot login

### ISSUE THREAD

**Issue by BettyD** [jsbin/jsbin#2991]
When trying to log in to JS Bin via GitHub I receive the message that "Sorry, that GitHub account is linked to another JS Bin account."
No any other possibility, no any windows open where I could give my login name and password, not even when I choose to login with my email address.
![image](https://cloud.githubusercontent.com/assets/9568703/23394732/119ae1ba-fd8b-11e6-9a4a-2fd0abdb62a7.png)
Please help! Thanks.

**Comment by lejonmanen** [comment]
I had this issue. The cookies have become corrupted somehow. I resolved the issue by clearing my jsbin cookies.

**Comment by BettyD** [comment]
Thank you, I finally did the same 2 weeks ago, and it worked. :)
