### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by mortensenm1205** [jsbin/jsbin#2992]
Hello, 

jsbin won't let me login, giving me the error message: 
'Sorry, that GitHub account is linked to another JS Bin account.'

I wasn't able to find out why it's giving me this message. Looks like some other people were having the same issue. 

Thanks!

**Comment by alcastaneda** [comment]
I am having the same issue

**Comment by sharepointcentric** [comment]
Same here and I need access to my working files.

**Comment by auser** [comment]
Same here. Any progress?
