### ISSUE TITLE
Distinguish expression evaluation result from log output in console

### ISSUE THREAD

**Issue by sesm** [jsbin/jsbin#2994]
People are often confused why statements like "console.log(1)" result in 2 outputs in console.
To solve this problem, browser consoles (Chrome and Firefox at least) distinguish expression evaluation result by putting '->' to the left of it.
It would be great if JS bin console did the same.

**Comment by NinaK2016** [comment]
Statement "console.log(1)" prints "1", but returns "undefined", wich not output in console JS Bin.
Distinguishing sign for the returned value would be convenient.
