### ISSUE TITLE
old posts

### ISSUE THREAD

**Issue by fbsdev** [jsbin/jsbin#2998]
Help me please,

I saved several HTML of the course I did in EDX, MITx, but I lost my account and I do not have the link of all the post's I made.

One of them is this

Http://jsbin.com/holugu

How can I find the other posts in my old account?

Account: fbilicki

Rgs

**Comment by remy** [comment]
Well, that bin is attached to the `fbilicki` user, but if you made bins without being logged in, I'm afraid there's no way for me to find them. If you know the URLs, but they're not under your account, if you just open each and clone them, you'll get a copy under your account.
