### ISSUE TITLE
Cant log into GitHub

### ISSUE THREAD

**Issue by sgfx** [jsbin/jsbin#2999]
trying to log in with GitHub account
I keep getting a
Sorry, that GitHub account is linked to another account. 

I have only had one. for about 3 years. 

![image](https://cloud.githubusercontent.com/assets/5022385/23736256/c1baa1f4-0450-11e7-8c26-c6b894391a93.png)

**Comment by sunlight200** [comment]
I have the same issue for more than 2 weeks

**Comment by lejonmanen** [comment]
I had this issue. The cookies have become corrupted somehow. I resolved the issue by clearing my jsbin cookies. After that GitHub login worked.
