### ISSUE TITLE
Login issue - using NON-Github authorization

### ISSUE THREAD

**Issue by rmakrenko** [jsbin/jsbin#3000]
I was working on JSBin as usual, but today around 11:25 Kiev time (9:25 UTC-0) I've experienced some strange bug with authorization. My current bin have changed its title (name) twice after saving - it's non standart behaviour.

Also, when I've cleared cookie in my chrome for jsbin site, nothing changed.

Afterwards I've login from different browser using my **rmwlux** account (non-github), tap onto Account - Profile and see.... Different person account (before accessing account-profile it was mine, rmwlux).

**Comment by rmakrenko** [comment]
![screenshot_221](https://cloud.githubusercontent.com/assets/3214159/23744396/bd61dd9a-04bc-11e7-9d19-8044fdd8f98c.png)
![screenshot_220](https://cloud.githubusercontent.com/assets/3214159/23744402/c0c1e156-04bc-11e7-97fe-7322a16d3dc4.png)

**Comment by remy** [comment]
Just to say, I'm on this. I'm not sure what the cause yet is, but I'm thinking about refactoring the in-memory cache for users (this is currently my only viable suspect).

Can I ask, do you have a pro account? (trying to rule out if that's a common factor).

**Comment by rmakrenko** [comment]
Hi Remy, sorry for delayed responce - nope, just basic account
