### ISSUE TITLE
GitHub login stopped working

### ISSUE THREAD

**Issue by lejonmanen** [jsbin/jsbin#3004]
Hello!

Yesterday GitHub login stopped working for me. I got the error message "Sorry, that GitHub account is linked to another JS Bin account" when I clicked on the "Login or Register via GitHub". It's possible to circumvent this by opening JS Bin in incognito mode in Chrome and logging in.

**Comment by remy** [comment]
Appreciate this was filled a while ago, but do you have this issue still?

**Comment by lejonmanen** [comment]
Yes, it's still there. Is there anything I can do to help?
The problem doesn't exist in Firefox or Edge.

**Comment by remy** [comment]
Can you try clearing your cookies or an incognito window?

**Comment by lejonmanen** [comment]
When I removed all cookies and reloaded the page, login with GitHub worked as usual. I don't know what caused it, but the fix was easy enough.
Thanks @remy !
