### ISSUE TITLE
problems logging in, please help!

### ISSUE THREAD

**Issue by bcostantino77** [jsbin/jsbin#3006]
I'm all of a sudden having problems logging in with the following message:
"Sorry that GitHub account is lined to another JS Bin account"
It has always been working fine, I always  logged in through my GitHub account and I did nothing differently today.
Please advise, I have a Bin project I need to work on that I need to access.

<img width="516" alt="screen shot 2017-03-13 at 2 12 56 pm" src="https://cloud.githubusercontent.com/assets/23282266/23868835/4e48d182-07f7-11e7-98fa-cc422d2ab658.png">

**Comment by remy** [comment]
This is happening a lot over the last few days, and although nothing has changed on jsbin's side, I'm now getting worried.

Is it possible that you've changed anything in your github account? Perhaps making your email private (bit of a wild guess atm)?

**Comment by bcostantino77** [comment]
Thanks for the response. I for sure have not changed anything on my end.

**Comment by remy** [comment]
Can you try to sign in from a private session, like a new incognito window in Chrome? (just ruling some things out)

**Comment by bcostantino77** [comment]
Chrome works fine. I was in Safari before. Also I was in a building with
really inconsistent signal.

**Comment by remy** [comment]
Are you able to replicate the issue you were seeing, or was it a one off?

(there's quite a few people who have raised the same issue, so I'm not saying it's a one off problem, but more that it was triggered in a specific situation for your account - and many others - again, just trying to rule out 😄 )

**Comment by bcostantino77** [comment]
Seems like a one off. But I think it could be related to bad signal in the
location of my work cubicle, I'm not in that building now but will be again
today. Perhaps I can replicate the issue later.

**Comment by bcostantino77** [comment]
I'm back on the same setup where the original problem occurred and I'm able
to replicate the issue. Its not solved on this particular computer setup in
Safari. However, it works fine when I use Chrome, so that's what I'm doing.

**Comment by remy** [comment]
I'm pretty sure this is linked to somehow already being logged in, and the code throws a weird error because of it, which also explains why it was fine in a private/incognito window.

**Comment by lejonmanen** [comment]
@bcostantino77 Try to clear all jsbin cookies and log in again. I had the exact same problem and that fixed it for me.
