### ISSUE TITLE
Unable to login jsbin with my GitHub 

### ISSUE THREAD

**Issue by mmcooper** [jsbin/jsbin#3007]
When I click on Login or Register Button to login JSBin via GitHub, I get the following message. 
Sorry that GitHub account is linked to another JS Bin Account. See screenshot. What should I do?  
Thanks, Michael 
![screen shot 2017-03-14 at 12 02 39 pm](https://cloud.githubusercontent.com/assets/19911932/23912789/d6b69218-08ae-11e7-96b7-048ec5b7490a.png)

**Comment by mmcooper** [comment]
Clearing my cache resolved the issue of logging into JS Bin with my GitHub account. Thanks.

**Comment by lejonmanen** [comment]
@mmcooper I had the same issue, it was enough to remove all jsbin cookies. If the issue is solved, you should close it :)

**Comment by mmcooper** [comment]
@lejonmanen Good to know. Closing comment.
