### ISSUE TITLE
JS Bin

### ISSUE THREAD

**Issue by EljamRussell** [jsbin/jsbin#3009]
When I go to any of the selections below:

Textarea editor mode
JS Bin features
Getting started
Keyboard Shortcuts
Exporting/importing gist

I get the following error:

**This page isn't here :-(
How about heading back to the homepage instead? It's nice there and there are lots of things to click on.

If you think there is supposed to be something here that isn't let us know via the Issues page.** "

**Comment by remy** [comment]
Fixed - thanks.
