### ISSUE TITLE
Broken links & missing education link

### ISSUE THREAD

**Issue by ptbobolakis** [jsbin/jsbin#3011]
Hey guys, 

I have problems accessing the /help & the /blog pages of jsbin.
Also I read, that you provide free accounts to everyone in the edu area. I was looking for a sign up link/preference setting, but I couldn't find it. Did I get it wrong? I have an ISIC student card, sind my school (and most schools in Germany) do not provide students with an email address.

Cheers.

**Comment by remy** [comment]
Ah, i think the learning site is down. I'll fix that.

Re: education, no it's only for teachers (rather than students, sorry).

**Comment by remy** [comment]
Fixed. Thanks.
