### ISSUE TITLE
TypeError: a.split is not a function

### ISSUE THREAD

**Issue by Manish-Giri** [jsbin/jsbin#3014]
I was trying out some code when I started seeing this error, I erased all the code, typed it in, erased it again, typed some other code, "saved" the bin, but whatever I do - I keep getting this error on the console

Here's my [bin](https://jsbin.com/tisaruw/edit?js,console).

Here's the code - 
```
//jshint esnext:true
function transformEmployeeData(array) {
  // your code here
  var result = [];
  for(var i = 0; i < array.length; i++) {
    let tempObj = {};
    let currValue = '';
    for(var j = 0; j < array[i].length; j++) {
      tempObj[array[i][j][0]] = array[i][j][1];
      
    }
    result.push(tempObj);
  }
  return result;
}

var input = [
    [
        ['firstName', 'Joe'], ['lastName', 'Blow'], ['age', 42], ['role', 'clerk']
    ],
    [
        ['firstName', 'Mary'], ['lastName', 'Jenkins'], ['age', 36], ['role', 'manager']
    ]
];

console.log(transformEmployeeData(input));
```
It works fine on codepen, jsfiddle, and elsewhere.

Screenshot - 
![ww](https://cloud.githubusercontent.com/assets/11348778/24234280/bcc7c474-0f6d-11e7-8e77-dc223188c80b.png)

<hr>

Update - I tried to trace the source of the error and it's occurring from this line in the jsbin code - 

![www](https://cloud.githubusercontent.com/assets/11348778/24235968/2360e35c-0f76-11e7-850a-5e7986fbc56c.png)

**Comment by benjaminEwhite** [comment]
See also: https://github.com/jsbin/jsbin/issues/3010

**Comment by remy** [comment]
Should all be fixed now. Managed to get latest deploy live again. Make sure to do a hard refresh.
