### ISSUE TITLE
Wierd account 

### ISSUE THREAD

**Issue by BOBONA** [jsbin/jsbin#3015]
I went onto jsbin and for some reason it showed a profile with a username named scolt and a ridiculous amount of projects. I logged out and back in and then it was normal.

**Comment by remy** [comment]
Are you able to replicate this at all? I've seen this once before but not able to replicate, which has made it extremely hard to debug…

**Comment by BOBONA** [comment]
I don't know if this helps, but I viewed one of the projects and can access
it through my history.

html:
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>

</body>
</html>


js:
var items = [
{name: "value_0", data:{a:1}},
{name: "value_0", data:{b:2}},
{name: "value_1", data:{c:3}},
{name: "value_1", data:{d:4}},
{name: "value_1", data:{e:5}},
{name: "zzz", data:{f:6}},
];

groupObjectsByName = function (items) {
  var curElem, unique;
  var result = {};

  for (var i = 0; i < items.length; i=i+1) {
    if (result[items[i].name]) {
      result[items[i].name].push(items[i])
    } else {
      result[items[i].name]=[];
      result[items[i].name].push(items[i])
    }
  }

  return result;
};


tmp = groupObjectsByName(items);
console.log(tmp);

/*[
  {
    name: 1,
    data: [
      objm obj
    ]
  }
]*/

**Comment by BOBONA** [comment]
https://github.com/scolt
