### ISSUE TITLE
Paid for yearly subscription instead of monthly (undesired)

### ISSUE THREAD

**Issue by chrisArmo** [jsbin/jsbin#3017]
In subscribing to jsbin I clicked on the monthly subscription but when I subscribed, I was charged for the yearly. Please help me revert to the monthly. I can't afford to pay the yearly at this time.
It just happened. How do I get a refund and change to monthly?

**Comment by remy** [comment]
Can you email me at support@jsbin.com with full details and I'll sort this
out for you.
