### ISSUE TITLE
Output error 

### ISSUE THREAD

**Issue by Azahamos** [jsbin/jsbin#3018]
Hi there, I've tried running a few different scripts, but nothing ever appears on the Output screen (no error messages either). I've tried clicking the run with JS button, deselecting the Output option, and reselecting, etc. with no luck.
The output screen has never worked for me, only displaying "960px" next to the Output text at the top of the output section. I'd like to check if there's  something I'm missing in my preferences or it it's an actual bug. This works the same from Chrome to IE. Thank you for any feedback. 

![js error](https://cloud.githubusercontent.com/assets/26092572/24366954/73c71560-12e0-11e7-81c2-65e11408e52b.JPG)

**Comment by remy** [comment]
A few problems there:

1. You're logging to the console - the output is for HTML/DOM (so open the console instead of the output panel).
2. The string "jsbin.com" is not valid JavaScript.
