### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bythckr** [jsbin/jsbin#3022]
I am unable to install jsbin by using `npm install -g jsbin` and my [npm-debug.log](https://gist.github.com/bythckr/3745ec25aed7a4b3b815486f1dc76e0f). I am using an OS X 10.11.6 with node v7.7.4 & npm v4.1.2.

I realize it is a [recurring problem](https://github.com/jsbin/jsbin/issues?utf8=%E2%9C%93&q=Installation). I did find a [solution](https://github.com/jsbin/jsbin/issues/2952#issuecomment-274253329), but I would like to verify if it is current, as jsbin is now at 3.41.9 while the solution was for 3.11.23. Also will this work on a mac as the original poster was using a windows.

**Comment by remy** [comment]
Local installs don't work on anything above 0.10.
