### ISSUE TITLE
Error: forbidden 403: forbidden

### ISSUE THREAD

**Issue by kash40k** [jsbin/jsbin#3026]
the code is giving e that error when I run it.

**Comment by remy** [comment]
Theres no actual information in this issue. Will reopen if any detail is provided.

**Comment by kash40k** [comment]
[http://jsbin.com/puniko/edit?html,css,js](url)

I am using the text below to test the program, it would just go to that error code when I click on submit. the text below is the metadata text.
"Follow all the action of the 2016 Rio Olympics as our crew of reporters and photographers bring
you all the action every day.
In this spot, we will also highlight the best stories from our crew in Rio. With so much action,
some of these stories may have flown under the radar."
