### ISSUE TITLE
do while loops throw syntax errors

### ISSUE THREAD

**Issue by rexfordkelly** [jsbin/jsbin#3030]
Hi there, long time user, love the product. 

been playing around with loops recently, and I noticed a bug, when i use do while loops jsbin thinks there is an error.

The thing is, it not, here is an example i whipped together.

```
function last_fib( n, a,b,f,i ){
  a = 0, b = f = i = 1;
  do {
    f = (( a = b ) + ( b = f ));
  } while( ++i < n  );
  return n > 1 ? f : 1;
}
```

Here is a screenshot ![screen shot 2017-04-21 at 9 39 31 am](https://cloud.githubusercontent.com/assets/3839452/25287510/7a9dc664-2676-11e7-87c3-2bbaf8b23430.png)

**Comment by reod** [comment]
The same for me. My code is:

```javascript
function generateNIP() {
  const weights = [6, 5, 7, 2, 3, 4, 5, 6, 7];
  let numbers = [0, 1, 2, 3, 4,5 ,6 ,7 ,8 ,9];
  let nip = [], sum;
  
  do {
    numbers = shuffleArray(numbers);
    nip = numbers.slice(0, 9);
    sum = 0;

    for (let i = 0; i < weights.length; i++) {
      sum += nip[i] * weights[i];
    }

    nip[9] = (sum % 11);
  } while (nip[9] === 10);

  return nip.join('');
};
```

... and throws similar error:
```
"SyntaxError: Unexpected token {
    at https://static.jsbin.com/js/prod/runner-3.41.6.min.js:1:13926
    at https://static.jsbin.com/js/prod/runner-3.41.6.min.js:1:10855"
```

**Comment by remy** [comment]
I believe this is the loop protect being a bit brutal to the code. Include `// noprotect` at the top of the JS and it will remove the loop protection and your code should run (assuming it's error free).
