### ISSUE TITLE
I have autorun JS enabled but nothing appears in the output section

### ISSUE THREAD

**Issue by Ollymid** [jsbin/jsbin#3031]
I am learning Javascript, I have a DOM manipulating exercise that involves JS and CSS, but nothing shows up in the output section. I have had difficulty with JSbin on my system for other JS lessons too with code not showing in output or showing errors.
Can anyone help me understand why it is not working?
<img width="1226" alt="screen shot 2017-04-23 at 16 40 48" src="https://cloud.githubusercontent.com/assets/25374239/25314873/a55db3cc-2843-11e7-9557-82e7dd7568d3.png">

**Comment by LewisSharpe96** [comment]
`for (i=1; i <= 3; i++) {
  var boxElement = document.createElement('div');
  boxElement.className = 'box-' + i;
  
  
  document.getElementsByTagName('body')
  [0].appendChild(boxElement)
}`

You forgot to close your 'for' loop.
