### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by pvosbur** [jsbin/jsbin#3032]
I can no longer log in to my account via email

**Comment by remy** [comment]
Ok. You've not given me much to go on, so I'll suggest trying in a private window (incognito, etc), and see how you get on.

I'll reopen if you have more (or new) information to share to help diagnose. Thanks.

**Comment by pvosbur** [comment]
It appears that something got corrupted in my Chrome history. I cleared out all history and cache and I was able to login.
