### ISSUE TITLE
New to jsbin but it does not seem to work with ext libraries 

### ISSUE THREAD

**Issue by wavesailor** [jsbin/jsbin#3033]
Hi, I created a new jsbin but cannot get it to work. here is the jsbin link:
https://jsbin.com/sapepem/edit?html,css,js,console,output

and here is a link to the actual working demo: 
http://harshen.github.io/jquery-autofill/

Not sure how to resolve issue.

Thanks

**Comment by VoxExMachina** [comment]
Hey, did you find a solution for this? I've been using Crafty for a long time, and it just recently stopped working on my machine, but seems to work on other machines just fine and I can't figure out why...

**Comment by VoxExMachina** [comment]
Here's a link to some code that worked when I wrote it, but "Crafty is not defined" is now the error I get when I try to run it.

https://jsbin.com/qocusa/4/edit?html,js,output

**Comment by remy** [comment]
I don't get the error and it's animating for me. Is it possible the linked library was missing originally?

<img width="1364" alt="screen shot 2017-06-07 at 19 28 29" src="https://user-images.githubusercontent.com/13700/26894857-8b17b890-4bb7-11e7-8e47-6a187041adfd.png">
