### ISSUE TITLE
Option to prevent ⌘D from deleting the current line

### ISSUE THREAD

**Issue by dannyhope** [jsbin/jsbin#3035]
In most web browsers, ⌘D bookmarks the current page. In JS Bin, it deletes the current line 😿

**Comment by remy** [comment]
Danny, it's possible you're the last person who uses browser bookmarks! 😂

**Comment by dannyhope** [comment]
An absence of evidence is not evidence of absence. https://en.m.wikipedia.org/wiki/Evidence_of_absence

We could apply the same approach for this as for other risky shortcuts:

![image](https://user-images.githubusercontent.com/22055/29117405-f6aa46a8-7cf5-11e7-8a06-1deff3114cc3.png)

JS Bin’s panel switching shortcuts (⌘ 1, ⌘ 2 and so on) override the browser's tab switching shortcuts, so we show an option to deactivate JS Bin’s shortcut.

**Comment by remy** [comment]
This will be solved in v5. You'll be able to protect specific keybinding.
