### ISSUE TITLE
Failed to install jsbin on both windows 10 and centos 7.2 due to too old sqlite3 refer issue.

### ISSUE THREAD

**Issue by shoutrain** [jsbin/jsbin#3036]
following command to install jsbin on both windows 10 and centos 7.2:
```
npm install -g jsbin
```
Error rises when installing sqlite3.  By communication with node-sqlite 3, I found jsbin uses the old sqlite 3 2.x version.   If I use node 0.10.x, it works.

jsbin want us to work with 0.10.x?

**Comment by remy** [comment]
Only node 0.10.x is supported for production.
