### ISSUE TITLE
Error Installing Jsbin Locally

### ISSUE THREAD

**Issue by dynamicstm** [jsbin/jsbin#3037]
**The following error appears on the terminal** 

node-pre-gyp ERR! cwd /usr/local/lib/node_modules/jsbin/node_modules/sqlite3
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
/usr/local/lib
└── (empty)

npm WARN In sqlite3@2.2.7 replacing bundled version of readable-stream with readable-stream@1.0.34
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "jsbin"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 7

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

**The Log looks  as follows:**

8004 silly decomposeActions fetch assert-plus@1.0.0
8005 silly decomposeActions extract assert-plus@1.0.0
8006 silly decomposeActions test assert-plus@1.0.0
8007 silly decomposeActions preinstall assert-plus@1.0.0
8008 silly decomposeActions build assert-plus@1.0.0
8009 silly decomposeActions install assert-plus@1.0.0
8010 silly decomposeActions postinstall assert-plus@1.0.0
8011 silly decomposeActions finalize assert-plus@1.0.0
8012 silly decomposeActions fetch statsd-parser@0.0.4
8013 silly decomposeActions extract statsd-parser@0.0.4
8014 silly decomposeActions test statsd-parser@0.0.4
8015 silly decomposeActions preinstall statsd-parser@0.0.4
8016 silly decomposeActions build statsd-parser@0.0.4
8017 silly decomposeActions install statsd-parser@0.0.4
8018 silly decomposeActions postinstall statsd-parser@0.0.4
8019 silly decomposeActions finalize statsd-parser@0.0.4
8020 silly decomposeActions fetch string_decoder@0.10.31
8021 silly decomposeActions extract string_decoder@0.10.31
8022 silly decomposeActions test string_decoder@0.10.31
8023 silly decomposeActions preinstall string_decoder@0.10.31
8024 silly decomposeActions build string_decoder@0.10.31
8025 silly decomposeActions install string_decoder@0.10.31
8026 silly decomposeActions postinstall string_decoder@0.10.31
8027 silly decomposeActions finalize string_decoder@0.10.31
8028 silly decomposeActions fetch readable-stream@1.1.14
8029 silly decomposeActions extract readable-stream@1.1.14
8030 silly decomposeActions test readable-stream@1.1.14
8031 silly decomposeActions preinstall readable-stream@1.1.14
8032 silly decomposeActions build readable-stream@1.1.14
8033 silly decomposeActions install readable-stream@1.1.14
8034 silly decomposeActions postinstall readable-stream@1.1.14
8035 silly decomposeActions finalize readable-stream@1.1.14
8036 silly decomposeActions fetch readable-stream@1.0.34
8037 silly decomposeActions extract readable-stream@1.0.34
8038 silly decomposeActions test readable-stream@1.0.34

**Comment by remy** [comment]
Node 0.10 I'm afraid

**Comment by dynamicstm** [comment]
![screen shot 2017-05-08 at 1 32 34 pm](https://cloud.githubusercontent.com/assets/2429372/25800639/d389454e-33f2-11e7-854e-640448f7871a.png) This is my Node Version. I had it installed in a couple of weeks time.

**Comment by remy** [comment]
This code base requires node 0.10 and won't run on anything higher until someone merges a PR to support newer versions.

**Comment by vdavid** [comment]
How about now? What is the currently recommended Node version (or better, a link where it's specified)? I couldn't find it in the docs.
