### ISSUE TITLE
UI styling is broken

### ISSUE THREAD

**Issue by benjaminEwhite** [jsbin/jsbin#3042]
This is on Mac, Chrome v. 57.0.2987.133 (64-bit) and appears to effect all jsbins.

![screen shot 2017-05-10 at 9 14 23 am](https://cloud.githubusercontent.com/assets/960351/25900342/240bd5a8-3561-11e7-9649-78bf289d272f.png)

**Comment by nerdkid93** [comment]
There is an error in the console where Chrome refuses to load a jsbin service worker when not using HTTPS, which is not enabled by default. Not sure if this is related or not.

**Comment by bdjnk** [comment]
It isn't just Chrome. This is Firefox 53.0.2 (64-bit) on macOS Sierra 10.12.3
<img width="1131" alt="screen shot 2017-05-10 at 4 02 17 pm" src="https://cloud.githubusercontent.com/assets/620722/25918686/51307bd6-359a-11e7-8ba0-4e83fe7d2fdb.png">

**Comment by remy** [comment]
Anyone is welcome to exercise their CSS skills and send a PR to fix. I don't have this problem on my Mac which means i can't replicate easily to fix. 

I do know it's nothing to do with the failed service worker. Possibly try switching to https to see if that's related? (I can't tell from the second screenshot).

Will close in the hope for an amazing PR to fix 💪👍
