### ISSUE TITLE
Getting Started page is dead link

### ISSUE THREAD

**Issue by WaffleSouffle** [jsbin/jsbin#3044]
Navigating from http://jsbin.com/?html,output
http://jsbin.com/help/getting-started returns "This page isn't here"

**Comment by younesshakky** [comment]
thats happend when i try to navigate any page, like blog, keyboard shortcuts...

**Comment by HerrSubset** [comment]
Same for me, none of the links on top of the page at http://jsbin.com/?html,output seem to work. Except for the ones going to other websites.

**Comment by remy** [comment]
Fixed a little while ago in a user contributed PR.
