### ISSUE TITLE
Github login not working? Can't save? csrf token issue? 400 on /save?

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#3045]
I'm seeing (from the server side) that there's a number of csrf token failures, but I don't have enough info to replicate myself and haven't experienced it personally yet.

If you're seeing anything like this, please comment here with as much detail to help replicate, diagnose and debug.

Thanks in advance.

**Comment by justinbmeyer** [comment]
I am unable to login.  Did my best to make a screen shot of the network tab:


![google chrome - developer tools - httpjsbincom](https://cloud.githubusercontent.com/assets/78602/26001345/aaf0fa1c-36f1-11e7-8903-9ede51a041a4.gif)

**Comment by justinbmeyer** [comment]
And the console:

<img width="804" alt="developer_tools_-_http___jsbin_com__and_downloads" src="https://cloud.githubusercontent.com/assets/78602/26001399/dd2225f6-36f1-11e7-964a-530c5a0659ff.png">

**Comment by justinbmeyer** [comment]
I am ABLE to login in Firefox 53.0.  Chrome  57.0.2987.133 is the problem.  I can try other browsers if that will help.  

I notice that chrome doesn't like:

```
navigator.serviceWorker.register('/sw-runner.js', { scope: '/' });
> Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).}
```

However, if I run that in FF it works.

**Comment by remy** [comment]
That exception shouldn't be an issue, it's basically chrome saying it can't load the SW over http (which is not fatal to the running of jsbin).

If you do a manual switch to https, are you signed in (in Chrome)?

I wonder if there's a cached cookie that's causing an issue on Chrome…though I'm pretty sure I get the same thing in an incognito window.

**Comment by justinbmeyer** [comment]
@remy I am unable to login using https.  I get redirected back to `http`.  But if I change again to `https` I am still logged out.

**Comment by remy** [comment]
I don't remember how to get the cookie to stradle http and https, damn memory is totally failing me on this 😣

**Comment by remy** [comment]
The github auth callback hits http too, so now I'm not even sure how https is signed in if the session isn't shared…

**Comment by deniseeileen** [comment]
I'm also haveing this problem. When I go to login in via github, it basically just refreshes the page. I am using Chrome.

**Comment by sunlight200** [comment]
I have the same problem ,I can't log in to my jsbin using github account ,it reloads the page without letting me in ,I cleaned my browser cache lots of times but it didn't work also

**Comment by deniseeileen** [comment]
I was able to login using Chrome Canary! Still not working on regular Chrome through.

**Comment by Imiszkusz** [comment]
I think I have the same issue too.

**Comment by remy** [comment]
Not fixed yet. Fixed offline, production doesn't seem to do it.

**Comment by remy** [comment]
Hmm...incognito works.

I'm thinking this might be a corrupted cookie in my local chrome stable machine. Anyone able to do a clean test? (i.e. drop all cache on http + https)

**Comment by andydavies** [comment]
Clearing all the storage via DevTools (Application > Clear Storage - I checked everything) allows me to login with GH

**Comment by programmer5000-com** [comment]
Screencast here:
[SCREENCAST.zip](https://github.com/jsbin/jsbin/files/1038254/DELETEME.zip)

Could not resolve issue.

**Comment by colinbate** [comment]
I had the same issue. After confirming it worked in incognito mode, I tried clearing cookies and session storage, and that seems to have done it. I also logged out of GitHub and therefore needed to login there again, not sure if that was a factor or not.

**Comment by programmer5000-com** [comment]
Fixed form me after clearing storage of jsbin.com and github.com.

**Comment by zorg-kirill** [comment]
Deleting all cookies helped me, thanks!

**Comment by nickgrealy** [comment]
I only needed to delete cookies and site data for `jsbin.com` only.
