### ISSUE TITLE
Can not login with github

### ISSUE THREAD

**Issue by whatthefun** [jsbin/jsbin#3046]
I click login via Github but nothing happened.

**Comment by remy** [comment]
Try clicking it some more. Also, there's news on the @js_bin Twitter account. Ta.

**Comment by whatthefun** [comment]
yeah, I tired it many times, but it still can't login. And it happened to my friends, too. 
And I don't use Twitter. Thanks.

**Comment by remy** [comment]
Try manually switching to HTTPS
