### ISSUE TITLE
Embedded jsbin snippets not working

### ISSUE THREAD

**Issue by dumbNickname** [jsbin/jsbin#3047]
Hi,

I used few jsbin embedded code samples in one of my reveal.js presentations. When I opened the presentation today I saw that some errors are present in the console:

```
VM30398 jsbin-4.0.0.min.js:28 Uncaught TypeError: Cannot read property 'saveOnExit' of undefined
    at unload (VM30398 jsbin-4.0.0.min.js:28)
    at dispatch (VM30396 jquery-1.11.0.min.js:3)
    at r.handle (VM30396 jquery-1.11.0.min.js:3)
```

```
jsbin-4.0.0.min.js:28 Uncaught TypeError: Cannot read property 'pro' of undefined
    at jsbin-4.0.0.min.js:28
    at start (jsbin-4.0.0.min.js:28)
    at start.js?890:1
```

The embedded editor is not loading, it seems to be hanging. The last thing I see is the "dave"(?) loading indicator.  To be honest I was quite convinced that yesterday it worked just fine (however I might ignore the loading indicator when going quickly through the slides). I saw that js bin script contains today`s release date, so maybe it is related.

When I open those jsbins directly via the browser, everything seems to work fine.

Thanks in advance for any help/response.

**Comment by justinbmeyer** [comment]
@remy I'm also seeing this across all of CanJS's guides:

https://canjs.com/doc/guides/recipes/simple-weather-report.html

https://canjs.com/doc/guides/todomvc.html

Do you expect this to be working tonight (w/i 4 hours)?  Going through one of these guides at a [meetup](https://www.meetup.com/DoneJS-Chicago/events/239140963/?_af=event&_af_eid=239140963) tonight.  I can work around it, but if you can, let me know if I should prepare to.  Thanks!!

**Comment by remy** [comment]
Can replicate offline, but it's coming up on 11pm here and I've just seen these messages so not entirely sure I'll be able to fix before my brain gives out.

Annoyingly doesn't replicate before concat'ted scripts…

**Comment by remy** [comment]
Fix going live atm—takes a little longer due to server move and not all the parts are fully up and running.

**Comment by remy** [comment]
Fixed and live. Don't forget to donate! https://gratipay.com/jsbin/ ❤️
