### ISSUE TITLE
JS Bin help (and blog) is offline

### ISSUE THREAD

**Issue by stdavis** [jsbin/jsbin#3054]
![image](https://cloud.githubusercontent.com/assets/1326248/26069968/1e58e404-3960-11e7-8675-5d2516a017d1.png)

**Comment by davidalekna** [comment]
same with http://jsbin.com/blog and password reset and everything else!

**Comment by stdavis** [comment]
Also, this project is AWESOME! Thanks for all of the hard work that is put into it. :)

**Comment by vpicone** [comment]
I'm experiencing this as well.

**Comment by remy** [comment]
No need to comment on whether people are expecting this too. The help is down, it hasn't been upgraded in the process of the server upgrade. It was non critical to the move, and I'll get it back online when I can. I appreciate this isn't the perfect response, but if you do *need* to dig into the help, the source is [here](https://github.com/jsbin/learn/tree/master/public/help) (in markdown).

Please just use a 👍 on the original openning comment, and if we're super lucky, someone might take a run at the upgrade themselves and earn PR kudos.

Thanks.

**Comment by stdavis** [comment]
@remy What would it take? I'd be interested in chipping in. Can you point me in the right direction?

**Comment by remy** [comment]
The repo is jsbin/learn, it currently doesn't `npm run compile` under node@7
- mostly jade/pug errors. I'll push the fixed I've managed, but there's
more that I don't understand.

**Comment by stdavis** [comment]
Not sure if this is helpful or not but I tried to make some progress: https://github.com/jsbin/learn/pull/92

**Comment by remy** [comment]
Back thanks to @lheberlie and his PR.
