### ISSUE TITLE
While loop not working properly in JSBIN javaScript external but works well when embedded/inline

### ISSUE THREAD

**Issue by kwanjara** [jsbin/jsbin#3061]
ar count=1;
var superScript;
while(true){
	if(count === 1){
  	superScript="st";
    }
	else if(count===2){
  	superScript="nd";
    }
	else if(count===3){
  	superScript="rd";
    }
	else{
  	superScript="th";
  }
	var password = prompt("Password please");
	if(password!=="Rugera"){
    document.write("No access granted "+count+superScript+"<br>");
    count++;
 		if(count===5){
    document.write(count-1," attempts made. No more goes. Bye!")
    break;
    }
  }
	else{
    document.write("At ",count+superScript, " attempt access granted. Well done");
    break;
  }
}

**Comment by remy** [comment]
Your code was kinda hosed. This is how it should be written:

```js
var count = 1;
var superScript;
while (true) {
  if (count === 1) {
    superScript = "st";
  } else if (count === 2) {
    superScript = "nd";
  } else if (count === 3) {
    superScript = "rd";
  } else {
    superScript = "th";
  }
  
  var password = prompt("Password please");
  if (password !== "Rugera") {
    document.write("No access granted " + count + superScript + "");
    count++;
    if (count === 5) {
      document.write(count - 1, " attempts made. No more goes. Bye!")
      break;
    }
  } else {
      document.write("At " + count + superScript, " attempt access granted. Well done");
      break;
  }
}
```

**Comment by kwanjara** [comment]
Thank you remy. Did you try it in JSBIN? My problem is that it runs only once and breaks. But if I use it in other environments it works perfectly. Thank you again
