### ISSUE TITLE
JSBin 504'ed

### ISSUE THREAD

**Issue by programmer5000-com** [jsbin/jsbin#3062]
JSBin.com is returning a 504 error. Tried in Chrome 58.0.3029.110:
![image](https://cloud.githubusercontent.com/assets/25020067/26583400/1648a4d4-4513-11e7-9958-838766a25b40.png)

And in opera (from VPN):
![image](https://cloud.githubusercontent.com/assets/25020067/26583417/242e864a-4513-11e7-8d2c-23f58f8d03e4.png)

And in another chrome account (different cache, cookies, etc):

![image](https://cloud.githubusercontent.com/assets/25020067/26583449/4547e920-4513-11e7-9bdb-e891039bc2b9.png)

Any idea why?

CURLing JSBin.com over http and https hangs, too.

**Comment by remy** [comment]
Was down. No idea why, cpu keeps spiralling out of control. Still unable to replicate offline.

**Comment by programmer5000-com** [comment]
It's back up now...
