### ISSUE TITLE
Angular Js 

### ISSUE THREAD

**Issue by jayaprakash19** [jsbin/jsbin#3063]
Hi Team,

  This is jayaprakash ,In your angular live demo page output is not working.
  NOTE:Kindly include below script  in your live demo page.
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
   
Regards,
jayaprakash K
jayaprakash0419@gmail.com

**Comment by remy** [comment]
There's no team here, just me. I think you're referring to a single bin that someone has made, so you'll need to find the original author and get in touch with them.
