### ISSUE TITLE
css file not included in output.jsbin.com

### ISSUE THREAD

**Issue by larrykluger** [jsbin/jsbin#3064]
The output pane within the JSBin editor includes the CSS content and works great.

But accessing the jsbin via http://output.jsbin.com/_bin_code does not include the CSS?

It was working great 2 days ago, has something changed?

**Comment by larrykluger** [comment]
I figured out the problem (and how to reproduce) -- when I included a non-Javascript script in the HTML source, JS Bin didn't include the CSS content in the output.jsbin.com output.

It's interesting that the CSS pane was included in the Output pane of the editor though.

Here's the script tag that caused the problem:

`
    <script id="html-sample-doc" type="text/text">
<html>
    <head></head>
    <body style="font-family:sans-serif;margin-left:2em;">
        <h1>Agreement</h1>
        <p>I agree to the agreement.</p>
        <p style="margin-top:3em;">Signed: <span style="color:white;">-signer1sig-</span></p>
        <p style="margin-top:3em;">Name: <span style="color:white;">-signer1name-</span></p>
        <p style="margin-top:2em;">City: <span style="color:white;">-signer1city-</span></p>
    </body>
</html>
</script>
`

**Comment by remy** [comment]
Are you able to share the original bin ID? So that I can see how it actually constructed the output?

**Comment by larrykluger** [comment]
Hi @remy,

Here is a test case:  http://jsbin.com/nohoziw/edit?html,css,js,output 

Thanks!

**Comment by nevenaves22** [comment]
I cannot see the CSS rules on the output. Can you please correct me if I am doing something wrong?
![image](https://user-images.githubusercontent.com/79667817/129167648-72b46aca-66ec-4034-92d5-6b82c56fbb02.png)
