### ISSUE TITLE
Installing JSBin Globally

### ISSUE THREAD

**Issue by MoonTahoe** [jsbin/jsbin#3065]
I am trying to install jsbin via npm `sudo npm install -g jsbin`. I am getting errors on post-install about grunt modules being installed. Is this the best way to install globally so I can run the `jsbin` command to start the app?

```
   > grunt build

   >> Local Npm module "grunt-contrib-uglify" not found. Is it installed? 
   >> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
   >> Local Npm module "grunt-contrib-concat" not found. Is it installed?
  Warning: Task "concat" not found. Use --force to continue.

  Aborted due to warnings.
```

**Comment by remy** [comment]
I'd say, for now, git-clone this repo and `yarn install` from there (there's a `yarn.lock` file included).

**Comment by kelvinau** [comment]
I got the same error, but I don't see the yarn.lock file.
