### ISSUE TITLE
Delete an anonymous bin.

### ISSUE THREAD

**Issue by delatitude** [jsbin/jsbin#3066]
Hi,
I have created a bin to help a developer with their code as "Anonymous". Now I am being requested to delete this bin since the application is private for them. I tried deleting but still it keeps coming back.  Below  is the bin URL to be deleted.

http://jsbin.com/heraqesecu/edit?html,output 

Here is the the request from user to delete this bin.
https://geonet.esri.com/message/691666-re-display-query-results-in-a-gridtable?commentID=691666&et=watches.email.thread#comment-691666

**Comment by remy** [comment]
That's removed now for you.

**Comment by zhouzhesheng** [comment]
Hi, good day.
I have the same problem.
