### ISSUE TITLE
Unregistered DNS causing the jsbin runner to not work

### ISSUE THREAD

**Issue by jjr2000** [jsbin/jsbin#3067]
jsbin-dev.com has had its DNS records removed which are causing the js bin runner to not work as it relies on files that are served from this domain.

Console errors caused:
<img src="https://i.imgur.com/TfGLZtD.png" />

As we can see there are no DNS records:
[Link](https://who.is/dns/jsbin-dev.com)
<img src="https://i.imgur.com/jgdpR9k.png" />

**Comment by remy** [comment]
Wait, is this a local install or jsbin.com that you're referring to?

**Comment by jjr2000** [comment]
This is jsbin.com

**Comment by remy** [comment]
Should be fixed - sorry, explanation on #3068 .

**Comment by jjr2000** [comment]
Thanks for resolving this issue
