### ISSUE TITLE
JSBin not running

### ISSUE THREAD

**Issue by HenriqueMahl** [jsbin/jsbin#3068]
Sorry to bother but I can't seem to get jsbin to work right now... tried refreshing, restarting my pc, making new bin... Nothing runs. Typing into console does nothing apart from moving the console bar down. I have been using jsbin for like a week and did not have this issue at all, I don't know what changed. Any help is appreciated. Also I'm on firefox

![jsbin bug](https://user-images.githubusercontent.com/29104514/26841077-cd9a86f6-4abe-11e7-8a34-f4faadf77f61.png)

![jsbin bug2](https://user-images.githubusercontent.com/29104514/26841026-a4c6d00e-4abe-11e7-8d5b-ca2586c97089.png)

**Comment by echonox** [comment]
@HenriqueMahl You are not only one, suddenly non of my bins work not a single console.log..
![capture3](https://user-images.githubusercontent.com/9529847/26841437-c5bb6d80-4ae9-11e7-814c-823924437ff9.PNG)

**Comment by RikkiGoss** [comment]
I'm having issues too, no output and no error messages in console.

**Comment by hseirafi** [comment]
the same issue as echonox scripts sources are not loading seems to be down 
![capture](https://user-images.githubusercontent.com/5142177/26842777-d3b04268-4aa2-11e7-90b0-cd843a77a505.PNG)

**Comment by remy** [comment]
I think somehow versions got messed up. The current version running was supposed to be 4.0.4, but in memory it was still running 4.0.2 - and thus couldn't find the files to load. That's fixed now, and I believe this core issue should also be fixed because of it.

(thanks for the report).

**Comment by jjr2000** [comment]
I've already opened this issue in #3067

**Comment by HenriqueMahl** [comment]
yep, working fine now, thanks!!
