### ISSUE TITLE
JSBin simple store?

### ISSUE THREAD

**Issue by MoonTahoe** [jsbin/jsbin#3070]
First I just want to say JSBin is awesome! I love it. I've been trying to get creative and run a simplified local solution that just executes the code, but I am not sure if it is possible?

* Does JSBin require a store? 
* Are there other options as opposed to SQLLite or MySQL? 
* Is it possible to run locally without the account login link?

I am attempting to run JSBin locally as simply as possible. I am less concerned with account, versioning, previously saved bins, I just want to execute code and see it in the preview locally when there is not an internet connection available. Are there configuration settings, or a specific branch or tag that helps with this, or is MySQL always required for the store?

**Comment by remy** [comment]
1. Yes.
2. No (and as right now it's mysql only)
3. Yes (anonymous bins)
