### ISSUE TITLE
Should runner scripts be secure outside production?

### ISSUE THREAD

**Issue by Arthur-W-White** [jsbin/jsbin#3071]
I noticed the hardcoded value for https on runner's scripts is true. Should it be so? It causes the scripts to fail to load when running locally with the default OS settings on Ubuntu 16.04.
Thanks.
```
 app.get('/runner', function (req, res) {
    req.session.open = !!req.query.pro;
    res.render('runner', {
      scripts: res.app.locals.is_production ? false : scripts.runner,
      'static': sandbox.helpers.urlForStatic(undefined, true),
    });
  });
```

**Comment by remy** [comment]
Been like this for [over 2 years](https://github.com/jsbin/jsbin/commit/b2346d09fefef50da0613f814833be8795a9027a#diff-52503f2920dcbf5082edfc5670ede0f1R292) so I believe it's correct.
