### ISSUE TITLE
Pro upgrade broken

### ISSUE THREAD

**Issue by mooyah** [jsbin/jsbin#3072]
Hello, when I try to pay for a pro account, after hitting Submit, I receive a "Forbidden" error page. Please help!

**Comment by remy** [comment]
Sorry, I'm aware of this and am trying to get the fix live. It'll be a
little while though. I'll keep this issue open so others can track it until
it's fixed.

**Comment by jasjitsingh85** [comment]
Any updates on this yet? Any way we can have a trial upgrade account until this is fixed?

**Comment by remy** [comment]
No. Sorry.

**Comment by teleolurian** [comment]
Also seeing this issue - glad it's being worked on !

**Comment by simevidas** [comment]
This is probably related. I’ve tried to update my credit card info, but the https://jsbin.com/account/subscription page does not load.

**Comment by bjonesy** [comment]
I guess this is still an issue.  I have been trying to upgrade and still get the 403 error and Forbidden text.  Is there any alternative methods to get a pro account working since this issue seems to have been going on for a while?  

![screen shot 2017-07-23 at 5 06 37 pm](https://user-images.githubusercontent.com/4111688/28502888-d3f60586-6fc9-11e7-83ba-8cee84eb29ac.png)
![screen shot 2017-07-23 at 5 06 20 pm](https://user-images.githubusercontent.com/4111688/28502890-d8fd6100-6fc9-11e7-8a87-377c3abb9ada.png)

**Comment by remy** [comment]
No, but I'm working on it.

What pro feature are you trying to access our of interest?

**Comment by xtbe** [comment]
Pro upgrade not working here either, got the message "forbidden".

**Comment by remy** [comment]
@xtbe for the record *everyone* is unable to upgrade. It's not a weird bug, XSS is broken which is deep inside the application code.

**Comment by bjonesy** [comment]
Hey @remy, 

I was just wanting to make some of my bins private.  I honestly did not fully look into the pro features.  For now just making some of my bins private would be cool when I want.  Sorry for leaving another comment in this issue.  I was not trying to be annoying but just wanted to make sure this was still happening.

Thanks

**Comment by remy** [comment]
Not at all, this is useful because I'm working in on an entirely fresh
codebase, so everything is being reviewed, so knowing that private is a
priority is good.

**Comment by remy** [comment]
An update, not great, but an update: https://twitter.com/js_bin/status/892658815908413440

**Comment by remy** [comment]
Everyone tracking this - I'm about 80% the way through new jsbin, and working on the backend to handle upgrades.

My biggest question to **all** of you, I wanted to ask specifically what is it about Pro that you need to upgrade? (so that I can prioritise these components).

Thanks in advance.

**Comment by xtbe** [comment]
Hi,

Mostly interested in private bins

Regards,
Tom

**Comment by yuriMalakhov** [comment]
Hi,

**Embeds: SSL**, Private bins, Vanity URLs

Still got forbidden when trying to upgrade.

Regards,

**Comment by trekkabout** [comment]
The Pro feature I am most interested in is being able to have upload capabilities for assets

Cheers

**Comment by gjhead** [comment]
There is really nothing I *need* with the Pro account, just wanted to support the site and your efforts, really.

**Comment by remy** [comment]
Thanks

**Comment by dbcohen** [comment]
Private bins for me, also to support running locally

**Comment by code-read** [comment]
I also tried to upgrade and received the _forbidden_ error reported above.

I volunteer to help with the new jsbin rollout; let me know if I can help test or debug.

The **Pro feature** that tipped the balance for me was **horizontal panes** as covered [here](https://github.com/jsbin/jsbin/issues/404).  

I'm also interested in the ability to choose a font other than _Source Code Pro_, which suffers from thin horizontal elements on my screen (25" in portrait orientation at 1440x2560).  I find the _consolas_ font easier to read in this case.  I've published a workaround for FireFox [here](https://superuser.com/a/1260594/460302).

**Comment by remy** [comment]
Thank you for waiting, but I believe this is now fixed 👉 https://jsbin.com/upgrade
