### ISSUE TITLE
Problem with my code

### ISSUE THREAD

**Issue by SicariuseZ** [jsbin/jsbin#3074]
I'm beginning javascript and i do some exercise to train my self, but i've a problem.
My code have to ask the time to the user and give the time one seconde after the time entered.
And my code show my always "temps erroné" (that mean ~wrong time).
Here's my code : 

var hour = Number(prompt("heure actuelle?"));
var minute = Number(prompt("minute actuelle?"));
var seconde = Number(prompt("seconde actuelle?"));

function isTimeValid(hour, minute, seconde){
if((hour >= 24) || (hour < 0)) {
  return false
 }
if((minute < 0) || (minute >= 60)) {
  return false
 }
if((seconde >= 60) || (seconde < 0)) {
  return false
 }
}
function displayNextHour(hour, minute, seconde){
if((seconde >= 0) && (seconde < 59)) {
  seconde++;
} else if(seconde === 59) {
  seconde = 0
  minute++
  }
if(minute === 60) {
  minute = 0
  hour++
  }
if(hour === 24) {
  hour = 0
  }
 var temps = "Il est " + h + "h " + m + "m " + s + "s";
 return temps
}

if(isTimeValid()){
 console.log(displayNextHour(hour, minute, seconde))
}else{
  console.log("temps erroné")
}

**Comment by remy** [comment]
You'll need to ask a community like StackOverflow - as this is for issues with jsbin itself. Good luck.
