### ISSUE TITLE
Experimental feature about Jsbin api/save details of settings object

### ISSUE THREAD

**Issue by Chaslee4** [jsbin/jsbin#3077]
![image](https://user-images.githubusercontent.com/13342187/27320111-3f2077f0-55c7-11e7-8cb2-3496052fd422.png)
I am confused about what can i do in settings?

**Comment by remy** [comment]
For now, I wouldn't bother with them. It's undocumented and unsupported. It's for things like preprocessors, but it's not required in the `POST`.
