### ISSUE TITLE
In Firefox, onhashchange is sometimes skipped

### ISSUE THREAD

**Issue by pygy** [jsbin/jsbin#3078]
When `window.location.hash` is changed more than once during a single tick, every change should result in a distinct, async `onhashchange` event.

https://cdn.rawgit.com/pygy/bfe0555ab0ef9a6bfc2a7dc471d0b9d0/raw/e0fad9b45a3a6d5235b8acbc2a7b74137082f1ee/index.html

However, in JSBin with Firefox, the first event is dropped:

https://jsbin.com/jasoheqeci/edit?html,output

Putting the first link within in an iframe doesn't change anything:

https://cdn.rawgit.com/pygy/1062d716c704c642c83a823360e8bcfc/raw/c2684c0b7369520e1df6f25b09b6c2a4289a75b6/index.html

Edit: show the HTML source

**Comment by MillerAppBeta** [comment]
There is a solution, window.location.hash, window.location.href and widnow.location.WHATEVER are unsupported in JSBin. It happened to me once, it was so hard to debug, but I narrowed it down to it. You can use an alternative method of counting the character number of the hash, replacing all text to the left with null, and decoding the hash component.

**Comment by pygy** [comment]
I didn't have the time to investigate this last week, and I let it slip, sorry.

The first onhashchange still doesn't fire in Firefox. Not sure if the changes mentioned by the bot have been pushed yet.

https://jsbin.com/putuxusogu/1/edit?html,output
