### ISSUE TITLE
RxJS timer not working properly

### ISSUE THREAD

**Issue by meiriko** [jsbin/jsbin#3079]
I have a demo that involves RxJS timer and swithMap operations. For some reason it didn't seem to work right, the number of output values was too low and the gaps not according to the timer values.

https://jsbin.com/qayuwi/edit?js,console

To make sure it is not a bug on my end, I ran the same code on jsfiddle and got the results correct:

https://jsfiddle.net/meiriko/6pz981gd/268/

(you need to open the console to see them)

I also created a second version that uses the same script (without a umd):

https://jsfiddle.net/meiriko/y68t6y3e/

which produces the correct results as well.

**Comment by remy** [comment]
Try adding `// noprotect` to your JS - it's possible it's exiting the loop early.
