### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by Robtopbob** [jsbin/jsbin#3080]
I have installed jsbin on ubuntu 16.04 and faced a bug where livereload would not work.

After installing it on Windows 10 the console said that a runner.js could not be loaded. It was trying to get it over https and therefor could not load it. 

I modified (in ubuntu again) runner.html under /view by replacing

` <script src="{{../static}}{{.}}"></script>`
with 
`{{#scripts}}<script src="http://localhost:3000{{.}}"></script>`

Im sure thats a ugly solution but the live reload works like a charme now. Is this a bug or did I miss a configuration?

SSL ist set to false in config.local.json

**Comment by meoze** [comment]
Hi Robtopbob

I had the same issue on ubuntu 16.04 and I modified the runner.js script src path from '../static' to just 'static' and it works.
From
<script src="{{../static}}{{.}}"></script>
To 
<script src="{{static}}{{.}}"></script>

**Comment by zenpho** [comment]
I have similar problems with live reload / code casting / streaming not working, except I don't have a local installation. The problem occurs on the jsbin.com site.

An error appears at the receiving Developer Tools JS console tab `EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`
