### ISSUE TITLE
Update to pro account

### ISSUE THREAD

**Issue by yukisong192517** [jsbin/jsbin#3081]
Hello,
 I am a master student at the University of Southampton. I would like to use js bin as an important part of my final project. In order to make it editable, it seems that I need to apply for a pro account. Can I ask for any discount for education? 

Thanks

**Comment by tomscholz** [comment]
You can run it locally on your own machine...

**Comment by yukisong192517** [comment]
I need to run it on the server and allow all respondents to edit code.

**Comment by tomscholz** [comment]
Than host it yourself, but I do not think, that something likea discount for education exists. This is a community driven project and it is actual very easy to setup a server. If you are looking for cheap and good hosting try uberspace.de.
