### ISSUE TITLE
jsbin.com is extremely slow

### ISSUE THREAD

**Issue by artin-phares** [jsbin/jsbin#3084]
jsbin.com used to be very fast couple of months ago.  
now its hardly usable for me.

Chrome: v59  
Location: Russia, Saint-Petersberg  

I have no network connection issues with other sites.  

But my current workflow looks like this:  
(this time bins cannot open from 'My Bins' list at all)

![gif](https://user-images.githubusercontent.com/671082/28125496-71bd5ec0-672f-11e7-83b7-c1ca55fdf00a.gif)

What happened?

**Comment by remy** [comment]
Oh, I've updated the web site so that users who contribute get less latency. It was super complex to implement too.

**Comment by artin-phares** [comment]
Still very slow. Didn't noticed any change.  

Bin open time >= 15sec (from 'My Bins' or direct URL),  
with 50% chance of success (otherwise just stop loading).


![gif](https://user-images.githubusercontent.com/671082/28175297-87496f7c-67fc-11e7-9172-6ebca17e9712.gif)

**Comment by artin-phares** [comment]
Last couple of days jsbin.com was blazingly fast again.
Thanks!
