### ISSUE TITLE
How does Web Console work?

### ISSUE THREAD

**Issue by kchojhu** [jsbin/jsbin#3085]
I'm trying to create my own (probably crappy) JavaScript online IDE.  I'm trying to understand how JSBIN executes the code and outputs into the web console.  I've really tried the starting point but I just couldn't find it.  Could someone give some hints on where I should start looking at?  Thanks again!

**Comment by remy** [comment]
Nest to read the source code. Can't really explain other than that - it was a lot of hacking.
