### ISSUE TITLE
504 returned

### ISSUE THREAD

**Issue by acidsound** [jsbin/jsbin#3089]
http://output.jsbin.com/gavire
http://output.jsbin.com/cisico

![image](https://user-images.githubusercontent.com/623157/28499415-409397a0-6ff0-11e7-9904-20fcc4ba267a.png)

Most of old pages returned 504 errors. but new don't.

**Comment by remy** [comment]
Should be back now. Sorry. Also https://twitter.com/js_bin/status/892658815908413440
