### ISSUE TITLE
Problems installing, need mysql

### ISSUE THREAD

**Issue by Indieberrie** [jsbin/jsbin#3090]
I found your great tool online, used it there and wanted to have it localy.
After trying to instal jsbin with npm I ran into this problem #3065
I used instruction from that issue and installed it with yarn without errors. Running that with node i get this error:
```
C:\Users\Korlsnlk\Downloads\jsbln-master> node lib\app
Config from C:\Users\Korlsnlk\Downloads\jsbln-master\llb\conflg.local.json 
C:\Users\Korlsnlk\Downloads\jsbln-master\llb\store.js:5
   throw new Error('floptions.adapter} is not supported, only mysql as of v4.");
   ^ 
Error: sqlite is not supported, only mysql as of v4.
   at new Store (C:\Users\Korlsnlk\Downloads\jsbln-master\llb\store.js:S:11) 
   at createStore (C:\Users\Korlsnlk\Downloads\jsbln-master\llb\store.js:93:10) 
   at Object.canonymous> (C:\Users\Korlsnlk\Downloads\jsbln-master\llb\app.js:16 :37) 
   at Module._complle (module.js:569:30) at Object.Module._extenslons..js (module.js:580:10) 
   at Module.load (module.js:503:32) 
   at tryModuleLoad (module.js:466:12) 
   at Functlon.Module._load (module.js:458:3)
   at Function.Module.runMaln (module.js:605:10) 
   at startup (bootstrap_node.js:158:16) 
```
I even tried using npm to install mysql manually which is listed in yarn.lock after, before, with -g and without.
Is there a way to fix npm installation (I haven't tryed manualy installing grunt-cotrib-jshint and others and don't know how in npm_modules if jsbin is not generated because of error in referenced issue.
Or can i fix this mysql problem?

Btw, I have one more question, can I share bins that I create on my local machine and is it possible to restrict sharing that to anyone?

**Comment by LC-shao** [comment]
@Indieberrie  hi, you should change the config file (config.local.json) in which, edit as below:
`  "store": {
    "adapter": "mysql",
    "sqlite": {
      "location": "jsbin.sqlite"
    },
    "mysql": {
      "host": "localhost",
      "user": "root",
      "password": "",
      "database": "jsbin",
      "charset": "utf8mb4",
      "collate": "utf8mb4_unicode_ci"
    }
  },`

the adapter, should be 'mysql', if you use mysql local.

**Comment by Indieberrie** [comment]
It works, thank you a lot!
