### ISSUE TITLE
real newbie! How do I make http://jsbin.com/ecenux/2/edit?html,css,js work, please?

### ISSUE THREAD

**Issue by NotherCodingNovice** [jsbin/jsbin#3094]
Hello

I'm not sure whether this is the right place for my question, but it'll just have to do for the moment :-/

I want to make a pretty fraction like the linked example, but....
I've copied in the html and the css, but I don't know what to do next to make the smart dividing bar.

Would someone kindly explain what I should do next?

Thanking you in advance for your help (and the lesson)
regards
NotherCodingNovice

**Comment by remy** [comment]
Best to file on stackoverflow. This issue tracker isn't for code help, but for software bugs in jsbin itself.
