### ISSUE TITLE
Can not add external js file which has the "console.js" in url

### ISSUE THREAD

**Issue by wtfil** [jsbin/jsbin#3095]
example
```html
<script type="text/javascript" src="//rawgit.com/wtfil/mobile-console/master/console.js"></script>
```

The actual url replaced with `https://rawgit.com/wtfil/mobile-console/master/window.runnerWindow.proxyConsole.js`

**Comment by remy** [comment]
This will be fixed in v5. https://twitter.com/js_bin/status/892658815908413440
