### ISSUE TITLE
'Login or Register' Broken (Transient Error?)

### ISSUE THREAD

**Issue by idfubar** [jsbin/jsbin#3097]
The interface is presenting a message stating: "Sorry, there was an error while accessing the database with your GitHub id (Error: ER_HOST_IS_BLOCKED: Host 'ec2-34-203-44-8.compute-1.amazonaws.com' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts')" when attempting to provide valid credentials; is the problem transient in nature & will the application "fix itself" automatically when the error condition has passed?

**Comment by Phissix** [comment]
having the same problem and i am lost

**Comment by unitario** [comment]
Same problem for me. Also cannot open "My Bins" while logged in.

<img width="558" alt="login-error" src="https://user-images.githubusercontent.com/9481000/29063588-a7e45a88-7c26-11e7-8424-f7ced0595bf5.png">

**Comment by remy** [comment]
Yay. New low. I'll fix as soon as I'm at my computer.

**Comment by remy** [comment]
It's "working" again. I use the word working in the loosest terms. More info [here](https://twitter.com/js_bin/status/892658815908413440)
