### ISSUE TITLE
'My Bins' doesn't open

### ISSUE THREAD

**Issue by Imiszkusz** [jsbin/jsbin#3099]
Hi guys,

I receive the following errors - see attached (I use Chrome, but I tried it in Firefox too, seems to be the same)
I need it really now ... it still worked yesterday evening.

Thank you in advance for any help!

![jsbin-mybins-doesn t-open-firefox](https://user-images.githubusercontent.com/11348251/29058311-ecd135ba-7c0f-11e7-87e6-dc70067ef967.PNG)

![jsbin-mybins-doesn t-open](https://user-images.githubusercontent.com/11348251/29058291-d5eaa958-7c0f-11e7-873e-5a9951e0fc24.PNG)

**Comment by remy** [comment]
No "guys" here, just me. It should be working again, though [this](https://twitter.com/js_bin/status/892658815908413440) is also relevant.
