### ISSUE TITLE
How to set static js files' proto to http?

### ISSUE THREAD

**Issue by g8up** [jsbin/jsbin#3101]
I'm deploying jsBin in local env (centos) under `http` protocol.
https://github.com/jsbin/jsbin/blob/b8d55a05ca09520a7d619ce99fbe0dceec9263d9/lib/routes.js#L338
I try to change line 338 to 
> 'static': sandbox.helpers.urlForStatic(undefined, !true),

but it doesn't work.
```html
<body style=""><div id="sandbox-wrapper"></div>
  <script src="http://true/js/vendor/polyfills.js"></script>
<script src="http://true/js/vendor/stringify.js"></script>
<script src="http://true/js/runner/utils.js"></script>
<script src="http://true/js/vendor/loop-protect.min.js"></script>
<script src="http://true/js/runner/proxy-console.js"></script>
<script src="http://true/js/runner/processor.js"></script>
<script src="http://true/js/runner/sandbox.js"></script>
<script src="http://true/js/runner/runner.js"></script>
<script src="http://true/js/runner/index.js"></script>

</body>
```

**Comment by nitramf** [comment]
Same problem here. I think it is a bug, because if the config has ssl = false there should be no https as this causes cross-origin problems.

**Comment by hush2** [comment]
Change it here:

https://github.com/jsbin/jsbin/blob/ce2ba94fda7a1d0a0b56211d7467efad57038901/lib/helpers.js#L139-L142

**Comment by g8up** [comment]
>      'static': sandbox.helpers.urlForStatic(undefined, true),
the second param should read from `url.static` in `config.json`
