### ISSUE TITLE
Cannot get my loop to work

### ISSUE THREAD

**Issue by Kobuksan** [jsbin/jsbin#3104]
var bottlesOfBeer = 99

for (bottlesOfBeer <=99; bottlesOfBeer > 0; bottlesOfBeer--) {
  if (bottlesOfBeer > 1) {
    var bottleRemaining = bottlesOfBeer - 1;
    console.log(bottlesOfBeer + " bottle(s) of beer on the wall, " + bottlesOfBeer + "bottle(s) of beer, if one of those bottle(s) should happen to fall, " + bottleRemaining + "bottle(s) of beer on the wall.");
  } else if (bottlesOfBeer = 1) {
     console.log("One bottle of beer on the wall, one bottle of beer, if this one bottle of beer should happen to fall, there'll be no more bottles of beer on the wall.");
}

**Comment by kauffmanes** [comment]
Are you sure you're not just missing a final bracket? It worked for me.

```
var bottlesOfBeer = 99;

for (bottlesOfBeer <=99; bottlesOfBeer > 0; bottlesOfBeer--) {

  if (bottlesOfBeer > 1) {
    var bottleRemaining = bottlesOfBeer - 1;
    console.log(bottlesOfBeer + " bottle(s) of beer on the wall, " + bottlesOfBeer + "bottle(s) of beer, if one of those bottle(s) should happen to fall, " + bottleRemaining + "bottle(s) of beer on the wall.");
  } else if (bottlesOfBeer = 1) {
    console.log("One bottle of beer on the wall, one bottle of beer, if this one bottle of beer should happen to fall, there'll be no more bottles of beer on the wall.");
  }
  
}
```

[working bin](http://jsbin.com/rowudus/edit?html,js,console)
