### ISSUE TITLE
JS Bin Snapshots Not Viewable (Opening Previously Saved Bin Reveals Inconsistent Code?)

### ISSUE THREAD

**Issue by idfubar** [jsbin/jsbin#3105]
When attempting to open a previously saved (snapshot) bin the editor presents code which is not consistent with the (correct) code rendered/displayed by the browser when the snapshot is visited via URL; a reproducible example is 'https://output.jsbin.com/qubefab/21' (and a later revision, 'https://output.jsbin.com/qubefab/28') - with loading of the early revision displaying CSS which was not associated with the page until later & the later revision missing the element for which that CSS applies (an '<img>' tag) as well as the correct (revised) page title.

Does the observed behavior reflect a corruption issue with the application (i.e. with 'jsbin.com', e.g. a database table) - or possibly some other problem?  Ideally the snapshots in question would be accessible for viewing in the editor (as there seems to be some processing to make the code coherent for a given browser & copying/pasting from the displayed page would, obviously, grow increasingly complicated when working with older code); is it possible to achieve without recreation?

PS:  This issue is similar to 'https://github.com/jsbin/jsbin/issues/2802' & 'https://github.com/jsbin/jsbin/issues/2968' suggests that snapshot editing shouldn't be expected'... and https://github.com/jsbin/jsbin/issues/541' suggests there might be a more fundamental change pending that would obviate the need for specific attention... but (and please do correct the thinking if needed) the conceptual metaphor of a "snapshot" being viewable does not seem inconsistent with the idea of being able to use such a snapshot as a starting point for making additional changes (even if doing the same amounts to creating a new bin and/or snapshot).

PPS:  Thanks in advance for any time & attention afforded the same.

**Comment by remy** [comment]
I'm struggling to follow what you're actually asking or trying to diagnose. Can you give it another shot, but perhaps a little less dense and shoot for one question if possible.

**Comment by idfubar** [comment]
Viewed from the browser, a given snapshot bin (e.g. 'https://output.jsbin.com/qubefab/21', 'https://output.jsbin.com/qubefab/28', etc.) is correct & consistent; when accessed via the editor the HTML/CSS displayed is not consistent with the snapshot (i.e. code at the time the snapshot was taken), which seems incorrect.  

Is the observed correct & consistent with the design & implementation and, if not, can it be made so (either by change to design, i.e. defect remediation, or implementation, e.g. databse table with inconsistent data)...?

**Comment by remy** [comment]
So: no, yes, no, yes, no.

Hope that helps. Look out for v5 in a month or so.

**Comment by idfubar** [comment]
Yes, that definitely points matters in the correct direction... but can any additional information be provided about why the observed occured?

(In this particular case the previous bins/snapshots are being accessed for a 'W3Cx: HTML5.0x HTML5 and CSS Fundamentals' course project; taking a snapshot allows for linking to a given step of the course's recipe project... but, given that other coursework is interspersed - and the project itself involves some steps that are non-linear, i.e. building on changes which pertain to something other than the most recent version, an attempt to review previous work from within the editor resulted in discovery of the application itself being corrupted - despite some basic troubleshooting & a very simple workflow of snapshoting submitted/linked bins and deleting the rest.)

= /

PS:  Gratipay will be sent shortly - an issue with Github (the sharing of all permissions with third-party applications by dfeault for organizations created before third-party application support) was making registration a choice between looking the other way & leaving an unmaintained organization (w/o any idea of whether it can be joined again).

**Comment by remy** [comment]
Can you point me to the fundamentals link? I can test these in the new
version of jsbin that I'm working on.

**Comment by idfubar** [comment]
Course is accessed via 'https://courses.edx.org/courses/course-v1:W3Cx+HTML5.0x+1T2017/course/' (URL for information about it is 'https://www.edx.org/course/html5-css-fundamentals-w3cx-html5-0x'); JS Bin is specifically referenced for use on course assignments... but no particular directions/instructions are suggested for the the purpose of the same.

PS:  Just to make certain could you please confirm that, at present, when accessing a snapshot via the editor there is reason the code displayed would not be consistent with the code at the time of the snapshot...?

**Comment by remy** [comment]
As for you question, if I followed it correctly: confirmed.
