### ISSUE TITLE
Password Reset Broken

### ISSUE THREAD

**Issue by snomu** [jsbin/jsbin#3108]
Password reset appears to be broken. I clicked "forgot my password," then clicked the link in the email. This directed me to a broken page. Now my old password won't work either and I'm locked out. Help!

**Comment by kenwhipday** [comment]
I've got the same problem too. I receive the email, click the link and get taken to a page displaying the message 

Found. Redirecting to

Then nothing happens.  
Any chance of fixing it?

**Comment by boltronics** [comment]
Same problem here. The password reset link from jsbin.com is busted. And our account just auto-renewed for another year while we are locked out.
