### ISSUE TITLE
please help to delete anonymous bin 

### ISSUE THREAD

**Issue by joeytony** [jsbin/jsbin#3117]
hello, good day.

I have created some bins as "anonymous". 
Now I am being requested to delete these bins since they are gone public and should remain private. 
I tried deleting but failed. Can you help me to delete those bins below? thank you very much.

https://jsbin.com/faqanoqiki/1/edit?html,output
https://jsbin.com/hacabedako/1/edit?html,output
https://jsbin.com/kupipun/1/edit?html,output
https://jsbin.com/loreleyilu/1/edit?html,output
https://jsbin.com/mipebobahu/1/edit?html,js,output
https://jsbin.com/ricuhoqato/1/edit?html,output
https://jsbin.com/tawidevona/1/edit?css,js,output
https://jsbin.com/wayomur/1/edit?html,output
https://jsbin.com/wuvuvokufa/edit?html,output
https://jsbin.com/xejatahaka/1/edit?html,output

**Comment by remy** [comment]
The bins weren't anonymous, you were anonymous.

I'll try to delete them this week (I'm away ATM)

**Comment by joeytony** [comment]
Thank you for your reply. I got it.
Please send one more reply after deleting these bins.
I have to report the result of that.
Thank you for your cooperation.

**Comment by remy** [comment]
Done.

**Comment by joeytony** [comment]
Thank you very much.
I can report that.
Thank you again.
