### ISSUE TITLE
Maximum Bin Size

### ISSUE THREAD

**Issue by richardkaplan** [jsbin/jsbin#3119]
If I upgrade to Pro, is the limit on maximum bin size waived?

**Comment by remy** [comment]
How big is the text you're uploading?

**Comment by richardkaplan** [comment]
It is 95K


Separate though related question - I see on your website that you sometimes do consulting projects involving Javascript.  Are you familiar with Applescript and Devonthink Pro Office?  I would like to build what would essentially be a programmable word processor for academic writing; this would utilize Javascript/jsbin as well as  automation of the Devonthink software via Applescript.    MIght that be something you are interested in?


________________________________
