### ISSUE TITLE
Javascript array.

### ISSUE THREAD

**Issue by TVK5300** [jsbin/jsbin#3124]
I want to use the code of [http://jsbin.com/fopugihuji/edit?html,js,output](http://jsbin.com/fopugihuji/edit?html,js,output) on my website. I try to create a Google maps with duplicate markers that can have more labels for the infowindow. Each week the map is rebuild according to the number of soccermatches of that week.

When I change manually the var locations on [http://jsbin.com/fopugihuji/edit?html,js,output](http://jsbin.com/fopugihuji/edit?html,js,output) with one marker in Belgium and 3 labels, it works. But my markers and labels come from  MYSQL tables (2 PHP-arrays which are showed on the testpage: [https://www.doskobeveren.be/dupmark/](https://www.doskobeveren.be/dupmark).

How to send these arrays to javascript in the format: `// locations [[ latitude, longitude, label]*]`?

**Comment by remy** [comment]
You probably want to ask something like the StackOverflow community as this isn't a bug with jsbin as far as I can tell.
