### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by justinbmeyer** [jsbin/jsbin#3127]
About 9 of 10 refreshes shows:

![502_bad_gateway](https://user-images.githubusercontent.com/78602/31142938-5a4e4e54-a841-11e7-832d-82f7a1bd33ca.png)

**Comment by Zoratul1** [comment]
![image](https://user-images.githubusercontent.com/32495183/31143376-7472d1c4-a87d-11e7-8a8a-dfb4d8ad0deb.png)
