### ISSUE TITLE
Object.freeze doesn't throw exception in strict mode when frozen object is mutated

### ISSUE THREAD

**Issue by JamesJefferyUK** [jsbin/jsbin#3129]
When using `Object.freeze()` in strict mode it's not throwing an exception when I attempt to modify a property of a frozen object.

[MDN says][1] attempting to mutate a frozen object will throw a `TypeError`:

> In strict mode such attempts will throw TypeErrors

Here's some simple code below: 

    'use strict';
    
    //jshint esnext:true
    const func = () => {
      const o = { id: 0 };
      Object.freeze(o);
      o.id = 3;
    };
    
    func();

**Demo:** https://jsbin.com/fobokipive/edit?js,console

The code does not throw any `TypeError` as it should. I am using Opera which is based on Chromium.

  [1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by remy** [comment]
I believe new (unreleased) jsbin handles this correctly.

<img width="910" alt="screen shot 2018-01-19 at 16 50 13" src="https://user-images.githubusercontent.com/13700/35161700-e3b55d94-fd38-11e7-997d-c68cf9a173c4.png">
