### ISSUE TITLE
502 Bad Gateway --  nginx

### ISSUE THREAD

**Issue by Jadog1** [jsbin/jsbin#3130]
Projects aren't saving, and many times, I can't go full screen. Is it just me, or is there an issue with the server?

**Comment by glvangorp** [comment]
I cannot even load the app at all. I tried clearing my browser cache and restarting my browser to no avail. I'm experiencing a similar situation as you.

**Comment by Jadog1** [comment]
As of right now, yes I can open everything. But it's been working on and off for almost a week now, and when it does work, everything loads slowly (Like when opening the project in a new tab, or initially loading jsbin, or when switching projects). I too have cleared browser cache. 

I have only been using chrome, but I opened up internet explorer and it worked in there, but was slow. It may have just been slow because its internet explorer though lol

**Comment by remy** [comment]
Honestly, it's been more than a few days. I'm in the process of a complete
rewrite which relieves the server from doing any work. Just it's a little
way off still…

**Comment by Jadog1** [comment]
@remy oh ok. Thanks for working on it! I understand it probably is a pain to do lol. Good luck and godspeed.

**Comment by DaAwesomeP** [comment]
@remy I think that you should put a "site under reconstruction" page up instead of just leaving the 502 error there.
