### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by chirovan5231** [jsbin/jsbin#3134]

**Comment by chirovan5231** [comment]
I have a problems with http and css editor  . Don't see on the screen this sections . Attas a printscreen. What  can I do ?
![image](https://user-images.githubusercontent.com/32265942/31432246-c70b5a76-ae7e-11e7-9721-e9a3cb56879c.png)

**Comment by bizlina** [comment]
I have the same problem. After accessing jsbin.com just the top of the bin is rotating - but nothing happens

**Comment by cyrilmesvayn** [comment]
#3135 related.
Also tested with Firefox 55.0.3. start.js takes forever to load, and then fails.

**Comment by Jadog1** [comment]
#3130 
Reason described there. The owner is working on re-writing some code to lessen work done by server
