### ISSUE TITLE
js bin keeps loading for ever

### ISSUE THREAD

**Issue by arunkumar413** [jsbin/jsbin#3135]
Hi Team,

I'm using chromium and firefox browser on Ubuntu 16.04. The Js bin keeps loading and never shows up the HTML, jsbin and css panels. The console doesn't show any error. However, in the network panel, the start.js file returns a 504 error.

Thanks,
Arrun 

![screenshot](https://user-images.githubusercontent.com/7776779/31445295-6133b10c-aebb-11e7-83af-cc8486376d9c.png)
![screenshot from 2017-10-11 19-33-19](https://user-images.githubusercontent.com/7776779/31445324-71b7e098-aebb-11e7-88f9-b02db8403f10.png)

**Comment by Jadog1** [comment]
#3130 
First off, if you didn't intentionally install chromium, it may be a virus, "The Chromium browser is actually the “alpha” version of modern Chrome. It was designed to be open source, meaning you can tweak it in all sorts of ways. In your case it may have been installed on your PC an injected with malicious code. Chromium itself is a completely legitimate program. The one on your PC may be not."

But the owner is in the process of rewriting the code for jsbin, as shows in the reference

**Comment by MillerAppBeta** [comment]
Dave, the JS Bin bot
504: Dave didn't come back quickly enough

This is embarrassing, you've asked for something and I've spent too long getting it. Maybe I got distracted by some pretty lights, but you'll never know.

Do check status.jsbin.com, but do ping @js_bin if this problem keeps happening.

If you want to add details please add it to the issues page and add any additional information you can to help diagnose this slackness.

**Comment by MillerAppBeta** [comment]
That's what you get when you try to log in. I have been automatically signed out (?), usually it keeps me signed in. I can't sign in anymore either. It never loads. I am using Microsoft Edge 14, on the Anniversary Update Windows 10.

**Comment by arunkumar413** [comment]
@Jadog1 

what about Firefox. The issue occurred on firefox as well. Do you think firefox is also malicious? I checked the chromium version and it says it's an official build. 
![screenshot from 2017-10-11 20-47-32](https://user-images.githubusercontent.com/7776779/31449904-c1057a16-aec5-11e7-89c3-18519c11d177.png)


Also I just noticed that the login form data is being revealed by the debug tool though the jsbin page is loaded with https.

![screenshot from 2017-10-11 20-42-44](https://user-images.githubusercontent.com/7776779/31449710-44a2435a-aec5-11e7-8cd2-bc89bd78b789.png)

**Comment by MillerAppBeta** [comment]
No, it isn't Firefox or Chrome that's doing the stuff. Everyone is having problems, I think.

**Comment by MillerAppBeta** [comment]
Isn't JSBin usually loaded over http?

**Comment by arunkumar413** [comment]
It's always https(secure). I think the issue is with the loading of the start.js file Seems like the letters 'e8c7' are added by mistake.

`<script async defer src="https://jsbin.com/bin/start.js?e8c7"></script>`

![screenshot from 2017-10-11 20-56-18](https://user-images.githubusercontent.com/7776779/31450401-f2530290-aec6-11e7-9903-9a2e38de8ad4.png)

**Comment by Jadog1** [comment]
@arunkumar413 my special code instead of e8c7 is 25b4. So i think it is intentional.

`<script async defer src="https://jsbin.com/bin/start.js?25b4"></script>`

**Comment by MillerAppBeta** [comment]
no, i think that's an id. what's the error?

**Comment by MillerAppBeta** [comment]
the server is probably responding with a 404.

**Comment by Jadog1** [comment]
@arunkumar413 sorry for late reply, i didn't see the earlier message. What i meant is just be wary of chromium, it's been known to cause lots of problems. The problem with signing in and stuff has to do with the server, not with the browser. And I'm not sure if the login file is bad to have up or not

**Comment by MillerAppBeta** [comment]
login is not working at the moment.

**Comment by arunkumar413** [comment]
Is jsbin down all over the world or only for few users?

**Comment by remy** [comment]
All.
