### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Hum4n01d** [jsbin/jsbin#3137]
I'm getting a 502 Bad Gateway when trying to visit https://jsbin.com. Anybody else?

**Comment by yingming25** [comment]
Me too! pelease  save it!

**Comment by MillerAppBeta** [comment]
SAME from yesterday

**Comment by yingming25** [comment]
I can use now.

**Comment by Hum4n01d** [comment]
@yingming25 Thanks, it's working now

**Comment by MillerAppBeta** [comment]
YAY!
