### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [jsbin/jsbin#3142]
The default "memory" storage for sessions suffer a well known memory leak. As pointed out on the `express-session` documentation. The usage is discouraged in production.

Consider switching to a leak-proof in-memory store: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by remy** [comment]
This isn't used in production. The local install is for personal dev purposes, and if you wish to extend and put it live: more power to you 👍
