### ISSUE TITLE
Syntax highlighting, commenting, and line numbers not working

### ISSUE THREAD

**Issue by csndra0504** [jsbin/jsbin#3144]
Hey there. It seems that JSBin is able to run my code and spit out the correct errors but syntax highlighting, commenting shortcut, and line numbers are not working today even though I have these features turned on in my settings.

![screen shot 2017-10-26 at 13 06 18](https://user-images.githubusercontent.com/1786399/32066698-a2a20ae6-ba4e-11e7-996e-c7e43ee3b6fe.png)

Any ideas why this might be happening? 

Thank in advance! :)

**Comment by remy** [comment]
You've switched to textarea mode. Open the big top menu (click on the jsbin icon in the menu) then uncheck textarea editor mode

**Comment by csndra0504** [comment]
oh wow thank you!
