### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by csndra0504** [jsbin/jsbin#3145]
Hey there! Seems like JSBin is having a problem? Thanks in advance for your response. Cheers!

<img width="754" alt="screen shot 2017-11-01 at 08 52 01" src="https://user-images.githubusercontent.com/1786399/32275542-02ee4832-bee2-11e7-8084-e66191996002.png">

**Comment by remy** [comment]
Late to reply, but since back online

**Comment by letzfets** [comment]
bery old issue, but appears again: tested in in safari & chrome
