### ISSUE TITLE
JSbin is down

### ISSUE THREAD

**Issue by superoo7** [jsbin/jsbin#3148]
The official website is down
![screen shot 2017-11-06 at 7 56 27 am](https://user-images.githubusercontent.com/15358452/32420621-01be8726-c2c8-11e7-8449-5ea840ea5022.png)
![screen shot 2017-11-06 at 7 56 19 am](https://user-images.githubusercontent.com/15358452/32420622-01f30fc8-c2c8-11e7-901c-897e20e22332.png)

**Comment by bammoo** [comment]
Is working.

**Comment by superoo7** [comment]
I'll close this issue
