### ISSUE TITLE
URLs in bin view are wrong... add'l slash

### ISSUE THREAD

**Issue by pfoser** [jsbin/jsbin#3159]
The links in the bin list have an add'l slash, e.g., http://jsbin.com**//**sdfsds

**Comment by remy** [comment]
Can I get a screenshot? I'm not sure what the "bin view" is.

**Comment by Utopiah** [comment]
I'm assuming `xalosi/5/edit` instead of `https://jsbin.com/xalosi/5/edit` in the `My Bins` view.

![image](https://user-images.githubusercontent.com/1076655/33473133-854a5d84-d675-11e7-8840-31a5d3730405.png)

**Comment by remy** [comment]
Closing as dupe of #3160.
