### ISSUE TITLE
Bins lately don't always autosave

### ISSUE THREAD

**Issue by jayphelps** [jsbin/jsbin#3162]
(Pro account user here)

In the last month or so I've noticed my bins often not autosaving. I can't always reproduce it but it seems to happen when I've cloned another existing bin of mine. After cloning it I'll make some modifications without manually doing any saving or snapshotting. If I refresh the page in that window, the changes often remain for that particular window (but not sure if _always_). But if I leave the page or open the same URL in another tab the changes are gone and it's back to the original cloned state. I can't be certain when it started as I at first chalked it up to user error since I sometimes have tons of bins open. But now I'm seeing it quite often.

e.g. I can consistently reproduce it with this bin: https://jsbin.com/gudosey/edit?js,console which was cloned from another one of mine.

Is there a setting I screwed up or something I can try?

**Comment by jayphelps** [comment]
@remy this has been us quite a bit

**Comment by remy** [comment]
Sorry, meant to reply much earlier. Auto save has been debounced to 30s of
idle. The server in its current state can't handle the requests coming in
at the old rate.

I'm in progress on jsbin v5 whose primary aim is to solve server issues -
so ideally this isn't the final answer.
