### ISSUE TITLE
html auto-indent is retarded

### ISSUE THREAD

**Issue by teo1978** [jsbin/jsbin#3166]
![image](https://user-images.githubusercontent.com/542107/33797856-5043a280-dd0f-11e7-92ea-f31c78c16b2b.png)

**Comment by teo1978** [comment]
Can you explain why you closed the issue??

**Comment by remy** [comment]
Language used was inappropriate.

**Comment by teo1978** [comment]
Feel free to edit the title.
Does that make it any less of an issue?
