### ISSUE TITLE
script inside jsbin does not import js file anymore

### ISSUE THREAD

**Issue by GrosSacASac** [jsbin/jsbin#3185]
http://jsbin.com/tepezuj/edit?html,js,output

This jsbin worked before but now the library in the script tag does not seem to get imported.

Thanks

**Comment by GrosSacASac** [comment]
solved

**Comment by dkazmer** [comment]
How solved?

**Comment by GrosSacASac** [comment]
I fixed imports to be correct
https://jsbin.com/bisuyayesi/1/edit?html,js,output
