### ISSUE TITLE
The Clone option of the "Bin info" menu doesn't work for code imported from a gist

### ISSUE THREAD

**Issue by user-e** [jsbin/jsbin#3188]
After using the website to test some webpage code, I clicked a button  
to export it [to a gist](http://jsbin.com/help/export-gist) and the files were saved on my Github user account.

At another time, I needed to import the code back into the editor so created a new _bin_, then  
"changed the `github` part of the URL to `jsbin`" so the gist files were imported into JS Bin.
This created an editor page URL in the format `http://jsbin.com/gist/<id text>?html`  
but didn't *save the bin automatically* as the help page describes and in the *Bin info* details
there was the username "anonymous" and an old incorrect date "9 Mar 2012".

To save it to my JS Bin account as a normal _bin_, I pressed the "Clone" option  
of the "Bin info" floating menu (bottom-right of editor area) and this changed the URL
in the web browser address bar but the new _bin_ didn't have any code that was  
imported from the _gist_, only two blank tabs for CSS and HTML with some weird  
text "sadfsdfsafsdsdsadf" for the JavaScript tab code.

Thanks for creating a useful website, please get this problem sorted out.

**Comment by user-e** [comment]
Here's some screenshots of two things described above:

The code after importing from a Github gist | After using the "Clone" option, there was only blank tabs and some weird text
--- | ---
![screenshot_2018-01-09-16-06-53_kindlephoto-184415535](https://user-images.githubusercontent.com/13541254/34731614-bad00cca-f55a-11e7-831e-5edccb73368d.png) | ![screenshot_2018-01-09-16-33-29_kindlephoto-185998994](https://user-images.githubusercontent.com/13541254/34731705-0a042754-f55b-11e7-9cee-27ff55ac8339.png)

**Comment by user-e** [comment]
I would like someone to find out more about this problem and it needs to be fixed.  
This issue could be reopened.

**Comment by remy** [comment]
@user-e I had a quick vote, and that person has been voted to be you. Cheers and I'll keep an eye out for the PR. Ta in advance.
