### ISSUE TITLE
There should always be document.body, even if it's not defined manually by user

### ISSUE THREAD

**Issue by limonte** [jsbin/jsbin#3190]
- `document.body` is `null`: https://jsbin.com/lejurej/1/edit
- `document.body` is available if I provide it manually: https://jsbin.com/tivewag/1/edit

This behavior breaks UI plugins which depend on `document.body`, e.g. https://github.com/sweetalert2/sweetalert2/issues/810

The same code works perfectly in jsfiddle: https://jsfiddle.net/nr30skeg/

**Comment by remy** [comment]
I know it doesn't help you particularly, but this works in the new (not-yet-available) jsbin: 

<img width="706" alt="screen shot 2018-01-10 at 14 33 04" src="https://user-images.githubusercontent.com/13700/34777751-3e619d7a-f613-11e7-8c2d-4725dfefc38c.png">

**Comment by limonte** [comment]
Love it! Is there any ETA for the new release?

**Comment by remy** [comment]
Hoping to open it up for beta testing this month, but it's still a long way off being perfect (though it's completely usable).

**Comment by limonte** [comment]
What's the right place to subscribe for the announcement of the new beta?

**Comment by remy** [comment]
Probably twitter https://twitter.com/js_bin or [my own](https://twitter.com/rem) twitter account.

**Comment by remy** [comment]
That said, hopefully I do a blog post on jsbin.com/blog to notify how people can opt-in to try it out.
