### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Vaniitio** [jsbin/jsbin#3192]
When I go to file then download, it says the page isn't here.

**Comment by DevdutttaBain** [comment]
![image](https://user-images.githubusercontent.com/7148042/34906873-f23c14d0-f89b-11e7-9b88-9fb5fc0724c8.png)

**Comment by user-e** [comment]
I've found a second duplicate issue for this problem at <https://github.com/jsbin/jsbin/issues/3149>.
