### ISSUE TITLE
Function Calling not works.

### ISSUE THREAD

**Issue by iskandarovBakshi** [jsbin/jsbin#3193]
```javascript
function add(a) {
  var totalSum = a;
  function f(b) {
    totalSum += b;
    return f;
  }
  f.toString = function () {
    return totalSum;
  };
  return f;
}
console.log(add(10)(20)(25)(40));
```
this code works but jsbin throws an error

>  "TypeError: d.toString(...).split is not a function
>   at c (https://static.jsbin.com/js/prod/runner-4.1.1.min.js:1:3840)
>    at c (https://static.jsbin.com/js/prod/runner-4.1.1.min.js:1:8476)
>    at b.(anonymous function) [as log] (https://static.jsbin.com/js/prod/runner-4.1.1.min.js:1:8811)
>    at null.js:14:34
>    at https://static.jsbin.com/js/prod/runner-4.1.1.min.js:1:13850
>    at https://static.jsbin.com/js/prod/runner-4.1.1.min.js:1:10792"

**Comment by remy** [comment]
It doesn't solve anything now, but this will work in version 5 of jsbin - due out in the coming months.

Example using the [new console](https://jsconsole.com/?function%20add%28a%29%20%7B%0A%20%20var%20totalSum%20%3D%20a%3B%0A%20%20function%20f%28b%29%20%7B%0A%20%20%20%20totalSum%20+%3D%20b%3B%0A%20%20%20%20return%20f%3B%0A%20%20%7D%0A%20%20f.toString%20%3D%20function%20%28%29%20%7B%0A%20%20%20%20return%20totalSum%3B%0A%20%20%7D%3B%0A%20%20return%20f%3B%0A%7D%0Aconsole.log%28add%2810%29%2820%29%2825%29%2840%29%29%3B) (though it's not reading the `toString` atm)
