### ISSUE TITLE
JS Bin error on working code

### ISSUE THREAD

**Issue by dberlind** [jsbin/jsbin#3199]
Hi, I'm thinking about moving from a competitor to JS Bin because I like the embedding options better (movable pane borders, the availability of the console, etc.).  However a cut n paste of my code which works fine elsewhere bombs in JS Bin. The error (echoed to console) says the following

"error"
"SyntaxError: Unexpected token {
    at https://static.jsbin.com/js/prod/runner-4.1.2.min.js:1:13850
    at https://static.jsbin.com/js/prod/runner-4.1.2.min.js:1:10792"

I dug around it appears as though it might have to do with end of line comments (of which I have many).  Is this going to get fixed or is there a work around?

Thanks.

**Comment by remy** [comment]
"is this going to be fixed?" - absolutely, send a pull request, thanks 👍

**Comment by dberlind** [comment]
Hi Remy, I don't have code to contribute and I'm sure exactly how to file a pull request given how you've got it setup. I do know that I narrowed the problem down by taking one comment out, at a time. One of my comments had the word "do" in it. That apparently was gumming up the works. Once I changed it to "make happen" (LOL!), the code worked.
