### ISSUE TITLE
Problem with async and setTimeout

### ISSUE THREAD

**Issue by wheresrhys** [jsbin/jsbin#3201]
The following bin executes as expected when co[pied to the dev tools console, but in the jsbin console it doesn't execute the second iteration when the test promise has a timeout. 
http://jsbin.com/demilol/edit?js,console
```
const test = () => new Promise(res => setTimeout(res, 0));

(async function () {
	for(const it in [1, 2]) {
      await test();
      console.log('yay?');      	
	}
})()

const sure = () => Promise.resolve();

(async function () {
	for(const it in [1, 2]) {
      await sure();
      console.log('yay!');      	
	}
})()
```

**Comment by remy** [comment]
The next iteration of jsbin (not live yet) uses the new jsconsole.com, can you test your case there and let me know if it worked as expected (or not).

**Comment by wheresrhys** [comment]
works ok in jsconsole :smile:

**Comment by remy** [comment]
Are you happy for me to close this? I'm not going to be putting any more effort into v4, so it won't change what's currently live, but as it works on jsconsole, it'll work on v5 jsbin.

**Comment by wheresrhys** [comment]
yep sure. When's v5 due out?

**Comment by remy** [comment]
Unsure, but it's about 85% complete. If you open your browser console there's instructions on how to access the alpha preview on jsbin.com
