### ISSUE TITLE
<Feature> has been blocked because of a Feature Policy applied to the current document

### ISSUE THREAD

**Issue by maciejjankowski** [jsbin/jsbin#3206]
I get an error when trying to run code which uses MIDI access
Seems like Chrome has recently updated cross-origin frame policies.

See:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

**Comment by remy** [comment]
Do you, um, have an example I can see, or are you hoping to send a PR to
fix it anyway?

**Comment by maciejjankowski** [comment]
I would like to fix it. I need to find  out where is the code which creates the runner iframe and add some attributes to it.

**Comment by remy** [comment]
The extra trick is that v4 is currently in maintenance _and_ I'm [working on v5](https://jsbin.com/blog/the-return-and-the-refactor/). 

That said, if you think it's just an iframe sandbox prop change, I'll see what it is, and I'll add it to the v5 branch so it's reflected in the new version when it goes live.

I'll see if I can point you in the right direction re: iframe runner…

**Comment by remy** [comment]
Pretty sure it's this: https://github.com/jsbin/jsbin/blob/master/public/js/runner/sandbox.js#L27

I _think_ the directions for local running still works, but I can't promise anything (hence the refactor to v5!).
