### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by Bodzagrafika** [jsbin/jsbin#3218]
Hello
I can't delete my bins. Please help.

**Comment by remy** [comment]
Sign in, then either delete individually from File -> Delete, or http://jsbin.com/account/delete.

Otherwise you'll need to send your URL here and I can delete.

**Comment by Bodzagrafika** [comment]
I signed in and out several times, but I still have the bins. I only need
the first one.
when I delete, nothing happenes. the link is https://jsbin.com/qaqumix/edit?

2018-02-27 18:08 GMT+01:00 Remy Sharp <notifications@github.com>:

**Comment by Bodzagrafika** [comment]
the first one and the last one I need. Nothing happens when I click on delete. Nothing shows up.

**Comment by remy** [comment]
What happens when you delete?

**Comment by Bodzagrafika** [comment]
Nothing! Nothing at all. No message pops up or any window, nothing changes.

**Comment by remy** [comment]
Okay, can you run a screencast of what you're doing? If nothing _at all_ is coming up, then I'd recommend trying with an incognito window to ensure there's no browser plugins at play.

**Comment by Bodzagrafika** [comment]
I tried again the same way and I could  delete one, but for the others it says I dont own that bin. I dont understand as it is a work project and I put it into jsbin, and I dont need it anymore, who else would own it if not me?

**Comment by Bodzagrafika** [comment]
and its so weird that I tried to delete several times, nothing came up and now suddenly worked on one bin. How this could happen in such a site?

**Comment by remy** [comment]
¯\_(ツ)_/¯ computers just do what we tell them to do.

**Comment by Bodzagrafika** [comment]
well in this case it did not do that! also, you havent answered my question!
why the hell I cant delete something that I put into jsbin and I own it??

**Comment by remy** [comment]
> Why the hell?

…

What URL please? I also can't confirm how you're signed in because you've not sent a screencast yet, I can only look at what works for me.

**Comment by Bodzagrafika** [comment]
I have signed in across github. how can i attach a screenshot here? and how that would help you? i feel like im talking to a robot....:(

**Comment by Bodzagrafika** [comment]
I really do not understand you. I dont know what it means screencast ( is it screenshot?) and why cant you tell me why i cant delete something that I put into jsbin. Please answer my question.

**Comment by Bodzagrafika** [comment]
![jsbin_no_delete](https://user-images.githubusercontent.com/35364338/36746946-e1f2eb6e-1bf3-11e8-8a53-b882bcfcb59e.png)
here is a screenshot. I click on file=>delete bin, delete this bin? yes. and nothing happens, nothing at all. for a minute it said arond 30 mins ago that I dont own this bin, but how could that be?

**Comment by Bodzagrafika** [comment]
and now jsbin just deleted the one Im working on. How this could happen? I lost all the datas and I have to re-do again. I really do not understand how this could happen. Im so disappointed with the whole jsbin and this communication as well.

**Comment by remy** [comment]
I see you've deleted all your original messages (which I received as emails). You're free to use another service (in fact, more than welcome to).

On "what is a screencast": http://bfy.tw/FMDw
