### ISSUE TITLE
`window.runnerWindow.protect.protect` cause webworker error

### ISSUE THREAD

**Issue by lomocc** [jsbin/jsbin#3221]
I create a webworker with function:

```js
function () {
  let start = Date.now();
  while(Date.now() - start < 3000){}
  willThrownError();
};
```

then jsbin transform it with insert the `window.runnerWindow.protect.protect`, and throw `ReferenceError: window is not defined`:

```js
function () {
  var start = Date.now();
  {
    ;window.runnerWindow.protect.protect({ line: 32, reset: true }); 
    while (Date.now() - start < 3000) {;
      if (window.runnerWindow.protect.protect({ line: 32 })) break;
    }
  }
  willThrownError();
}
```

see also: https://jsbin.com/wusobex/edit?js,console

thanks.

**Comment by remy** [comment]
Add the comment `// noprotect` to your JavaScript and it will work.
