### ISSUE TITLE
Missing Embed Style for V5. 

### ISSUE THREAD

**Issue by Alaboudi1** [jsbin/jsbin#3222]
Great work on jsbin V5. I know it is still in alpha version, but I am worried that the ability to customize embedded bins is going to be dropped in the new version. So, can please confirm whether this feature is going to be available for the new release or not. Thanks!

**Comment by remy** [comment]
Unsure at the moment. I'm going to be fully reviewing all the pro offerings before full release. I'm going to flag this up in the TODO in v5, but leave the issue open (note that stalebot will try to close it - just ping the issue and it'll remain open).

**Comment by Alaboudi1** [comment]
Cool!
