### ISSUE TITLE
JS runtime issue, unexpected result

### ISSUE THREAD

**Issue by iloahz** [jsbin/jsbin#3225]
Test Url: http://jsbin.com/vovetagehi/1/edit?js,console

Repro Steps:
1. Click run, see 2 random numbers at the end.
2. Copy and run script in console, should see 999999 as expected.

**Comment by remy** [comment]
Add "// noprotect" to your JS code: 

<img width="1280" alt="screen shot 2018-03-22 at 11 33 26" src="https://user-images.githubusercontent.com/13700/37768258-dfd5927c-2dc4-11e8-8117-e48b15073e93.png">
