### ISSUE TITLE
Embedding default HTTP links for non pro users

### ISSUE THREAD

**Issue by drozumek** [jsbin/jsbin#3228]
I think for people with no pro account generated embedding links should be HTTP by default, for now, they are HTTPS
https://i.imgur.com/WKtEeF1.png

**Comment by remy** [comment]
It picks up the protocol from the URL you're currently on. So if you open the share box when on https, it'll give you an https url.

I've taken note, but this UI is being dropped in v5 so it's not worth making any changes right now. Thanks for the heads up.
