### ISSUE TITLE
Is jsbin.com down?

### ISSUE THREAD

**Issue by leohomer** [jsbin/jsbin#3231]
Been trying to access it for a while now.  First it said "bad gateway", then it got there and sits there with the spinning guy and goes nowhere.

**Comment by ProgramGal** [comment]
I can't get on either...

**Comment by leohomer** [comment]
Looked at the console:
Failed to load resource: the server responded with a status of 504 (Gateway Time-out) at http://jsbin.com/bin/start.js?1520b
Failed to load resource: the server responded with a status of 504 (Gateway Time-out) at http://jsbin.com/1x

**Comment by leohomer** [comment]
At least I know it's not just me.

**Comment by ernestohs** [comment]
Yep, is down :(

**Comment by Jn1532** [comment]
down for me too:
File not found: /bin/start.js?183a8

**Comment by leohomer** [comment]
Any ideas when it will be up?

**Comment by remy** [comment]
Close for #3234
