### ISSUE TITLE
Add option to disable the sandbox

### ISSUE THREAD

**Issue by TheAmazingPT** [jsbin/jsbin#3236]
I wanted to test the new Clipboard API on jsbin.com in Chrome v66, but because of the sandboxing of the iframe its not possible for security reasons.

https://www.w3.org/TR/clipboard-apis/#async-clipboard-api

From my understanding, there is no sandbox flag, which i could provide to allow the API to work in an sandboxed iframe. I can imagine, that there are more API's, which are suffering from the sandboxing.

I was thinking about an option for the viewer of a bin, to optionally disable the sandbox mode of an iframe. There could be a checkbox in the output pane next to the "Auto-run JS" checkbox, which would be called "Disable sandboxing". The checkbox would be unchecked by default and only the viewer should be able to disable it, meaning that it shouldn't be forced by the creator. Maybe there should be a tooltip or an alert for warning the user about the consequences of this action.

What do you think about it @remy? Would it be interesting to have such a feature?

**Comment by remy** [comment]
Disabling the sandbox would unlock a _lot_ of security issues in JS Bin. I don't really want to add more UI, but I don't see why the "Run with JS" couldn't strip the sandbox at that time. That said, I'm not sure how it would look on the V5 implementation (to access - see button at the end of this post: https://jsbin.com/blog/the-return-and-the-refactor/ ).

This might also solve #3238
