### ISSUE TITLE
Since Chrome 66 many examples that use webcam, geolocation etc. stopped working

### ISSUE THREAD

**Issue by micbuffa** [jsbin/jsbin#3238]
This is due to cross origin iframe constraints. The output tab of jsbin is an iframe and when the code uses getUserMedia for example, it stopped working with Chrome 66...

Read : https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

jsbin should allow cross origin iframes use of these APIs... i.e

<iframe src="https://example.com" allow="geolocation; microphone; camera; midi; encrypted-media"></iframe>

**Comment by Alaboudi1** [comment]
I am currently really struggling with the limitation that comes with the cross-origin constrain. I am building an interactive coding web page and I was trying to get the code that the user is typing, but no luck due to this constraint. I am already pro user and would like some control over this.

**Comment by remy** [comment]
I'm happy to add more sandbox properties, but I'll need either a PR or some direction as to what is missing.

There's no user control over this to keep jsbin as secure as possible given the fact it runs user code.

**Comment by micbuffa** [comment]
Remi, I'm pretty sure that adding to the iframe the attribute allow="geolocation; microphone; camera; midi; encrypted-media" would be harmless ans solve the problem. This is what all other online IDEs do. 
With jsbin, I can run an example that uses the WebCam when I click the black arrow from the output tab, in standalone mode it's ok. It's just the preview of the output in the editor that is broken by this limitation.
