### ISSUE TITLE
Word wrap was not active by default (but it was)

### ISSUE THREAD

**Issue by sergx** [jsbin/jsbin#3239]
Hello!
Word wrap was not active by default on first load the app. (i did not use jsbib for a long time).
I may think, that this is a bug, because in settings "Wrap lines" was checked, and then i got back to my bin all was fine...
And!... it was REALY hard to find this settings! Why there is no link in top? Or in the context menu of "file"?!
Thank you!

**Comment by remy** [comment]
I don't have a context menu. Why isn't on by default? Choices really. Glad you found it in the end. The UX on 5 actually surfaces this differently
