### ISSUE TITLE
Bin doesn't load

### ISSUE THREAD

**Issue by Zydnar** [jsbin/jsbin#3241]
Main site loads immediately, but http://jsbin.com/feloni/3/quiet loads until reaching timeout or 504. Checked on Firefox Quantum 60 and Google Chrome 68.

**Comment by remy** [comment]
Problem with processor possibly.

**Comment by Zydnar** [comment]
I do have issues with disk write speed, but other sites load nicely including sites of same type as jsfiddle.net, or codesandbox.io as well.

**Comment by Zydnar** [comment]
Same location.

**Comment by remy** [comment]
Yeah, db went a bit doppy. All fixed now.
