### ISSUE TITLE
run v. 5?

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#3244]
in branch feat/next-v5, `node .` returns:
```
Nothing to see right now, head over to https://jsbin.com for now ❤️
```
is this the right branch for the development version? Thank you!!

**Comment by remy** [comment]
`npm start`

**Comment by titaniumbones** [comment]
thx!  looks really neat, though maybe  not quite ready for my audience in India yet :-/ .  `npm run build && npm start` works for me w node lts/carbon.
