### ISSUE TITLE
Error while installing JsBin locally 

### ISSUE THREAD

**Issue by renganathan** [jsbin/jsbin#3251]
> C:\Users\rgovindarajan>npm install jsbin -g
> npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are
>  deprecated. See https://nodemailer.com/status/
> npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least
>  2.1.6 to avoid a serious bug with socket data flow and an import issue introduc
> ed in 2.1.0
> npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
> npm WARN deprecated buildmail@4.0.1: This project is unmaintained
> C:\Users\rgovindarajan\AppData\Roaming\npm\jsbin -> C:\Users\rgovindarajan\AppDa
> ta\Roaming\npm\node_modules\jsbin\bin\jsbin
> 
> > jsbin@4.0.3 postinstall C:\Users\rgovindarajan\AppData\Roaming\npm\node_module
> s\jsbin
> > grunt build
> 
> >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
> >> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
> >> Local Npm module "grunt-contrib-concat" not found. Is it installed?
> Warning: Task "concat" not found. Use --force to continue.
> 
> Aborted due to warnings.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 3
> npm ERR! jsbin@4.0.3 postinstall: `grunt build`
> npm ERR! Exit status 3
> npm ERR!
> npm ERR! Failed at the jsbin@4.0.3 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional log
> ging output above.
> 
>

**Comment by remy** [comment]
Sorry. As per readme, this is not supported anymore.
