### ISSUE TITLE
Site doesn't redirect from http->https

### ISSUE THREAD

**Issue by sitefinitysteve** [jsbin/jsbin#3252]
Just an FYI...

These both work:
http://jsbin.com/?html,output
![image](https://user-images.githubusercontent.com/1542376/40799973-11863af2-64dd-11e8-85c4-28f6e75f18a9.png)

https://jsbin.com/?html,output
![image](https://user-images.githubusercontent.com/1542376/40799997-1ca8a5fa-64dd-11e8-8bf4-9e55a4957700.png)

Google will index as separate sites with no redirect... maybe not worth the hassle, but just a heads up, feel free to close this right away.

**Comment by remy** [comment]
This is intentional to allow users to use non-https assets.
