### ISSUE TITLE
For loop error - TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by eniallator** [jsbin/jsbin#3267]
**Description**: When trying to use a for loop in jsbin, I get a weird error that's got nothing to do with the code that I have inputted. Not sure if it's my end or not but I'm currently getting the error in the latest chrome version and I also don't get an output (with console.log) in the latest edge either.

**The bin I'm having the error with**: https://jsbin.com/henanel/edit?js,console

**Chrome error message (from dev tools)**:
```
jsbin-4.1.4.min.js:27 Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
    at jsbin-4.1.4.min.js:27
    at Array.forEach (<anonymous>)
    at e (jsbin-4.1.4.min.js:27)
    at jsbin-4.1.4.min.js:28
```

**Comment by binki** [comment]
Appending a `;` to your line of code causes the issue to go away. Looks like the same sort of thing as discussed in #3272.
