### ISSUE TITLE
My account will not create the vanity url/homepage.

### ISSUE THREAD

**Issue by cdgittler** [jsbin/jsbin#3275]
<img width="694" alt="screen shot 2018-09-17 at 11 13 19 am" src="https://user-images.githubusercontent.com/43047944/45641587-bc1b3700-ba6a-11e8-966f-25d471af1622.png">
Please provide any additional information, record a screencast with http://quickcast.io or http://screenr.com and attach a screenshot if possible.

**JS Bin info**

* [https://jsbin.com/edit](https://jsbin.com/edit)
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:62.0) Gecko/20100101 Firefox/62.0
* cdgittler

**Comment by remy** [comment]
You need to create a bin first (hit save) so you've got a URL, _then_ save to vanity url.
