### ISSUE TITLE
No Output for Demo Custom Legend Multi Pie Chart

### ISSUE THREAD

**Issue by vkadimisetti** [jsbin/jsbin#3276]
Hi Team

I found that there is no associated output for Custom Legend Multi Pie chart when run in JS Bin.
http://jsbin.factset.com/?html,js,output 

Can you have a look into this and fix it.

**Comment by remy** [comment]
No as this isn't the source for that particular project. Someone (factset dot com) cloned the repo and have deployed it themselves, so it's their own copy. 

Domain doesn't even resolve for me (me being the "team" you're referring to btw).
