### ISSUE TITLE
Ctrl+L is conflicting with the Chrome's "focus on the address bar" hotkey

### ISSUE THREAD

**Issue by Szuruburu** [jsbin/jsbin#3278]
Please change it, or give a dude ability to change it. Be better than Google Chrome devs (as they won't let me change it :( ).

The hotkey is no use if you have to use your mouse anyway to get off that cheeky address bar.

Thanks.

**Comment by remy** [comment]
This was in the original code base - it's odd that is somehow disabled. I've not verified this bug, but can you fill in some info about your browser, OS, and anything that's applicable.

Code: https://github.com/jsbin/jsbin/blob/master/public/js/chrome/app.js#L29
