### ISSUE TITLE
Sublime/Atom/etc. keyboard shortcuts?

### ISSUE THREAD

**Issue by josephrocca** [jsbin/jsbin#3279]
Codemirror provides a drop-in sublime text keyboard shortcut list, and these shortcuts are used in most modern editors (not sure about visual studio editor). Can jsbin (maybe just v5, at least) use that keymap? I really miss ctrl+shift+d to duplicate a line, and a bunch of others.

**Comment by remy** [comment]
v5 allows you to configure the shortcuts, and v4 allows you to change the key bindings via the prefs (which is broken, but being investigated #3283).
