### ISSUE TITLE
Cannot access jsbin.com

### ISSUE THREAD

**Issue by tonix-tuft** [jsbin/jsbin#3285]
Hello,

I created a jsbin HTML page with some JS into it and saved it (https://jsbin.com/qefehuyini/1/edit?output). However, if I try to open jsbin.com now I get this error:

![screen shot 2018-10-19 at 23 33 28](https://user-images.githubusercontent.com/10134421/47244880-6f26d980-d3f7-11e8-8548-3f4da40da267.png)

All other websites can be accessed so I guess it is not a network error. Could you please check if everything is OK?

Thank you!

**Comment by remy** [comment]
Sorry, outage.

**Comment by tonix-tuft** [comment]
Everything works now!

Thank you for the support!

**Comment by tonix-tuft** [comment]
Hello, the site is down again today!

**Comment by tonix-tuft** [comment]
Thank you! It's up again!
