### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by zzal** [jsbin/jsbin#3292]
In the readme, https://gratipay.com/jsbin/ link is broken.

**Comment by ForrestLonganecker** [comment]
The "supporter" footer blocks out the bottom line of code in the input fields making it difficult to see all of the code that you are submitting.

**Comment by jacebenson** [comment]
It's just a update to the link.  
![image](https://user-images.githubusercontent.com/638764/49964789-f6b53400-fee0-11e8-9845-19a36ed0dded.png)
