### ISSUE TITLE
when scroll bar is available, textarea auto scrolls to top

### ISSUE THREAD

**Issue by eyalsela** [jsbin/jsbin#331]
I don't think the actual instance is relevant, because it happens to me in all of them once the scroll bar is available.
I took a video showing what happens... http://www.screenr.com/AM68

**Comment by lhaberke** [comment]
Hey slightly different issue, but is there a way to not have the output auto scroll to the top every time you modify the html or css files?  I'm using Chrome on windows 10 so I'm not sure if this happens for everyone.

**Comment by remy** [comment]
CSS shouldn't scroll, since it's live injected. HTML, currently not because
the entire iframe is rerendered.
