### ISSUE TITLE
loading of `processor.js` is ad-blocked when run in development mode

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#3310]
Not sure of a fix, except maybe a documentation update. 

 `processor.js` is the name of a common crypto-mining script which most adblockers will block by default.  See for instance https://github.com/hoshsadiq/adblock-nocoin-list/ and what I think is the source of the script, https://github.com/JayWalker512/CryptoNoter . 

running in production mode folds `processors/ processor.js` into jsbin.min.js, ~but `/js/runner/processor.js` is still called somewhere in the load process, and that script will fail to load as well. Not sure why not script by that name is loaded in the official jsbin.com, but maybe that has something to do with your deploy process there~

~Presumably the jsbin.com script has been whitelisted somehow; not sure why that would be.~ 

**EDIT:** Local changes related to #3311  were blocking loading of `prod/runner.min.js` and replacing with the component scripts.  Updated title to reflect actual nature of the problem

**Comment by remy** [comment]
Jsbin v4 is no longer in development, nor is dev supported. When I finally get around to getting v5 to stable, it'll supercede and doesn't have these problems.
