### ISSUE TITLE
not possible to build for production without ssl

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#3311]
there appear to be various places in `lib/routes.js` where `is_production` overrides `config.url.ssl`. This probably makes sense most of the time, but it makes building for production in an offline environment (w. no ssl option) difficult. 

Not sure how or whether to address this.

**Comment by titaniumbones** [comment]
I htink I may have a fix here: https://github.com/code-at-the-edge/jsbin/commit/f9fe4bda4872834a6ddc98c70eb8b07fb4cdc2bb 

Not sure if you would want this code or not, though, given that ssl is a good idea in most circumstances.

**Comment by remy** [comment]
Just to reiterate the other reply I posted, but I'm afraid this version of jsbin is not supported for development (only changes go in are critical bug fixes). V5 is where the development and support lives for now.

> Jsbin v4 is no longer in development, nor is dev supported. When I finally get around to getting v5 to stable, it'll supercede and doesn't have these problems.
