### ISSUE TITLE
[regression] jsbin saving not working

### ISSUE THREAD

**Issue by laukstein** [jsbin/jsbin#3313]
Regression bugs related to save:
1. after added any code, in most case it doesn't automatically update url
2. after clicked Ctr+S, not always it updated url, after twice or more tries, might update
3. after when changed previously saved code, it drops from url version, `id/2/edit` turned to `id/edit`
3. after another version "saved" trough Ctr+S, `.../id/3/edit` accessed in another browser will have old version (first version) code

**Comment by OliverJAsh** [comment]
Also live updates do not seem to be applied, e.g.

1. Go to JS Bin
2. Enter some HTML
3. Save
4. View the latest version of that JS Bin in another tab: `https://output.jsbin.com/ID` (no version number)
5. Edit the HTML. IIUC, JS Bin should auto save this.
6. Return to tab from step 4. Expected tab to update but it did not. Refresh also shows old version.
