### ISSUE TITLE
Redirected http://34.203.44.8 to https://jsbin.com

### ISSUE THREAD

**Issue by laukstein** [jsbin/jsbin#3315]
*.jsbin.com hosed under 34.203.44.8. Still it mustn't be accessible trough IP, is also security issue.

**Comment by remy** [comment]
I don't follow. What are you seeing?

**Comment by laukstein** [comment]
@remy, here what I see

![grabilla em9396](https://user-images.githubusercontent.com/183966/53192902-36527780-3618-11e9-8a4d-31164816d9ce.png)

Instead I would expect it redirect to jsbin.com or don't respond anything at all.
Perhaps use also CloudFlare to hide you server origin IP.
