### ISSUE TITLE
const is unavailable

### ISSUE THREAD

**Issue by corysimmons** [jsbin/jsbin#3316]
![image](https://user-images.githubusercontent.com/224636/53909433-ab15b080-401f-11e9-9fbd-41393e6830a6.png)

I'm using this:

![image](https://user-images.githubusercontent.com/224636/53909443-b2d55500-401f-11e9-99dc-e0bd9a437e75.png)

Why do I get this warning?

**Comment by cduran** [comment]
Duplicate of #2820

Solution as Remy said, here:
![Screen Shot 2019-03-09 at 1 13 03 PM](https://user-images.githubusercontent.com/164527/54076135-8ca4f480-426d-11e9-802d-0072276be847.png)

**Comment by corysimmons** [comment]
So I have to make an account, and go and tweak user settings so that JSBin can into ES6? It's not the default for some reason? 🤔

Can a contrib rename this to _"Feature Request: Make ES6 the Default for All Users, Including Guests"_?
