### ISSUE TITLE
console.clear fails to clear the console

### ISSUE THREAD

**Issue by Hocoh** [jsbin/jsbin#3323]
Firstly I LOVE the new interface of the application, just refined, simple, essential-centered, I really like it! thanks guys for your awesome work!

Now, let's talk about the problem:
Here the url: https://jsbin.com/?source=javascript&result=console

Here my illustration of the case: https://i.imgur.com/gg510Xv.png

As you can see the console fails to remove the previous content at each rendering. Maybe I have missed a parameter? 

I have tried to enter console.clear() or clear() in the console's aera, but they return me undefined. 

any hint would be great,
thanks

**Comment by remy** [comment]
I've spotted the same issue too (it's in the jsbin/issues repo iirc). Not
sure the cause, definitely going to fix it.

Aside: it's not "guys". It's just me.

**Comment by remy** [comment]
Fixed.
