### ISSUE TITLE
No security contact listed anywhere

### ISSUE THREAD

**Issue by thephpjedi** [jsbin/jsbin#3326]
There is no security contact listed at jsbin.com nor in this repo.

I want to report a potential security issue, but cannot find how to do so. I do not want to publish the details on a public repo. :) There should also be a security contact published for any future reports to be handled sensitively.

**Comment by remy** [comment]
You can email me directly on remy@leftlogic.com - it's just me behind jsbin

**Comment by thephpjedi** [comment]
Thanks for the contact info. Sent the security report via email a few minutes ago.

Providing a contact form or email address as a security contact would help folks attempting to disclose responsibly. The contact methods should be easily findable on jsbin.com and anywhere else a user or security researcher is likely to look. Took a bit of effort to determine this issue tracker was the best place to reach out. Others with less patience or more malicious intent may give up sooner.

Let me know if I can help with this in any way. Appreciate the great work!
