### ISSUE TITLE
不能正确显示html, https js 被禁用

### ISSUE THREAD

**Issue by 15678871232** [jsbin/jsbin#3332]
![TIM截图20190801190302](https://user-images.githubusercontent.com/34463530/62288552-3be99e80-b48f-11e9-8ad0-363c077e6dd7.png)
https://jsbin.com/libihed/edit?html,output
 Google Chrome
版本 75.0.3770.142（正式版本） （64 位）

**Comment by remy** [comment]
I can't read what the issue here is, but my guess is that you're seeing mixed https content. It's because of your unpkg URL in the bin:

<img width="249" alt="Screenshot 2019-08-31 at 17 27 58" src="https://user-images.githubusercontent.com/13700/64066665-b20b2d80-cc14-11e9-8650-7db5953bb812.png">
