### ISSUE TITLE
Dark theme (OPTION)

### ISSUE THREAD

**Issue by jgreen7773** [jsbin/jsbin#3347]
The dark theme is super nice, i am sitting between vscode and jsbin, and I just don't want to even do my code in jsbin because the bright background. If there was an OPTION for a dark theme, it would be amazing.... Oh! Also, I seem to have accidentally clicked or pressed something, now I can't get the top menu bar (where selection between 'html', 'console', 'output', etc...) to be a constant on my page, it keeps sliding back up into a thin bar, I looked for a good while, that OPTION should be more visible, because every time I try to go and run my code...the bar pops down in the way of my button. Just pro tips for the finery & finish. Thanks!

**Comment by remy** [comment]
Do you mean like how jsbin v5 has? Or are you referring to v5 in the first instance?

<img width="1552" alt="Screenshot 2019-10-30 at 22 31 12" src="https://user-images.githubusercontent.com/13700/67904015-05422380-fb65-11e9-996b-88db92f7e35c.png">
