### ISSUE TITLE
The ad bar hides horisontal scrollbar

### ISSUE THREAD

**Issue by arieroos** [jsbin/jsbin#3349]
Without an adblocker:
![Screenshot from 2019-11-07 13-34-16](https://user-images.githubusercontent.com/44861268/68385922-8bf99080-0163-11ea-998f-1664f84a632d.png)

With an adblocker:
![Screenshot from 2019-11-07 13-35-09](https://user-images.githubusercontent.com/44861268/68385934-97e55280-0163-11ea-82fb-8d5eeac663a0.png)

**Comment by avh-on1** [comment]
Seconded. The ads themselves are fine, but obscuring page content/controls with them is frustrating.
