### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by abhay382** [jsbin/jsbin#3366]
i am to much irritate because down load issue

**Comment by sid-1111** [comment]
i am not able to download my code

**Comment by iffishells** [comment]
Download issue

**Comment by MicrolemurDev** [comment]
same

**Comment by MicrolemurDev** [comment]
you can't share your link either

**Comment by 14725** [comment]
sometimes 'https://jsbin.com/xxx/download' works.

**Comment by Rohith-73** [comment]
I'm irritated and I've wasted soo much of time to download the file

**Comment by PrajwalPATIL2** [comment]
Work is not downloading
