### ISSUE TITLE
Request: Keep It Lite. 

### ISSUE THREAD

**Issue by johnaweiss** [jsbin/jsbin#3389]
Hi, i love JSBin, cuz it's the lightest, quickest, simplest full-featured online IDE, compare to:

Please keep it quick and lite.

Also love that i can totally HIDE any pane (HTML, JS, CSS ETC). LOVE that there's no clutter taking up screen real-estate. So you get BIG panes. I'm on a tiny computer, so that's very important to me. Please keep this. Other editors have ridiculous tiny-ass panes. 

CodeSandbox, CodePen, JSFiddle, TryIt Editor, Code Playground, StackBlitz, Plunker, etc. all suck, compared to JSBin. They are loaded with clutter and cutesy crap i don't need. Please stay clutter-free!

Thx!

**Comment by remy** [comment]
See v5. v4 is not being developed.
