### ISSUE TITLE
Request: Remove "Bin Info" Button

### ISSUE THREAD

**Issue by johnaweiss** [jsbin/jsbin#3390]
It's just extra clutter, and it blocks part of the work area. 
It's redundant-- Everything in the Bin Info button is already available in the File menu (except Transfer).

**Comment by remy** [comment]
See v5 for current designs.

**Comment by johnaweiss** [comment]
thx, is v5 coming to jsbin.com editor?

thx

**Comment by remy** [comment]
Yes. One day. When the developer runs out of paying work and decides to
finish v5.

**Comment by johnaweiss** [comment]
Ok, thx. So, v4 is still the current release, right?

thx!
