### ISSUE TITLE
Can you please add ES6 by default?

### ISSUE THREAD

**Issue by corysimmons** [jsbin/jsbin#3407]
Why do we have to fight with JSBin to use semi-modern JS?

It's insane that we have to:

1. Look for a "ES6 / Babel" in the dropdown where Javascript is
2. Google why that doesn't work
3. Create an account
4. Go into Settings > Linting > JSHint > and set some option from some really dated linter

I really don't understand. I just want to be able to share snippets with people without having to reach for something heavy like CodeSandbox.

**Comment by remy** [comment]
Unless you're stuck in ie11 land, your es6 *is* on by default. The browser supports it natively.

Not that I've got any planned changes for jsbin v4, my efforts, when I've got any, are in v5

**Comment by corysimmons** [comment]
Okay, so to be clear: if you are logged out of the current (June, 2020) JSBin, or don't have JSHint configured with esnext setting, you can't use ES, and this is expected behavior.

And JSBin v5 has been in the works for at least 2 years according to when the README was last updated.

![image](https://user-images.githubusercontent.com/224636/85861328-2e679200-b78e-11ea-8277-6fcfba306c30.png)

Would it be possible to simply add the config for ESNext by default so people don't have to make an account?

JSBin could still fill the _"can you help me by tinkering with this snippet?"_ niche if it just focused on providing modern ES (without having to login) with an output.

**Comment by remy** [comment]
Probably, happy to merge a PR for you.

**Comment by corysimmons** [comment]
>happy to merge a PR for you

_Ahhh! My weakness!_

It's a whole thing to dev it locally. :) Is this request as simple as swapping out the empty string here with this setting per chance?

https://github.com/jsbin/jsbin/blob/7760be77cc464cf7871addfbf3012460f003d7e3/public/js/account/preferences-settings.js#L41

```js
{
  "esnext": true
}
```

**Comment by remy** [comment]
Looking at where that property (jshintOption) is used, I think you're right.

I should be able to shove that change in but I'm not sure when jshint was last updated (on jsbin) it's entirely possible that it doesn't even know what that means (and good lord jshint is showing its age…)

**Comment by corysimmons** [comment]
Cool, thank you so much Remy. I think a lot of people will really enjoy being able to use `const` by default without having to login, so if it's that easy then it seems worth.

Yeah 6 years is a century in JS. :|

Thanks again for all your contributions. Big fan.
