### ISSUE TITLE
html tidy?

### ISSUE THREAD

**Issue by titaniumbones** [jsbin/jsbin#341]
Hi remy,

Is there already a feature to allow tidying of HTML (e.g. the way the command-line tool "tidy" does)?  Mostly I'm just looking for a way to copy in poorly formatted code from a given website, then make it presentable so students can seethe structure a little better.  I can do this directly with tidy but it would be cool if jsbin let me (and my students) click a button somewhere...  Thanks,
matt

**Comment by remy** [comment]
Done!

**Comment by wamatt** [comment]
pretty cool! ;)

**Comment by awangstar** [comment]
Hi @remy  love this  beautify feature, however for some weird reason. My Command  + Shift + L stopped working after couple of times. 

I am using chrome  on a mac.
