### ISSUE TITLE
Strange String Behavior

### ISSUE THREAD

**Issue by AmeerTaweel** [jsbin/jsbin#3427]
I used JSBin for the first time and wanted to check it out, and randomly selected the `console.clear()` function to use, and wrote this code:

```js
console.clear()
console.log("Testing new feature: ")
console.log("console.clear()")
```

The output was:

```
"Testing new feature: "
"window.runnerWindow.proxyConsole.clear()"
```

I was surprised by this, and tried this:

```js
console.clear()
console.log("Testing new feature: ")
console.log("console.clear()")
const strangeString = "console.clear()"
console.log(strangeString)
```

and got the following result:

```
"Testing new feature: "
"window.runnerWindow.proxyConsole.clear()"
"window.runnerWindow.proxyConsole.clear()"
```

tbh I don't have any idea of why it's doing this, or how to fix it, but this is a super unexpected behavior that shouldn't stay...

**Comment by remy** [comment]
To intercept and print to the in browser console, string replacement is happening. Which is why you're seeing what you do.

A work around is to break the string. Such as `console.log("console"+".clear")` - or put it in a variable etc.
