### ISSUE TITLE
Lost 70% of code from yesterday

### ISSUE THREAD

**Issue by Shazid2021** [jsbin/jsbin#3433]
Hi, I was working on a code yesterday and may/may not have saved a snapshot before leaving jsbin but I come back today and it showed an error I already dismissed. Now I have to retype all those codes, please see if it can be recovered.

[https://jsbin.com/hojataf/4]

**Comment by PGR-penguin** [comment]
I also lost most of my code from yesterday!!(Feb 19) I am very careful about saving and downloaded my work after showing it to someone so i do have a witness that I did it right! Somehow the server must have glitched between about 3pm and 9pm when I did my last save! Uuuuugh so frustrating! Please let me know if you found a way to get the code back!

**Comment by Shazid2021** [comment]
> I also lost most of my code from yesterday!!(Feb 19) I am very careful about saving and downloaded my work after showing it to someone so i do have a witness that I did it right! Somehow the server must have glitched between about 3pm and 9pm when I did my last save! Uuuuugh so frustrating! Please let me know if you found a way to get the code back!

Hey, sorry to hear about that. I retyped 200 lines of code as I was never able to find a fix. I would say JSBin is not of acceptable quality/performance when it comes to storage and saves. I worked my code in sublime 3 which is a desktop IDE and saved my file as .html  also, I uploaded my code to github to preserve my code long term.
