### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by probonopd** [jsbin/jsbin#3442]
Hello @remy do you know why https://output.jsbin.com/qoqukof is giving `Internal Server Error`?

Had been working for years.

The code is mirrored at
https://gist.github.com/probonopd/45636fc168d3dbf71db2463bfa07319c

Reference:
https://github.com/AppImage/docs.appimage.org/issues/61

**Comment by probonopd** [comment]
@Stale

**Comment by probonopd** [comment]
This is not resolved yet.

**Comment by CrimsonVex** [comment]
Encountered this today

**Comment by eladoni1** [comment]
Is this like a common thing or between june 26 and now it wasn't an issue?

**Comment by remy** [comment]
Different error. Tracking on a different issue.

**Comment by probonopd** [comment]
> Tracking on a different issue.

Thanks.
Where?

**Comment by probonopd** [comment]
http://output.jsbin.com/qoqukof is still broken. Been almost a year now.
