### ISSUE TITLE
Is JSBin development dead

### ISSUE THREAD

**Issue by janstieler** [jsbin/jsbin#3460]
Hi,
is JsBin dead? The last update on V5 was before 13 months.

**Comment by remy** [comment]
jsbin is code, it was never alive.

**Comment by janstieler** [comment]
You don't know if we live in the matrix, than we are all code ;) .
You now I mean is the project in development? I know its hard to find time for freetime projects, but in the last time I stumbled often in nice products that are not in further development.
And I ask because I like it more than codepen or similar.

Cheers

**Comment by remy** [comment]
There's no active development going on at the moment, and hasn't been for a while. That doesn't mean the project will be going anywhere and going by my own project history, it'll be around for as long as I am.
