### ISSUE TITLE
Can't log in through github

### ISSUE THREAD

**Issue by H-F-T** [jsbin/jsbin#3467]
I've been using jsbin for a while now worked fine but today trying to log in through github it gives me "Internal Server Error" so I can't log in anymore.

**Comment by axk154030** [comment]
I have ran into the same issue. Please fix :)

**Comment by Jason-Henrickson15** [comment]
I am dealing with the same issue.

**Comment by rjtvr** [comment]
Yes same, every time i try to login, transferred to this "Internal Server Error"

**Comment by FineThankYouSusan** [comment]
+1   Internal Server Error, and I guess, because I only used GitHub, I can't retrieve anything another way?

Great tool though - I should say that, so my one and only comment isn't complaining about a bug! 👍

**Comment by mygithub07** [comment]
Same issue for me. Cant login through github.  Gives "internal server error". Is there a way to retrieve stuff  and put it in a new account maybe?

**Comment by TomiRitola** [comment]
Same issue in here also

**Comment by TomiRitola** [comment]
I have the same problem.

**Comment by Jn1532** [comment]
Same problem - can't login

**Comment by remy** [comment]
Acknowledge. I've been fairly disconnected due to short break and birthdays and will be looking at this issue this week.

I'm pretty sure I know what it is, and I know it's affecting everyone who's signing in, so I'll try to expedite the solution and release.

**Comment by CrimsonVex** [comment]
Same problem

**Comment by FineThankYouSusan** [comment]
Thanks @remy   - much appreciated, it's a really handy tool and much easier to work with than other tools I've had to use in the interim.

**Comment by remy** [comment]
Fixed and live.
