### ISSUE TITLE
can't register jsbin via github.

### ISSUE THREAD

**Issue by Naks702** [jsbin/jsbin#3469]
i can't register jsbin via github. it says internal server error

**Comment by lager-beer** [comment]
Same here

**Comment by honeykpatel** [comment]
Same!! Trying since a week..

**Comment by Jason-Henrickson15** [comment]
Been trying to do the same for about a week also. I have a project I really need to finish too!

**Comment by Jn1532** [comment]
Was working on stuff and received internal server error - please help!  
Can't access my bins !

**Comment by HekatesDaughter** [comment]
I'm having this same issue. Until it's fixed I'll be looking for an alternative for my coursework.

**Comment by remy** [comment]
Fixed and live.
