### ISSUE TITLE
Downloading wont work.

### ISSUE THREAD

**Issue by SurveyMan-AdMe** [jsbin/jsbin#3495]
For some reason I cant download my file.
I have a video on it: https://youtu.be/N7XYNhUypak

**Comment by SurveyMan-AdMe** [comment]
# Im stupid lol
so it was just the fact that i hadnt saved a snapshot.
STUPID ME
# #I_AM_STUPID

**Comment by SurveyMan-AdMe** [comment]
# Im stupid lol
so it was just the fact that i hadnt saved a snapshot.
STUPID ME
# #I_AM_STUPID

**Comment by Skywebb** [comment]
Where are you from

And what file are you downloading ??
