### ISSUE TITLE
Saving a snapshot command triggers a 500 error

### ISSUE THREAD

**Issue by shai-yotpo** [jsbin/jsbin#3508]
https://www.loom.com/share/a4202db0ea984c78b73c9d21a3b64d3e

![Xnip2023-03-10_14-45-44](https://user-images.githubusercontent.com/46312057/224413673-7de79a7a-a814-4042-9f27-3efa39c635ec.jpg)
Thanks in advance :)

**Comment by remy** [comment]
Fixed now - thanks.
