### ISSUE TITLE
jsbin is not saving/auto saving.

### ISSUE THREAD

**Issue by Lazydotexe** [jsbin/jsbin#3509]
Nothing is saving, I'm unable to archive anything (The Archiving failed. You can only archive bins that you own) Cant snapshot, clone, or download. I've tried different browsers, logging out and back in. I even deleted my account and re-made it.

**Comment by christinescheller** [comment]
Same problem here.

**Comment by vibinyama** [comment]
I also have this problem

**Comment by Lazydotexe** [comment]
I would recommend using codepen until jsbin is fixed. Works about the same from what i can tell.

**Comment by FGabi83** [comment]
I have the same problem

**Comment by remy** [comment]
I'm acknowledging this - apparently, the jsbin database is "full". Not something I've ever seen in my 20+ years of development. 

This won't be a quick fix, but I'll try to keep you posted.

**Comment by remy** [comment]
Oh, apparently it was relatively straight forward (certainly compared to previous years). The data drive filled up, jsbin had stored 400gb of text from bins. Apparently not enough after 15 years or runtime. I've increased to 800gb, so hopefully that should cover the next decade (for now).

**Comment by remy** [comment]
(resolved)
