### ISSUE TITLE
Access to some bins that are temporarily saved are missing

### ISSUE THREAD

**Issue by jjadloc-yotpo** [jsbin/jsbin#3518]
Hello guys,

Our team has been using JSBin for as long as I can remember and it has been one of the tools that has been very helpful. But just recently, we came across an issue. There were some links that for some reasons weren't accessible anymore. Can someone assist us in retrieving the codes added on the following bins:

https://jsbin.com/petuxigeza/
https://jsbin.com/barimoduvu/
https://jsbin.com/mivaxodoxa/

For some reasons, we weren't able to access this links and we have codes in here that is a bit vital. Hope someone can assist us here. Thank you

**Comment by remy** [comment]
I missed this coming in - but it's fixed now.

**Comment by jjadloc-yotpo** [comment]
Thank you very much. This is very helpful.
