### ISSUE TITLE
Hello! Why these 3-years-old links are not work anymore? What has happend?

### ISSUE THREAD

**Issue by VitaliiHatsenko** [jsbin/jsbin#3520]
верстка кнопки - https://jsbin.com/zogixubuve/1/edit?html,css,output
вертска логотипа - https://jsbin.com/leweharaye/1/edit?html,css,output, https://jsbin.com/nonoxupame/1/edit?html,css,output
верстка переключателя карусели через псевдоэлементы - https://jsbin.com/bewiquqiqu/1/edit?html,css,output
пример расположения блоков карусели - https://jsbin.com/wadireliva/1/edit?html,css,output, https://jsbin.com/foyafifoji/1/edit?html,css,output
привер с 3-мя изображениями из зачетного макета - https://jsbin.com/yolizaluto/1/edit?html,css,output, https://jsbin.com/vigaqokeko/1/edit?html,css,output
верстка карточки проекта с эффектами - https://jsbin.com/beraremeci/1/edit?html,css,output, https://jsbin.com/hazajotiqe/1/edit?html,css,output
верстка элемента второго блока - https://jsbin.com/nefijamavu/1/edit?html,css,output
верстка пагинации - https://jsbin.com/puhibasuwa/1/edit?html,css,output
верстка переключателя карусели - https://jsbin.com/koqikixepi/1/edit?html,css,output, https://jsbin.com/wunehosoxi/edit?html,css,output
верстка нижнего подчеркивания через псевдоэлемент - https://jsbin.com/tazezamece/1/edit?html,css,output
верстка поиска - https://jsbin.com/nacutocifu/1/edit?html,css,output, https://jsbin.com/nadurajuyi/1/edit?html,css,output
пример верстки 4-го блока - https://jsbin.com/xaxajanode/1/edit?html,css,output

**Comment by remy** [comment]
I'll take a look. It looks like a new bug (due to a change I made to fight an increase in spam), but skimming a few of these they seem like they should be loading.

**Comment by remy** [comment]
You're back - thanks for filing the issue 👍
