### ISSUE TITLE
Some simple javascript does nothing

### ISSUE THREAD

**Issue by thany** [jsbin/jsbin#3523]
Consider this piece of javascript:

```javascript
import dateFns from "date-fns";

const date = dateFns.addMinutes(new Date(), 100);
console.log({ date }); 
```

I would expect something to get logged. But nope. Absolutely nothing appears in the console.
Pretty sure nothing is wrong with it. Since there's no explicit way to include npm packages, I have no choice but to assume they are installed automatically.

Strange how to claims there's some kind of error on ` });` - `expected : but instead saw }` - There's nothing wrong there, the syntax is fine. Just execute it, I promise it will work.

But even something much simpler:

```javascript
import dateFns from "date-fns";

console.log(dateFns); 
```

Doesn't work. It just doesn't do anything. I would expect at least *something* to be logged.

**Comment by remy** [comment]
Why would you assume that a load package is globally installed to the browser? 

It's not. You are not using import maps, so the browser has no idea what you are asking to import. You could import directly from something like a cdn but you need to make sure you point to the absolute URL of the package you're trying to import. This isn't a JS bin problem this is how the code being written
