### ISSUE TITLE
Installing jsbin via NPM on Windows 7 x64

### ISSUE THREAD

**Issue by okfro** [jsbin/jsbin#353]
I'm trying to install jsbin using the command:

npm install -g jsbin

My first error was issue #338, which I resolved by adding Git (/bin) to my PATH. Then I hit  the issue with bcrypt #94, which I solved by installing OpenSSL-Win32 (and OpenSSL-Win64 for good measure) and adding them (/lib and /bin) to my PATH. 

From there, I updated my Python 2.7.3 to 2.75. I installed SQLite WIndows (and sqlite3 in node). I already had the Windows 7.1 SDK and Visual Studio 2010 and Visual Studio 2012 installed, but I also installed the C++ 2005, 2008, 2010 and 2012 (x86 and 84) libraries. I ran Windows Update. I also installed the Visual Studio 2010 C++ Express edition as recommended by other posts.

Nothing so far has prevailed. I should note I can install various other packages without issue (Grunt, Brunch, Yeoman, etc).

This is the result of my last attempt, running:

npm -dd install -g jsbin

Any hope?

NOTE: the npm-debug.log does not appear to fully reflect all of the errors I see in the command prompt (which I cannot see all of much less copy/paste, because this is Windows). Nonetheless,  log begins: https://gist.github.com/3805457

**Comment by neechange** [comment]
windows10 node4.4.2 可以安装吗

**Comment by ednja** [comment]
The documentation says to install nodejs.   I downloaded nodejs and the website said that it was for Windows 7.  When I tried installing it, I got error saying that it won't install on anything less than Windows 8.1.  Were you able to install nodejs on your Windows 7?  If so, how?
