### ISSUE TITLE
Find & replace

### ISSUE THREAD

**Issue by metude** [jsbin/jsbin#391]
To make a simple editor feature, could you add find and replace for every code column?

Also I want to thank you for this awesome app. It's absolutely better than others.

**Comment by rafaelcastrocouto** [comment]
Why is this issue closed? It's not working right now so I'm wondering ... was it fixed at some point or is it broken ever since?

**Comment by remy** [comment]
@rafaelcastrocouto this issue isn't closed. It never was.

**Comment by rafaelcastrocouto** [comment]
Oh ... ok sorry remy ... gonna try to fix this ... I'm tired of copy/paste into a local text editor to replace stuff.

**Comment by rafaelcastrocouto** [comment]
Seens like you are just missing the dialog.css (http://codemirror.net/addon/dialog/dialog.css) ... everything else is working just fine.

**Comment by stephaneAG** [comment]
hey, I just did a quick pull request while adding @rafaelcastrocouto 's code ( thx :p ) to fix the find & replace dialog troubles
see https://github.com/jsbin/jsbin/pull/3447
+
