### ISSUE TITLE
horizontal panes

### ISSUE THREAD

**Issue by redchair123** [jsbin/jsbin#404]
Would be nice to have horizontal panes or some more exotic layout a la jsfiddle

**Comment by mnpenner** [comment]
I take it this feature has since been removed?

**Comment by jonleung** [comment]
I wish I could do this in JSBin!

**Comment by dandv** [comment]
:+1: Miss this from Codepen.

**Comment by tamj0rd2** [comment]
It would be great if this was still a feature

**Comment by remy** [comment]
It's part of the pro experiments if you want to try it out: http://jsbin.com/help/experimental-features#morelayouts
