### ISSUE TITLE
Adding custom libraries in console doesn't work

### ISSUE THREAD

**Issue by davidshimjs** [jsbin/jsbin#438]
Hi.

I tried to add my library. 
http://jsbin.tumblr.com/custom-libraries

but It doesn't work. It just adds one 'undefined' menu in Add Library tab.

**Comment by sumitramteke** [comment]
By following steps from [JS Bin Help section](https://jsbin.com/help/adding-custom-libraries), I am running `typeof libraries` which in return shows `"undefined"`. 
Am I missing something?

**Comment by remy** [comment]
@sumitramteke are you doing this in your browser's native console - i.e. *not* JS Bin's console.

**Comment by sumitramteke** [comment]
No @remy, I am doing it in JS Bin only

**Comment by remy** [comment]
Okay, so you want to do it in the browser console.

**Comment by sumitramteke** [comment]
No, actually I wanted to add my custom library in JS Bin but was failing. While debugging I found that `libraries` object was showing `undefined`.

**Comment by remy** [comment]
This is the result of `typeof libraries` in incognito, not logged in:

<img width="1392" alt="screen shot 2016-02-08 at 13 41 33" src="https://cloud.githubusercontent.com/assets/13700/12887048/b6d663fe-ce69-11e5-8577-36b579f066ee.png">

**Comment by sumitramteke** [comment]
@remy thanks! I misunderstood your previous comment. Its working now. From documentation I thought we have to use JS Bin console
