### ISSUE TITLE
enabling ssl on jsbin gives unexpected results. 

### ISSUE THREAD

**Issue by ghost** [jsbin/jsbin#467]
I installed jsbin via npm on Ubuntu 10.0.4 LTS.   When I enable SSL on jsbin I get this:

Error 107 (net::ERR_SSL_PROTOCOL_ERROR): SSL protocol error

The only configuration parameter is the    "ssl": true," parameter in config.json.   Not sure what SSL certificate jsbin is trying to use and whether this is changeable.  

-Chris

**Comment by chinchang** [comment]
Facing the same issue.
@ghost Can you please explain a bit more on what other things did you enable apart from doing `ssl: true`?
