### ISSUE TITLE
Highlight of closing brackets and curly brackets.

### ISSUE THREAD

**Issue by pbrewczynski** [jsbin/jsbin#548]
Wouldn't it be nice if jsBin have "highlight" of closed and opened bracket, 
![fsc_JS_Bin_Collaborative_JavaScript_Debugging](https://f.cloud.github.com/assets/3111143/295135/23d667ea-9459-11e2-869e-f791fc06aa43.png)

So if cursor was before or after closing "bracket"  it would highlight the current bracket and the opening one. 
(and vice versa also) 

I think such a function will really help readability.

**Comment by jcrben** [comment]
This also seems like it should be closed...
