### ISSUE TITLE
Run button in console panel does not work.

### ISSUE THREAD

**Issue by MrOrz** [jsbin/jsbin#720]
Example: http://jsbin.com/oselih/2/edit?javascript,console

Pressing the "run" button on the top right corner of console panel does not work anymore.

However the "Run with JS" button in output panel still runs the Javascript.

**Comment by elranu** [comment]
:+1: when I logged in does not work. Only the output html works. Not the console panel

**Comment by remy** [comment]
Bin example? Browser version? Or should I guess...

**Comment by elranu** [comment]
https://jsbin.com/feboyu/edit?html,js,console
Chrome 45.0.2454.101

**Comment by elranu** [comment]
![bin](https://cloud.githubusercontent.com/assets/873616/10344820/d6afc1e0-6cfb-11e5-871e-149146360124.PNG)

**Comment by danday74** [comment]
this sux, neither button working on Chrome or FF
