### ISSUE TITLE
JSBIN IS DOWN

### ISSUE THREAD

**Issue by teo1978** [jsbin/jsbin#794]
It's been a few days.
It's impossible to clone or save a jsbin, that is, to use jsbin at all.

Is it going to be fixed any soon?

**Comment by programmer5000-com** [comment]
jsBin.com is down.
![image](https://cloud.githubusercontent.com/assets/25020067/23306634/5b74cf60-fa72-11e6-9d23-dbbdd6a7ab4c.png)

**Comment by remy** [comment]
Thanks, I caught this shortly after and it's back
