### ISSUE TITLE
Can't get jsbin to install on mac

### ISSUE THREAD

**Issue by matbathome** [jsbin/jsbin#813]
I'm not very experienced at installing software from the Terminal. I've been having trouble getting the install to work. I know that the terminal says "bash" and it looks like that has posed a problem for others. Let me know if there is more info I can give.

**Comment by simplewei** [comment]
@mibamur  my system is osx, your solution is helpful, thank you very much!

**Comment by mibamur** [comment]
@simplewei your welcome
