### ISSUE TITLE
Embedded version not loading properly with Chrome

### ISSUE THREAD

**Issue by pasiaj** [jsbin/jsbin#943]
I encountered a web page where JSBin throws a SecurityError on Chrome but works on Safari.

"Uncaught SecurityError: Blocked a frame with origin "http://jsbin.com" from accessing a frame with origin "http://teropa.info". Protocols, domains, and ports must match. "

http://teropa.info/blog/2013/11/03/make-your-own-angular-part-1-scopes-and-digest.html

I'm using Chrome Version 30.0.1599.66 with no extensions loaded.

**Comment by Penderworth** [comment]
Hi all! I work at 1Password and was looking into reproducing this issue today during some triaging. Looks like it's gone, though it has been quite a while since it was here in the first place. It may be a good idea to close this issue as well.
