### ISSUE TITLE
Port project offline (with external dependencies)

### ISSUE THREAD

**Issue by tpiros** [jsbin/jsbin#963]
It would be great to have an option to port a project offline - especially if the external libraries (jquery, angular etc) would automatically be downloaded hence allowing users to carry on with the development offline.

Once the connection is back (or once someone has finished with the offline editing) the source could auto-sync so the latest version is available online as well.

**Comment by tamaspiros** [comment]
Just wondering will this be looked at? :)

**Comment by remy** [comment]
Honestly, no. But props for following up on an 18 month issue (and still being a user) :)

The next focus is offline support for jsbin, though no promises as to when it lands just yet, but some work has already gone live to prepare this (also explains the bug in codecasting you're seeing)
