### ISSUE TITLE
Where do I get an API key?

### ISSUE THREAD

**Issue by SamB** [jsbin/jsbin#975]
I was hoping to use the API to automatically upload things to jsbin, but I can't see how to get an API key ...
- [http://jsbin.com](http://jsbin.com)
- Mozilla/5.0 (Windows NT 5.1; rv:17.0) Gecko/20100101 Firefox/17.0
- SamB

**Comment by kaihendry** [comment]
I have a simple client side app that I would ideally like to keep synced as a JSBIN, so people could collaborate at anytime. https://github.com/kaihendry/myhaze

**Comment by remy** [comment]
@kaihendry you need a pro account and to enable experiments: http://jsbin.com/help/experimental-features#api

**Comment by kaihendry** [comment]
Thanks the API works!

    (jq -Rs '{ html: . }' index.html; jq -Rs '{ javascript: . }' main.js; jq -Rs '{ css: . }' style.css) | jq -s add > payload.json
    curl -H "Content-Type: application/json" -H "authorization: token $token" -X POST --data @payload.json  "https://jsbin.com/api/save"
